### ISSUE TITLE
bayesfactor() method

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#101]
Is there a reason why we don't have a `bayesfactor()`-method, maybe with `method`-argument that calls bf-savage-dickey?

**Comment by DominiqueMakowski** [comment]
Because I plan to have a bayesfactor method that runs the 2 main different methods depending on its arguments :)

But I agree, we need this "meta" method able to call the others.

**Comment by DominiqueMakowski** [comment]
> Because I plan to have a bayesfactor method that runs the 2 main different methods depending on its arguments

i.e., when a vector/dataframe/single model is passed, calls savagedickey, when multiple models are passed, calls bayesfactor_models

**Comment by strengejacke** [comment]
Ok, and is there a reason why we don't have this done for 0.2.0? :-)

**Comment by DominiqueMakowski** [comment]
Well, I would say mostly time... Better to polish the existing function and docs for v2, then we can discuss the implementation of the wrapper. Unless you want to delay v2 until this feature is there, but I'd say it is not a "critical" feature but more of a quality-of-life improvement, so it can wait for v3...

**Comment by strengejacke** [comment]
> quality-of-life improvemen

Yes, and I'm desperately in need of improved quality of life right now!

**Comment by DominiqueMakowski** [comment]
Copy pasted from [here](https://github.com/easystats/bayestestR/issues/80):

- I think it could still all be wrapped in a single wrapper function `bayesfactor`. Here's how:
  - `bayesfactor(vector)`: runs by default savage-dickey BF.
  - `bayesfactor(model)`: runs by default savage-dickey BF for all parameters' posteriors
  - `bayesfactor(model1, model2)` = `bayesfactor(model2, hypothesis=model1)`: runs by default `bayesfactor_models` on the models. 
  - if we pass the result of the precedent function (`bayesfactor_models`) to `bayesfactor`, it runs by default `bayesfactor_inclusion` on the models.

What do you think of this design?

**Comment by mattansb** [comment]
Sounds okay.
How would you distinguish (in the code) between `bayesfactor(model)` and `bayesfactor(model1, model2)`.

```R
bayesfactor <- function(x,...){
  if (is.numeric(x)) {
    bayesfactor_savagedickey(x,...)
  } else if (is(x,"bayesfactor_savagedickey")) {
    bayesfactor_inclusion(x,...)
  } else if (???) {
    
  } else {
    
  }
}
```

**Comment by DominiqueMakowski** [comment]
I am not too familiar with ellipsis. 

However, I think we could try to capture directly everything in it:

`bayesfactor <- function(..., arguments) { }` 

And then check its length, if only one object in the list, then do savage_dickey, otherwise BF models?

**Comment by mattansb** [comment]
This would then look something like this:
```R
bayesfactor <-
  function(...,
           prior = NULL,
           direction = "two-sided",
           hypothesis = 0,
           effects = c("fixed", "random", "all"),
           verbose = TRUE,
           denominator = 1,
           match_models = FALSE,
           prior_odds = NULL) {
    mods <- list(...)
    
    if (length(mods)>1) {
      bayesfactor_models(..., denominator = denominator)
    } else if (is(mods[[1]],"bayesfactor_models") || is(mods[[1]],"BFBayesFactor")) {
      bayesfactor_inclusion(..., match_models = match_models, prior_odds = prior_odds)
    } else {
      bayesfactor_savagedickey(...,prior = prior, direction = direction,
                               hypothesis = hypothesis, effects = effects,
                               verbose = verbose)
    }
  }
```

And it would work for all cases but the following (comparing two models, one specified with `denominator `):
```R
mo0 <- lm(Sepal.Length ~ 1, data = iris)
mo1 <- lm(Sepal.Length ~ Species, data = iris)

# works
bayesfactor(mo0, mo1)
#> Bayes factor analysis
#> --------------                      
#> [2] Species    1.7e+29
#> 
#> Against denominator:
#> 	 [1] (Intercept only)   
#> ---
#> Bayes factor type:  BIC approximation

# fails
bayesfactor(mo0, denominator = mo1)
#> Error in UseMethod("bayesfactor_savagedickey") : 
#>   no applicable method for 'bayesfactor_savagedickey' applied to an object of class "lm"
```

**Comment by DominiqueMakowski** [comment]
This seems good! though I feel it should also work for the last example. Maybe check if `is.null(denominator)` and then run BF sd is TRUE?

**Comment by mattansb** [comment]
I think checking for `!is.numeric(denominator)` and then running sdBF if `TRUE` is better - It will preserve the  default `denominator = 1` from `bayesfactor_models`:

```R
bayesfactor <-
  function(...,
           prior = NULL,
           direction = "two-sided",
           hypothesis = 0,
           effects = c("fixed", "random", "all"),
           verbose = TRUE,
           denominator = 1,
           match_models = FALSE,
           prior_odds = NULL) {
    mods <- list(...)
    
    if (length(mods)>1 || !is.numeric(denominator)) {
      bayesfactor_models(..., denominator = denominator)
    } else if (is(mods[[1]],"bayesfactor_models") || is(mods[[1]],"BFBayesFactor")) {
      bayesfactor_inclusion(..., match_models = match_models, prior_odds = prior_odds)
    } else {
      bayesfactor_savagedickey(...,prior = prior, direction = direction,
                               hypothesis = hypothesis, effects = effects,
                               verbose = verbose)
    }
  }
```

**Comment by mattansb** [comment]
@DominiqueMakowski Can you take a look / improve the documentation? I made it pretty bare-bones, mostly referring to the other functions.

**Comment by strengejacke** [comment]
I would use `inherits()` rather than`is()`, because latter requires `methods::is()`.

**Comment by DominiqueMakowski** [comment]
I'll try to check it tonight
