### ISSUE TITLE
docs bf-savagedickey

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#102]
I think here:
https://easystats.github.io/bayestestR/reference/bayesfactor_savagedickey.html

under _Details_ we can add a sentence to what is actually computed when the input is a model. I have made a suggestion (see commit-link below), is this ok/correct?

**Comment by mattansb** [comment]
> This method is used to examine if the hypothesis value is less or more likely given the observed data. For stanreg objects, if prior = NULL, the model is updated to incliude prior-information and then for each model parameter the prior is compared to the posterior distributon.

The only reason there is a `prior = NULL` is to be consistent with the `.numeric` method, but in all practicality, I can't imagine anyone ever providing their own `prior` with the `stanreg` method (at least not one that would give a correct Bayes factor).
I suggest changing to:

> When `posterior` is a model (`stanreg`), posterior and prior samples are extracted for each parameter, and Savage-Dickey Bayes factors are computed for each parameter.

**Comment by DominiqueMakowski** [comment]
What if someone wants to test against a cauchy 0.707?

**Comment by DominiqueMakowski** [comment]
I agree that most of the users will use the rstanarm priors, but still, the ability to provide custom priors should be open, for consistency.

**Comment by mattansb** [comment]
Since the posteriors are based on the model-priors, using different priors to compute sdBF make the sdBF not valid, as it essence is to see the change from prior to posterior (and not just compare some X to some Y). Thus, if users want custom priors, they should provide them when fitting their `stanreg` model.

**Comment by mattansb** [comment]
But if a user insists, they *can* provide priors, and the function will return some value (a meaningless one^). I just don't think this should be emphasized in the doc, as it might lead users to try something that is wrong.

**Comment by DominiqueMakowski** [comment]
Mmmh, I see, makes sense. I didn't get that point :)
