### ISSUE TITLE
bayestestR and see

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#108]
@mattansb @DominiqueMakowski Guys, you did a great job with the latest development of this package and the implementation of the BF stuff! 👍 

What do you think about this plot-approach? We currently add two class-attributes (`<fun_name>` and `<fun_name>_see`) to objects returned by `hdi()`, `rope()` etc. And when `plot()` is called, `bayestestR::plot.<fun_name>()` is called, which just checks if _see_ is available, and if so, calls `NextMethod()` (which then calls the actual plot-method in _see_).

https://github.com/easystats/bayestestR/blob/master/R/plot-methods.R

Do you think this is a good approach?

**Comment by DominiqueMakowski** [comment]
That's an interesting and elegant solution! This way, there should be no conflict when see and bayestestR are loaded together?

Maybe we could swap `<fun_name>_see` to `see_<fun_name>`. First of all, it sounds better, but also currently users might wonder what is this second class with the `see` suffix, whereas starting with `see` makes it more clear that it is "another class" in the sense of "related to another package". But mainly it sounds better 😅 sorry for nitpicking.

**Comment by mattansb** [comment]
(Had to look up `NextMethod`...)
That does seem very elegant!

**Comment by mattansb** [comment]
I've added a plotting function for sdBF.
Any idea why I'm not actually getting the (beautiful) plot? Sseems to be passing to `plot.data.frame`...
``` r
library(bayestestR)
library(see)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang

prior <- distribution_normal(1000, mean = 0, sd = 1)
posterior <- distribution_normal(1000, mean = .5, sd = .3)
sdBF <- bayesfactor_savagedickey(posterior, prior)
class(sdBF)
#> [1] "bayesfactor_savagedickey"     "see_bayesfactor_savagedickey"
#> [3] "data.frame"
plot(sdBF)
```

![](https://i.imgur.com/UtsRDZK.png)

``` r
see:::plot.see_bayesfactor_savagedickey(sdBF)
```

![](https://i.imgur.com/z3PDUhv.png)

<sup>Created on 2019-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mattansb** [comment]
LOOK!!!

``` r
library(bayestestR)
library(see)

prior <- distribution_normal(1000, mean = 0, sd = 1)
posterior <- distribution_normal(1000, mean = .5, sd = .3)

sdBF <- bayesfactor_savagedickey(posterior, prior)
sdBF
#> # Bayes Factor (Savage-Dickey density ratio)
#> 
#>   Bayes Factor
#> 1          1.2
#> ---
#> Evidence Against Test Value: 0
plot(sdBF)
```

![](https://i.imgur.com/8C6lcIS.png)

``` r

library(rstanarm)
stan_model <- stan_glm(extra ~ group, data = sleep)
sdBF <- bayesfactor_savagedickey(stan_model)
#> Sampling Priors
sdBF
#> # Bayes Factor (Savage-Dickey density ratio)
#> 
#>     Parameter Bayes Factor
#> 1 (Intercept)        0.066
#> 2      group2        0.841
#> ---
#> Evidence Against Test Value: 0
plot(sdBF)
```

![](https://i.imgur.com/In2bnwK.png)

<sup>Created on 2019-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mattansb** [comment]
``` r
library(bayestestR)
library(see)

prior <- distribution_normal(1000, mean = 0, sd = 1)
posterior <- distribution_normal(1000, mean = .5, sd = .3)

sdBF <- bayesfactor_savagedickey(posterior, prior, direction = "<")
sdBF
#> # Bayes Factor (Savage-Dickey density ratio)
#> 
#>   Bayes Factor
#> 1         0.11
#> ---
#> Evidence Against Test Value: 0
#> Left-Sided test
plot(sdBF)
```

![](https://i.imgur.com/dzeQrjY.png)

<sup>Created on 2019-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
I think this had been adressed
