### ISSUE TITLE
check_collinearity

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#116]
@strengejacke I was wondering whether the current internal should/could be exported. It seems like an easy and "intuitive" helper to quickly check the correlations between predictors, which could be re-exported (or maybe reexport the internal?) in performance, so we would have the current `check_collinearity` and this simpler `check_correlation`.

Also, are there any rules of thumb or guidelines for the current threshold (0.5)?

**Comment by strengejacke** [comment]
I'm not sure about the thresholds, and neither if VIF is appropriate for Bayesian models. See this example, which returns inconsistent results:

``` r
library(bayestestR)
library(performance)
library(rstanarm)

set.seed(123)
model <- rstanarm::stan_glm(mpg ~ wt + cyl, data = mtcars)

# high correlation?
equivalence_test(model)
#> Warning: Possible multicollinearity between cyl and wt (r = 0.77). This
#> might lead to inappropriate results. See 'Details' in '?equivalence_test'.
#> # Test for Practical Equivalence
#> 
#>   ROPE: [-0.60 0.60]
#> 
#>    Parameter       H0 inside ROPE       95% HDI
#>  (Intercept) rejected      0.00 % [36.19 43.30]
#>           wt rejected      0.00 % [-4.78 -1.75]
#>          cyl rejected      0.00 % [-2.32 -0.69]

# collinearity ok?
check_collinearity(model)
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>  Predictor  VIF Increased SE
#>         wt 2.42         1.55
#>        cyl 2.42         1.55
```

<sup>Created on 2019-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
I would say we keep this "correlation-check" internal and think about a useful threshold, while the VIF may stay in _performance_, as it's probabibly not useful in the above situation.

**Comment by DominiqueMakowski** [comment]
Okay. 
Yeah the sensitive part is the threshold. Although I am not sure about the alternative, I feel like 0.5 might be a bit too conservative... maybe 0.8 as default? Or maybe some steps, for > 0.7 it throws a message, and  > 0.9 a warning?

**Comment by strengejacke** [comment]
Yeah, that sounds good! I would opt for > .7 and > .9 as well, and print the corr-value in the msg/warning (as already implemented).

**Comment by DominiqueMakowski** [comment]
(though I still think that somehow this function could be useful in a more general context (or as an additional method of collinearity detection), as it is a very straightforward and convenient way to check the predictors' correlation... anyway let's keep it as is for now, and we'll see in the future if there's ever a need for it to be exported)
