### ISSUE TITLE
BF models -> log by default?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#117]
BF sd and BF inclusion both seem to return regular BFs (non-log) by default, which is not the case for BF models. Maybe we could switch its default return to also non-log BFs?

**Comment by mattansb** [comment]
BF inclusion also returns logged BFs.
For precision that BF models return a logged BF.

Should sdBF be changed to also return logged for consistency?

**Comment by DominiqueMakowski** [comment]
I think that I would prefer all them to be non-log BFs by default. 

One of the (*few?* haha jk 😅) values of BFs is that they are easily interpretable and understandable as odds. IMO the log transformation removes this clarity and straightforwardness (and I don't see how it increases precision?). Moreover, the interpretation guidelines for BFs (> 3, > 10) are simple and easily encoded. 

I think the default output the BF as it is more straightforward to explain (we don't have to explain, in the docs why we return log tranformation).

**Comment by mattansb** [comment]
![Alrightythen](https://media.tenor.com/images/8e3cb190ec82395a0b3fc6cf205a2f6e/tenor.gif)

**Comment by DominiqueMakowski** [comment]
haha don't you think so?

**Comment by mattansb** [comment]
Haha i guess it would be easier on the user's side to manipulate these objects with non-log BFs :)

You win this time @DominiqueMakowski !

**Comment by DominiqueMakowski** [comment]
I used to lose a lot with @strengejacke... but it was for the best (otherwise there would be plenty of inconsistencies in argument names and `return(stuff)` at the end of functions) ☺️
