### ISSUE TITLE
rope_range.BFBayesFactor?

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#121]
``` r
rope_range.BFBayesFactor <- function(x){
  sd(x@data[,1]) * c(-0.1,0.1)
}

library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.2. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************

data("puzzles")
bf_aov <- anovaBF(RT ~ shape*color + ID, data = puzzles, whichRandom = "ID",
                  whichModels = 'top', progress=FALSE)

bf_ttest <- ttestBF(x = sleep$extra[sleep$group==1], y = sleep$extra[sleep$group==2], paired=TRUE)

bf_corr <- correlationBF(y = iris$Sepal.Length, x = iris$Sepal.Width)


rope_range.BFBayesFactor(bf_aov)
#> [1] -0.255992  0.255992
rope_range.BFBayesFactor(bf_ttest)
#> [1] -0.1229995  0.1229995
rope_range.BFBayesFactor(bf_corr)
#> [1] -0.08280661  0.08280661
```

<sup>Created on 2019-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
Does a rope-range make sense for t-tests and correlations? For bf_aov, `rope_range()` already works.

**Comment by DominiqueMakowski** [comment]
Well, for correlations the rope range would be "very small threshold"/2, which for correlation is 0.1 (Cohen's 1988) /2  = 0.05. 

So for correlations it would be c(-0.05, 0.05). 

For t-tests, as it does not return a standardized difference, we would have to scale it based on the SD of the response (for `ttest(response ~ group)`) or SD of joined group1 and group2 (for `ttest(group1, group2)`)

**Comment by mattansb** [comment]
>So for correlations it would be c(-0.05, 0.05).

Agreed.

> For t-tests, as it does not return a standardized difference, we would have to scale it based on the SD of the response (for ttest(response ~ group)) or SD of joined group1 and group2 (for ttest(group1, group2))
> so 0.1*sd(c(Var1, Var2))

This is what is returned by `BF@data[,1]` both for paired and un-paired ttests.
