### ISSUE TITLE
describe_posterior.data.frame reorders columns?

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#123]
It seems that `describe_posterior.data.frame` reorders columns alphabetically:
``` r
library(bayestestR)
X1 <- data.frame(B = rnorm(100),
                 C = rnorm(100),
                 A = rnorm(100))
describe_posterior(X1)
#>   Parameter      Median       MAD CI    CI_low  CI_high pd ROPE_CI
#> 1         A  0.03138170 0.7555735 90 -1.678399 1.256958 54     100
#> 2         B -0.04152045 1.1276244 90 -1.494413 1.411409 51     100
#> 3         C  0.20905436 0.9989163 90 -1.459137 1.710532 59     100
#>   ROPE_low ROPE_high ROPE_Percentage
#> 1     -0.1       0.1              13
#> 2     -0.1       0.1               7
#> 3     -0.1       0.1               8
```
<sup>Created on 2019-05-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Any reason for this?

**Comment by strengejacke** [comment]
Yeah, this happens when using `merge()` - I guess that `merge()` reorders the columns depending on the order of the input, i.e. "new" columns from later objects are appended to the end, no matter where this column was positioned in the original object...

**Comment by DominiqueMakowski** [comment]
currently for dataframs I managed to recover the order, but maybe a better trick is required to make it more general (for instance models)
