### ISSUE TITLE
Spike-and-slab model: unifying posterior estimation and BFs?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#126]
(thanks to @mattansb 's question on twitter), I've come across this paper where [Rounder et al., 2018](https://link.springer.com/article/10.3758/s13423-017-1420-7) discuss a framework to supposedly unify BFs and posterior description.

However, I am not sure to understand it, and how/if we can implement this. Any simplified clarification?

**Comment by strengejacke** [comment]
link not found?

**Comment by DominiqueMakowski** [comment]
Fixed link

**Comment by mattansb** [comment]
I'm trying to warp my head around this too.
The main claim made in the paper it that the difference between Bayesian inference based on estimation (HDI / rope) and that based on model selection (BF) can be formalized as a difference in the specification of priors - where the priors for BFs give equal weight to some value that is categorically different than the rest (typically 0). So where estimation priors say "the parameter can have these values, e.g. `~Cauchy(0,1)`", BF priors say "the parameter is either 0, or `~Cauchy(0,1)`" (a prior they call "the spike and slab", an approximation of which seems to be possible with `rstanarm` - see [Product-normal family](http://mc-stan.org/rstanarm/reference/priors.html)).

I am waiting to see if Rouder replies to [my tweet](https://twitter.com/mattansb/status/1129614208356835328) - then was can see how (and if) to implement this in our (already awesome) package 😄

**Comment by mattansb** [comment]
Taking another look at this.

There are two solutions:
1. Use a spike and slab prior.
2. Using method for combining posterior distributions in a weighted manner, such as done by `brms::posterior_average`.

Here is my attempt a the latter - inspired by Paul's code:

``` r
library(bayestestR)
library(rstanarm)

stan_m0 <- stan_glm(extra ~ 1,
                    data = sleep,
                    family = gaussian(),
                    diagnostic_file = file.path(tempdir(), "df0.csv")
)

stan_m1 <- stan_glm(extra ~ group,
                    data = sleep,
                    family = gaussian(),
                    diagnostic_file = file.path(tempdir(), "df1.csv")
)

# The function
average_posterior <- function(..., prior_odds = NULL, missing = 0, verbose = TRUE,
                effects = c("fixed", "random", "all"),
                component = c("conditional", "zi", "zero_inflated", "all"),
                parameters = NULL){
  Mods <- list(...)
  
  # Get Bayes factors
  BFMods <- bayesfactor_models(..., denominator = 1, verbose = verbose)
  
  # Compute posterior model probabilities
  prior_odds <- c(1, prior_odds)
  posterior_odds <- prior_odds * BFMods$BF
  priorProbs <- prior_odds / sum(prior_odds)
  postProbs <- posterior_odds / sum(posterior_odds)
  
  # Compute weighted number of samples
  nsamples <- min(sapply(Mods, rstantools::nsamples))
  weighted_samps <- round(nsamples * postProbs)
  
  # extract parameters
  params <- lapply(Mods, insight::get_parameters, effects = effects, component = component, parameters = parameters)
  par_names <- unique(unlist(sapply(params, colnames), recursive = TRUE))
  
  for (m in seq_along(weighted_samps)) {
    temp_params <- params[[m]]
    temp_params <- temp_params[sample(nrow(temp_params),size = weighted_samps[m]), ,drop = FALSE]
    
    # If any parameters not estimated in the model, they are assumed to be 0 (the default value of `missing`)
    temp_params[, setdiff(par_names, colnames(temp_params))] <- missing
    
    params[[m]] <- temp_params
  }
  
  # combine all
  do.call("rbind", params)
}

bayesfactor_models(stan_m0, stan_m1)
#> # Bayes Factors for Model Comparison
#> 
#>   Model       BF
#>   [2] group 0.84
#> 
#> * Against Denominator: [1] (Intercept only)
#> *   Bayes Factor Type: marginal likelihoods (bridgesampling)

res <- average_posterior(stan_m0, stan_m1)

plot(hdi(res))
```

![](https://i.imgur.com/IsuyZ6m.png)

<sup>Created on 2020-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


As we can see from the Bayes factor analysis, the model without the effect for `group` is slightly more supported by the data, and as such, 0 is included in the credible interval.

What do you guys think?

**Comment by mattansb** [comment]
Note that some stan folks (and Paul among them) point out that this method should be used with care, as the meaning of a parameter can change between two models (e.g., the meaning of the "simple slope" changes between models with or without an interaction, depending on variable centering, etc.)

**Comment by mattansb** [comment]
Further, see the differences here in the estimation of the intercept and the group effect with and without model averaging:

``` r
describe_posterior(res, test = NULL)
#>     Parameter   Median CI     CI_low  CI_high
#> 1 (Intercept) 1.233317 89 0.04407218 2.149354
#> 2      group2 0.000000 89 0.00000000 2.272178

describe_posterior(stan_m1, test = NULL)
#> # Description of Posterior Distributions
#> 
#>    Parameter Median CI CI_low CI_high Rhat  ESS
#>  (Intercept)  0.767 89 -0.209    1.74    1 3464
#>       group2  1.561 89  0.186    2.94    1 3046
```

**Comment by DominiqueMakowski** [comment]
With bimodal distributions, we will have to refactor the HDI code to allow for multiple regions, because above I don't think the red area is indeed the 89 HDI (should be a bit of the big spike and additionally eventually a region of the right bump).

Aside from this, I cannot really say anything about the mathematical side. And on the philosophical side of the spike & slab priors, it boils down to the very deep and complex question of whether there is such a thing as no effect (0) or only undetectable/negligible effects 🙄 

If I understand, in the above, first you fit two models, one without the effect of interest (baseline model) and one with (group), then you... average the posteriors? got lost at this point 🙃

**Comment by mattansb** [comment]
The psudo-code is:
1. Compute Bayes factors comparing all models.
2. From the BFs, compute the posterior probabilities of the models.
3. Sample posterior draws from each model, weighted on the model's posterior probability.
    - If a model is missing a parameter, this means that that parameter is fixed as 0, so add the missing parameter fixed at 0.
4. `rbind` posterior samples across models.

I agree that HDI is not suitability here (have you ever seen a multi-interval HDI?) - ETI would work better.

I've been thinking of this method for a while, and was surprised by how easy it was to hack together...  it is a "hack" for cases where mixing priors (such as the spike and slab) is difficult, but it leave much room for mistakes that can be crucial... 
(Note that the overall recommendation by stan folk is to avoid doing this - instead they recommend averaging predictive distributions, [in the works in `rstantools`], which are safer, but answers a somewhat different question).

**Comment by mattansb** [comment]
I've done working on this - I'm really proud that the results are identical to those from `brms::posterior_average` (see below), but it also support `BayesFactor` models (below) and `rstanarm` models (above).

Pushing this to dev, now. **I think this issue can be closed**? @DominiqueMakowski @strengejacke 

``` r
library(bayestestR)
library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.2. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************
BFmods <- anovaBF(extra ~ group + ID, sleep, whichRandom = "ID")

res <- average_posterior(BFmods)[1:3]
plot(eti(res))
```

![](https://i.imgur.com/LFuAJvl.png)

``` r

# Compare to brms::posterior_average
library(brms)
#> Loading required package: Rcpp
#> Registered S3 method overwritten by 'xts':
#>   method     from
#>   as.zoo.xts zoo
#> Loading 'brms' package (version 2.10.0). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
fit1 <- brm(rating ~ treat + period + carry,
            data = inhaler,
            refresh = 0, 
            save_all_pars = TRUE)
#> Compiling the C++ model
#> Start sampling
fit2 <- brm(rating ~ period + carry,
            data = inhaler,
            refresh = 0, 
            save_all_pars = TRUE)
#> Compiling the C++ model
#> recompiling to avoid crashing R session
#> Start sampling

set.seed(444)
res_BT <- average_posterior(fit1, fit2)
#> Warning in .bayesfactor_models_stan(..., denominator = denominator): Bayes factors might not be precise.
#> For precise Bayes factors, it is recommended sampling at least 40,000 posterior samples.
#> Computation of Bayes factors: estimating marginal likelihood, please wait...

set.seed(444)
res_brms <- brms::posterior_average(fit1, fit2, weights = "marglik", missing = 0)[, 1:4]
#> Iteration: 1
#> Iteration: 2
#> Iteration: 3
#> Iteration: 4
#> Iteration: 1
#> Iteration: 2
#> Iteration: 3
#> Iteration: 4
#> Iteration: 5

(res_BT <- eti(res_BT))
#> # Equal-Tailed Interval
#> 
#>  Parameter        89% ETI
#>  Intercept [ 1.39,  1.47]
#>      treat [-0.37, -0.13]
#>     period [-0.03,  0.13]
#>      carry [-0.13,  0.04]
(res_brms <- eti(res_brms))
#> # Equal-Tailed Interval
#> 
#>  Parameter        89% ETI
#>  Intercept [ 1.39,  1.47]
#>      treat [-0.37, -0.13]
#>     period [-0.03,  0.13]
#>      carry [-0.13,  0.04]

plot(res_BT)
```
![image](https://user-images.githubusercontent.com/35330040/72088741-78a9a380-3313-11ea-89c3-ed5e7f988a5e.png)
```R
plot(res_brms)
```
![image](https://user-images.githubusercontent.com/35330040/72088741-78a9a380-3313-11ea-89c3-ed5e7f988a5e.png)

<sup>Created on 2020-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
That's awesome!!!
