### ISSUE TITLE
mcse and effective_samples

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#129]
names are just a suggestion, feel free to refactor, or to revise the docs...

**Comment by DominiqueMakowski** [comment]
I think it's good! I've unified the docs a bit. And I've renamed `effective_samples` to `effective_sample`, as it is the effective size of *the* sample I think 😬

**Comment by DominiqueMakowski** [comment]
Are there any rules of thumb for MSCE? similar to Rhat or ESS?

**Comment by DominiqueMakowski** [comment]
```r
model <- stan_glm(Sepal.Length ~ Petal.Length, data=iris)
describe_posterior(model)
``` 
Seems like msce fails depending on whether there are one or more parameters. It seems that it changes the dimensions of the dataframe

**Comment by strengejacke** [comment]
I'm looking into it

**Comment by DominiqueMakowski** [comment]
thanks, I think it works as expected!

**Comment by DominiqueMakowski** [comment]
Updating `parameters` I've come accross this issue in this model:
``` r
model <- rstanarm::stan_glm(mpg ~ wt + cyl, data = mtcars)
bayestestR::describe_posterior(model)
#> Possible multicollinearity between cyl and wt (r = 0.79). This might lead to inappropriate results. See 'Details' in '?rope'.
#> Warning in stddev/sqrt(ess): longer object length is not a multiple of
#> shorter object length
#>     Parameter    Median CI    CI_low    CI_high      pd ROPE_CI   ROPE_low
#> 1 (Intercept) 39.660062 90 36.740356 42.5072875 100.000     100 -0.6026948
#> 2         cyl -1.514884 90 -2.198714 -0.8000347  99.975     100 -0.6026948
#> 3          wt -3.151506 90 -4.509644 -1.9065831  99.950     100 -0.6026948
#>   ROPE_high ROPE_Percentage  ESS     Rhat
#> 1 0.6026948           0.000   NA       NA
#> 2 0.6026948           1.925 1860 1.001103
#> 3 0.6026948           0.250 2032 1.001010
```

<sup>Created on 2019-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

> Warning in stddev/sqrt(ess): longer object length is not a multiple of shorter object length

**Comment by strengejacke** [comment]
ok, we need some testing for mcse() and effective_sample(), but I hope it now works.

**Comment by DominiqueMakowski** [comment]
👍
