### ISSUE TITLE
BF vignette fails with current see version

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#137]
```
Quitting from lines 124-146 (bayes_factors.Rmd) 
   Error: processing vignette 'bayes_factors.Rmd' failed with diagnostics:
   no applicable method for 'group_by_' applied to an object of class "list"
```

Not sure if to be solved in see or here :)

**Comment by strengejacke** [comment]
hm, there is no `group_by_` in see. Is it something internal from ggplot2 due to `group_by()` in see?

**Comment by strengejacke** [comment]
Do you have a reprex?

**Comment by DominiqueMakowski** [comment]
bayestestR fails upon vignette building in CRAN checks (the errors happens in lines 124-146 in bayes_factors.Rmd)

**Comment by DominiqueMakowski** [comment]
But maybe it's just at my place?

**Comment by mattansb** [comment]
Are you running the latest version of `see`? I just made a minor change there and here for plotting sdBF.

**Comment by mattansb** [comment]
I was able to knit the vignette.

**Comment by DominiqueMakowski** [comment]
It works with updated packages
