### ISSUE TITLE
docs effective_sample

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#142]
year for Kruschke is not consistent, reference Bürkner is missing.

**Comment by DominiqueMakowski** [comment]
By Bürkner you mean 

Bürkner, P. C. (2017). brms: An R package for Bayesian multilevel models using Stan. Journal of Statistical Software, 80(1), 1-28

?

**Comment by strengejacke** [comment]
Not sure, you revised the docs... :-) At least I can't remember that I added that reference.

**Comment by DominiqueMakowski** [comment]
Although there is no Bürkner in your [original commit](https://github.com/easystats/bayestestR/commit/24ef5bd656dc6aabec69a8540008175752f38500)

**Comment by strengejacke** [comment]
No, but you said (https://github.com/easystats/bayestestR/issues/129#issuecomment-493675007) you revised the docs, so I thought it was you who added the reference :-)

I don't mind, you can keep it, if it fits into the docs, or remove it.
