### ISSUE TITLE
Bayes factor or Bayes Factor

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#146]
Just a very minor detail for consistency, do we say Bayes factors or Bayes Factors?

**Comment by mattansb** [comment]
I prefer Bayes factor (also checked, this is how Wagenmakers spells it).

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab
