### ISSUE TITLE
arg estimate -> centrality? 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#148]
Currently in point_estimate and thus in describe_posterior, the argument `estimate` is used and takes stuff like "mean", "median" etc. it was named this way in the first place in reference to "point estimates". However, I wonder if "centrality" would not be more appropriate, as it refers to indices of centrality... your thoughts?

**Comment by strengejacke** [comment]
yes, or `typical` as typical value from a vector, but centrality also sounds good to me.
