### ISSUE TITLE
docs and vignette ROPE

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#150]
Yes, that's kind of the point I think I'm trying to make - the ROPE range should correspond to the predictors' units. How would you change this?

_Originally posted by @mattansb in https://github.com/easystats/bayestestR/pull/149_

**Comment by DominiqueMakowski** [comment]
Seems like the discussion related to this has unfolded more into the original issue, I would suggest closing this in favour of the other one?

**Comment by strengejacke** [comment]
True, but that was exactly the reason for this issue, that we for the next release should at least address the docs part... So we don't forget it.

**Comment by strengejacke** [comment]
So here we have only a small part.

**Comment by strengejacke** [comment]
I think this is closed, right?

**Comment by mattansb** [comment]
Yes, this is still open here #144
