### ISSUE TITLE
bayesfactor() for BFBayesFactor

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#153]
```r
library(BayesFactor)
results <- BayesFactor::correlationBF(iris$Sepal.Length, iris$Sepal.Width)
bayesfactor(results)
```

I guess it would make sense that running `bayesfactor()` on a (single) BFBayesFactor object would return the stored BF. To my knowledge, for simple models as above, it can be retrieved as follows:

```r
numerator <- results@numerator[[names(results@numerator)]]
numerator@prior$rscale
```

But I am not sure if that holds for more complex models...

This would be useful to replace the current `bayesfactor_savagedickey()` in `describe_posterior` by the generic function, so asking for BFs does not error when a BFBayesFactor object is passed.

**Comment by mattansb** [comment]
Hmmm... Not sure exactly what you need here? A wrap around `BayesFactor::extractBF`? This is what `bayesfactor_models` does in these cases:
``` r
library(BayesFactor)
bf <- correlationBF(y = iris$Sepal.Length, x = iris$Sepal.Width)
BayesFactor::extractBF(bf,logbf = FALSE, onlybf = TRUE)
#> [1] 0.5090175
bayestestR::bayesfactor_models(bf)
#> Bayes factor analysis
#> --------------                         
#> [2] Alt., r=0.333    0.51
#> 
#> Against denominator:
#>   [1] Null, rho = 0   
#> ---
#> Bayes factor type:  JZS (BayesFactor)

bf <- ttestBF(x = sleep$extra[sleep$group==1], y = sleep$extra[sleep$group==2], paired=TRUE)
BayesFactor::extractBF(bf,logbf = FALSE, onlybf = TRUE)
#> [1] 17.25888
bayestestR::bayesfactor_models(bf)
#> Bayes factor analysis
#> --------------                       
#> [2] Alt., r=0.707    17
#> 
#> Against denominator:
#>   [1] Null, mu=0   
#> ---
#> Bayes factor type:  JZS (BayesFactor)
```

<sup>Created on 2019-05-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
Right, I forgot that this was taken care of by bf_model :) 
Then, we could make `bayesfactor(bf)` use bf_model? What do you think?

**Comment by mattansb** [comment]
Should work now.

**Comment by DominiqueMakowski** [comment]
Works awesome, thanks!


``` r
library(BayesFactor)
library(bayestestR)
results <- BayesFactor::correlationBF(iris$Sepal.Length, iris$Sepal.Width)
bayesfactor(results)
#> Bayes factor analysis
#> ---------------------                         
#> [2] Alt., r=0.333    0.51
#> 
#> Against denominator:
#>   [1] Null, rho = 0   
#> ---
#> Bayes factor type:  JZS (BayesFactor)
```

<sup>Created on 2019-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

However, I wonder if we should try improving the printing in this case so that the name of the model (`Alt., r=0.333`) is less obscure and that the BF is clearly indicated via something like `BF = 0.51` (currently I find that the value of the BF lacks emphasis, despite being the central thing), what do you think?

**Comment by mattansb** [comment]
I agree - I can give this a try, but I wouldn't hold on a CRAN release for this, as there are many (many!) unique cases to test :/

**Comment by DominiqueMakowski** [comment]
Yep, v3 seems more appropriate for such polishing.

However, one thing we could fix before CRAN release is enabling BF to be computed by `describe_posterior`:

``` r
library(bayestestR)
library(BayesFactor)
bf <- ttestBF(x = rnorm(100, 1, 1))
describe_posterior(bf)
#>    Parameter   Median CI    CI_low  CI_high  pd ROPE_CI ROPE_low ROPE_high
#> 1 Difference 1.067273 89 0.8915712 1.247194 100      89     -0.1       0.1
#>   ROPE_Percentage Prior_Distribution Prior_Location Prior_Scale
#> 1               0             cauchy              0   0.7071068
describe_posterior(bf, centrality = "all", dispersion = TRUE, test = "all")
#>    Parameter   Median       MAD     Mean       SD      MAP CI    CI_low
#> 1 Difference 1.066483 0.1106514 1.066957 0.110962 1.063188 89 0.8964673
#> 2  Posterior       NA        NA       NA       NA       NA NA        NA
#>    CI_high  pd ROPE_CI ROPE_low ROPE_high ROPE_Percentage ROPE_Equivalence
#> 1 1.252223 100      89     -0.1       0.1               0         rejected
#> 2       NA  NA      NA       NA        NA              NA             <NA>
#>           Model           BF Prior_Distribution Prior_Location Prior_Scale
#> 1          <NA>           NA             cauchy              0   0.7071068
#> 2 Alt., r=0.707 1.830444e+13               <NA>             NA          NA
```

<sup>Created on 2019-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Currently, the issue is that `bayesfactor_models` return a column `Model`. This makes sense, but for BFBayessFactor objects, describe_posterior expects a Parameter column similar to all the other functions, to merge the values accordingly.

I think this can be either be fixed in bayesfactor_models to return the same "model" name returned by `insight::get_parameters(bf)` (instead of retrieving the model's name from the object, which is quite opaque (`Alt., r=0.707`). Or I believe it can also be fixed in describe_posterior, but I think it would be much more ugly and less robust (as we would somehow cbind the dataframes instead of merging them). Any thoughts?

**Comment by mattansb** [comment]
I don't know the workings of `describe_posterior`, but since all BF function return a column `BF`, can't these just be pulled in order by `describe_posterior`?

**Comment by DominiqueMakowski** [comment]
right, I'll give it a try when I come back this evening
