### ISSUE TITLE
checks failing due to Latex error

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#156]
I have "shortened" some example outputs by wrapping `head()` around it, e.g. `estimate_density()`. my hope was to get a less cluttered log-file from the Travis-checks, so we can try to find out where the Latex errors come from, but I have no idea right now.

@DominiqueMakowski does it help when you revert the formula-stuff I used in `p_direction()`?

**Comment by DominiqueMakowski** [comment]
I am not sure, since at the same time it started failing on devel... 😕 But still have the feeling that the error comes from that paragraph (the one in pd docs with or without the equations)

**Comment by strengejacke** [comment]
yes, let's comment it out, and then do some step-by-step debugging ;-)

**Comment by strengejacke** [comment]
I can do it later, or you may start now (I'll get back to this in ~3 hours)

**Comment by DominiqueMakowski** [comment]
Do you have any particular technique to comment out roxygen chunks?

**Comment by pdwaggoner** [comment]
@DominiqueMakowski from Hadley, just remove the `'` (https://stackoverflow.com/questions/21530401/r-what-is-the-proper-way-comment-out-a-roxygen-tag)

**Comment by strengejacke** [comment]
Ok, that seems not to be the source of the error...

**Comment by DominiqueMakowski** [comment]
I don't get it because [this commit](https://github.com/easystats/bayestestR/pull/151/commits/81ad26f1ad6f66e9a3934e7da2bcb5c7014f3fef) passed and the only change from the previous commit (that did not pass) was that the first paragraph was added and the two last were left out, which suggests that the error is within them. But now I don't know anthing, my world crumbles 😨

**Comment by strengejacke** [comment]
Since we revised the docs, let's wait an hour until all travis checks finished, and see if this helped in some way (I guess not, but I still hope...)

Has someone Tex etc. installed? You can build the PDF manually, and if it fails, you still have the tex-file where you can try to find the errors. I tries to build the PDF, however, the process never stops. Here's the code you need to run from the shell:

```
# Unix
R CMD Rd2pdf ~/path/tp/package/bayestestR

# Windows
set PATH=C:\Program Files\R\R-3.6.0\bin\x64;%PATH%
R CMD Rd2pdf C:\path\to\package\bayestestR
```

**Comment by strengejacke** [comment]
Ok, it already helps (as so often) not to rely on devtools and use R's base tools to check the package. I'll see if I find any hints how to solve this Latex error.

**Comment by strengejacke** [comment]
didn't want to close this overhasty... But I think I have solved the issue

**Comment by strengejacke** [comment]
@DominiqueMakowski Not sure if you use devtools to check the package, but before submission, make sure you _do not check_ the package using devtools, but R's standard tools. This also checks for invalid URLs etc., giving a more comprehensive check.

**Comment by strengejacke** [comment]
I think we can close this, if checks still fail due to this error, let's re-open.

**Comment by strengejacke** [comment]
And here you have your formula:

![image](https://user-images.githubusercontent.com/26301769/58466251-9554ea80-8139-11e9-8087-f8671db42756.png)

:-)

**Comment by DominiqueMakowski** [comment]
> Not sure if you use devtools to check the package, but before submission, make sure you do not check the package using devtools, but R's standard tools. This also checks for invalid URLs etc., giving a more comprehensive check.

Yes I use the `--a-cran` flag

> And here you have your formula

awesome!!

**Comment by strengejacke** [comment]
> Yes I use the --a-cran flag

This doesn't help. You need to change the RStudio preferences and say **not to sue devtools**. That's the only reliable check.

**Comment by DominiqueMakowski** [comment]
good to know, thanks, but how come devtools is not reliable tho 🤔

**Comment by strengejacke** [comment]
It's some months (or years?) ago where I mentioned that devtools does not detect broken links and maybe one or two other points, but I can't remember why this was not addressed.
