### ISSUE TITLE
"bayesfactor_models" Error msg

### ISSUE THREAD

**Issue by ms1948** [easystats/bayestestR#157]
If I run the commands:
library(bayestestR)
lm0 <- lm(qsec ~ 1, data = mtcars)
lm1 <- lm(qsec ~ drat, data = mtcars)
lm2 <- lm(qsec ~ wt, data = mtcars)
lm3 <- lm(qsec ~ drat + wt, data = mtcars)
result <- bayesfactor_models(lm1, lm2, lm3, denominator = lm0)
I receive the following error msg:
**Error in bayesfactor_models(lm1, lm2, lm3, denominator = lm0) : 
  could not find function "bayesfactor_models"**

**Comment by DominiqueMakowski** [comment]
@ms1948 Thanks for reaching out! I believe you have to update your version of `bayestestR`. Try running the following:

```r
install.packages("devtools")
devtools::install_github("easystats/bayestestR")
library("bayestestR")
```

**Comment by ms1948** [comment]
Ok thanks, it works.

--Marco
