### ISSUE TITLE
emmeans integration

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#159]
For v3 I think we should add `emmeans` integration - this would mostly be via an addition of a simple method:
```R
foo.emmGrid <- function(x, ...){
  x <- as.data.frame(as.matrix(as.mcmc.emmGrid(x, names = FALSE)))
  foo.data.frame(x, ...)
}
```

For `bayesfactor_savagedickey.emmGrid` we can also add a multiple comparison correction for full pairwise comparisons (would have to see if this can be detected from a `emmGrid` object), according to [de Jong's paper](https://doi.org/10.31234/osf.io/s56mk) (I suspect this would take some work).

Thoughts?

---

EDIT: Steps to make this work:
- [x] add `emmGrid` methods for all functions that have a `data.frame` method.
- [x] add `bayesfactor_savagedickey.emmGrid` (that will `update(emmGrid, post.beta = as.matrix(insight::get_parameters(fit_prior)))`), that will need users to pass the original model (as `prior` arg), that will be passed to:
    - [x] New `.update_to_priors` internal function (?) with `brmsfit` and `stanreg` methods (returns a model?) 
    - [x] `.update_to_priors` will also be used in `bayesfactor_savagedickey.stanreg` and `bayesfactor_savagedickey.brmsfit` (will actually make them the same function - so one can simply pass to the other for simplicity.)
    - [x] Will also need to better doc `prior` arg for *all* methods.
    - [ ] multi comp correction?

**Comment by strengejacke** [comment]
Sounds great! If it doesn't affect dependencies (I don't think so), let's do it.

**Comment by DominiqueMakowski** [comment]
Totally! (And that would be very useful to streamline the workflow for `estimate`!) 

To my knowledge, I remember that `emmeans` depended somewhat on `coda` to extract the posterior draws, did that change?

**Comment by DominiqueMakowski** [comment]
I wonder if it would be also worth supporting emmeans objects directly in `insight`; maybe there is additional information contained in these objects that could be extracted (and used).

**Comment by mattansb** [comment]
`emmeans` [does depend on `coda` for `as.mcmc.emmGrid`](https://github.com/rvlenth/emmeans/blob/master/R/MCMC-support.R#L132). Is that an issue?

**Comment by DominiqueMakowski** [comment]
Not really :)

for de dependencies, it should work using the traditional:

```r
if (!requireNamespace("emmeans", quietly = TRUE)) {
    stop("Package `emmeans` required. Please install it by running `install.packages(emmeans)`.", call. = FALSE)
  }
```

**Comment by DominiqueMakowski** [comment]
The two main things that are a bit tricker would be 1) finding a rope_range (that's why I wonder if it is possible to retrieve the original response in the object) and 2) retrieving or finding priors for BFs. For the rest of the functions (such as pd) it is indeed quite straightforward.

**Comment by mattansb** [comment]
Unfortunately, non of this information is directly available in the `emmGrid` object. So users would have to select their own ROPE range for ROPE, and provide their own priors (as demonstrated in the emmeans blog post) for BFs.

It is possible to get the original model call, is that helpful in any way?
``` r
library(rstanarm)
library(emmeans)

junk <- capture.output(fit <- stan_glm(mpg ~ wt + cyl + am, data = mtcars))
x <- emmeans(fit, ~wt)
x@model.info$call
#> stan_glm(formula = mpg ~ wt + cyl + am, data = mtcars)
```

<sup>Created on 2019-05-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
Not really, we would need to refit the model which seems very inefficient.

In that case, I would suggest going the easy way with ROPE and BFs functions (i.e., requiring the user to manually provide the missing information). However, as `estimate` is a wrapper that wraps *around* emmeans, it would have access to the original model, from which we could derive the missing info and pass  them down to bayestestR's functions.

**Comment by mattansb** [comment]
Okay, so I think I did it! I added `emmGrid` methods to all functions that has a `data.frame` method: `bayesfactor_savagedickey`, `ci`, `describe_posterior`, `equivalence_test`, `estimate_density`, `hdi`, `p_direction`, `p_map`, `p_rope`, `point_estimate`, and `rope`.

@strengejacke @DominiqueMakowski would love to hear your opinion one two things:
1. For `bayesfactor_savagedickey` and `describe_posterior`, users need to provide the **original model** (as `prior` / `bf_prior` respectively) from which priors are sampled etc... I think this is best most simple solution, seeing as how we cannot recover the model from the `emmGrid` object.
2. I've revamped the doc for `bayesfactor_savagedickey` - I tried to be more clear about when and what should be passed to as `prior`. Can you read it, see that all is clear and makes sense?

**Comment by strengejacke** [comment]
Most functions save the name of the object as attribute, that's how we access the data from the environment in _see_. Maybe we can do this similarly here?

**Comment by mattansb** [comment]
`emmGrid` objects don't have the model or model name...

**Comment by strengejacke** [comment]
True, you're passing a different object...

**Comment by mattansb** [comment]
Oh, sorry, I thought your question was an answer to my first question above.
Let me take a look at that (:

**Comment by mattansb** [comment]
Okay, added `"object_name"` attribute where applicable.

**Comment by mattansb** [comment]
@strengejacke This would also mean that the plotting functions in `see` need to be updated to use `as.data.frame(as.matrix(as.mcmc.emmGrid(x, names = FALSE)))`, right?

**Comment by strengejacke** [comment]
Not sure, I need to look into this. Can do this when I'm back from vacation.

**Comment by mattansb** [comment]
multi comp correction will maybe be addressed in future versions.

**Comment by mattansb** [comment]
@DominiqueMakowski How do I rebuild the site so the new `emmGrid` methods and the update Bayes factor article appear there?

**Comment by DominiqueMakowski** [comment]
`pkgdown::build_site()`
