### ISSUE TITLE
Inclusion BF differs from JASP for interaction?

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#164]
This issue only occurs when:
1. Computing inclusion BFs for **interaction terms**
2. Comparing "Across **matched models** only"

**Comment by mattansb** [comment]
[Fixed](https://github.com/easystats/bayestestR/commit/ae37eed9d4dec100a53ffb501bc4a74464667831)

**Comment by mattansb** [comment]
@DominiqueMakowski @strengejacke Not sure how major of an issue this is, as it only affects a specific use case in one function.
I would feel more comfortable if this was pushed to CRAN sooner rather than later :/

**Comment by strengejacke** [comment]
I can't say how much the difference was (before your fix), is it a common use case with serious deviations in the results? Else, we should probably wait some time, since CRAN asks for a moderate submission frequency (which is understandable, to reduce their workload).

**Comment by mattansb** [comment]
There can be serious deviations in the results in some cases. More
importantly, this is a very popular feature in JASP...

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by strengejacke** [comment]
Is the difference from Inclusion BF due to JASP, or was it a bug in bayestestR? And what is JAPS, anyway? ;-)

**Comment by mattansb** [comment]
The difference was due to a bug in bayestestR...
JASP is the free, Bayesian oriented, SPSS alternative.. (:
--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by strengejacke** [comment]
Ok, last thing to fully understand this:

> Comparing "Across matched models only"

What does this exactly mean?

**Comment by mattansb** [comment]
Inclusion BFs are kind-of-sort-of average BFs per effect (comparing models with effect A to models without effect A).
Averaging can be done across all models,
or over only a subset of models (the "matched models"), according to the [following rule](https://www.cogsci.nl/blog/interpreting-bayesian-repeated-measures-in-jasp):
- Model with effect A are not compared to models that include an interaction with A.
- Models with interaction A:B are compared only to models that contain both effects (<- this was the part I messed up).

Although the default is to average across all models (both in JASP and here: `match_models = FALSE`) , it seems that [JASP users tend to use the "matched models" option](https://search.cogsci.nl/?q=matched&cx=partner-pub-9276598827173431%3A7001979481&cof=FORID%3A10&ie=UTF-8&sa=) (`match_models = TRUE`).

**Comment by strengejacke** [comment]
OK, I see! I'm a bit undecided on the severity / urgency of this issue. I would also tend to say that it's good to have a quick fix here, however, this would mean that _further_ updated of bayestestR should wait a bit. Indeed, CRAN checks yield a warning when pkg submissions happen too frequently.

I would say, @DominiqueMakowski as maintainer has the final decision on this.

**Comment by strengejacke** [comment]
@DominiqueMakowski Issue can be close, just leaving it open for discussion on your decision.

**Comment by mattansb** [comment]
The more I think about it, the more I am convinced this should be addressed ASAP for potential new users' sake... Awaiting to hear @DominiqueMakowski 's verdict :)

**Comment by DominiqueMakowski** [comment]
too much pressure on my shoulders :)

I would stay it can wait a few weeks. anyway good thing is in the vignette (and everywhere if I remember correctly) we recommend downloading the package directly from github. Hence it's good to have a a very stable master branch (as I consider it as a true alternative to CRAN) ((((thus the need for a Dev branch 😅😅)))).

on a side note, following a bit the recent announcements of github, it seems that they have the will of being more than just a code repo but also a "true" package host. Even for R, I feel it will be more and more a common thing to download packages directly from github. so to me it's okay to consider our master branch as our current main stable release, and recommending to download the package from it, and using CRAN releases more like milestones releases (similar to github's release system)

**Comment by mattansb** [comment]
I guess it can wait a few weeks if in blog posts, tweets etc we link to github and not CRAN (which I believe is what we do).
