### ISSUE TITLE
inconsistent docs in describe_posterior

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#167]
I just read the blog-post and looked up the docs for `?describe_posterior`, and saw that there's some confusion, in particular the `test`-argument.

- options shown in "Usage" are `c("pd", "rope")`
- options shown in "Arguments" are `"p_direction", "rope", "p_map" or "bayesfactor"`
- options actually usable in code are
```r
    test <- match.arg(tolower(test), c(
      "pd", "p_direction", "pdir", "mpe",
      "rope", "equivalence", "equivalence_test", "equitest",
      "bf", "bayesfactor", "bayes_factor", "all"
    ), several.ok = TRUE)
```

I think we should make this more clear, and also give more details about these options.

**Comment by DominiqueMakowski** [comment]
to me it's relatively alright: the default (what is shown as usage but is actually the default) is c(pd, rope), the possible options are additionally bf or equitest and behind the scene we allow for some different spelling...

**Comment by strengejacke** [comment]
> behind the scene

This is what I meant ;-)
The Usage-section shows `pd`, but this is not listed in the Arguments-section. All options (at least all that refer to a unique test), including some explanation, should be listed in the Arguments-section, or explanation should be at least provided in the details. It might be sufficient to add something like "tests refer each function that will be called, like `pd()` ..." or something like that.

**Comment by strengejacke** [comment]
Maybe I can make a proposal.

**Comment by DominiqueMakowski** [comment]
right I see! then we could remplace pd in the default by p_direction. and indeed specify that they correspond to functions

**Comment by strengejacke** [comment]
Just saw that `p_map` is listed in the docs, but not allowed in the code?

**Comment by DominiqueMakowski** [comment]
might have forgot... oops 🤭

**Comment by strengejacke** [comment]
`mpe` = `pd`?

**Comment by DominiqueMakowski** [comment]
yes

**Comment by strengejacke** [comment]
https://easystats.github.io/bayestestR/reference/describe_posterior.html ?
And I enabled `p_map`.

**Comment by DominiqueMakowski** [comment]
thanks
