### ISSUE TITLE
Capitalize factors levels?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#181]
``` r
knitr::kable(bayestestR::describe_posterior(insight::download_model("stanreg_glm_2"), test="all")[, c("Prior_Distribution", "ROPE_Equivalence")])
#> Possible multicollinearity between cyl and wt (r = 0.7). This might lead to inappropriate results. See 'Details' in '?rope'.
#> Computation of Bayes factors: sampling priors, please wait...
```

<table>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Prior_Distribution</th>
<th style="text-align: left;">ROPE_Equivalence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: left;">normal</td>
<td style="text-align: left;">rejected</td>
</tr>
<tr class="even">
<td>3</td>
<td style="text-align: left;">normal</td>
<td style="text-align: left;">undecided</td>
</tr>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">normal</td>
<td style="text-align: left;">rejected</td>
</tr>
</tbody>
</table>

<sup>Created on 2019-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Should we capitalize these levels, `normal` -> `Normal`, `rejected` -> `Rejected` etc.

IMO it makes sense whether one uses this output in some formatted table for publication, uses these levels in plots (the legend is nicer when factor levels are capitalized) or `group_by` them.

On the other hand, it *could* be a small breaking change. Thoughts?

**Comment by strengejacke** [comment]
I have no special preferences, but your reasoning sounds reasonable. So, OK from my side (as long as you fix https://github.com/easystats/bayestestR/issues/168, I WILL PUT THIS INTO MY SIGNATURE, SINCE THIS IS MY "PASSING TRAVIS TIC"!)

**Comment by mattansb** [comment]
Might `Prior_Distribution` might be used to make new priors in new models? In that case, it might be better to leave as it? Though this might some weird code writing that can be solved with `tolower()`...

**Comment by DominiqueMakowski** [comment]
> Might Prior_Distribution might be used to make new priors in new models? In that case, it might be better to leave as it?

true
