### ISSUE TITLE
add as.numeric method to BF, and others

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#187]
Would be nice to have this method work for all indices.

```r
#' Convert to Numeric
#'
#' @inheritParams base::as.numeric
#' @method as.numeric p_direction
#' @export
as.numeric.p_direction <- function(x, ...) {
  if ("data.frame" %in% class(x)) {
    return(as.numeric(as.vector(x$pd)))
  } else {
    return(as.vector(x))
  }
}
```

**Comment by mattansb** [comment]
maybe `as.vector` instead?
(How would ci and hdi be handled?)

**Comment by strengejacke** [comment]
Yes, CI and HDI are a bit tricky

- lower and upper limit
- what if you have more than one CI-level?

**Comment by DominiqueMakowski** [comment]
for CI it's a special case, we could simply convert the dataframe into a numeric matrix... or not having this method at all (since it's different anyway)

**Comment by DominiqueMakowski** [comment]
Should we close this?

**Comment by mattansb** [comment]
Just added the BF methods.

**Comment by DominiqueMakowski** [comment]
I think we can close
