### ISSUE TITLE
Remove dataset from package

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#19]
Hum, I just realised that the `bayes_indices.csv` dataset, used in the vignettes, is loaded with the package. Which is unintended and unwanted from a weight perspective. Moreover, the vignettes work by downloading the dataset from github, so no need for it to be stored in the package.

From [here](http://r-pkgs.had.co.nz/data.html):

> - If you want to store parsed data, but not make it available to the user, put it in R/sysdata.rda. This is the best place to put data that your functions need.
> - If you want to store raw data, put it in inst/extdata.

**Comment by strengejacke** [comment]
Is this issue resolved?

**Comment by DominiqueMakowski** [comment]
Yes! Was moved to circus
