### ISSUE TITLE
eti(): Equal-Tailed Interval

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#192]
Related to #36 
Proposition in paper:

---- 

In order to measure the uncertainty associated with the estimation, **bayestestR** provides two functions: `eti()`, the Equal-Tailed Interval **ETI**, and `hdi()`, the **Highest Density Interval (HDI)**. Both indices (accessible via the `method` argument in the `ci()` function) can be used in the context of Bayesian posterior characterisation as **Credible Interval (CI)**.

[`hdi()`](https://easystats.github.io/bayestestR/reference/hdi.html)
computes the HDI of a posterior distribution, i.e., the interval which contains all points within the interval have a higher probability density than points outside the interval. HDIs have a particular property: Unlike an equal-tailed interval (computed by [`eti()`](https://easystats.github.io/bayestestR/reference/eti.html)) that typically exclude 2.5% from each tail of the distribution, the HDI is *not* equal-tailed and therefore always includes the mode(s) of posterior distributions.

By default, `hdi()` and `eti()` return the 89% intervals (`ci = 0.89`), deemed to be more stable than, for instance, 95% intervals. An effective sample size of at least 10.000 is recommended if 95% intervals should be computed [@kruschke2015doing]. Moreover, 89 is the highest prime number that does not exceed the already unstable and arbritrary 95% threshold [@mcelreath2018statistical].

``` r
hdi(posterior)
#> # Highest Density Interval
#> 
#>       89% HDI
#>  [0.11, 6.05]

eti(posterior)
#> # Equal-Tailed Interval
#> 
#>       89% ETI
#>  [0.42, 7.27]
```

**Comment by DominiqueMakowski** [comment]
I think it makes sense to have these two methods available separately and via the `ci()` mother-function. What do you think?

**Comment by mattansb** [comment]
I agree - two methods for computing CIs.

**Comment by DominiqueMakowski** [comment]
This will also help to streamline the docs of `ci()` as it is further reused for frequentist models in parameters

**Comment by DominiqueMakowski** [comment]
Ok I'll start adding that - should be fast

**Comment by strengejacke** [comment]
Note that we have to update "see" accordingly. Maybe also performance? `ci()` should default to eti, to not break changes with other packages.

In general I think this is a good idea.

**Comment by DominiqueMakowski** [comment]
https://github.com/easystats/bayestestR/pull/193
