### ISSUE TITLE
ROPE 🔪😱

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#196]
https://github.com/easystats/bayestestR/blob/8b3779297d70aef74d18ffe32e1c54157a8ea0ad/R/rope.R#L205

 👇👇👇👇👇👇👇👇
👉  @strengejacke 👈  
 ☝️ ☝️☝️☝️☝️☝️☝️☝️☝️

**Comment by mattansb** [comment]
![](https://media.giphy.com/media/26qGaINqDqiAdFUjM7/giphy.gif)

**Comment by DominiqueMakowski** [comment]
@strengejacke I imagine we should change it to a 0-1 proportion as well?

**Comment by strengejacke** [comment]
I would say yes.

**Comment by humanfactors** [comment]
Always make `%` a 'proportion'. 

Always.
