### ISSUE TITLE
p_rope() returns values between 0 and 100, not 0 and 1

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#2]
I would expect the p-value to have a range from 0-1, not 0 to 100.

**Comment by strengejacke** [comment]
``` r
library(bayestestR)
library(rstanarm)
set.seed(123)
m <- stan_glm(
  vs ~ wt + am,
  data = mtcars,
  family = binomial("logit"),
  chains = 1
)

# > 1
p_rope(as.data.frame(m)$am)
#> [1] 95.1

# between 0 and 1
p_map(as.data.frame(m)$am)
#> [1] 0.1020263
```

<sup>Created on 2019-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
I think the expectation for most people doing statistics is to retrieve a value between 0 and 1 when we think of probabilities. I would return a value between 0 and 1 (also to avoid confusion if you have a probabilities of 0.1%), and maybe add a `print()`-method, which, however, should add a `%`-sign to emphasize that the output is a percentage value.

**Comment by DominiqueMakowski** [comment]
That's a great suggestion. Thanks a lot!!
