### ISSUE TITLE
Automatic ROPE bounds selection for models: the case of binomial data

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#20]
Related to the fact that ROPE bounds are selected automatically for models with the `0.1 * SD(response)` formula. How to adapt this to binomial models?

Log odds can be converted to standardized differences (see [formula](https://easystats.github.io/report/articles/interpret_metrics.html#cohen1988statistical-3)), so maybe through something involving it?

**Comment by strengejacke** [comment]
The question is, what is a "practical equivalent region" for a binary outcome? I have tried this in `sjstats::equi_test()`:

```r
stats::sd(response_value) * eff_size / 4
```

So simlar to linear models, but additional dividing the range of the ROPE by 4... This _feels_ like a useful default in _some_ situations, but not in general.

**Comment by DominiqueMakowski** [comment]
I've added a `rope_bounds()` function in order to be able to simply tweak the behaviour. 

Here's what I did:

- Since `d <-log_odds * (sqrt(3) / pi)` and `d in our case is `0.1 * d`
- log_odds_equivalent_to_01_d <- 0.1 * (pi / sqrt(3))

Does that make sense ^^?

**Comment by strengejacke** [comment]
I have looked a bit closer into the supplemental material of the Kruschke paper. There he describes how to define the ROPE for logistic regression. We need to know two specific details here:

1. The probability of "success" of an event. We can simply take the mean of the (binary) response for this probability.
2. The negligible change for this probability. This is a bit more difficult, since it depends on the context of the data (for one outcome, a change of 3 percentage points in the probability of success is great, in other contexts, it might be 10 percentage points).

For 2), we may either require an additional argument, and/or could set a default, e.g. if the probability of success changes for more than 1/4, then it's an important effect.

I have done this for a paper I am currently working on, and this might be a useful code-snippet here:

```r
prob_fall <- mean(as.numeric(as.vector(get_response(model))))
neg_change <- .03
# or this, then neg_change would be ~ .25
neg_change <- prob_fall / 4
# or this, then neg_cchange would be ~ .31
neg_change <- prob_fall / pi

# calculate ROPE, based on Kruschke
rope <- (qlogis(prob_fall + neg_change) - qlogis(prob_fall - neg_change)) / 4

# call to sjstats-function
equi_test(model, rope = c(-1,+1) * rope)
```

**Comment by DominiqueMakowski** [comment]
It seems indeed tidier to have the rope bounds set to default by default, which would compute a preset rope range based on the model's response, and let the user input his own values through the same argument as for linear models, by adjusting rope's bounds (now that I am thinking of it, we could maybe rename `bounds` to ` range`?).

However, we should compare the new default you (and Kruschke?) are suggesting with the linear equivalent I mentioned above (based on the relationship between log odds and standardized differences), just to make sure that we chose the most sensible defaults ☺️  (consistent accross model types)

**Comment by strengejacke** [comment]
I would rather use the above method only for logistic regression models, or in general for models with binary outcome.

**Comment by strengejacke** [comment]
> now that I am thinking of it, we could maybe rename bounds to range?

Why not `rope`? That's exactly the range of interest here.

**Comment by DominiqueMakowski** [comment]
You're right, I was thinking specifically about logistic models. Do you suggest, then, having a different "default" of logistic models compared to other binomial, such as for e.g. probit?

> Why not `rope`? That's exactly the range of interest here.

Well, besides being redundant with the function's name, I initially specified "bounds" as the two provided values actually correspond to the lower and upper bounds of the region (rather than the region *per se*). It is also to underline the fact that this argument modifies the parameters of the output of rope (for instances where you can chose to compute the rope's percentage, available parameters can be, `rope=TRUE, rope_bounds=c(1,2), rope_ci=.90`). But as always, it is a soft opinion :)

**Comment by strengejacke** [comment]
> Do you suggest, then, having a different "default" of logistic models compared to other binomial, such as for e.g. probit?

No, I would say we use the same default here. It's a different thing for count models though. But maybe we can think about that later.

And regarding the argument name: I had `equivalence_test()` in mind. For `rope_bounds()` it indeed makes sense to have a more specific name. Maybe `limits`? This is a common and known term.

**Comment by DominiqueMakowski** [comment]
as a range of values is usually expressed by the [min, max], `range` it applies well to our argument. But `limits` could do also... The worst thing is now changing all its instances ^^

**Comment by strengejacke** [comment]
I think we can close this issue now, or not?

**Comment by strengejacke** [comment]
I have renamed bounds into range...

**Comment by DominiqueMakowski** [comment]
Sorrrryyy, I've reopened this as this is still somehow running through my mind 😅 

Correct me if I am wrong, but from what I understood the logit scale is a form of standardized coefficient (with a more or less direct correspondence to a linear standardized coef) that does not depend on characteristics of the outcome (i.e., a coefficient x represents the same "amount" independently of the "number of successes" (the mean of the outcome)). 

Thus, it is hard for me to understand the rationale of adjusting the rope range of the logit scale based on the characteristics of the outcome...

Maybe we could:
- Ask for opinion (stan discourse?)
- Add method parameters with "cohen" (his proposed d equivalent) and "kruschke" possibilities (this I think of adding as I might soon need it for a study)

**Comment by strengejacke** [comment]
> Correct me if I am wrong, but from what I understood the logit scale is a form of standardized coefficient 

I'm not sure about this, but I have never seen the logit scale and standardized coefficients being in such a relation, so I won't correct you. :-)

Kruscke actually does not derive the negligible effect from some maths, but defines it based on what can be expected or is know. He then calculates the "ROPE" by 

((prob. of sucess + negligible effect) - (prob. of sucess - negligible effect)) / 4

and this values is the "ROPE", which says that if a beta from a _standardized_ coefficient is larger than this value, we have a relevant effect, and if a beta from a _standardized_ coefficient is _not_ larger than this value, we have a negligible effect - which often ends up in being a value ~ 0.05. So we could also set the ROPE-range to -.05 to +.05, and "standardize" the coefficients (i.e. the posterior samples), and see if the 95% HDI covers this ROPE region.

Or we should do some simulation if our approach comes close to that approach.

I have revised the docs to 1) draw more attention from the user on this issue and 2) make a bit clearer that we are going in Kruschke's direction, but probably not exactly implementing his calculations.

I think for the initial release, we can live with how `rope_range()` finds its defaults.

**Comment by strengejacke** [comment]
btw, this is related t0 #52

**Comment by DominiqueMakowski** [comment]
> > Correct me if I am wrong, but from what I understood the logit scale is a form of standardized coefficient
Since log odds can be transformed to odds and odds are standardized... 

Anyway, I realised I did my math wrong!!

With the help of [this](https://www.meta-analysis.com/downloads/Meta-analysis%20Converting%20among%20effect%20sizes.pdf), the correct formula for converting between log odds and d is:
`logodds = d * sqrt(3) / pi`

So, for a d of 0.1 (= for `sd(y)*0.1`), `equivalent_of_01 = 0.1 * sqrt(3) / pi = 0.05513289`. Which seems pretty close from the `~ .05` you mentioned. 

So rather than further adjusting this value for the mean of the outcome, I think it is reasonable to "fix" the range from -0.0551... to 0.0551..., so the logic is consistent between linear and logistic models. 

As for other kinds of binary models (probit, ...)... Well I don't know 😅

**Comment by strengejacke** [comment]
Maybe we should mention this in the docs as well.

**Comment by DominiqueMakowski** [comment]
Changed it. Will try a first CRAN submission now :)

**Comment by mattansb** [comment]
> As for other kinds of binary models (probit, ...)... Well I don't know

I think the `sigma` for probit models is 1 - so this would just need to be 0.1 :)
