### ISSUE TITLE
plot() for CI / ETI

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#200]
Just curious, why do we have `plot.bayestestR_ci()`, and not `plot.eti()`? Does it currently not work with the *see* package version on CRAN? I think, since the next class attribute is `see_ci`, it might interfere with `parameters::ci()`?

**Comment by DominiqueMakowski** [comment]
I haven't focus a lot on the plots so idk 😕

**Comment by strengejacke** [comment]
I think we can safely release an update of _see_ shortly after bayestestR, so maybe we can indeed use `plot.eti()` here, and make the changes accordingly in the see-package. I guess not many (if any) people will recognize if the plot-function doesn't work for a few days.

I plan to finish the first implementation of `plot.point_estimate()` for the next see-update, should be done before we submit bayestestR.

**Comment by strengejacke** [comment]
ok, I have checked all class-attributes, fixed them in _see_, so everything is working with the forthcoming bayestestR update. _see_ can be released a bit later then (or in parallel, doesn't matter anyway).

**Comment by mattansb** [comment]
Just did the same for `see_bayesfactor_savagedickey` -> `see_bayesfactor_parameters`
