### ISSUE TITLE
Bayes factor User Meeting

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#202]
The first Bayes factor user meeting will be on the 19th and 20th of December 2019. The meeting will take place in Utrecht, the Netherlands, at the Utrecht Science Park (university campus).

https://bayesfactor.wp.hum.uu.nl/

**Comment by DominiqueMakowski** [comment]
please do go as the proud herald of bayestestR and spread the easyword ☺️!

**Comment by mattansb** [comment]
Can I get some easyfunding? 😜

**Comment by strengejacke** [comment]
> 19th and 20th of December 2019

what a date - don't they have xmas in netherlands? ;-) two reasons I can't attend: my wife's birthday and movie start of Star Wars 9 (can't say right now which is more critical...)

**Comment by DominiqueMakowski** [comment]
> can't say right now which is more critical

I have a bad feeling about this... 😄 

> Can I get some easyfunding? 😜

as soon as the "easymoney" package is on CRAN ^^

**Comment by DominiqueMakowski** [comment]
> Can I get some easyfunding

but in all seriousness this might actually a valid question... the project could really grow and further improve with some funds. I wonder if there are any grants to which we could apply and submit the project... we should be on the lookout :moneybag:

**Comment by strengejacke** [comment]
r foundation?

**Comment by mattansb** [comment]
I'll see if I can get my department to spare some $$ - maybe I'll present (We don't have Christmas break here 😁✡).

**Comment by strengejacke** [comment]
deadline's approaching... anybody attending?

**Comment by mattansb** [comment]
I am unable to go :(

**Comment by strengejacke** [comment]
ok, I think we can close this "reminder", or not?
