### ISSUE TITLE
R version requirement

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#207]
See my comments here:
https://github.com/easystats/bayestestR/commit/8fa8c5626a0506b9c98a66a24f27f4ea522ec78f

We should rather stop in `bf_inclusion()` when R < 3.6, but we should not set the requirement to the current release version. I think this is critical and should not go into the next CRAN submission.

**Comment by DominiqueMakowski** [comment]
@mattansb you would be surprised by the number of people using older versions and not wanting to go through the hassle of upgrading...

**Comment by mattansb** [comment]
@DominiqueMakowski but but... [`installr`](https://www.r-statistics.com/2013/03/updating-r-from-r-on-windows-using-the-installr-package/)...

I'm okay with adding an internal check for R version in `bf_inclusion`. I'll do that then.

**Comment by mattansb** [comment]
Okay, I made the changes.
I'm pretty sure the way I internally test the R version could be improved... 😅
I've also suggested `installr` - feel free to remove this from the error message if you'd like.

**Comment by DominiqueMakowski** [comment]
I think the tests fail on oldrel because of that, is it possible to deactivate the tests for bf inclusion if oldrel?

**Comment by strengejacke** [comment]
We could use the same if-switch in the tests.

**Comment by DominiqueMakowski** [comment]
@mattansb do you know the reason why it fails on < 3.6?

**Comment by mattansb** [comment]
I have a hunch. I'll investigate today and try and solve this... Will keep
you posted.

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by mattansb** [comment]
Found a computer with R 3.4, and debugged there.
Got it to work + all test pass.

**Comment by DominiqueMakowski** [comment]
Awesome ☺️ I am sure @strengejacke does the happiness dance 🕺
