### ISSUE TITLE
Bayes factor vignette toc?

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#211]
@DominiqueMakowski any idea why the [bf vignnette](https://easystats.github.io/bayestestR/articles/bayes_factors.html) is missing the table of contents on the right?

**Comment by strengejacke** [comment]
I think this might be due to the customization of the template, see this file:
https://github.com/easystats/bayestestR/blob/master/_pkgdown.yml

**Comment by DominiqueMakowski** [comment]
It shows "true", so I think it is a parameter in the YAML header of the vignette (where it is true instead of something else)

**Comment by mattansb** [comment]
Maybe because the toc is limited in the BF vignette?

```
toc:
  depth: 3
```

**Comment by DominiqueMakowski** [comment]
Maybe, or maybe because there is misspecification: try like this
```
toc: true
toc_depth: 2
```

**Comment by mattansb** [comment]
Done ^_^
