### ISSUE TITLE
informative prior check 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#215]
https://twitter.com/StatModeling/status/1160178750325235713?s=19

"For each parameter (or other qoi), compare the posterior sd to the prior sd. If the posterior sd for any parameter (or qoi) is more than 0.1 times the prior sd, then print out a note: “The prior distribution for this parameter is informative." 

could think of a check_ function to support that...

**Comment by mattansb** [comment]
I like this!
Though this does makes some assumptions about the collected data - that is
it informative (strong priors + strong data ≈ weak priors + weak data in
their affect on posterior width)...
But hopefully no one has uninformative data 😅

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by mattansb** [comment]
Hmmm also worth looking at the comments in the post - seems like some work
has been done on prior appropriatness / sensitivity to priors...

**Comment by DominiqueMakowski** [comment]
I've implemented Gelman's method and Lakeland's method (in the comments of the post)

What do you think?

**Comment by mattansb** [comment]
Looks great! Very useful! Though I wish it wasn't so dichotomous... 🤔 Can we maybe for Lakeland's method also return the %rope?

`simulate_prior` is very useful - I wonder if that can be used to cut-down on bf_params runtime (which currently generates MCMC samples from the true priors). Will play with this when I get back from vacation 🌴🍹 😎

**Comment by DominiqueMakowski** [comment]
> Can we maybe for Lakeland's method also return the %rope?

I was thinking about it, yeah we could :) Also, I wonder if we should ask green and red messages such as in most of the other check_ functions 

> simulate_prior is very useful - I wonder if that can be used to cut-down on bf_params runtime

We should benchmark the two methods indeed :)

Enjoy your vacations!!!

**Comment by mattansb** [comment]
Also, I think Gelman's method should have informative / uninformative, and Lakeland's informative / missinformative, as they test slightly different thinks: Gelman's answers "how strong are your priors" (uninformative = weak), Lakeland answers "how close / appreciate was your prior" (missinformative = wrong).
(maybe also add this in the doc?)

**Comment by DominiqueMakowski** [comment]
> Also, I think Gelman's method should have informative / uninformative

I also agree, initially, I added a different output, but then changed Gelman's to misinformative to consistency across methods. But yes, should revert to uninformative, makes more sense!

**Comment by DominiqueMakowski** [comment]
@strengejacke What are your thoughts on this? Should we add the red/green message? What is still missing from the docs? How to include the continuous index in the case of lakeland's method?

**Comment by mattansb** [comment]
Red / green might imply bad / good, who at least for Gelman's method is irrelevant
