### ISSUE TITLE
Remove priors from output

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#22]
`equivalence_test()` returns results for the complete posterior distribiution. However, if you fit your model with _brms_ and use `sample_prior = TRUE`, then you have parameters for the priors as well, which are most likely of no interest for functions like `equivalence_test()`.

Hence, remove all paramaters starting with `prior_`.

I can work on this issue...

**Comment by DominiqueMakowski** [comment]
Make sense :)

**Comment by strengejacke** [comment]
This is fixed, meanwhile...
