### ISSUE TITLE
HDI and ROPEs alterations

### ISSUE THREAD

**Issue by BrittanyJane** [easystats/bayestestR#226]
Hello :) Thankyou for a great package. I am fairly new to this but think I have grasped how to change code by now. However, when I try to amend the HDI to 95% (rather than 89%) and fix the ROPEs range to -.1 to .1, the output default to the 89% and a ROPE of -4.04 to 4.04. I think my specified priors also still revert to default :( Can someone please help a noobie out and provide some code to stop it going back to default? Thankyou so much.

**Comment by mattansb** [comment]
Hi @BrittanyJane ,

Can you provide an example / snippet of the code you're running? (a [reprex](https://cran.r-project.org/package=reprex) would be best, if possible).

**Comment by DominiqueMakowski** [comment]
Hey @BrittanyJane (and welcome to github!), did you manage to solve your issue?

**Comment by BrittanyJane** [comment]
Hi! Sorry I forgot I posted this and then forgot my login :D Yes I did, thankyou. I was overriding the command with a second package I was trying to integrate (noobie problem, haha).
