### ISSUE TITLE
describe_posterior fails with rstanarm different algorithms (meanfield or fullrank)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#232]
``` r
parameters::model_parameters(rstanarm::stan_glm(Sepal.Length ~ Petal.Width, data = iris, algorithm = "fullrank"))
#> Error in data.frame(Parameter = rownames(s), ESS = s[["n_eff"]], stringsAsFactors = FALSE, : arguments imply differing number of rows: 2, 0
```

<sup>Created on 2019-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
``` r
bayestestR::describe_posterior(rstanarm::stan_glm(Sepal.Length ~ Petal.Width, data = iris, algorithm = "fullrank"))
#> Error in data.frame(Parameter = rownames(s), ESS = s[["n_eff"]], stringsAsFactors = FALSE, : arguments imply differing number of rows: 2, 0
```

<sup>Created on 2019-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
Any idea where it fails?

**Comment by DominiqueMakowski** [comment]
Not yet, just noticed it during some of my data analysis, created issue as a reminder. Will investigate deeper when I have time

**Comment by DominiqueMakowski** [comment]
But I feel it has to do with the diagnostic measures, which are not existing/different when for variational inference

**Comment by strengejacke** [comment]
I assume that debugging this is one of my tasks, since you're not suppoesed to be a pro-RStudio-debug-user! ;-)

**Comment by DominiqueMakowski** [comment]
If you have time please do give it a look, but it should be fairly quick and easy to fix, so if you don't manage I can do it on Thursday (swamped til then) ☺️

**Comment by strengejacke** [comment]
Haha, rstanarm itself fails when calling summary... 😱 

```r
Diagnostics:
Error in x[, c("mcse", "Rhat"), drop = FALSE] : subscript out of bounds
```

And it's apparantly the same issue we had in bayestestR: for fullrank-models, the statistic is `khat`, not `Rhat`.

**Comment by DominiqueMakowski** [comment]
And with algorithm = "meanfield"?

**Comment by strengejacke** [comment]
Same. (fails)
The current commit will not fail, but return NA for ESS statistic, so I will change this so that an informative message is returned.
