### ISSUE TITLE
Problem of ROPE with super large posteriors?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#233]
Rather than an all or nothing threshold (0 - reject, else - undecided), we recommend a more continuous interpretation. But if thresholds have to set, there is another problem. Let's say we say that for instance that a threshold value of 1% in ROPE is reasonable. If the posterior in ROPE < 1%, then it's evidence for rejection of null. 

During my analyses, I came upon a result with a very small % in ROPE, but a pd of 80%. My surprise was quickly dispersed when I saw the width of the posterior. It was so large than the whole ROPE technically represent a small fraction of the posterior. So the % in ROPE of the posterior was small, but the percentage OF THE ROPE in the posterior was 100%. 

Two possibilities of addressing this caveat would be 1) to adjust the % in ROPE depending on the width of the posterior or take into account what the ROPE interval represent compared to the posterior interval.  

However, I feel like the most straightforward and meaningful approach would sequential testing (cf. the SEXIT framework initially formalized here https://github.com/easystats/easystats/issues/33#issuecomment-522239636). Because with a pd > 99% it's safer to investigate the percentage in ROPE (as it suggests that the ROPE is not included in the posterior). 

Would be interesting to formally discuss that in a not-too-distant future... 😉

**Comment by strengejacke** [comment]
I don't see the problem here. If 100% of the ROPE are inside a small portion of the posterior, this means that the posterior covers both positive and negative values, thus it is undecided.

If, like in your case, the pd is still that large, probably the ROPE (range) is mis-specified.

**Comment by DominiqueMakowski** [comment]
Not really, because we're testing the percentage of the posterior in ROPE, which is *not* equivalent to the percentage of the ROPE in the posterior. 

Hence, in my example, the posterior was very wide, covering the whole rope on both sides, still all the points in the ROPE only made up for like less than 1% of the posterior. Hence less than 1% of the posterior was in the ROPE, for which if I was unattentive and tired, I could have said "great! my effect is non-negligible", but then does that make any (common) sense to say that when we're not even sure about the direction of the effect?

**Comment by strengejacke** [comment]
Ah, true. Confused it. In essence, the inference remains the same (effect is non-negligible) , however, the direction is unclear.

But the chance of having _any_ non-negligible effect is still large. :-)

We could combine the rope with clear/unclear direction.

**Comment by mattansb** [comment]
Having a small %ROPE and an undecided PD does, generally, seem weird - the effect is not negligible, but it's hard to say its direction?
In most cases I would say that either the rope is miss-specified, but if this isn't the case - the numbers don't lie!

Solutions:
1. *Interpret* the results as is, with the ambiguity.
2. *Improve* the results by collecting more data (this is one of my fav parts of Bayesian stats).
3. *Avoid* the problem with SEXIT.
4. *Specify* a better prior? For example, if we have an *aprior* hypothesis that *theta > 0* = the prior dist is only positive = the posterior is only positive, and the long negative tail is ignored (this is essentially what happens when a directional BF is computed).

**Comment by mattansb** [comment]
I see 4 is kind of, sort of implemented in `p_significance`. Interesting function!

**Comment by DominiqueMakowski** [comment]
> I see 4 is kind of, sort of implemented in p_significance. Interesting function!

Correct, although it's an early and experimental implementation :) Related to #237

**Comment by DominiqueMakowski** [comment]
Since this is not a real issue, but rather something connected #237, I'll close it :)
