### ISSUE TITLE
Temporarily use [[]] indexing for `get_priors()`

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#245]
`get_priors()` should be fixed as well, affects _bayestestR_.

_Originally posted by @strengejacke in https://github.com/easystats/insight/issues/133#issuecomment-538084572_

**Comment by strengejacke** [comment]
@DominiqueMakowski Do you want to address this? I think iz's _slightly_ more complicated, because in cases like here: https://github.com/easystats/bayestestR/blob/d46fe0ce6d140b69a057006a7a003d629410e913/R/describe_prior.R#L46 you also need to adjust the subsequent code...

**Comment by DominiqueMakowski** [comment]
What's the context?

**Comment by strengejacke** [comment]
https://github.com/easystats/insight/issues/133

**Comment by DominiqueMakowski** [comment]
I don't get why/how get_priors get affected by the renaming of the parameters column

**Comment by strengejacke** [comment]
`get_priors()` currently returns only lower-case column names, and we wanted to change that. So you have to reference to those column names via `[[...]]`.

**Comment by DominiqueMakowski** [comment]
It doesn't seem to be affected, as in toTitleCase will not change "Parameter", so the result is exactly the same

**Comment by strengejacke** [comment]
Not sure. toTitleCase results in `Adjusted_scale`, but I would change the column name in `insight::get_priors()` to `Adjustes_Scale`.

**Comment by DominiqueMakowski** [comment]
But if that change happens in insight it doesn't affect bayestestR, the latter just takes the column names, whatever they are, and uppercase the first letters. So I am not sure where is the issue here, do you have an example?

**Comment by strengejacke** [comment]
Does toTitleCase automatically converts all other letters to lowercase?

**Comment by DominiqueMakowski** [comment]
```
tools::toTitleCase(c("aHaHa", "hello"))
[1] "aHaHa" "Hello"
```

Seems that it has a more complex behaviour as it won't capitalize words like "for" for example

**Comment by strengejacke** [comment]
Ok, so if we want to harmonize column names in insight, we have to address this issue here sooner or later?

**Comment by DominiqueMakowski** [comment]
> we have to address this issue here sooner or later?

I don't think so, as it picks whatever the names are in insight without modifying them (aside from titlecase) and without calling them by name

**Comment by strengejacke** [comment]
I think so, because...

``` r
tools::toTitleCase("Adjusted_Scale")
#> [1] "Adjusted_Scale"
```

and we use in bayestestR:
https://github.com/easystats/bayestestR/blob/d46fe0ce6d140b69a057006a7a003d629410e913/R/describe_prior.R#L50

**Comment by DominiqueMakowski** [comment]
aaaaaaaaah I finally get what you mean ^^

**Comment by DominiqueMakowski** [comment]
let me hotfix

**Comment by strengejacke** [comment]
And _after_ these temporary fixes, we can revise insight's get_priors(), so we slowly change from "old" to "new" colmn names in insight, without breaking package functions.
