### ISSUE TITLE
equivalence_test differs from sjstats::equi_test

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#25]
The covered percentage in ROPE differs between those two functions. We need to check which of these both are probanly wrong, or if the computational basis just differs.

**Comment by strengejacke** [comment]
Ok, was a bug in sjstats...

**Comment by DominiqueMakowski** [comment]
Hope it wasn't too big

**Comment by strengejacke** [comment]
No, I just returned the percentage inside rope from the whole posterior, instead of just the proportion of posterior that was inside the 95% HDI.

**Comment by DominiqueMakowski** [comment]
It's not a bug then, you were just ahead of your time 😆 (since it might be more stable and sensitive, in the end, than using the HDI)
