### ISSUE TITLE
Plotting rhat values?

### ISSUE THREAD

**Issue by pdwaggoner** [easystats/bayestestR#254]
Hi guys - I thought I would just open an issue ticket with this question. I don't do much with Bayesian things. But I am working on a paper with a buddy where we fit a Bayesian IRT model and we need to generate a plot of rhat values. Can this be done with `bayestestR`? Thanks!

**Comment by DominiqueMakowski** [comment]
What kind of plot do you have in mind?

**Comment by pdwaggoner** [comment]
Well, we fit an IRT model across 3 chains of 20,000 iterations and want to plot the rhat values in some intuitive way to discuss convergence. Is there any support for this sort of thing in `bayestestR`?

**Comment by DominiqueMakowski** [comment]
Not currently, but if you have an example of a plot and how to do it (i.e., if you manage to create the plot that you desire for your project 😁 ), we could think about adding support for it!
