### ISSUE TITLE
p_significance returns "wrong" results or wrong description?

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#256]
From https://easystats.github.io/bayestestR/reference/p_significance.html

> Returns: Values between 0.5 and 1 corresponding to the probability of practical significance (ps).

However, the example shows:

```r
# Simulate a dataframe of posterior distributions
# -----------------------------------------------
df <- data.frame(replicate(4, rnorm(100)))
p_significance(df)
#> # Probability of Significance (ps [0.10])
#> 
#>  Parameter     ps
#>         X1 49.00%
#>         X2 47.00%
#>         X3 49.00%
#>         X4 48.00%
```

**Comment by mattansb** [comment]
Mistake in the description - the range is 0-1. We might want this to be larger than 0.5, but this depends on the ROPE - for example, here almost all of the distribution is inside the ROPE:
![image](https://user-images.githubusercontent.com/35330040/67675851-e4bd7200-f988-11e9-9602-3fbf9d68be46.png)

**Comment by DominiqueMakowski** [comment]
Yes, error in the description
