### ISSUE TITLE
rope_range(): allow for a flexible "method" paradigm

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#26]
Altough for now, there is only the "kruschke2018" method, I might be interesting to prepare the terrain for an easy switch between methods of default values selection, in a similar way to the [`interpret_*`](https://easystats.github.io/report/articles/interpret_metrics.html#standardized-difference-d-cohens-d) functions in report. As with every rules of thumb, I can foresee a debate surrounding the appropriate values in the literature, so we might as well support them here :)

**Comment by strengejacke** [comment]
Would you consider this as something for the initial release or more a long term goal?

**Comment by DominiqueMakowski** [comment]
Long term goal as there is currently no other method than Krushke's, but this idea might inform the way the function is written so that it will be simpler changing the "backend". Maybe for now, we could put the "main" function into an internal `.rope_range_kruschke()` that would be used by the main function (just a wrapper). In the future, **if there is ever such need**, we could easily add more variants and switching between them with an argument. 

This would mimic in a way the current behaviour of `performance` that has the `r2_author` written explicitly. Also, maybe this way it would emphasise code-wise the fact that the "default" ROPE range values are based on literature suggestions and that there is no "mathematical way" to find the correct ROPE range (i.e., it is a Human-defined thing).

**Comment by DominiqueMakowski** [comment]
Not relevant for now. This is something we can still add later if there is ever some new methods in the literature for specifying rope range differently.
