### ISSUE TITLE
Restriction models for factors with 3+ levels

### ISSUE THREAD

**Issue by courtneygoodridge** [easystats/bayestestR#260]
I'm new to Bayesian stats and I have been learning through your helpful online resources. I have recently been following the guide on how to implement restriction models (https://easystats.github.io/bayestestR/articles/bayes_factors.html#specifying-correct-priors-for-factors-with-more-than-2-levels)

However I have ran into some issues which hopefully someone can help with.

Firstly, an example of my dataframe:

`structure(list(heading = structure(c(4L, 1L, 4L, 3L, 4L, 3L, 
4L, 3L, 4L, 1L, 4L, 4L, 4L, 4L, 4L, 3L, 3L, 3L, 4L, 4L), contrasts = "contr.bayes", .Label = c("0.5", 
"1", "1.5", "2"), class = "factor"), FirstSteeringTime = c(0.433389999999999, 
0.449999999999989, 0.383199999999988, 0.499899999999997, 0.566800000000001, 
0.58329999999998, 0.5, 0.449799999999982, 0.566600000000022, 
0.466700000000003, 0.433499999999981, 0.466799999999978, 0.549900000000036, 
0.483499999999992, 0.533399999999972, 0.433400000000006, 0.533200000000022, 
0.450799999999999, 0.45022, 0.46651), pNum = c(1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L
)), row.names = c(NA, 20L), class = "data.frame")`

I fit my model as follows. As I am working with RT data, I set the family as Gamma with identity link function:
`contrasts(magnitudedata$heading) <- "contr.bayes"`
`fit_bayes <- stan_glm(FirstSteeringTime ~ heading, family = Gamma(link ="identity"), adapt_delta = 0.999, data = magnitudedata)`

I then compute my posterior marginal means and my restriction:
`bayes_sum <- emmeans(fit_bayes, ~ heading)`
`hyp <- c("2 < 1.5 & 1.5 < 1 & 1 < 0.5")`

Following the example, I then attempt to compute the Bayes factor for my restriction model:
`bayesfactor_restricted(bayes_sum, fit_bayes, hypothesis = hyp)`

However when I run this code, I get the following error message:
`Error in x@post.beta %*% t(x@linfct[, use, drop = FALSE]) : non-conformable arguments`

I have tried to decipher the message but I have had no luck. Even if i set a weakly informative prior such as cauchy(0.5, 0.1), I generate the same error.

I then try to follow the example more exactly by setting the family to gaussian() but I get the following result. Again, even if a set a weakly informative prior of cauchy(0.5, 0.1), I get the same result:

`contrasts(magnitudedata$heading) <- "contr.bayes"`
`fit_bayes <- stan_glm(FirstSteeringTime ~ heading, family = gaussian(), adapt_delta = 0.999, data = magnitudedata)`
`hyp <- c("2 < 1.5 & 1.5 < 1 & 1 < 0.5")`
`bayes_sum <- emmeans(fit_bayes, ~ heading)`
`bayesfactor_restricted(bayes_sum, fit_bayes, hypothesis = hyp)`

![image](https://user-images.githubusercontent.com/44811378/69818858-96a0c600-11f5-11ea-9867-1313d63e2ab9.png)

Does anybody have any ideas where I might be going wrong? When I set my own contrasts via a contrast matrix, I can compute a Bayes factor for each one using the bayesfactor_parameters() function. However this restriction model would be ideal. Any help is appreciated, thank you!

**Comment by mattansb** [comment]
Hi @courtneygoodridge !

I think there a couple of things going on here:
1. At least in the example you give, your factor `heading` don't have any values of `"1"`, so the model can't be restricted based on this level.
2. When parameters / estimate names are numbers, the names in `hypothesis` must be defined with back-ticks (else there are just numeric values), as follows:
```R
hyp <- c("`2` < `1.5` & `1.5` < `1` & `1` < `0.5`")
```
3. There is some problem with the `Gamma` family that I need to look into :/
But for now, this can be circumvented by:
    1. Fitting a prior only model
    2. Extracting the same `emmean` estimates with this model.
    3. Passing the prior and posterior estimates to `bayesfactor_restricted`.

All together, this looks like this:
``` r
library(rstanarm)
library(bayestestR)
library(emmeans)

magnitudedata <- structure(
  list(heading = structure(c(4L, 1L, 4L, 3L, 4L, 3L, 4L, 3L, 4L, 1L, 4L, 4L, 4L, 4L, 4L, 3L, 3L, 3L, 4L, 4L),
                           .Label = c("0.5", "1", "1.5", "2"), class = "factor"),
       FirstSteeringTime = c(0.433389999999999, 0.449999999999989, 0.383199999999988, 0.499899999999997, 0.566800000000001, 0.58329999999998, 0.5, 0.449799999999982, 0.566600000000022, 0.466700000000003, 0.433499999999981, 0.466799999999978, 0.549900000000036, 0.483499999999992, 0.533399999999972, 0.433400000000006, 0.533200000000022, 0.450799999999999, 0.45022, 0.46651),
       pNum = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L )),
  row.names = c(NA, 20L), class = "data.frame"
)

contrasts(magnitudedata$heading) <- "contr.bayes"

fit_bayes <- stan_glm(FirstSteeringTime ~ heading,
                      family = Gamma(link ="identity"),
                      adapt_delta = 0.999,
                      data = magnitudedata)
bayes_sum <- emmeans(fit_bayes, ~ heading)
#> Warning: contrasts dropped from factor heading due to missing levels

## Do this again, with prior samples
fit_bayes_prior <- update(fit_bayes, prior_PD = TRUE)
bayes_sum_prior <- emmeans(fit_bayes_prior, ~ heading)
#> Warning: contrasts dropped from factor heading due to missing levels

## Can't condition on "1" + added backticks:
hyp <- c("`2` < `1.5` & `1.5` < `0.5`")

## Instead of passing the original model to "prior", pass the prior-based estimates:
bayesfactor_restricted(posterior = bayes_sum,
                       prior = bayes_sum_prior,
                       hypothesis = hyp)
#> # Bayes Factor (Order-Restriction)
#> 
#>                   Hypothesis P(Prior) P(Posterior) Bayes Factor
#>  `2` < `1.5` & `1.5` < `0.5`     0.12          0.2         1.58
#> 
#> * Bayes factors for the restricted movel vs. the un-restricted model.
```

<sup>Created on 2019-11-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Please let me know if this works for you or if you have any more questions!

I will look further into why this fails on `Gamma` family...

**Comment by courtneygoodridge** [comment]
Hi @mattansb !

Thank you for your help! This solution works!

I do have one question though just to help my understanding of the method you've used for the solution. Regarding this part:

`fit_bayes_prior <- update(fit_bayes, prior_PD = TRUE)` 
`bayes_sum_prior <- emmeans(fit_bayes_prior, ~ heading)`

The  `prior_PD` argument relates to the "prior predictive distribution", however I am not sure what this actually is. Is it equivalent to the posterior predictive distribution (distribution for future predicted data based on data already seen) but instead of using data already seen, it uses the prior distribution that I specify?

Then I assume that this part:

`bayes_sum_prior <- emmeans(fit_bayes_prior, ~ heading)`

creates my marginal means based upon this new prior model?

Thanks again for your help and I'll keep a look out for the `Gamma` fix!

**Comment by mattansb** [comment]
Setting `prior_PD = TRUE` generates samples from the prior distributions of the parameters ([the name is somewhat confusing](https://discourse.mc-stan.org/t/what-does-prior-pd-sample/11384/5)...). So `fit_bayes_prior` is the same as `fit_bayes`, just with draws from the priors instead of the posteriors.

> Then I assume that this part:
`bayes_sum_prior <- emmeans(fit_bayes_prior, ~ heading)`
creates my marginal means based upon this new prior model?

Yes, that is correct.

**Comment by courtneygoodridge** [comment]
Perfect, thank you for your help!

**Comment by strengejacke** [comment]
@mattansb Could you please also update the news? Thanks! :-)

**Comment by mattansb** [comment]
[Done](https://github.com/easystats/bayestestR/commit/3a5ad199970dd5cad340de850f21205e6258dae2#diff-8312ad0561ef661716b48d09478362f3R12)!
