### ISSUE TITLE
Using posteriors as new priors (replication analysis)

### ISSUE THREAD

**Issue by courtneygoodridge** [easystats/bayestestR#278]
I have 2 experiments that I aim to analyse. The second is a small iteration of the first, and thus I aim to use the Bayesian analysis of the first to inform my priors of the second. In my first experiment, I use a normal distribution prior centred at 0 with a scale of 0.3 to analyse my data:

An example dataset:

`dat <- structure(list(heading = c(2, 0.5, 2, 1.5, 2, 1.5, 2, 1.5, 2, 0.5, 2, 2, 2, 2, 2, 1.5, 1.5, 1.5, 2, 0, 2, 1, 1.5, 2, 1, 0.5, 1, 0.5, 1.5, 0.5), FirstSteeringTime = c(0.433389999999999, 0.449999999999989, 0.383199999999988, 0.499899999999997, 0.566800000000001, 0.58329999999998, 0.5, 0.449799999999982, 0.566600000000022, 0.466700000000003, 0.433499999999981, 0.466799999999978, 0.549900000000036, 0.483499999999992, 0.533399999999972, 0.433400000000006, 0.533200000000022, 0.450799999999999, 0.45022, 0.48342000000001, 0.46651, 0.68336, 0.483400000000003, 0.5167, 0.383519999999997, 0.583200000000005, 0.449999999999989, 0.58329999999998, 0.4999, 0.5334)), row.names = c(NA, 30L), class = "data.frame")`

` fit_1 <- stan_glm(FirstSteeringTime ~ heading, family = Gamma(link = "identity"), prior = normal(0, 0.3), adapt_delta = 0.999, data = dat)
`

Using this model I can compute Bayes factors, investigate the posterior distributions etc. However I am wondering how I can use the posteriors of the fit_1 model to inform priors of my second model for experiment 2.

It does not seem as simple as drawing from the posterior of the first model, and using this in the priors argument of the second model:

`posteriors <- insight::get_parameters(fit_1)
`

`dat2 <- structure(list(heading = structure(c(2L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 1L, 1L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 1L, 2L, 1L, 1L, 2L, 1L, 2L, 1L, 1L, 1L, 1L, 1L), contrasts = "contr.bayes", .Label = c("1", "2"), class = "factor"), startingpos = structure(c(3L, 1L, 3L, 3L, 2L, 3L, 2L, 3L, 1L, 1L, 3L, 2L, 2L, 1L, 1L, 1L, 3L, 3L, 1L, 2L, 2L, 2L, 2L, 3L, 2L, 2L, 3L, 3L, 2L, 1L), contrasts = "contr.bayes", .Label = c("1", "2", "3"), class = "factor"), FirstSteeringTime = c(0.3000240576829, 0.3833560075234, 0.4333325988244, 0.332885282886096, 0.349735018357208, 0.500228955489106, 0.33254630198401, 0.166676577506308, 0.400026140468498, 0.933583287728609, 0.366613128009007, 0.400152315016001, 0.466582308819014, 0.43335584150401, 0.516691111726999, 0.383459543097199, 0.483226482407986, 0.416576739631978, 0.783127987777988, 0.449786605031989, 0.283220203865, 0.416811581253, 0.383292920249005, 0.400114583392991, 0.18360026695899, 0.416630167609981, 0.500080141967999, 0.466509864102989, 0.183366330894984, 0.69996205708)), row.names = c(NA, 30L), class = "data.frame")
`

`fit_2 <- stan_glm(FirstSteeringTime ~ heading * startingpos, family = Gamma(link = "identity"), priors = posteriors, adapt_delta = 0.999, data = dat2)
`
Error: passing unknown arguments: priors.

Is there a way of using Bayesian analysis from one experiment to inform priors of the next (I'm sure there is, I'm just not sure how!).

Any help is most appreciated, thank you!

**Comment by mattansb** [comment]
Hi @courtneygoodridge ,

I think you can do this using the "replications analysis" - you can read about it here [https://doi.org/10.3758/s13428-018-1092-x](https://doi.org/10.3758/s13428-018-1092-x).
The idea is to build two models:
1. Model based on first sample.
2. Model based on both first sample and second sample **together**.

Thus the second model represents the accumulated posterior of both data sets. (The paper goes more into detail about this and what should be analysed exactly.)

Alternatively, you can use the mean + sd of the posteriors of the first sample as the location and scale of a *normal* prior for the second sample.

**Comment by courtneygoodridge** [comment]
Thank you for your advice! @mattansb
