### ISSUE TITLE
[doc] outputs do not match with description

### ISSUE THREAD

**Issue by StevenLi-DS** [easystats/bayestestR#279]
In the following example, some numbers in the outputs does not match with the ones in the description.
https://easystats.github.io/bayestestR/articles/example1.html#point-estimate

For example:
![image](https://user-images.githubusercontent.com/33796896/72907968-cacec980-3d02-11ea-99d9-3b0f5b58e4ed.png)

![image](https://user-images.githubusercontent.com/33796896/72907867-a4109300-3d02-11ea-986c-2cb2a0875d4a.png)

![image](https://user-images.githubusercontent.com/33796896/72908088-ff428580-3d02-11ea-9957-332b05dd9cc9.png)

**Comment by mattansb** [comment]
Good catch!

**Comment by StevenLi-DS** [comment]
https://easystats.github.io/bayestestR/articles/example1.html#point-estimate

![image](https://user-images.githubusercontent.com/33796896/73295080-08d15f00-41d5-11ea-8f7f-a7c11b744108.png)

I think it should be `rope_range` right? Btw, is that ok to assign a variable that has the same name with a function in r?

**Comment by strengejacke** [comment]
> Btw, is that ok to assign a variable that has the same name with a function in r?

It's possible, and R is clever enough to know whether the function or the variable is meant, but I personally try to avoid using function names as variable names.
