### ISSUE TITLE
Function for credible intervals

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#28]
I think we should also add a function that returns the credible intervals (not HDI) as well, for convenience reasons, where the output meets our needs.

In case of transformation, eg having odds ratios, you can also exp the CI, but not the HDI.

See https://discourse.mc-stan.org/t/exponentiation-or-transformation-of-point-estimates/7848

**Comment by DominiqueMakowski** [comment]
That's a very good point indeed!!! (it struck me as obvious upon reading your issue and I now I wonder how is it possible that I had never thought of it 😅)

**Comment by DominiqueMakowski** [comment]
If I understand correctly, CIs based on percentile (equal-tailed intervals) would be more suited for binomial data. However, CIs based on the HDI could still be better for other types of models... is that right?

We could have a function, e.g. `ci()` with a parameter `method="hdi"` or `method="percentile"` that would return the two versions of what can be further referred to as credible interval. Also, a "default" argument would compute the most appropriate CIs based on the data/the model at hand. Would that do the trick?

**Comment by strengejacke** [comment]
Having one function with `method`-argument would maybe indeed be a good solution.

> However, CIs based on the HDI could still be better for other types of models... is that right?

You can use either CI or HDI for any model, however, HDI is useful / appropriate if it's reported on the scale of the linear predictor. For instance, for a logistic regression, reporting log-odds and HDI is fine. Reporting odds ratios with exponentiated HDI may be misleading, because in one case (log-odds scale) the HDI does _not_ include "zero", while on the odds ratio scale, it may include "zero" (resp. "one" in this case). In frequentist terms: on the log-scale, the point-estimate is "significant", while it's no longer significant on the exponentiated scale.

So for functions like `equivalence_test()`, we should keep using HDI. But if you report estimates on the exponentiated scale, the credible interval (CI) is more appropiate, because both on log- and exp-scale, the CI "preserves" the "(non-)significance".

**Comment by strengejacke** [comment]
Closing in favour of #30
