### ISSUE TITLE
Brain Bug: logical operations

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#282]
@DominiqueMakowski @mattansb Guys, we have made a stupid mistake, meaning that pkgs like bayestestR now still fail ("warn") for CRAN checks...

```if (!requireNamespace("rstanarm", quietly = TRUE) &&
    !requireNamespace("dplyr", quietly = TRUE) &&
    !requireNamespace("ggplot2", quietly = TRUE)) {
  knitr::opts_chunk$set(eval = FALSE)
}
```

**should be**

```
if (!requireNamespace("rstanarm", quietly = TRUE) ||
    !requireNamespace("dplyr", quietly = TRUE) ||
    !requireNamespace("ggplot2", quietly = TRUE)) {
  knitr::opts_chunk$set(eval = FALSE)
}
```

`&&` => `||`

**Comment by DominiqueMakowski** [comment]
What do you mean?

**Comment by strengejacke** [comment]
I think I have fixed all occurrences... In the vignettes, we have `!requireNamespace() && !requireNamespace()` etc. But it should be `||`, not `&&`. Else, the vignettes will be compiled, unless _all_ packages are _unavailable_. However, it should only compile if _all_ packages are _available_.

So, for bayestestR 0.5.1, we now still have warnings on CRAN:
https://cran.r-project.org/web/checks/check_results_bayestestR.html

Which probably should be fixed the next time (we could wait some days for rstanarm to be fixed, then the warnings will disappear).

**Comment by mattansb** [comment]
oops :/

**Comment by strengejacke** [comment]
damn, I hope we have fixed every occurence now, and in the right way... better closing this - at some point, we also need _hope_ to fix bugs. ;-)
