### ISSUE TITLE
weighted_posteriors fails when a model with very low posterior probability is included 

### ISSUE THREAD

**Issue by frankhezemans** [easystats/bayestestR#286]
**Describe the bug**
Thanks for the great package! I'm interested in computing weighted posterior estimates for regression coefficients. I've got a relatively large number of regression models under consideration. When I try to run `weighted_posteriors`, I receive an "out of bounds" error message, which I believe is due to a rounding issue when computing the weighted number of samples (see below).

**To Reproduce**
Here's a quick reproducible example:
```{r}
library(BayesFactor)
library(bayestestR)

# compute Bayes Factor for 1023 different regression models
test_BF <- BayesFactor::regressionBF(mpg ~ ., data = mtcars)

weighted_est <- bayestestR::weighted_posteriors(test)
#Error in value[[jvseq[[jjj]]]] : subscript out of bounds
```
**Expected behaviour**
A data frame with posterior distributions for each parameter (weighted across models).

**Potential solution**
After inspecting the `weighted_posteriors` code, I believe this error message is caused by the calculation of the weighted number of samples. When some of the models under consideration have a relatively low posterior model probability, the weighted number of samples for those models get rounded down to zero, which causes issues further on in the function. Specifically:

```{r}
# Compute weighted number of samples
nsamples <- 4000
weighted_samps <- round(nsamples * postProbs)
# Problem: For a given model [i], if postProbs[i] is extremely small,
# weighted_samps[i] will be zero

# from .weighted_posteriors
for (m in seq_along(weighted_samps)) {
  temp_params <- params[[m]]
  temp_params <- temp_params[sample(nrow(temp_params),size = weighted_samps[m]), ,drop = FALSE]
  # Problem: If weighted_samps[m] is zero, then an empty vector
  # will be assigned to temp_params
```
It seems that this problem could be solved by increasing `nsamples` to an arbitrarily large number, e.g. 10000.

**Specifiations**
 - Platform: x86_64-w64-mingw32/x64 (64-bit)
 - R version 3.6.1
 - BayesFactor Version 0.9.12-4.2
 - bayestestR Version 0.5.2

**Comment by mattansb** [comment]
Hi @frankhezemans - thanks for the bug report;
This should now be fixed.

``` r
library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.2. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************
library(bayestestR)

# compute Bayes Factor for 31 different regression models
test_BF <- regressionBF(mpg ~ cyl + disp + hp + drat + wt, data = mtcars)

weighted_est <- weighted_posteriors(test_BF)
#> Warning: Cannot sample from BFBayesFactor model with intercept only (model prob = 0%).
#> Ommiting the intercept model.
```
You can also see the actual weights in the `weights` attribute.
```R
attr(weighted_est, "weights")
#>                          Model weights
#> 1                            1       0
#> 2                          cyl      13
#> 3                         disp       9
#> 4                           hp       0
#> 5                         drat       0
#> 6                           wt      55
#> 7                   cyl + disp      11
#> 8                     cyl + hp       4
#> 9                   cyl + drat       4
#> 10                    cyl + wt    1246
#> 11                   disp + hp       6
#> 12                 disp + drat       2
#> 13                   disp + wt      38
#> 14                   hp + drat       4
#> 15                     hp + wt     946
#> 16                   drat + wt      12
#> 17             cyl + disp + hp       3
#> 18           cyl + disp + drat       3
#> 19             cyl + disp + wt     209
#> 20             cyl + hp + drat       3
#> 21               cyl + hp + wt     491
#> 22             cyl + drat + wt     174
#> 23            disp + hp + drat       4
#> 24              disp + hp + wt     134
#> 25            disp + drat + wt       7
#> 26              hp + drat + wt     293
#> 27      cyl + disp + hp + drat       1
#> 28        cyl + disp + hp + wt     123
#> 29      cyl + disp + drat + wt      35
#> 30        cyl + hp + drat + wt      92
#> 31       disp + hp + drat + wt      51
#> 32 cyl + disp + hp + drat + wt      27
```

<sup>Created on 2020-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by frankhezemans** [comment]
Thanks for the update! There's a new bug though: If the BayesFactor object doesn't contain an intercept-only model (e.g. when you manually specified the null model), the line `intercept_only <- which(BFMods$Model == "1")` will assign an empty value to `intercept_only`. This causes an error for the subsequent line `if (m == intercept_only) {`, "argument is of length zero".

**Comment by strengejacke** [comment]
ok, should be fixed now. @mattansb the object `priorProbs` is defined, but not in use - can you please check that?

**Comment by mattansb** [comment]
Fixed + added tests
