### ISSUE TITLE
describe_posterior() seems to break if an interaction term is included in the model

### ISSUE THREAD

**Issue by masurp** [easystats/bayestestR#292]
Hey everyone, 

first of all, thank you for your great work! I really enjoy using the easyverse.

I recently stumbled across this error after including an interaction term in a multilevel model and trying to describe the posteriors using the function `describe_posterior()`of your package.  

```{r}
#> Error in `[.data.frame`(as.data.frame(model), , valid_parameters): undefined columns selected 
```
Couldn't figure out what was wrong. I was able to reproduce the error with the simple example below. So: Is this a known problem? I was wondering whether anyone has encountered this before. Is there any reason why it should break? The sampling with brms should not be the problem as the brmsfit object looks fine.

```{r}
# Packages
library(brms)
#> Loading required package: Rcpp
#> Registered S3 method overwritten by 'xts':
#>   method     from
#>   as.zoo.xts zoo
#> Loading 'brms' package (version 2.12.0). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar
library(bayestestR)
# simulate data
set.seed(10)
x <- rnorm(500)
z <- rnorm(500)
y <- 0.5*x + 1.5*(z*x) + 2*x + rnorm(500)
data <- data.frame(x, z, y)

# Estimate model
lm <- brm(y ~ x*z, data = data, chains = 1)
#> Compiling the C++ model
#> (Skipping the sampling procedure here, to shorten the example)
describe_posterior(lm)
#> Error in `[.data.frame`(as.data.frame(model), , valid_parameters): undefined columns selected

# Testing the brmsfit object
lm
#> Family: gaussian 
#> Links: mu = identity; sigma = identity 
#> Formula: y ~ x * z 
#> Data: data (Number of observations: 500) 
#> Samples: 1 chains, each with iter = 2000; warmup = 1000; thin = 1;
#> total post-warmup samples = 1000
#> 
#> Population-Level Effects: 
#>            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> Intercept     0.02      0.05    -0.08     0.12 1.00     1261      811
#> x             2.54      0.05     2.44     2.62 1.00     1517      820
#> z             0.10      0.05     0.00     0.19 1.00     1183      827
#> x:z           1.56      0.05     1.47     1.67 1.00     1017      712
#> 
#> Family Specific Parameters: 
#>           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> sigma     1.08      0.03     1.01     1.14 1.00     1593      833
#> 
#> Samples were drawn using sampling(NUTS). For each parameter, Bulk_ESS
#> and Tail_ESS are effective sample size measures, and Rhat is the potential
#> scale reduction factor on split chains (at convergence, Rhat = 1). 
```
bayestestR is Version 0.5.2

Thanks in advance! Stay safe in these troubling times.

**Comment by masurp** [comment]
P.S. The function works fine if I do not include an interaction term.

**Comment by strengejacke** [comment]
For me, it works fine, so I guess this bug might have been fixed already... Can you please update [insight](https://github.com/easystats/insight) from GitHub, and check again? And if this does not solve this issue, maybe also update bayestestR from GitHub?

**Comment by masurp** [comment]
Thanks for the fast reply. I had to remove and reinstall all easystats packages, and get the dev version of bayestestR from github. Now it does work. Sorry for bothering you with this. 

(Didn't think it would be solved with reinstallation as the function was working fine with other models, but sometimes you don't really know whats wrong, I guess). 

Thanks for your help and best regards!
