### ISSUE TITLE
'Bias adjusted' centrality and uncertainty measures for models fit using transformed variables and/or random effects

### ISSUE THREAD

**Issue by nahorp** [easystats/bayestestR#309]
Hello,

I came across bias adjustment for frequentist models while reading the [detailed vignette in the `emmeans` package](https://cran.r-project.org/web/packages/emmeans/vignettes/transformations.html#bias-adj) and wondered if the same applied to Bayesian models as well. Indeed, [`emmeans` have a small section on this](https://cran.r-project.org/web/packages/emmeans/vignettes/sophisticated.html#bias-adj-mcmc).

Could something like this be introduced in `bayestestR` using `bias.adjust` and `sigma` arguments (or anything else similarly named) to relevant functions?

Thank you

**Comment by mattansb** [comment]
What functions did you have in mind?

Note that the beauty of working with posterior samples, is that you can do whatever you like to the posteriors (transform, any computation...) and then pass the transformed samples to any of the `bayestestR` functions to have then analyzed.

**Comment by nahorp** [comment]
Ah, apologies. I just realised that this is better suited to the `modelbased` package, I'll post it there.
