### ISSUE TITLE
bayesfactor() example fails

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#313]
See https://github.com/easystats/bayestestR/runs/719465840#step:10:105

The problem seems to be that `bayesfactor()` has more arguments (like `effects`) than `bayesfactor_parameters()`, so the `effects`-argument is passed down to bayesfactor_parameters via `...`:
https://github.com/easystats/bayestestR/blob/d2b4a040bc7a5da45f47fb3bdad2be5a8c62bb40/R/bayesfactor.R#L79

That function, in turn, passes `...` (including the `effects`-arg, which is now in `...`) down this this function:
https://github.com/easystats/bayestestR/blob/d2b4a040bc7a5da45f47fb3bdad2be5a8c62bb40/R/bayesfactor_parameters.R#L330

which in turn passes it further to `logspline(...)` (and that one fails).

**Solution**

Either don't pass `...` to logspline, or let bayesfactor_parameters have at least all those arguments that `bayesfactor()` has (i.e. adding e.g. `effects`), even if not used / ignored.

@mattansb ?

**Comment by mattansb** [comment]
Solution 2 - get rid of `bayesfactor()`? (Which I totally forgot existed)

But I'm gonna opt for solution 3 - make a wrapper around `logspline::logspline`.

https://github.com/easystats/bayestestR/commit/a32ba55c7a7180a52c8d192b96516a0d44304054#diff-ded0ae8d1c45311cbc7b9889345bd0dbR329-R340

Seem to for now.

**Comment by mattansb** [comment]
Seems to be working now, no?

Closing this (:

**Comment by strengejacke** [comment]
Haven't checked, but I believe in you...

**Comment by mattansb** [comment]
Haha good luck to us both ^_^
