### ISSUE TITLE
Vignette builder

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#32]
I can't check the package because vignettes can't be built. The vignette index is missing. Any ideas? Or is it because I'm testing the dev branch?

**Comment by DominiqueMakowski** [comment]
Weird, never had that error message 😕 Maybe turn it off and on again 😶

**Comment by strengejacke** [comment]
```r
devtools::build_vignettes()
#> NULL
```

???

**Comment by strengejacke** [comment]
You are the maintainer, so I leave it up to you to do the final steps for submission. :-)

**Comment by DominiqueMakowski** [comment]
Is your error still happening?

**Comment by strengejacke** [comment]
`devtools::build_vignettes()` still return `NULL` for me... strange, but in the end, it must pass CRAN checks, than it's ok ;-)

**Comment by DominiqueMakowski** [comment]
That's super weird though

**Comment by DominiqueMakowski** [comment]
you were right! it also returns NULL for me (I hadn't run the command separately). Investigating

**Comment by DominiqueMakowski** [comment]
The vignette builder parameter was missing from the vignettes. It takes quite some time to build (due to the ggplots in the indices comparison), but it works.

**Comment by strengejacke** [comment]
I have the same issue now with _performance_ and don't know how to fix this... strange.

**Comment by DominiqueMakowski** [comment]
I just remembered that, don't hesitate to ping me!

The reason why vignettes were not building is because it missed this paragraph of the yaml header in the vignette:

```
vignette: >
  %\VignetteIndexEntry{Get Started with Bayesian Analysis}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
```

**Comment by strengejacke** [comment]
Yes, but I had this paragraph included... Strange. Also entries in DESCRIPTION.

**Comment by DominiqueMakowski** [comment]
Because previously in bayestestR there was only one of the three lines, and it doesn't work if it's not specified exactly as above (with the percentages and such). But if you have that and it doesn't work either... strange indeed 😕
