### ISSUE TITLE
Bayes Factors for model comparison with different random effects structure

### ISSUE THREAD

**Issue by nahorp** [easystats/bayestestR#326]
Hello,

I want to do Bayesian Model Averaging involving 19 models (intercept only model + 18 models involving combinations of main and/or interaction effects with the three categorical predictors I have, all run via `brm`) and then go via the Inclusion Bayes Factors route (thus, using `bf_models` first and then `bf_inclusion`). My questions are as follows,

1) I want to fit each model with a maximal random effect structure. That is, `m1 <- A * B + (A * B | id)` and `m2 <- A * B * C + (A * B * C | id)` before passing the models through to `bf_models`. I did a test for `bf_inclusion` with 2 models and while it works, there are random effect terms in there as well. I am _only_ interested in the fixed effects and while my guess is that those random effect terms won't affect the computation of the prior and posterior probabilities of the fixed effect predictors in the `bf_inclusion` output, I just wanted to make sure that is indeed the case...

2) Following on from this, I then want to use the `emmeans` package to look at certain contrasts. Now I have [read the blog post about where I can do this for a single model](https://easystats.github.io/blog/posts/bayestestr_emmeans/) but is there a way to do this for the posterior distribution from the output of the `weighted_posteriors`?

3) Lastly, is there a reference for a recommendation of at least 40,000 posterior samples for Bayes Factors?

Thank you for reading and I would appreciate your help and advice in this regard. Thank you :)

**Comment by mattansb** [comment]
Hi Rohan,

1. Since `bayesfactor_inclusion()` computes the BF per term, and not per model, if there are terms you're not interested in, you can just ignore them, I guess. However, since this BF is based on the provided models, your use-case might give biased results, as fixed effects would be paired with random effects - so the same models that do or don't have a fixed effects, also do or don't have the random effect. For example:

``` r
library(bayestestR)
library(lme4)
#> Loading required package: Matrix
library(ggplot2)
library(magrittr)

## Make data
set.seed(111)
n <- 30
k <- 6
x <- seq_len(k)
slopes <- distribution_normal(n)
e <- sample(distribution_normal(k, sd = 0.3))

data <- lapply(slopes, function(b) {
  data.frame(x = x,
             y = b*x + e)
})
data <- do.call("rbind", data)
data$ID <- rep(seq_len(n), each = k)

## Clearly no fixed effect, only a random effect
ggplot(data, aes(x, y, color = factor(ID))) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE)
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/9jaRfbS.png)

``` r


## But...
mod1 <- lm(y ~ 1, data = data)
mod2 <- lmer(y ~ x + (x | ID), data = data)
#> boundary (singular) fit: see ?isSingular

# Large BF inclusion for the fixed effect
bayesfactor_models(mod1, mod2) %>% 
  bayesfactor_inclusion()
#> # Inclusion Bayes Factors (Model Averaged)
#> 
#>      Pr(prior) Pr(posterior) Inclusion BF
#> x          0.5             1   1.238e+189
#> 1:ID       0.5             1   1.238e+189
#> x:ID       0.5             1   1.238e+189
#> 
#> * Compared among: all models
#> *    Priors odds: uniform-equal
```

<sup>Created on 2020-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

2. You cannot pass the results of `weighted_posteriors()` to `emmeans`, but you can pass the results from `emmeans` to `weighted_posteriors()`. For example:
``` r
library(bayestestR)
library(emmeans)
library(rstanarm)
library(magrittr)

data(sleepstudy, package = "lme4")

## fit two models
m1 <- stan_glm(Reaction ~ 1, 
               data = sleepstudy,
               family = gaussian(), 
               diagnostic_file = file.path(tempdir(), "df1.csv"),
               refresh = 0)
m2 <- update(m1, Reaction ~ Days, diagnostic_file = file.path(tempdir(), "df2.csv"))

## Get BFs
BFs <- bayesfactor_models(m1, m2)

## contrasts from 2nd model
c_2 <- emmeans(m2, ~ Days, at = list(Days = c(1,2))) %>% 
  pairs() %>% 
  # extract posteriors
  as.mcmc.emmGrid() %>% 
  as.matrix() %>% 
  as.data.frame()

## contrasts from 1st model (are just 0 in this case)
c_1 <- c_2
c_1$`contrast 1 - 2` <- 0

## combine posteriors from both models, weighted by the BF
w <- weighted_posteriors(c_1, c_2, prior_odds = BFs$BF[-1])

hdi(w)
#> # Highest Density Interval
#> 
#> Parameter      |         89% HDI
#> --------------------------------
#> contrast 1 - 2 | [-12.41, -8.66]
```

<sup>Created on 2020-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

3. I think here [https://doi.org/10.1007/s11336-018-9648-3](https://doi.org/10.1007/s11336-018-9648-3)?

**Comment by nahorp** [comment]
> 1. However, since this BF is based on the provided models, your use-case might give biased results, as fixed effects would be paired with random effects - so the same models that do or don't have a fixed effects, also do or don't have the random effect. For example:

That's a very good point @mattansb. But surely by considering all models in the model space, the BF value of the predictor would not be so different (relative to the lack of true effect) as in your example with only 2 models?

In JASP where Inclusion Bayes Factor can be done (as is pointed out in the Bayes Factors vignette), the only random effect for every model is 'subject' (i.e., it is _not_ the maximal random effect structure for all models except the intercept only model). I could go that way [i.e., only have (1 | subject) as the random effect)] but I'm then wondering how to reconcile not fitting the maximal random effect structure as recommended by [Barr et al., 2013](https://doi.org/10.1016/j.jml.2012.11.001) as well as [Singmann and Kellen 2019](http://singmann.org/download/publications/singmann_kellen-introduction-mixed-models.pdf)...

> 2. You cannot pass the results of `weighted_posteriors()` to `emmeans`, but you can pass the results from `emmeans` to `weighted_posteriors()`. For example:

Ah, I think I understand what you've done there. Basically, run the contrast (via `emmeans`) separately for every model and then combine the posteriors using the `weighted_posteriors` function (weighted based on the BFs obtained via `bf_models`) and then I can get the median, hdi etc. of that weighted posterior, correct?

I could avoid this whole process and use the `weighted_posteriors` function directly on the models (side note - as depicted in the [vignette here](https://easystats.github.io/bayestestR/articles/bayes_factors.html#weighted_posteriors) if I pass models here I don't need a `prior_odds` argument for the weighting, right?) if I can figure out the contrasts via the parameters of the model itself?

> 3. I think here https://doi.org/10.1007/s11336-018-9648-3?

I'm seeing a lot of 90,000 posterior samples in there but not 40,000...

**Comment by mattansb** [comment]
> But surely by considering all models in the model space, the BF value of the predictor would not be so different (relative to the lack of true effect) as in your example with only 2 models?

Not sure what you meant here.

> I'm then wondering how to reconcile not fitting the maximal random effect structure as recommended by Barr et al., 2013 as well as Singmann and Kellen 2019.

Note that both these references are (mostly) concerned with that parameters of the final data. However, for inference about *fixed effects* from model comparison (which is what we are discussing here) you would want to build a series of models, with the comparisons between then representing some question.
If you compare `y ~ X1 + (X1|ID)` to `y ~ X1 + X2 + (X1 + X2|ID)` and find that the second model is better, you cannot tell if this is because of the addition of `X1` as a fixed effect or as a random effect - they are confounded in this comparison (as I demonstrated above).

Note that in `afex::mixed()`, even though the final model can be have maximal random structure, the type-3 ANOVA table, represents comparisons between models with and without each fixed effect, but without change to the random structure. This ***decouples*** the fixed effects from the random effects.

> I could avoid this whole process and use the weighted_posteriors function directly on the models (side note - as depicted in the vignette here if I pass models here I don't need a prior_odds argument for the weighting, right?) if I can figure out the contrasts via the parameters of the model itself?

Yes, you can do this. (Note that not supplying `prior_odds` just means you assume uniform prior odds).

3. Try here: https://arxiv.org/pdf/1710.08162.pdf "*As a rule of thumb, we suggest that testing requires about an order of magnitude more posterior samples than estimation.*".

**Comment by nahorp** [comment]
> If you compare `y ~ X1 + (X1|ID)` to `y ~ X1 + X2 + (X1 + X2|ID)` and find that the second model is better, you cannot tell if this is because of the addition of `X1` as a fixed effect or as a random effect - they are confounded in this comparison (as I demonstrated above).

That makes sense (with 'X1' in the second sentence possibly a typo and should read 'X2' I am assuming).

> Note that in `afex::mixed()`, even though the _final_ model can have maximal random structure, the type-3 ANOVA table, represents _comparisons between models with and without each fixed effect_, but without change to the random structure. This _**decouples**_ the fixed effects from the random effects.

But if I want to go the Bayesian route (via `brm`), I can't achieve this decoupling between fixed and random effects correct? So, in summary, this is what I'm thinking,

1. Run all 19 models with only a random intercept for ID and then using `bf_models` and `bf_inclusion`, I can explicitly answer the question about whether the data is more probable in models with a fixed effect than without them (i.e., no confound of different random effect structures then).

2. Then I can run contrasts (via `emmeans`) separately for every model and then combine the posteriors using the `weighted_posteriors` function (weighted based on the BFs obtained via bf_models) and then I can get the median, hdi etc. of the weighted posterior distribution of the contrast, correct?

Out of theoretical curiosity and to make sure I understood your point, for doing number 2 above, I could run the 19 models again with the _maximal random effect structure for each model_ since I am now interested in the parameters of the data?

Thank you for that reference too.

**Comment by mattansb** [comment]
> 1. Run all 19 models with only a random intercept for ID and then using bf_models and bf_inclusion...

The inclusion or exclusion of random effects can change likelihood of fixed effects, so these results would have to be taken with a (large?) grain of salt.

> I can't achieve this decoupling between fixed and random effects correct?

Why not? You can fit `y ~ (1|S)`, `y ~ x + (1|S)` and `y ~ x + (x|S)`, and `y ~ 1 + (x|S)` - comparing the first to the second tells you about the addition of a fixed effect for `x`, comparing the second to the third tells you about the addition of a random effect for `x`... etc.

This will result in comparing (or averaging with `bf_inclusion()` or [`emmeans()` ->] `weighted_posteriors()`) much much more than 19 models.............

**Comment by nahorp** [comment]
> The inclusion or exclusion of random effects can change likelihood of fixed effects, so these results would have to be taken with a (large?) grain of salt.

Indeed, I agree. I'm curious to know how you would go about deciding on the random effect structure if you wanted to get Inclusion Bayes Factors for all possible fixed effect predictors (x1, x2, x3, x1:x2, x1:x3, x2:x3, x1:x2:x3) via Bayesian Model Averaging when the maximal fixed effect model is `y ~ x1 * x2 * x3`?

> Why not? You can fit `y ~ (1|S)`, `y ~ x + (1|S)` and `y ~ x + (x|S)`, and `y ~ 1 + (x|S)` - comparing the first to the second tells you about the addition of a fixed effect for `x`, comparing the second to the third tells you about the addition of a random effect for `x`... etc.
> 
> This will result in comparing (or averaging with `bf_inclusion()` or [`emmeans()` ->] `weighted_posteriors()`) much much more than 19 models.............

Ah yes, that make sense and I can also see how this would lead to a _lot_ more than 19 models. Out of curiosity (I could probably try this myself...), would the fixed effect of x be the same when comparing `y ~ (1|S) and y ~ x + (1|S)` vs. `y ~ x + (x|S) and y ~ 1 + (x|S)`?

**Comment by mattansb** [comment]
> I'm curious to know how you would go about deciding on the random effect structure if you wanted to get Inclusion Bayes Factors for all possible fixed effect predictors....

This is a hard question... I don't know that there is any good guidelines on this, other than to try and narrow down the number of models you have. There can always be more and more models to conciser, in an infinite space of possibilities, but if you're fully exploratory you probably shouldn't be computing BFs anyway (do you have a thought-out prior that you want to test for each fixed effect?), and should instead look at the posterior distribution of the parameters/estimates in the full model (or some models that are a subset of the full model, possible averaged across these models).

> ... would the fixed effect of x be the same when comparing ...

Yes, it seems so.

**Comment by mattansb** [comment]
Closing this.
