### ISSUE TITLE
failing test with new `rstanarm::stan_glm`

### ISSUE THREAD

**Issue by bgoodri** [easystats/bayestestR#327]
**Describe the bug**

This is not a bug, per se, but one of the unit tests of bayestestR fails with the new rstanarm. Specifically, line 34 of testthat/test-emmGrid.R now fails. I believe the functionality is basically the same and working, but the default prior in `rstanarm::stan_glm` is changing for @andrewgelman @avehtari and Jennifer Hill's textbook, which is starting to be delivered now. So, I urgently need you to upload a bayestestR to CRAN that drops or updates that test so that the new rstanarm can be uploaded to CRAN and have it automatically go through.

More broadly, tests like this are very brittle. No one can expect to reproduce hard-coded values (even within some tolerance) with a different compiler, different version of R, different version of StanHeaders, etc.

**To Reproduce**

Install rstanarm from GitHub, then run these lines from tests/testthat/test-emmGrid.R
```
library(rstanarm)
library(emmeans)
set.seed(300)
model <- stan_glm(extra ~ group, data = sleep, refresh = 0) # new default prior on the intercept

em_ <- emmeans(model, ~group)
c_ <- pairs(em_)
xestden <- estimate_density(c_, method = "logspline", precision = 5)
testthat::expect_equal(xestden$x, c(-4.67, -2.91, -1.16, 0.60, 2.35), tolerance = 0.2)
testthat::expect_equal(log(xestden$y), c(-6.18, -2.12, -0.86, -3.62, -7.90), tolerance = 0.2)
```

**Expected behaviour**

What used to happen with the old default prior on the intercept is that the test would pass. It is expected to fail (and does fail) with the new default prior on the intercept and those hard-coded values like

```
Error: log(xestden$y) not equal to c(-6.18, -2.12, -0.86, -3.62, -7.9).
4/5 mismatches (average diff: 1.17)
[1] -7.74 - -6.18 == -1.557
[2] -3.40 - -2.12 == -1.281
[4] -2.95 - -3.62 ==  0.666
[5] -6.74 - -7.90 ==  1.161
```

**Screenshots**

Not necessary

**Specifiations (please complete the following information):**
 - Package Version 0.7.0

**Comment by strengejacke** [comment]
Thanks for reporting. What would you suggest instead of using hard coded values for tests? Dropping tests should be the last option, I'd say.

**Comment by bgoodri** [comment]
I haven't looked into it in great detail, but in rstanarm we have moved toward unit tests that are not dependent on the exact MCMC output. One thing that can be done in this case might be to construct a `c_` without using the output of `rstanarm::stan_glm` and then use that `c_` to unit test `estimate_density(c_, method = "logspline", precision = 5)`. If you want, you could also test whether using `rstanarm::stan_glm` to construct `em_` and `c_` produces valid objects, but it isn't really bayestestR's responsibility to ensure that `rstanarm::stan_glm` is producing reasonable output or even especially similar output to what it was producing before.

**Comment by mattansb** [comment]
> we have moved toward unit tests that are not dependent on the exact MCMC output

I'd say almost all unit tests in this package are doing this :/ we don't really care about the values *per se*, we just want to make sure that our functions consistently deal with `rstanarm`/`brms` objects (i.e., that any changes don't have an unexpected effect on the computations etc...).

The solution might be to skip such tests on CRAN and only run them locally / in GitHub Actions.

**Comment by DominiqueMakowski** [comment]
Thanks @bgoodri for notifying!

I have an issue installing rstanarm from github:

```
Error: (converted from warning) package 'Rcpp' was built under R version 4.0.2
Execution halted
ERROR: lazy loading failed for package 'rstanarm'
* removing 'C:/Users/domma/Documents/R/win-library/4.0/rstanarm'
* restoring previous 'C:/Users/domma/Documents/R/win-library/4.0/rstanarm'
Error: Failed to install 'rstanarm' from GitHub:
  (converted from warning) installation of package ‘C:/Users/domma/AppData/Local/Temp/Rtmpgb3Wcr/filebf60411538f0/rstanarm_2.21.1.tar.gz’ had non-zero exit status
In addition: Warning message:
In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\domma\AppData\Local\Temp\Rtmpgb3Wcr\filebf6011c3b3.tar.gz" -C "C:/Users/domma/AppData/Local/Temp/Rtmpgb3Wcr/remotesbf60330f5c87"’ returned error code 
```

(I have the latest Rtools etc)

I'll look into the tests, maybe we can replace value-based tests by format/shape-based ones.

**Comment by bgoodri** [comment]
Try it after doing

Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")

**Comment by bgoodri** [comment]
There is also

> Failure: bayesfactor_parameters BRMS (@test-bayesfactor_parameters.R#90)

which also seems to be overly sensitive to stochastic output, but that test is skipped on CRAN anyway.

So, are you good with me uploading rstanarm?

**Comment by DominiqueMakowski** [comment]
Thanks a lot @bgoodri for your thorough checks. I added a bit of tolerance. 

> So, are you good with me uploading rstanarm?

Yes, we will submit bayestestR likely today ☺️

**Comment by bgoodri** [comment]
Thanks! Let me know the instant you upload.

**Comment by DominiqueMakowski** [comment]
@bgoodri It has been submitted

**Comment by DominiqueMakowski** [comment]
On its way to CRAN
