### ISSUE TITLE
Typo in CI vignette?

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#328]
> On the other hand, the ETI range does change when transformations are applied to the distribution (for instance, for a log odds scale to probabilities): the lower and higher bounds of the transformed distribution will correspond to the transformed lower and higher bounds of the original distribution. On the contrary, applying transformations to the distribution will change the resulting HDI

(https://easystats.github.io/bayestestR/articles/credible_interval.html)

Should the first ETI in line 1 be "HDI"?

**Comment by DominiqueMakowski** [comment]
I think it should be "On the other hand, the ETI range does [NOT] change..." doesn't it?

**Comment by strengejacke** [comment]
Yes, makes sense.
