### ISSUE TITLE
Is the HDI represented in JoSS accurate?

### ISSUE THREAD

**Issue by Jimbilben** [easystats/bayestestR#331]
I'm not sure if this is the right place to be posting this, and I could also be wrong about the issue, but I am wondering if the HDI you represent in the illustrations for your package in JoSS is accurate. Shouldn't either end of the distribution be equally credible, and therefore of the same height in the posterior distribution? In the picture given for the HDI of page 4 here https://joss.theoj.org/papers/10.21105/joss.01541.pdf there seem to be values that have higher density outside the HDI on the left of the distribution than many that are included in the HDI on the right. This strikes me as incorrect, though I may be wrong.

**Comment by strengejacke** [comment]
You can find the code to repoduce the figure [here](https://github.com/easystats/bayestestR/blob/master/paper/Figure2.R).

``` r
library(bayestestR)
set.seed(123)
posterior <- distribution_chisquared(100, 3)

hdi(posterior)
#> # Highest Density Interval
#> 
#> 89% HDI     
#> ------------
#> [0.11, 6.05]

HDInterval::hdi(posterior, .89)
#>     lower     upper 
#> 0.1148318 6.0544722 
#> attr(,"credMass")
#> [1] 0.89
```

The _HDI_ is actually correct, however, `density()` adds "tails" to the values returned by `distribution_chisquared(100, 3)`. See the two different plots here:

``` r
library(bayestestR)
set.seed(123)
posterior <- distribution_chisquared(100, 3)

hdi(posterior)
#> # Highest Density Interval
#> 
#> 89% HDI     
#> ------------
#> [0.11, 6.05]

plot(density(posterior))

plot(estimate_density(posterior))
```

![](https://i.imgur.com/yiLR7Mq.png)![](https://i.imgur.com/q6iKMSC.png)

<sup>Created on 2020-07-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So, there's indeed an "inaccuracy", caused by the short length of `posteriors`, i.e. only having 100 data points for the distribution. Increasing it would change the image, getting more accurate:

``` r
library(bayestestR)
library(tidyverse)

set.seed(123)
posterior <- distribution_chisquared(10000, 3)
dat <- as.data.frame(density(posterior))

dat %>% mutate(fill = ifelse(x < hdi(posterior)$CI_low, "low",
                             ifelse(x > hdi(posterior)$CI_high, "high", "middle"))) %>%
  ggplot(aes(x=x, y=y, fill=fill)) +
  geom_ribbon(aes(ymin=0, ymax=y)) +
  geom_vline(xintercept=0, linetype="dotted") +
  theme_classic(base_size = 20) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, .25)) +
  scale_fill_manual(values=c("high"="#FFC107", "low"="#FFC107", "middle"="#E91E63"), guide=FALSE) +
  annotate("text", x=2.5, y=.05, label="The 89% HDI", color="white", size=10) +
  xlab(NULL) +
  ylab("Probability Density\n")
```

![](https://i.imgur.com/njGz9Ym.png)

**Comment by mattansb** [comment]
> Shouldn't either end of the distribution be equally credible, and therefore of the same height in the posterior distribution?

In theory, yes. But we don't have the posterior distribution, we only have samples from it.
The algorithm used here gives a (pretty good) estimate of the HDI, but when plotting things get smoothed out, and so in the plot the edges of the interval might not the exact same height.

**Comment by Jimbilben** [comment]
Yes, I see - it makes sense that if the density plot is based on a smaller set of draws it might not line up so well with the HDIs and so look like the ends of the HDI don't reflect equally likely points. For figures showing people the HDI, it might just be ideal to use a larger sample then, as otherwise a key point of the HDI might be lost on the viewer. Otherwise it just looks like a shifted over ETI :)

**Comment by mattansb** [comment]
I've updated the README to use a larger number of samples in the plot.
Thanks for the input, @Jimbilben

**Comment by Jimbilben** [comment]
Nice one! Thanks for making this useful package
