### ISSUE TITLE
set.seed argument for bf_models?

### ISSUE THREAD

**Issue by nahorp** [easystats/bayestestR#332]
Hello :)

Just wondering if there is a `set.seed` type of argument for `bf_models`? The BF changes every time it is run and it'd be nice to be able to share the code for a publication and get the reported BFs in the manuscript...

Thank you

**Comment by mattansb** [comment]
This isn't available (yet?), but you can set this in your script, just before the call to `bf_models`:

```R
set.seed(1234)
bf_models(m0,m1,m2)
```

**Comment by nahorp** [comment]
Ah yes, easy solution. Thanks 👍

**Comment by mattansb** [comment]
Increasing the length and/or number of chains should stabilize the estimated BF.

Closing this.
