### ISSUE TITLE
Checks

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#334]
Looking at the check results:

https://github.com/easystats/bayestestR/runs/948772167#step:10:147

Why is there such a large difference on Linux? We don't even compile the model at runtime, but download a model object from _circus_, so I'd expect the same coefficients on each OS.

**Comment by DominiqueMakowski** [comment]
Looks like I missed 😕  but I have locally and here these weird C things that appear: https://github.com/easystats/bayestestR/runs/1483421232#step:10:243 now sure what it means and if that's an error 🤔

**Comment by strengejacke** [comment]
For me, it fails, too: _rstanarm_ fails in line 62 of `test-describe_posterior.R`:

```r
model <- rstanarm::stan_glm(mpg ~ drat, data = mtcars, algorithm = "meanfield", refresh = 0)
```

Not sure why, but this test is run only for dev-versions, i.e. once you increase the version number to 0.7.6 or so, this failing test is passed anyway. Looks like an rstanarm thing.

**Comment by strengejacke** [comment]
```
--(test-describe_posterior.R:62:7): describe_posterior ------------------
Error: stan::variational::normal_meanfield::calc_grad: The number of dropped evaluations has reached its maximum amount (10). Your model may be either severely ill-conditioned or misspecified.
Backtrace:
\-rstanarm::stan_glm(...) [90mtest-describe_posterior.R:62:6[39m
  \-rstanarm::stan_glm.fit(...)
   +-base::do.call(vb, args = vb_args)
   +-(new("nonstandardGenericFunction", .Data = function (object, ...
      \-(new("nonstandardGenericFunction", .Data = function (object, ...
       \-rstan:::.local(object, ...)
         \-sampler$call_sampler(c(args, dotlist))
```

**Comment by DominiqueMakowski** [comment]
Mmh... alright, I will bump the version to 0.8.0 and run the CRAN winchecks to see

**Comment by strengejacke** [comment]
I need to update _insight_, due to a failing check after the _parameters_ update 🤣  Can you say when you might submit _bayestestR_? @mattansb wants to submit _effectsize_ then, and actually after that all packages then use the new `export_table()`, so we could now add `format_table()` as alias for `parameters_table()` for this "hotfix-update" of _insight_...

But if not, not urgent to change the functions names now.

**Comment by DominiqueMakowski** [comment]
I submitted to winbuilder, so based on the results I'll submit probably tomorrow morning (i.e., in about 10-11 hours) if that's okay

**Comment by strengejacke** [comment]
Yeah, actually, there is no hurry, it would probably be a "nice to have" to have `format_table()` as alias for `parameters_table()`, then we finished the transition of our "printing API" in this case... ;-)

**Comment by DominiqueMakowski** [comment]
3 winbuilder checks yielded nothing else than this: https://win-builder.r-project.org/dR16N6fc5pQ6/00check.log

**Comment by DominiqueMakowski** [comment]
Wait I just updated my insight but now I have this error: 

``` r
library(bayestestR)
#> Note: The default CI width (currently `ci=0.89`) might change in future versions (see https://github.com/easystats/bayestestR/issues/250).
#> To prevent any issues, please set it explicitly when using bayestestR functions, via the 'ci' argument.

s <- sexit(rnorm(1000, -1, 1))
s
#> # Following the Sequential Effect eXistence and sIgnificance Testing (SEXIT) framework, we report the median of the posterior distribution and its 95% CI (Highest Density Interval), along the probability of direction (pd), the probability of significance and the probability of being large. The thresholds beyond which the effect is considered as significant (i.e., non-negligible) and large are |0.05| and |0.30|.
#> 
#> The effect (Median = -0.96, 95% CI [-3.01, 0.92]) has a 82.50% probability of being negative (< 0), 81.60% of being significant (< -0.05), and 74.20% of being large (< -0.30)
#> Error in cat(insight::format_table(out[[i]], digits = digits)): argument 1 (type 'list') cannot be handled by 'cat'
```

<sup>Created on 2020-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

```
 Error in cat(insight::format_table(out[[i]], digits = digits)) : 
  argument 1 (type 'list') cannot be handled by 'cat' 
4.
cat(insight::format_table(out[[i]], digits = digits)) at utils_print_data_frame.R#63
3.
print_data_frame(df, digits = digits, ...) at sexit.R#265
2.
print.sexit(x) 
1.
(function (x, ...) 
UseMethod("ÿþprintÿþ"))(x) 
```

Which comes from [print_data_frame](https://github.com/easystats/bayestestR/blob/master/R/utils_print_data_frame.R#L1) is there anything I missed on whether I need to fix it or something?

**Comment by strengejacke** [comment]
> 3 winbuilder checks yielded nothing else than this: https://win-builder.r-project.org/dR16N6fc5pQ6/00check.log

You need to remove the _Remotes_ field from the DESCRIPTION file (at the very bottom), this was just that GitHub-CI passes when the GitHub-version from insight was required. Else, everything seems to be ok to submit.

**Comment by strengejacke** [comment]
> Wait I just updated my insight but now I have this error:

I'd say you need to update _bayestestR_ ^^ Are you submitting an outdated version? 🤣 
Line 63 of `utils_print_data_frame.R` is now:

```r
cat(insight::export_table(out[[i]], digits = digits))
```

**Comment by strengejacke** [comment]
> > 3 winbuilder checks yielded nothing else than this: https://win-builder.r-project.org/dR16N6fc5pQ6/00check.log
> 
> You need to remove the _Remotes_ field from the DESCRIPTION file (at the very bottom), this was just that GitHub-CI passes when the GitHub-version from insight was required. Else, everything seems to be ok to submit.

Actually, I already did this. You're probably not running the latest _bayestestR_...

**Comment by DominiqueMakowski** [comment]
> Actually, you (or me?) already did this.

Yeah I removed it, but indeed somehow I did not install the latest version myself 😅 I'll submit now

**Comment by strengejacke** [comment]
Are you planning to submit _modelbased_ as well? I'm currently struggling with the test results, same strange R/C-bug in modelbased as for bayestestR...

**Comment by DominiqueMakowski** [comment]
Yeah I started looking at modelbased this morning and I too have these weird C things... Will come back to it this evening

**Comment by DominiqueMakowski** [comment]
For bayestestR:

package bayestestR_0.8.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/bayestestR_0.8.0_20201203_035824/Windows/00check.log>
Status: 2 NOTEs
Debian: <https://win-builder.r-project.org/incoming_pretest/bayestestR_0.8.0_20201203_035824/Debian/00check.log>
Status: 1 NOTE

**Comment by DominiqueMakowski** [comment]
For modelbased it seems to pass the winbuilder checks so 🤷

**Comment by strengejacke** [comment]
URL failure maybe temporary? Else, the other one is indeed skipping long-running examples...
