### ISSUE TITLE
Indices of effect existence and significance for joint posterior distributions?

### ISSUE THREAD

**Issue by nahorp** [easystats/bayestestR#342]
Hello,

Firstly, I'm not sure if my conceptualization of 'joint posterior distributions' is correct or not (hence, the title might be off) but I'll try to explain what I wish to do...

Imagine I have a model - `y ~ x * z` where x and z are categorical predictors, each with 2 levels (x: x1 and x2; z: z1 and z2). Now, I will get only 4 parameters from the model - intercept, effect of x, effect of z, interaction effect (the specifics will depend on how the factors are coded and are not important for now). 

Now, I can run pairwise contrasts using `emmeans(model, pairwise ~ x * z)`, which outputs 6 pairwise comparisons, as follows,

x1 vs x2,
x1 vs. z1,
x1 vs. z2,
x2 vs. z1,
x2 vs. z2,
z1 vs. z2

<img width="225" alt="Screen Shot 2020-09-30 at 4 02 16 pm" src="https://user-images.githubusercontent.com/43395036/94648659-5559d500-0336-11eb-9574-d5e066244d50.png">

However, when I run `describe_posterior` I will get only 4 rows corresponding to the 4 parameters (which is intended to do only that). What I was wondering was is there a way for me to use `describe_posterior` to get all 6 contrasts (or combination of levels of my factors) as I'd like to use indices such as pd, ROPE etc.?

**Comment by mattansb** [comment]
Yes, you need to pass the contrast part of the result:

``` r
library(rstanarm)
data("mtcars")
m <- stan_glm(mpg ~ factor(cyl), data = mtcars, refresh = 0)

library(emmeans)
em_ <- emmeans(m, pairwise ~ cyl)


bayestestR::describe_posterior(em_[[1]]) # 1 is the means
#> # Description of Posterior Distributions
#> 
#> Parameter | Median |           89% CI |      pd |        89% ROPE | % in ROPE
#> -----------------------------------------------------------------------------
#> 4         | 26.618 | [25.000, 28.256] | 100.00% | [-0.100, 0.100] |         0
#> 6         | 19.755 | [17.790, 21.808] | 100.00% | [-0.100, 0.100] |         0
#> 8         | 15.143 | [13.742, 16.564] | 100.00% | [-0.100, 0.100] |         0

bayestestR::describe_posterior(em_[[2]]) # 2 is the contrasts
#> # Description of Posterior Distributions
#> 
#> Parameter | Median |          89% CI |      pd |        89% ROPE | % in ROPE
#> ----------------------------------------------------------------------------
#> 4 - 6     |  6.870 | [4.223,  9.339] | 100.00% | [-0.100, 0.100] |         0
#> 4 - 8     | 11.520 | [9.389, 13.679] | 100.00% | [-0.100, 0.100] |         0
#> 6 - 8     |  4.634 | [2.055,  6.990] |  99.67% | [-0.100, 0.100] |         0
```

<sup>Created on 2020-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
I've implemented support for `emm_list` objects in _insight_, at least a few functions. We could probably directly support emm_list in _bayestestR_, though this is quite some work to add functionality in all places.

``` r
library(emmeans)
library(insight)
library(rstanarm)
#> Loading required package: Rcpp
#> This is rstanarm version 2.21.1
#> - See https://mc-stan.org/rstanarm/articles/priors for changes to default priors!
#> - Default priors may change, so it's safest to specify priors, even if equivalent to the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#>   options(mc.cores = parallel::detectCores())

data("mtcars")
m <- stan_glm(mpg ~ factor(cyl) * factor(am), data = mtcars, refresh = 0)
em <- emmeans(m, pairwise ~ cyl * am)

get_parameters(em)
#>          Parameter    Estimate Component
#> 1  cyl [4], am [0]  22.9185249   emmeans
#> 2  cyl [6], am [0]  19.1273531   emmeans
#> 3  cyl [8], am [0]  15.0412930   emmeans
#> 4  cyl [4], am [1]  28.0202280   emmeans
#> 5  cyl [6], am [1]  20.5359158   emmeans
#> 6  cyl [8], am [1]  15.4218625   emmeans
#> 7        4 0 - 6 0   3.8503815 contrasts
#> 8        4 0 - 8 0   7.8948210 contrasts
#> 9        4 0 - 4 1  -5.0390333 contrasts
#> 10       4 0 - 6 1   2.2964715 contrasts
#> 11       4 0 - 8 1   7.5385774 contrasts
#> 12       6 0 - 8 0   4.0720809 contrasts
#> 13       6 0 - 4 1  -8.8896898 contrasts
#> 14       6 0 - 6 1  -1.4482438 contrasts
#> 15       6 0 - 8 1   3.6629444 contrasts
#> 16       8 0 - 4 1 -12.9617914 contrasts
#> 17       8 0 - 6 1  -5.4969203 contrasts
#> 18       8 0 - 8 1  -0.3735272 contrasts
#> 19       4 1 - 6 1   7.4669824 contrasts
#> 20       4 1 - 8 1  12.5801652 contrasts
#> 21       6 1 - 8 1   5.1364598 contrasts
```

<sup>Created on 2020-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I've already added frequentist support in _parameters_:

``` r
library(emmeans)
library(parameters)

data("mtcars")
m <- lm(mpg ~ factor(cyl) * factor(am), data = mtcars)
em <- emmeans(m, pairwise ~ cyl * am)

model_parameters(em)
#> # Estimated Marginal Means 
#> 
#> Parameter       | Coefficient |   SE |         95% CI |     t | df |      p
#> ---------------------------------------------------------------------------
#> cyl [4], am [0] |       22.90 | 1.75 | [19.30, 26.50] | 13.08 | 26 | < .001
#> cyl [6], am [0] |       19.12 | 1.52 | [16.01, 22.24] | 12.61 | 26 | < .001
#> cyl [8], am [0] |       15.05 | 0.88 | [13.25, 16.85] | 17.19 | 26 | < .001
#> cyl [4], am [1] |       28.07 | 1.07 | [25.87, 30.28] | 26.19 | 26 | < .001
#> cyl [6], am [1] |       20.57 | 1.75 | [16.97, 24.17] | 11.75 | 26 | < .001
#> cyl [8], am [1] |       15.40 | 2.14 | [10.99, 19.81] |  7.18 | 26 | < .001
#> 
#> # Contrasts 
#> 
#> Parameter | Coefficient |   SE |           95% CI |     t | df |      p
#> -----------------------------------------------------------------------
#> 4 0 - 6 0 |        3.77 | 2.32 | [ -0.99,   8.54] |  1.63 | 26 | 0.587 
#> 4 0 - 8 0 |        7.85 | 1.96 | [  3.83,  11.87] |  4.01 | 26 | 0.005 
#> 4 0 - 4 1 |       -5.18 | 2.05 | [ -9.39,  -0.96] | -2.52 | 26 | 0.155 
#> 4 0 - 6 1 |        2.33 | 2.48 | [ -2.76,   7.42] |  0.94 | 26 | 0.932 
#> 4 0 - 8 1 |        7.50 | 2.77 | [  1.81,  13.19] |  2.71 | 26 | 0.107 
#> 6 0 - 8 0 |        4.07 | 1.75 | [  0.48,   7.67] |  2.33 | 26 | 0.219 
#> 6 0 - 4 1 |       -8.95 | 1.86 | [-12.77,  -5.13] | -4.82 | 26 | < .001
#> 6 0 - 6 1 |       -1.44 | 2.32 | [ -6.20,   3.32] | -0.62 | 26 | 0.988 
#> 6 0 - 8 1 |        3.72 | 2.63 | [ -1.67,   9.12] |  1.42 | 26 | 0.716 
#> 8 0 - 4 1 |      -13.02 | 1.38 | [-15.87, -10.18] | -9.41 | 26 | < .001
#> 8 0 - 6 1 |       -5.52 | 1.96 | [ -9.54,  -1.49] | -2.82 | 26 | 0.086 
#> 8 0 - 8 1 |       -0.35 | 2.32 | [ -5.11,   4.41] | -0.15 | 26 | > .999
#> 4 1 - 6 1 |        7.51 | 2.05 | [  3.29,  11.73] |  3.66 | 26 | 0.013 
#> 4 1 - 8 1 |       12.67 | 2.40 | [  7.75,  17.60] |  5.29 | 26 | < .001
#> 6 1 - 8 1 |        5.17 | 2.77 | [ -0.52,  10.86] |  1.87 | 26 | 0.444
```

<sup>Created on 2020-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
Should work now, with the Github version of `insight`

**Comment by nahorp** [comment]
Thank you @mattansb and @strengejacke for acting so swiftly, that works perfectly! I did have a few more questions (some related, some not so related)

1) When I run `describe_posterior(model)`, it recognises that it is a logit model and gives me the default ROPE range (-0.181, 0.181)

![Screen Shot 2020-10-01 at 10 27 59 am](https://user-images.githubusercontent.com/43395036/94753183-c948bb80-03d0-11eb-8737-2c8495d5ccc8.png)

However, when I run `describe_posterior` on the emm_list object, it doesn't recognise it and defaults to the -0.1 and 0.1 range. Is there something in the `emm_list` object that would pass on the information that it is a logit scale?

![Screen Shot 2020-10-01 at 10 30 18 am](https://user-images.githubusercontent.com/43395036/94753284-1cbb0980-03d1-11eb-964d-158d0de92651.png)

2) Any recommendations for ROPE ranges for Gamma (link = log) and Shifted_lognormal models? Is the default -0.1 to 0.1 fine? I know this isn't an easy question to answer but any recommendations or leads would be great!

3) On another note, I might do some Bayes Factors as well.. Now, when I used `bf_parameters`, it samples from the prior even when I had `save_all_pars = TRUE` and `sample_prior = "yes"` in my `brm` call for the model. Does `bf_parameter` not find the priors for brmsfit objects?

![Screen Shot 2020-10-01 at 10 34 54 am](https://user-images.githubusercontent.com/43395036/94753495-c1d5e200-03d1-11eb-9032-fec7be5253b9.png)

4) Similarly to my initial post, is there a way to get Bayes Factors for the contrasts too (as opposed to only the parameters)?

**Comment by mattansb** [comment]
1. This is not possible, as `emmeans` does not store the original model, and would be very hard (if at all) to find out from the object what type of model it was originally. Also, even if this where the case, if the emmeans are on the response scale, then this would be the "wrong" rope-range to use anyway.

A workaround (**only if the emmeans are on the latent scale**) could be:
```R
describe_posterior(emm_obj, rope_range = rope_range(model))
```

3. Unfortunately, setting `sample_prior = "yes"` doesn't return all the priors we need. For example, it only returns prior samples of parameters that have a defined (non-flat) prior, so `bayestestR` can't fully rely on it:


```R
library(brms)

m <- brm(mpg ~ cyl, data = mtcars, sample_prior = "yes")

m_priors <- prior_samples(m)

colnames(m_priors) # where is the "b_cyl" parameter?
#> [1] "Intercept" "sigma"    
```

If you're only interested in a specific parameter that *has* a defined prior, you can do this explicitly:
```R
m_priors <- prior_samples(m)
m_post <- posterior_samples(m)

library(bayestestR)
bayesfactor_parameters(posterior = m_post$b_Intercept, 
                       prior = m_priors$Intercept)
#> # Bayes Factor (Savage-Dickey density ratio)
#> 
#> BF       
#> ---------
#> 3.083e+12
#> 
#> * Evidence Against The Null: [0]
```

4. Yes! The docs of `bayesfactor_parameters()` contain an explanation under "Setting the correct prior", as well as an example (the "emmGrid objects"-example).

**Comment by nahorp** [comment]
Thank you so much! I understand 1) and 3).

With 4), a question - how do I create an `emmGrid` object with the prior samples that are contained within my model that has been run with `sample_prior = "yes"`. I don't want to run another model again with `sample_prior = "only"` and then run emmeans on that - seems like a waste of time when I already have the prior samples...

**Comment by mattansb** [comment]
4. Not that I know of...

**Comment by nahorp** [comment]
It was easy (and quick enough) just running the model with `sample_prior = "only"`... thank you so much @mattansb for your prompt replies, I really appreciate it! :)

**Comment by nahorp** [comment]
Didn't feel like it was appropriate to open a new issue, or even appropriate to ask @mattansb and @strengejacke again but I thought it was kind of related to the emmeans stuff and to be completely honest, am at my wit's end...

https://github.com/rvlenth/emmeans/issues/255#issuecomment-778150691

Feel free to tell me you don't have the time/interest :)

**Comment by mattansb** [comment]
Sorry, those are out of our scope here...
