### ISSUE TITLE
Add more `distribution_*()` functions

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#346]
For nbinom1-family:

https://stat.ethz.ch/pipermail/r-sig-mixed-models/2020q4/029023.html

**Comment by mattansb** [comment]
Added `phi` as an argument to the `distribution_nbinom()`:

``` r
library(bayestestR)

hist(distribution_nbinom(100, prob = 0.25, size = 4))
```

![](https://i.imgur.com/3qTnB2J.png)

``` r

hist(distribution_nbinom(100, size = 4, mu = 12))
```

![](https://i.imgur.com/dOa0mDs.png)

``` r

hist(distribution_nbinom(100, mu = 12, phi = 3))
```

![](https://i.imgur.com/eIDD0K6.png)

<sup>Created on 2020-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
