### ISSUE TITLE
Bayes factor vignette fails on CRAN

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#348]
because "object ‘My_first_BF’ not found". @mattansb @DominiqueMakowski Any ideas, why? I'm not sure what these different code-chunks (and their names) actually mean and how these are evaluated.

Failing check: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/bayestestR-00check.html

**Comment by mattansb** [comment]
It knits locally on my computer... No idea why that would happen.

Added some better conditional evaluation, hope that solves it :/

**Comment by strengejacke** [comment]
The code chunk that fails is:

```r
'''{r, eval=require(effectsize)}
effectsize::interpret_bf(My_first_BF$BF[2], include_value = TRUE)
'''
```

**Comment by strengejacke** [comment]
This makes no sense at this point, as some lines before, we have 
```r
```{r}
library(see)
plot(My_first_BF)
 '``
```

So, the only way to explain this might be:

The setup fails:

```
if (!requireNamespace("rstanarm", quietly = TRUE) ||
      !requireNamespace("BayesFactor", quietly = TRUE) ||
      !requireNamespace("emmeans", quietly = TRUE) ||
      !requireNamespace("logspline", quietly = TRUE) ||
      !requireNamespace("lme4", quietly = TRUE) ||
      !requireNamespace("ggplot2", quietly = TRUE) ||
      !requireNamespace("see", quietly = TRUE)
      ) {
  knitr::opts_chunk$set(eval = FALSE)
```

because _rstanarm_ fails on Linux (see [here](https://cran.r-project.org/web/checks/check_results_rstanarm.html)). So no chunks are evaluated, `My_first_BF` does not exist. However, the chunk with `effectsize::interpret_bf(My_first_BF$BF[2], include_value = TRUE)` _is_ evaluated, because it sets `eval=require(effectsize)`. I think we just need to remove this. In the example,

**Comment by strengejacke** [comment]
Ok, I think this should be resolved...
