### ISSUE TITLE
Is p_significance complementary to p-ROPE?

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#349]
Following https://github.com/easystats/bayestestR/issues/237

1. Should `p_significance` compute the two tailed probability (making it conceptually complementary to p-ROPE, <sub>which is what I thought it was suppose to be</sub>)? Currently it computes the maximal directional probability.

Now:

```
p_lower <- mean(x[x < -abs(threshold)])
p_upper <- mean(x[x > abs(threshold)])

psig <- max(p_lower, p_upper)
```

Suggested:

```
p_lower <- mean(x[x < -abs(threshold)])
p_upper <- mean(x[x > abs(threshold)])

psig <- p_lower + p_upper
```

2. Should we allow `p_significance()` to have a range for `threshold`? I can think of cases where we wouldn't want the range to be symmetric, of centered around 0 (e.g., odds ratios) - again, like the p-ROPE.

**Comment by DominiqueMakowski** [comment]
> Should p_significance compute the two tailed probability

That *is* the p-rope no? p-sig is meant as the unidirectional version of p-rope

**Comment by mattansb** [comment]
Hmmm... the docs for p-rope say it's "Probability of not being in ROPE", but the computation is actually the probability of being **in** the rope, which is what I would expect a function called p-rope to do + in the docs it says "It is equivalent to running rope(..., ci = 1)", so...


``` r
x <- rnorm(10000, sd = 0.2, mean = 0.1)
bayestestR::p_rope(x)
#>   ROPE_low ROPE_high p_ROPE
#> 1     -0.1       0.1   0.34
bayestestR::rope(x, ci = 1)
#> # Proportion of samples inside the ROPE [-0.10, 0.10]:
#> 
#> inside ROPE
#> -----------
#> 33.67 %
```

<sup>Created on 2020-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So something here is off...

**Comment by DominiqueMakowski** [comment]
indeed, wrong docs

**Comment by mattansb** [comment]
Is it just me? Seems weird that `p_rope()` gives p-**Not**-ROPE?  

I would rename `p_rope` to `p_significant` - and add a "direction" argument which defaults to "both" or something (similar to how `bayesfactro_parameters` has)...

**Comment by DominiqueMakowski** [comment]
> Is it just me?

yes 😁 

well but p-rope is really just a convenience function to replace rope(ci=1). We named it p_rope for consistency reason (along with p_direction, p_map etc.). 

I think that people that want the traditional percentage in rope will be comfortable using `rope()` or `p_rope()`. Whereas p_sig is conceptually something else (even though it's technically a one-sided p_rope). 

I mean we could add a direction option, but then we'll have 3 ways of doing the same thing, we would rather add confusion than clarity. In this case, I think it's better to keep them functions short and sweet.

**Comment by mattansb** [comment]
> yes 😁

lol, thanks

If no one else has any quarrel with this, you may proceed :P

> I mean we could add a direction option, but then we'll have 3 ways of doing the same thing...

I did offer some time ago to have all the p_rope, p_sig, rope, etc to be unified under a p_range, such that:
`rope(x, ci = 1)` == `p_range(x, range = c(-0.1,0.1), type = "in")`
`p_rope(x)` == `p_range(x, range = c(-0.1,0.1), type = "out")`
`p_sig(x)` == `p_range(x, range = sign(median(x)) * c(0.1,Inf), type = "in")`
`p_direction(x)` == `p_range(x, range = sign(median(x)) * c(0,Inf), type = "in")`

But maybe let's not break everything just yet (:

**Comment by DominiqueMakowski** [comment]
> I did offer some time ago to have all the p_rope, p_sig, rope, etc to be unified under a p_range, such that:

Technically and conceptually that'd be a good idea indeed... if we were to rewrite bayestestR but unless you're really bored and looking for something to do, I'd say we leave it as is and focus on priorities (like solving the hard problem of the standardization of regression effect sizes 😅 )

**Comment by mattansb** [comment]
Should we tag this issue with "For when Mattan is board"?
