### ISSUE TITLE
ROPE range discrepancies for logistic models

### ISSUE THREAD

**Issue by nahorp** [easystats/bayestestR#350]
Hello,

I'm having a look at the default ROPE range for logistic models in `bayestestR` and there seems to be discrepancies amongst the different models.

[This webpage says](https://easystats.github.io/bayestestR/articles/region_of_practical_equivalence.html) it is √3/𝜋, whereas [this webpage says ](https://easystats.github.io/bayestestR/reference/rope_range.html) says it is 𝜋/√3... I think it is the latter that is implemented in `bayestestR` but not 100% sure.

Thank you

**Comment by strengejacke** [comment]
It's indeed `pi / sqrt(3)`, however, @mattansb or @DominiqueMakowski, where does this value come from? The variance for logistic regression is `pi^2 / 3`, I think.

**Comment by DominiqueMakowski** [comment]
I think it's from Cohen's rule for d -> logodds transformation

**Comment by strengejacke** [comment]
ah, ok. So it's only a matter of changing the docs.

**Comment by nahorp** [comment]
Thanks for that @DominiqueMakowski and @strengejacke! 

Just another question - for parameters on the log odds scale the recommendation is +/- 0.1 * pi / sqrt(3). Is there any recommendation for parameters on the log scale?

**Comment by DominiqueMakowski** [comment]
What do you mean?

**Comment by nahorp** [comment]
> What do you mean?

I'm running a Gamma GLMM with a log link function, so the parameters are on the log scale. Wondering if there were any ROPE recommendations for this as there are for parameters in linear and logistic regression? Would it just be log(0.1 * SD of y)?

**Comment by mattansb** [comment]
> It's indeed pi / sqrt(3), however, @mattansb or @DominiqueMakowski, where does this value come from? The variance for logistic regression is pi^2 / 3, I think.

Yup - the sd of the logistic distribution:
``` r
x <- rlogis(5e6)
sd(x)
#> [1] 1.813998

pi / sqrt(3)
#> [1] 1.813799
```

> I'm running a Gamma GLMM with a log link function, so the parameters are on the log scale. 

That logic overall seems right to me, but I don't know much about the Gamma distribution.

**Comment by nahorp** [comment]
> That logic overall seems right to me, but I don't know much about the Gamma distribution.

Thanks for that @mattansb, appreciate it!

**Comment by bwiernik** [comment]
The `pi / sqrt(3)` makes sense in that it produces a "Cohen's d" like metric in the sense of Cohen's d unit differences in log odds between `y = 0` and `y = 1` groups. That said, I really don't understand what this means. I don't know any of the popular *d* benchmarks (e.g., .2, .4, .6; .2, .5, .8) apply well on the log-odds scale. 

I think that the ROPE here should be defined in terms of probabilities.

**Comment by mattansb** [comment]
How can it be in terms of probability when the scale is log(odds ratio)? 🤔

**Comment by bwiernik** [comment]
Ah, that's a good point.

**Comment by mattansb** [comment]
Closing this as all questions seem to have either been answered
