### ISSUE TITLE
printing for si broken 

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#353]
``` r
library(bayestestR)

prior <- distribution_normal(1000, mean = 0, sd = 1)
posterior <- distribution_normal(1000, mean = .5, sd = .3)

s <- si(posterior, prior)
#> Loading required namespace: logspline

as.data.frame(s)
#>   CI     CI_low  CI_high
#> 1  1 0.03999124 1.053103

print(s)
#> # Support Interval
#> Error in names(df) <- col_names: 'names' attribute [1] must be the same length as the vector [0]
```

Previously looked like this… 

``` r
# # Support Interval
# 
# Parameter |    BF = 1 SI
# ------------------------
# group2    | [0.15, 3.04]
```

<sup>Created on 2020-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

(We really need to add printing testing, like in report / effectsize...)

I think this is due to switching to `insight::export_table`, but I can't pin it down... @DominiqueMakowski @strengejacke

**Comment by mattansb** [comment]
Alternative solution - make a new printing function fo SI that does not depend on the ETI/HDI method?

**Comment by strengejacke** [comment]
I'm not sure, but I _think_ this may be due to the strange structure that the numeric-method of `si()` calls the data.frame method of `si()`? "Unclassing" the si.object in export_table() seems to solve this issue (should be fixed in https://github.com/easystats/insight/commit/20b30790109ef6015e44ad7cc56361e2f1e166db).

**Comment by strengejacke** [comment]
Although the `si`-object is also a data frame, this code in `export_table.R` breaks:

```r
  df <- x

  # round all numerics
  col_names <- names(df)
  df <- as.data.frame(sapply(df, function(i) {
    if (is.numeric(i)) {
      format_value(i, digits = digits, protect_integers = protect_integers, missing = missing, width = width, zap_small = zap_small)
    } else {
      i
    }
  }, simplify = FALSE), stringsAsFactors = FALSE)
```

changing the first line to:

```r
  df <- as.data.frame(x)
```

fixed it.

**Comment by mattansb** [comment]
Weird. Thanks!
