### ISSUE TITLE
Default CI width might change in the future

### ISSUE THREAD

**Issue by nahorp** [easystats/bayestestR#355]
Hello :)

I was reading the ['General' log of the bayestestR 0.7.6](http://cran.fhcrc.org/web/packages/bayestestR/news/news.html) and noticed that,

"Added startup-message to warn users that default ci-width might change in a future update." Is there any discussion anywhere here regarding that? Thank you

**Comment by DominiqueMakowski** [comment]
> Is there any discussion anywhere here regarding that?

Oh yes 😅  

Feel free to chime in on https://github.com/easystats/bayestestR/discussions/250
