### ISSUE TITLE
Publication in JOSS

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#36]
What do you think about preparing (and submitting) a paper for JOSS?

https://joss.theoj.org/

It would be a very short paper, mostly similar to a readme-file, but would have the advantage of a "nicer" citation for the package. The journal has an ISSN, so it's being considered as "citable".

**Comment by DominiqueMakowski** [comment]
Yes definitely! However, I would like the JOSS paper to be a bit longer than usual (maybe by including some examples or things from the vignettes). Maybe around 1-2 pages? The shameful reason for that is that my two previous JOSS papers have been weirdly look at on researchgate by people not used to "technical publications"... 😅 

"*Ah you have published a new paper! Let's see the full text...*" **\*clicks on "full-text"\***

 **\*nothing changes\***

 **\*tries to scroll past the first half-page\***

 **\*nothing changes\***

**Comment by strengejacke** [comment]
:-D

I think there are no limitations to number of pages. My ggeffects-paper has 4 pages, I think. I just wanted to say that it should not be too much effort...

**Comment by DominiqueMakowski** [comment]
We should do this independently of the other paper. Maybe we could (re)use the content of the README for this one?

**Comment by DominiqueMakowski** [comment]
Requirements:

- [ ] statement of need
- [ ] conceptual presentation
- [x] features presentation (in the README)

**Comment by strengejacke** [comment]
I can give it a try next week and work on the statement of need. I think the introduction as it currently stands is too long and too generic. We might shorten a bit here and then focus a bit more on what is currently missing (and thus needed), and how _bayestestR_ can help here.

**Comment by DominiqueMakowski** [comment]
okay. however if possible I would rather add what's missing rather than replace the current generic intro (altho it can definitely be streamlined); since bayestestR might be a point of entry for beginners to Bayesian stats, and that the package is not only the functions but the documentation, it would not hurt having such few paragraphs presenting a bit the idea.

Also, although fairly decent, I feel like the title could be improved to be more impactful/catchy :)

**Comment by mattansb** [comment]
> since bayestestR might be a point of entry for beginners to Bayesian stats, and that the package is not only the functions but the documentation

😎

**Comment by DominiqueMakowski** [comment]
>  since bayestestR might be a point of entry for beginners to Bayesian stats, and that the package is not only the functions but the documentation [as well]

Well at least I have a strong prior that it is the case ¯\_(ツ)_/¯

**Comment by strengejacke** [comment]
Ok, I started working on the paper. I streamlined the intro a bit, and will now add a statement of need.

To summarize my idea behind the changes:
- I removed the frq-paragraph with repro-crisis, not 100% sure if this paragraph captures the story correctly
- I removed the examples with "correlation" and ".42", because I think the message is clear w/o those examples.
- I think we need a transition to the statement of need and the content of the paper. I like the idea, and I think this is most accessible / readable, of the four characteristics of a posterior: centrality, uncertainty, existance and significance. Thus, the intro ends with

> In essence, the Bayesian sampling algorithms (such as MCMC sampling) return a probability distribution (*the posterior*) of an effect that is compatible with the observed data. The effect can be described by [characterizing the posterior distribution](https://easystats.github.io/bayestestR/articles/guidelines.html) of the related effect in relation to its centrality (point-estimates), uncertainty, existance and significane.

and I will now continue with the statement of need (that _bayestestR_ boldly goes where no package has gone before) and then we almost have the same structure "centrality (point-estimates), uncertainty, existance and significane" already in the paper, which makes it easy to follow.

**Comment by strengejacke** [comment]
I added the statement of need to the paper, and a shorter version to the readme.

We need to think about where to put which function. If we really follow the outline "centrality (point-estimates), uncertainty, existance and significane", which functions goes where?

1. Centrality / Point-Estimate
- `map_estimate()`

2. Uncertainty
- `hdi()`
- `ci()`

3. Existance (Evidence?)

4. Significance (Evidence?)



`rope()`, `equivqalence_test()`, `p_direction()`, `p_map()`, `bayesfactor()`, ... Suggestions where to place these functions?

**Comment by strengejacke** [comment]
I'll wait for feedback before continuing here.

**Comment by mattansb** [comment]
I think:
1. `p_map` and `pd` should be moved to **Existance** (together with they BF they answer the Q: is the parameter different than 0?)
2. `equivqalence_test` and `rope`/`p_rope` should be moved to **Significance** (they BF they answer the Q: is the parameter *meaningfully* different than 0?)

**Comment by mattansb** [comment]
This is a short paper, right? I might not get to it before Thursday... Sorry..

**Comment by strengejacke** [comment]
> This is a short paper, right?

Yes. JOSS-papers typically are about 2 to 5 pages, I think. The current insight-paper is an exception with some more pages... The focus for JOSS also lies on well-documented packages, including the website. So we need to take care of readme, website, package-docs and papers. In short, the repository typicall reqires a certain outline and content.

**Comment by DominiqueMakowski** [comment]
let me read

**Comment by DominiqueMakowski** [comment]
I've rephrased the statement of need and changed the title:

I am wondering about chaning the title from:

"**Understanding and Describing Bayesian Models with bayestestR**" 

to something like:


"**Estimating Effects and their Uncertainty, Existence and Significance in the Bayesian Framework using BayestestR**"

A bit longer but more accurate and punchy?

**Comment by strengejacke** [comment]
Revisions look good! According to the title: "Estimating Effects" is probably misleading, else I think a longer title is ok!

**Comment by strengejacke** [comment]
We may use your revisions from the last intro-paragraph for the readme as well.

**Comment by DominiqueMakowski** [comment]
>  p_map and pd should be moved to Existance (together with they BF they answer the Q: is the parameter different than 0?)
equivqalence_test and rope/p_rope should be moved to Significance (they BF they answer the Q: is the parameter meaningfully different than 0?)

**pd** is 100% an index of effect existence (about the certainty associated with a directionality). Rope percentage ans equivalence test are 100% indices of effect signififance (in the original meaning, important as in *non-negligible*).

For p_rope and p_map, I am not so sure, I would tend to say respectively significance and existence. For BF, it seems like it could be both depending on the hypothesis being tested (0, `]-Inf, 0[`, or `ROPE`)

**Comment by DominiqueMakowski** [comment]
title -> **Understanding and Describing Effects and their Uncertainty, Existence and Significance in the Bayesian Framework using BayestestR**?

**Comment by DominiqueMakowski** [comment]
`bayestestR: Understanding and Describing Effects and their Uncertainty, Existence and Significance in the Bayesian Framework`

**Comment by mattansb** [comment]
> For BF, it seems like it could be both depending on the hypothesis being tested

Good point! In that case it might be better to merge 3 and 4... I can add some explanation about the usage that is possible with out code regarding BFs (focusing on models and sdBF I think is most concise for this short ms).

**Comment by DominiqueMakowski** [comment]
In that case, maybe let's merge it under "NHST" here and we will discuss this category (and the distinction between existence and significance) in details in the other paper?

**Comment by strengejacke** [comment]
Sounds good! Shall I continue to work on the paper, or do you want to do the next step? I'm fine with both.

**Comment by DominiqueMakowski** [comment]
If you want you can go ahead I'll take a dinner break :)

**Comment by strengejacke** [comment]
Ok. One thing I also removed from the intro was the "compatible"-point, which is still in the get-started vignette:

> The Bayesian master assumes no such thing. The data are what they are. Based on this observed data [...] returns a probability distribution of the effect that is **compatible** with the observed data.

In the recent Nature article from Amrhein et al (https://www.nature.com/articles/d41586-019-00857-9), they use exactly the same wording for frequentist "confidence intervals". The correct interpretation of freq. CI is as if you think of it as a compatible interval.

That's why I would actually see more similarities between Freq and Bayes than some of the wording in the vignettes would suggest...

**Comment by strengejacke** [comment]
Oh, and bon appetit!

**Comment by mattansb** [comment]
This is interesting as this doesn't seem to be true for Bayes (well, only true if the prior is non-informative, which though a popular choice, is by no means the only possible one...) nor for freq (that "data is what it is" is almost blasphemous in the freq frame-work!)... No?

**Comment by DominiqueMakowski** [comment]
> One thing I also removed from the intro was the "compatible"-point

Sure, as long as this: "*The Bayesian master assumes no such thing. The data are what they are.*" stays somewhere (in the get started vignette). It is a very "mindfulness"-style punchline, and I think it fits nicely the broader imagery of the package... (as a loosely related fact, George Lucas' Jedi "religion" was directly inspired by the Buddhist/zen philosophies, that were themselves further formalised into the occidental Kabat-Zinnian mindfulness... so in a way, this punchline brings us closer to the Force 🙄)

**Comment by DominiqueMakowski** [comment]
> hat "data is what it is" is almost blasphemous in the freq frame-work!)

I agree that I hardly see how it applies to the freq framework as it is to my knowledge pretty much all built upon the assumption that the data is a random sample from a (normal) parent distribution 🤔

**Comment by strengejacke** [comment]
Actually, my only point was the emphasized **compatible**... :-?

**Comment by mattansb** [comment]
I went over the JOSS paper - polished up the BF stuff, and also some other little stylistic things in the into (I'm actually bilingual with English as one of my native languages - so even though my spelling is horrible, my grammar is actually pretty good (just ask my mom!)).

Looks good (:

**Comment by strengejacke** [comment]
Have you commited any changes?

**Comment by mattansb** [comment]
Yes, sorry - I forgot to tag this issue.
I committed to [dev](https://github.com/easystats/bayestestR/commit/805e9979ac1d2342f61d95ed6d2e235a250c5cb6)

**Comment by strengejacke** [comment]
Ok, I have revised the paper and I think I'm done with the first draft - it's your turn now. :-)

Here's a compiled PDF:
[paper.pdf](https://github.com/easystats/bayestestR/files/3335182/paper.pdf)

ToDo:
- [ ] Some references are not bib-styled yet, can someone check that all references are referring to a bibtex-entry?
- [ ] We have currently 8 pages, which might be too long. Can we shorten somewhere?

**Comment by mattansb** [comment]
Ideas for shortening:
1. A lot of the length seem to be related to placing of figs. So maybe make figures smaller / have the NHST figures as sub-figures together in a single figure (or both).
2. I think the part about the relationship between pd and the p-value can be cut. This will feature extensively elsewhere (soon!).

I think perhaps the intro can use some re-structuring, which will also have the desired effect of shortening, as some concepts seem to appear more than once: NHST, and the idea of how one might describe the posterior dist (once as a general intro, and again as what the aim of bayestestR is).
I will have some time tomorrow evening (easytime?) to get to this, if you'd like me to have a go at it.

**Comment by strengejacke** [comment]
> to get to this, if you'd like me to have a go at it.

Yes, would be great if you can take the next step. Note that I have also uploaded the R code files that generate the new figures into the paper-folder, in case that might help...

**Comment by DominiqueMakowski** [comment]
I have further streamlined the intro. I like the new figures. How did you generated the pdf? I wonder if it fits now into the 6 pages limit.

> I think the part about the relationship between pd and the p-value can be cut. This will feature extensively elsewhere (soon!).

True, especially since this information actually comes from the data for the other paper

**Comment by mattansb** [comment]
I removed the pd=pval stuff, and reduced the last 4 figures into 1 figure (now Fig 3) with captions (kinda? Just italicized text below the figures - other options didn't work) + some light touch-ups.

See [the PDF](https://github.com/easystats/bayestestR/blob/dev/paper/paper.pdf), now at just over 7 pages long (with references).

**Comment by DominiqueMakowski** [comment]
very nice :)
I would tend to try as is, and if they really need to further shorten a bit we will give it a second round

**Comment by strengejacke** [comment]
> How did you generate the pdf?

If you have a Tex installed, you can knit to PDF from RStudio.

**Comment by strengejacke** [comment]
Ok, I have updated the paper and checked the consistency of style.. We had some mixtures of `p value`, `p-value` and `*p*-value`, or sometimes packages were bold, sometimes in code-style. I now changed this to be consistent throughout the paper:

- p-value
- package names in bold
- function names in backticks, not formatted

I also added the reference to the figure 3 in the text, where appropriate, and I added the manual figure legends into the "legends" tags of the figures. JOSS will automatically set these as legends and numerate the figures.

Also, one reference from Mill's was missing.

I think the paper is in a really good shape now. We now have to check the [review-list](https://github.com/openjournals/joss-reviews/issues/1412) and see if we have also addressed all points _for the repo and website_.

@DominiqueMakowski will you finish this and do the submission?

**Comment by strengejacke** [comment]
And in general, what would you say if we update the section `map_estimate()` in our readme, similar to the paper, so we show all three types of point-estimates? I think the Fig. 1 in our paper nicely shows the differences (yes, I know I made this figure, but sometimes I _have to_ praise myself... :-D)

**Comment by strengejacke** [comment]
Oh, @mattansb we should think about giving @DominiqueMakowski a typewrite to reduce his inflationary use of italics. ;-)

**Comment by mattansb** [comment]
> what would you say if we update the section `map_estimate()` in our readme...

Agree.

> @mattansb we should think about giving @DominiqueMakowski an old-school typewriter...

Sure thing! We need to find a place that ships to Singapore!

**Comment by DominiqueMakowski** [comment]
> old-school typewriter to reduce his inflationary use of italics


it adds *reliefs* to the ***text***, making less prone to TLDR

> p-value

@humanfactors actually suggested using "*p* value" as it seems to be APA's guidelines...

> @DominiqueMakowski will you finish this and do the submission?

Alrighty

**Comment by strengejacke** [comment]
Ok, I'm open to any style for p-value as long as it's consistent. I just found:

> "P value" or "p value"
There is no uniform style.
The APA suggest "p value" The p is lowercase and italicized, and there is no hyphen between "p" and "value".
GraphPad has adapted the style "P value", which is used by the NEJM and journals. The P is upper case and not italicized, and there is no hyphen between "P" and "value". 
Sometimes, you see  "p-value". Note the hyphen.

**Comment by strengejacke** [comment]
> it adds reliefs to the text, making less prone to TLDR

*d*o **y**o_u_ _re**al**_y _t_**hi**n_k_ **so**?

**Comment by DominiqueMakowski** [comment]
> The APA suggest "p value" The p is lowercase and italicized, and there is no hyphen between "p" and "value".

Let's follow that then (these appears in several instances throughout the easystats project, I've started changing whenever I saw one)

I'll review everything tmr morning (my ***time***) and if probably submit in the morning (easytime) ☺️

**Comment by DominiqueMakowski** [comment]
> Let's follow that then (these appears in several instances throughout the easystats project, I've started changing whenever I saw one)

In fact, I think it makes sense to use "*p*-value": It is consistent with other similar stuff (*t*-test) and thanks to the hyphen it remains unified whether the italicized p is allowed or not (i.e., in R outputs p-value looks tidier than p value)...

**Comment by DominiqueMakowski** [comment]
I have revised the paper a bit, fixed some issues with citations, streamlined some parts (e.g., ROPE and equitest sections had some redundant info) and polished the figures. 

To me, it looks quite good ☺️ 

I have updated the [pdf](https://github.com/easystats/bayestestR/blob/master/paper/paper.pdf) and I will submit whenever I have your greenlight

**Comment by DominiqueMakowski** [comment]
Should we change the title from 

"bayestestR: Understanding and Describing Effects and their Uncertainty, Existence and Significance in the Bayesian Framework"

to 

bayestestR: Understanding and Describing Effects ***as well as*** their Uncertainty, Existence and Significance in the Bayesian Framework

To avoid too much "and"?

**Comment by humanfactors** [comment]
I don't think so...

> "bayestestR: Understanding and Describing Effects and their Uncertainty, Existence and Significance in the Bayesian Framework"

is a straightforward title, and the **_as well as_** doesn't actually add any information. To be honest, I'm not a huge fan of the title, but it does the job. I think you should be looking at making it shorter rather than longer - so I'd keep it as it is.

 If I was to change anything I would make `in the Bayesian Framework` `using/with a Bayesian Framework`.

**Comment by strengejacke** [comment]
Paper looks good, one thing you could change is the comment in the code-output on page 3: "Credible Interval" => "Equi-tailed interval" or so, to be consistent.

Title: what about

> bayestestR: Describing Effects and their Uncertainty, Existence and Significance using a Bayesian Framework

w/o "understanding"? If you describe something, you either already understood what you've done, or you begin to understand, so "understanding" is somehow implied with describing. :-)

**Comment by mattansb** [comment]
Maybe:
> bayestestR: Describing Effects and their Uncertainty, Existence and Significance within the Bayesian Framework

Other than that - looks good! 👍

**Comment by DominiqueMakowski** [comment]
> Paper looks good, one thing you could change is the comment in the code-output on page 3: "Credible Interval" => "Equi-tailed interval" or so, to be consistent.

As a matter of fact, should we add a function `eti()` for equal-tailed interval? So then `ci()` would be a more neutral function with two possible methods?

**Comment by DominiqueMakowski** [comment]
It has been submitted 🎉

**Comment by DominiqueMakowski** [comment]
Pre-review state: https://github.com/openjournals/joss-reviews/issues/1537

**Comment by DominiqueMakowski** [comment]
Link to review: https://github.com/openjournals/joss-reviews/issues/1541#issuecomment-507707525

**Comment by strengejacke** [comment]
Shall we add a new release now, to register a zenodo-DOI for the latest version?

**Comment by DominiqueMakowski** [comment]
I would wait for the editor's decision

**Comment by strengejacke** [comment]
probably makes sense...

**Comment by DominiqueMakowski** [comment]
😁

**Comment by strengejacke** [comment]
Looks like we might manage it to get the JOSS citation in time for the requested CRAN update, right?

**Comment by mattansb** [comment]
Amen to that!

**Comment by DominiqueMakowski** [comment]
https://www.youtube.com/watch?v=NgqtL8NqyOM

**Comment by mattansb** [comment]
@DominiqueMakowski  The most advance SW gif yet...

**Comment by strengejacke** [comment]
Shall we ping the editor?

**Comment by DominiqueMakowski** [comment]
tbh I would find it a bit impolite haha, it's summer after all some people do have a life (from what I've heard) :)

the cran deadline require us to submit the 8th at max. so I say we wait and worst case scenario we submit as is the 0.2.5 and the updated ref will go into the future update no big deal to me...

**Comment by strengejacke** [comment]
True, didn't want to push or be impatient. Usually reviewers explicitly ping the handling editor saying they are done, not sure if was clear 😉

Anyway, we can submit w/o joss citation in "worst case" (that case wouldn't be too bad anyway)

**Comment by DominiqueMakowski** [comment]
since CRAN submission are closing from 9 to 18, I suggest submitting this as-is now, and parameters down the road if it gets accepted fast. What do you say?

**Comment by mattansb** [comment]
Fine with me.

**Comment by strengejacke** [comment]
Yes, let's submit bayestestR (after win builder checks?).

**Comment by DominiqueMakowski** [comment]
@strengejacke if you have access to a computer can submit to winbuilder, otherwise I'll do it in 1 hour

**Comment by strengejacke** [comment]
I just arrived in the office and can do it if not too late

**Comment by strengejacke** [comment]
ok, done,

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/HkM0svA1p2sV
The files will be removed after roughly 72 hours.
Installation time in seconds: 14
Check time in seconds: 715
Status: OK
R Under development (unstable) (2019-07-05 r76784)

----

https://win-builder.r-project.org/zS4mvi9NvWjS
The files will be removed after roughly 72 hours.
Installation time in seconds: 14
Check time in seconds: 711
Status: 2 ERRORs, 1 NOTE
R version 3.5.3 (2019-03-11)

**Comment by DominiqueMakowski** [comment]
### tests that fail

```
  > library(testthat)
  > library(bayestestR)
  > 
  > test_check("bayestestR")
  -- 1. Failure: emmGrid ci (@test-emmGrid.R#16)  --------------------------------
  xci$CI_low not equal to c(-0.236749774206338, 1.23103419307697, -2.99025704276072).
  3/3 mismatches (average diff: 0.0574)
  [1] -0.266 - -0.237 == -0.0289
  [2]  1.338 -  1.231 ==  0.1070
  [3] -2.954 - -2.990 ==  0.0362
  
  -- 2. Failure: emmGrid p_rope (@test-emmGrid.R#58)  ----------------------------
  xprope$p_ROPE not equal to c(0.695, 1, 0.87).
  2/3 mismatches (average diff: 0.025)
  [1] 0.655 - 0.695 == -0.04
  [3] 0.880 - 0.870 ==  0.01
  
  # Proportion of samples inside the ROPE [-0.10, 0.10]:
  
   inside ROPE
        6.19 %
  
  == testthat results  ===========================================================
  [ OK: 110 | SKIPPED: 10 | WARNINGS: 14 | FAILED: 2 ]
  1. Failure: emmGrid ci (@test-emmGrid.R#16) 
  2. Failure: emmGrid p_rope (@test-emmGrid.R#58) 
  
  Error: testthat unit tests failed
  Execution halted
** running tests for arch 'x64' ... [64s] ERROR
  Running 'testthat.R' [63s]
Running the tests in 'tests/testthat.R' failed.
Complete output:
  > library(testthat)
  > library(bayestestR)
  > 
  > test_check("bayestestR")
  -- 1. Failure: emmGrid ci (@test-emmGrid.R#16)  --------------------------------
  xci$CI_low not equal to c(-0.236749774206338, 1.23103419307697, -2.99025704276072).
  3/3 mismatches (average diff: 0.0574)
  [1] -0.266 - -0.237 == -0.0289
  [2]  1.338 -  1.231 ==  0.1070
  [3] -2.954 - -2.990 ==  0.0362
  
  -- 2. Failure: emmGrid p_rope (@test-emmGrid.R#58)  ----------------------------
  xprope$p_ROPE not equal to c(0.695, 1, 0.87).
  2/3 mismatches (average diff: 0.025)
  [1] 0.655 - 0.695 == -0.04
  [3] 0.880 - 0.870 ==  0.01
  
  # Proportion of samples inside the ROPE [-0.10, 0.10]:
  
   inside ROPE
        6.19 %
  
  == testthat results  ===========================================================
  [ OK: 110 | SKIPPED: 10 | WARNINGS: 14 | FAILED: 2 ]
  1. Failure: emmGrid ci (@test-emmGrid.R#16) 
  2. Failure: emmGrid p_rope (@test-emmGrid.R#58) 
```

### Examples too long

``
Examples with CPU or elapsed time > 10s
   user system elapsed
ci 4.29   0.64   10.07`
```

**Comment by DominiqueMakowski** [comment]
I'll address and submit

**Comment by strengejacke** [comment]
> increasing the tol should resolve

I don't think so, we would end up in having a tolerance for literally _any_ value. Maybe we should skip for R < 3.6? We have had these problems with emmeans before, and I'm not sure why.

**Comment by mattansb** [comment]
Question is - why have the values changed at all - it ran fine last time around, no?

**Comment by strengejacke** [comment]
Yes, strange indeed. I recall i had something similar with one of my other packages, also related to emmeans. Not sure how I fixed it, though.

**Comment by strengejacke** [comment]
@DominiqueMakowski I just saw that the handling editor has changed his posting into a check-list, not sure if you can check those items? Maybe he waits until these are marked as "done"?

**Comment by DominiqueMakowski** [comment]
I can't check them... but I start to think that Chris has a cyclical schedule of checking the state of its assigned papers  like once every x days 😁, thus he'll probably accept on his next round 🤞

**Comment by strengejacke** [comment]
great work, guys, nice publication! @mattansb I think you must request authorship in researchgate, not sure if your account was correctly linked to the entry in RG.

Close this now?

**Comment by DominiqueMakowski** [comment]
Let's close, awesome synergic teamwork, that can now fully focus ON OUR NEXT CHALLENGE 👀 ☺️
