### ISSUE TITLE
Roll back R dependency to 3.4

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#362]
See https://github.com/easystats/easystats/issues/98

**Comment by IndrajeetPatil** [comment]
https://github.com/easystats/bayestestR/blob/611064234deafa94aa51f8895e9095e361f921db/DESCRIPTION#L57-L58

**Comment by bersbersbers** [comment]
I do not understand this change - maybe someone can explain? `bayestestR` depends on `R>=3.4`, but depends on `insight≥ 0.12.0` which in turn requires `R>=3.6`.

So what happens is that `R==3.5` tries to update from `bayestestR==0.8.0` to `bayestestR==0.8.2` and fails:

```
* installing *source* package ‘bayestestR’ ...
** package ‘bayestestR’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘insight’ 0.11.1 is being loaded, but >= 0.12.0 is required
```

How is this supposed to be installed on `R==3.5`?

**Comment by IndrajeetPatil** [comment]
Hi, you are right that this is inconsistent across `easystats` packages. We have been updating packages to be internally consistent. You can track that progress here:
https://github.com/easystats/easystats/issues/98

By the end of this or next month, all `easystats` packages should expect minimum `R` version to be `3.4`.

**Comment by strengejacke** [comment]
Yes, we decided to make our packages work for R > 3.4 last month, and depending on the time schedule, some packages are earlier on CRAN than others. I guess by the end of this month, most packages, including insight, should be on CRAN and depend on R > 3.4
