### ISSUE TITLE
Extremely minor question - bf_point*ull* ?

### ISSUE THREAD

**Issue by stephensrmmartin** [easystats/bayestestR#363]
I noticed that you have bf_point*ull*; was this supposed to say bf_point*null*?

That's it. That's the "bug" report.

**Comment by DominiqueMakowski** [comment]
omg 😱 how did we miss this!
 
It's actually a totally legit bug report ^^ thanks a lot @stephensrmmartin

**Comment by strengejacke** [comment]
Indeed strange, that no-one from caught this? 😭

**Comment by mattansb** [comment]
🤣🤣🤣🤣🤣

**Comment by IndrajeetPatil** [comment]
![tenor](https://user-images.githubusercontent.com/11330453/105146933-cc42f580-5b00-11eb-8cea-2c039744f2f3.gif)
