### ISSUE TITLE
Allow specifying "pars" for inclusion in bayestestR functions

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#37]
See https://github.com/strengejacke/sjstats/issues/72

> I fit an errors-in-variables model in brms (i.e., with the term me(age, age_se)) and sjstats parameter extraction misfired (it shows a bunch of parameters in tab_model and equi_test that are not shown when calling summary.brmsfit. It would be cool, if you permitted a pars argument like many brms and bayesplot functions to allow customisation.
>
> This would not just be useful for misfiring like above, but also to trim the tested parameters in equi_test if not all are of substantial interest.

**Comment by strengejacke** [comment]
@DominiqueMakowski We should think about addressing this issue for the initial release... It shouldn't be too hard, given that we already filter out some parameters. And in the long term, this will be handled inside insight (haha).

**Comment by DominiqueMakowski** [comment]
yes, and it applies to all the function that runs on models (hdi, rope, future ci...) right ?

**Comment by strengejacke** [comment]
yes. Affected should be `hdi()`, `rope()`, `equivalence_test()` and (future) `ci()`.

**Comment by rubenarslan** [comment]
Reproducible example


```r
  library(brms)
  mod <- brm(y ~ me(x, sdx), data = data.frame(y = rnorm(100), x = rnorm(100), sdx = runif(100, min = 0, 1)), cores = 4)
sjPlot::tab_model(mod)
mod <- brm(y ~ me(x, sdx), data = data.frame(y = rnorm(100), x = rnorm(100), sdx = runif(100, min = 0, 1)), cores = 4, save_mevars = TRUE)
sjPlot::tab_model(mod)
```

Even worse, when we turn on save_mevars = TRUE

**Comment by strengejacke** [comment]
What are parameters of interest here? `bsp_mexsdx`, but also `meanme_mex` or `sdme_mex `?

**Comment by strengejacke** [comment]
Meanwhile, I'm not quite sure if bayestestR is affected by this issue... It gets the data from `insight::get_parameters()`, and that function only returns "coefficients", i.e. parameters starting with `b_`.

It actually removes probably a bit too much, since monotonic or categorical effects (starting with `bsp_` and `bcs_`) are also filtered out, but this is already fixed (see https://github.com/easystats/insight/commit/fe8fe31f12090a0c3a402bb84f1fe88ba8e06a84).

But we could implement something like `pars` anyway, in order to select specific parameters only. We should probably also think about if `get_parameters()` is indeed too strict, but my impression is that the current implementation is ok - if someone wants _all_ parameters, you still can use `as.data.frame()` on the model-object.

**Comment by DominiqueMakowski** [comment]
I agree, people interested in *all* auxiliary parameters can just run `as.data.frame(model)` and the bayestestR functions on that. Although it might be worth a small section in one vignette somewhere showing how to do that with sapply.

**Comment by rubenarslan** [comment]
Please add a `pars` argument – I often want to restrict a graph or table to relevant effects.

I think it would be good if the default mirrored whatever @paul-buerkner does in brms:::summary.brmsfit, maybe you can just copy that rule? In this case, we want bsp_ but not meanme oder sdme

**Comment by strengejacke** [comment]
Ok, I think we can make it this way... Filtering all `b_`, `bsp_` and `bcs_` for fixed part of the model, and `pars` accepts regex for further filtering.

**Comment by strengejacke** [comment]
I just realized that we could extend `pars` to other functions like `p_rope` etc. as well...

**Comment by DominiqueMakowski** [comment]
Yes, sure, although I am not fond of the "pars" name... Wouldn't it be more consistent for the argument to be called something like `parameters`?

**Comment by strengejacke** [comment]
Yeah, we could name it `parameters`, I currently just used the naming convention from brms or rstanarm.

**Comment by DominiqueMakowski** [comment]
Then `parameters` with "*See `pars` argument in brms and rstanarm*" in the docstrings 😁 ?

**Comment by strengejacke** [comment]
Just to clarify: for `equivalence_test()`, I would just report the _fixed_ effects from the _conditional_ component (i.e. no random effects nor zero-inflation part), or does it make sense to include these values in the equivalence-testing as well?

**Comment by strengejacke** [comment]
I think we can close this now, as this option is now implemented for all functions in bayestestR. After checks have passed, I'll merge the PR.

**Comment by rubenarslan** [comment]
That was quick! Cheers. What is the counterpart of `sjPlot::tab_model` in the easyverse? Does it allow restricting parameters too now?

**Comment by strengejacke** [comment]
No, not yet. It requires some substantial re-writing of code to implement the easyverse packages, but it's definitely a future goal.

**Comment by strengejacke** [comment]
@rubenarslan I just remembered that there are some arguments to filter parameters from the output in `tab_model()`, namely `terms` and `rm.terms`. Were you looking for this?

**Comment by paoloinglese** [comment]
Can you please update your website where you explain how to use equi_test with these additional options? Thx!
