### ISSUE TITLE
Argument for pd so that the pd is calculated relative to a non-zero number

### ISSUE THREAD

**Issue by nahorp** [easystats/bayestestR#374]
**Describe the solution you'd like**
Currently, for `pd`, using the `direct` method, the % is a reflection of the ratio of samples superior and inferior to 0 (depending on the median's sign). However, there are occasions, where a non-zero 'reference' value, so to speak, might be beneficial. For instance, passing a contrast that is a ratio (instead of a difference) to `describe_posterior` and hence `pd` (if requested) where 1 indicates 'no difference' and hence that is the value around which the ratio of samples should be calculated (not 0).

Solution would be to be able to choose the reference value (perhaps having 0 as the default)

**How could we do it?**
An argument passed to `pd`, such as, `reference` or `ref`, that can be selected to be 1 (in the above example).

**Comment by DominiqueMakowski** [comment]
Interesting point, @mattansb @strengejacke thoughts? We could indeed add an argument similar to `bf_pointnull(x, null=0)`

**Comment by mattansb** [comment]
Yup, makes sense (:

Are there really any other values that it can take besides 0 (difference) and 1 (for ratio)?

**Comment by nahorp** [comment]
> Are there really any other values that it can take besides 0 (difference) and 1 (for ratio)?

Those are the only 2 that I can think of...

**Comment by nahorp** [comment]
I don't wish to be persistent (considering many aspects that don't require you acting on this request) but is there some sort of timeframe with this or some sort of manual code I could use on the `emmGrid` object that is passed to `describe_posterior` (writing my first Bayesian manuscript based on parameter inference and a bit under the pump to get moving... #phdlife) ?

**Comment by mattansb** [comment]
Until then, here is a quick and dirty work around:

``` r
library(rstanarm)
library(emmeans)

m <- stan_glm(
  am ~ factor(cyl),
  data = mtcars,
  family = binomial(),
  refresh = 0
)

M <- emmeans(m, ~ cyl)
C <- pairs(M)
(Cr <- regrid(C, trans = "response"))
#>  contrast odds.ratio lower.HPD upper.HPD
#>  4/6            3.70     0.146      21.8
#>  4/8           17.76     0.907     120.5
#>  6/8            4.89     0.109      36.3
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95

vals <- insight::get_parameters(Cr)

bayestestR::p_direction(vals - 1)
#> # Probability of Direction (pd)
#> 
#> Parameter |     pd
#> ------------------
#> 4/6       | 89.58%
#> 4/8       | 99.92%
#> 6/8       | 92.07%
```

<sup>Created on 2021-02-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
@nahorp would you mind trying a PR :) ? we can assist you in the process

**Comment by nahorp** [comment]
Thanks @mattansb, that works great! :)

Haven't done a PR to a repository like this before (and not that well versed in R even though conceptually I think I know what needs doing) but happy to give it a shot! Just to be clear, I'd tinker with the code at the link below and then send a pull request?

https://github.com/easystats/bayestestR/blob/master/R/p_direction.R

**Comment by DominiqueMakowski** [comment]
yes :)

**Comment by DominiqueMakowski** [comment]
it can be a bit overwhelming the first time, especially if they are conflicts or such, but don't worry we've all been there

**Comment by nahorp** [comment]
Sounds good @DominiqueMakowski - shall give this a crack in due time :)

**Comment by IndrajeetPatil** [comment]
Did #385 address all of this? Can this issue be closed?

**Comment by DominiqueMakowski** [comment]
I think so
