### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#38]
This issue to plan the documentation, to avoid redundancy and making the documentation useful, clear and easily findable

- **README**
  - All main functions with their docstrings?
- **Vignettes**
  - Get started
    - Why use the Bayesian framework?
    - A very simple linear model
  - Example: Bayesian GLMs
  - Example: Bayesian mixed models
  - In depth: Point estimates comparison
  - In depth: Indices of effect existence comparison
  - Reporting guidelines

@strengejacke How would do you see it?

Altough I feel like analyses examples should be in this repo, the home for Bayesian-related stuff, at the same time it would make then sense to add here the other aspects related to Bayesian models present in easystats (such as model's performance, contrasts estimates, report (and visreport?) etc.

Ressources (for inspiration):
- https://strengejacke.github.io/sjstats/articles/bayesian-statistics.html

**Comment by strengejacke** [comment]
Yes, sounds good to me!

One thing I don't understand in the docs, from `rope()`:

> Besides the ROPE-based decision criteria, the proportion of the 95% CI that falls in the ROPE can be used as a continuous index.

**Comment by strengejacke** [comment]
We have a circular dependency here:
https://github.com/easystats/bayestestR/blob/master/vignettes/bayestestR.Rmd

This vignettes can't be included until _reporter_ is on CRAN.

**Comment by DominiqueMakowski** [comment]
shoot, that's right. I will remove it from the docs from now, so bayestestR's release is not tied to the others. And I will push for the others' initial CRAN submission, I think that they are stable enough in their basic features to be released? what do you think?

> > Besides the ROPE-based decision criteria, the proportion of the 95% CI that falls in the ROPE can be used as a continuous index.

I will address that.
