### ISSUE TITLE
effective sample size for BayesFactor objects

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/bayestestR#382]
Does it make sense for us to add a method for `BFBayesFactor` objects for computing ESS?

For example, http://pcl.missouri.edu/sites/default/files/Rouder.bf_.pdf talks about ESS for _t_-test.

![image](https://user-images.githubusercontent.com/11330453/109530734-534b9c00-7ab7-11eb-94dd-fdb1652fe33b.png)

To the best I know, `BayesFactor` doesn't return these by default, and maybe `bayestestR` can fill in that gap?

**Comment by mattansb** [comment]
This is really interesting - I'm not sure this is the ESS as it relates to the posterior samples (as BayesFactor doesn't use posterior samples to compute BFs)...
