### ISSUE TITLE
bayesfactor_models throws warning for lavaan objects

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#383]
``` r
library(lavaan)
#> This is lavaan 0.6-6
#> lavaan is BETA software! Please report any bugs.

structure <- " visual  =~ x1 + x2 + x3
                 textual =~ x4 + x5 + x6
                 speed   =~ x7 + x8 + x9

                  visual ~~ textual + speed "
m1 <- lavaan::cfa(structure, data = HolzingerSwineford1939)

structure <- " visual  =~ x1 + x2 + x3
                 textual =~ x4 + x5 + x6
                 speed   =~ x7 + x8 + x9

                  visual ~~ 0 * textual + speed "
m2 <- lavaan::cfa(structure, data = HolzingerSwineford1939)

bayestestR::bayesfactor_models(m1, m2)
#> Warning: Unable to extract terms from the following models:
#> m1, m2
#> # Bayes Factors for Model Comparison
#> 
#> Model         BF
#> [2] m2 2.432e-07
#> 
#> * Against Denominator: [1] m1
#> *   Bayes Factor Type: BIC approximation
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It wasn't present in earliest versions, but i wonder if it's from insight or bayestestR 🤔 

> Warning: Unable to extract terms from the following models: m1, m2

**Comment by strengejacke** [comment]
Warning stems from here:

https://github.com/easystats/bayestestR/blob/8804dcbbbb5ba52b6b2d8551991d732acd207f5b/R/bayesfactor_models.R#L178-L196

Not sure when this change was made, but the call

```
 temp_forms <- sapply(mods, .find_full_formula)
```

does return `NULL` for the formula, because the formula from lavaan-models can't be extracted.

**Comment by mattansb** [comment]
Yes, I will move this warning to the correct place (and will explain) tomorrow 🤧
