### ISSUE TITLE
revise printing methods, part 2

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#399]
Follow up of #393, but w/o all the cluttered comments from me ;-)

New print already implemented for:

- [x] ci / eti
- [x] describe_posterior
- [x] ~~describe_prior~~ _(doesn't need a print?)_
- [ ] equivalence_test (a bit trickier)
- [x] hdi
- [x] map_estimate
- [x] mhdior
- [x] p_direction
- [x] p_map
- [x] p_rope
- [x] p_significance
- [x] point_estimate
- [x] ~~rope~~ _(this is lower priority, as the print-method is a bit trickier to generalize)_
- [x] si

Bayes factors seem to have quite recent print-methods

**Comment by strengejacke** [comment]
So here are the templates:

`format()`: https://github.com/easystats/bayestestR/blob/master/R/format.R
`print()`: https://github.com/easystats/bayestestR/blob/master/R/print.R
`print_html()`: https://github.com/easystats/bayestestR/blob/master/R/print_html.R
`print_md()`: https://github.com/easystats/bayestestR/blob/master/R/print_md.R

**Comment by strengejacke** [comment]
@mattansb @DominiqueMakowski should we round ESS values to integers?

**Comment by DominiqueMakowski** [comment]
> should we round ESS values to integers?

I think so, it seems common practice (e.g., in "posterior")

**Comment by strengejacke** [comment]
I also updated bayesfactor_models. The advantage of having the new API is that we can easily add print for html/md:

``` r
library(bayestestR)
#> Note: The default CI width (currently `ci=0.89`) might change in future versions (see https://github.com/easystats/bayestestR/discussions/250). To prevent any issues, please set it explicitly when using bayestestR functions, via the 'ci' argument.

lm1 <- lm(Sepal.Length ~ 1, data = iris)
lm2 <- lm(Sepal.Length ~ Species, data = iris)
lm3 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm4 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)

bayesfactor_models(lm1, lm2, lm3, lm4, denominator = 1)
#> Bayes Factors for Model Comparison
#> 
#>       Model                      BF
#> [lm2] Species                > 1000
#> [lm3] Species + Petal.Length > 1000
#> [lm4] Species * Petal.Length > 1000
#> 
#> * Against Denominator: [lm1] (Intercept only)
#> *   Bayes Factor Type: BIC approximation

print_md(bayesfactor_models(lm1, lm2, lm3, lm4, denominator = 1))
```

<table>
<caption>Bayes Factors for Model Comparison</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Model</th>
<th style="text-align: right;">BF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">[lm2]</td>
<td style="text-align: left;">Species</td>
<td style="text-align: right;">&gt; 1000</td>
</tr>
<tr class="even">
<td style="text-align: left;">[lm3]</td>
<td style="text-align: left;">Species + Petal.Length</td>
<td style="text-align: right;">&gt; 1000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">[lm4]</td>
<td style="text-align: left;">Species * Petal.Length</td>
<td style="text-align: right;">&gt; 1000</td>
</tr>
</tbody>
</table>

Against Denominator: \[lm1\] (Intercept only)
Bayes Factor Type: BIC approximation

``` r
print_html(bayesfactor_models(lm1, lm2, lm3, lm4, denominator = 1))
```
<div id="xmgkvewvuf" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="3" class="gt_heading gt_title gt_font_normal" style>Bayes Factors for Model Comparison</th>
    </tr>
    <tr>
      <th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Name</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Model</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">BF</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">[lm2]</td>
      <td class="gt_row gt_center">Species</td>
      <td class="gt_row gt_center">&gt; 1000</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">[lm3]</td>
      <td class="gt_row gt_center">Species + Petal.Length</td>
      <td class="gt_row gt_center">&gt; 1000</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">[lm4]</td>
      <td class="gt_row gt_center">Species * Petal.Length</td>
      <td class="gt_row gt_center">&gt; 1000</td>
    </tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="3">Against Denominator: [lm1] (Intercept only)</td>
    </tr>
    <tr>
      <td class="gt_sourcenote" colspan="3">Bayes Factor Type: BIC approximation</td>
    </tr>
  </tfoot>
  
</table></div>

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
awesome (not to brag or anything but I too did update the printing of correlation... all the *two* methods in it 😁)

**Comment by strengejacke** [comment]
@mattansb for `bayesfactor_restricted()`, should the column names be `P(...)`, or `Pr(...)`?

``` r
library(bayestestR)
#> Note: The default CI width (currently `ci=0.89`) might change in future versions (see https://github.com/easystats/bayestestR/discussions/250). To prevent any issues, please set it explicitly when using bayestestR functions, via the 'ci' argument.
prior <- data.frame(
  X = rnorm(100),
  X1 = rnorm(100),
  X3 = rnorm(100)
)

posterior <- data.frame(
  X = rnorm(100, .4),
  X1 = rnorm(100, -.2),
  X3 = rnorm(100)
)

hyps <- c(
  "X > X1 & X1 > X3",
  "X > X1"
)

bayesfactor_restricted(posterior, hypothesis = hyps, prior = prior)
#> Bayes Factor (Order-Restriction)
#> 
#> Hypothesis       P(Prior) P(Posterior)   BF
#> X > X1 & X1 > X3     0.14         0.31 2.21
#> X > X1               0.47         0.71 1.51
#> 
#> * Bayes factors for the restricted model vs. the un-restricted model.
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
Ok, I think this can be closed. There are a few print-methods untouched, but I will not revise those now or any time soon. We could think about revising print for rope or equivalence_test as well, so we have md/html tables, but this seems to be a bit more work...

**Comment by mattansb** [comment]
@strengejacke As long as bf_inclusion and bf_restricted are the same, doesn't matter if it's P ot Pr (:

Honestly I should have also made the column names in the output the same... Too late?

**Comment by strengejacke** [comment]
> Honestly I should have also made the column names in the output the same... Too late?

No, I don't think so. If I see it correctly, only the BF column should be named "BF", else the column names are changed in the print-methods, anyway, and not referred to directly.
