### ISSUE TITLE
Skip CI on Windows?

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#401]
Looking at the test results from GitHub CI, these mysterious errors on Windows don't seem to disappear. Do we want to skip Windows in the GitHub action?

**Comment by mattansb** [comment]
Super weird errors... Can't even track where in the test it fails??

**Comment by IndrajeetPatil** [comment]
Hmm, no, I think it's a bad idea to not check on Windows, given how many of our users will be working with PCs. We'd like to know if something is not working as expected.

We just need to figure out which `brms` model is running into this issue. It's the same issue as this one: https://discourse.mc-stan.org/t/c-stack-trace-errors/19172

I wish I knew any `C++` to debug things like these. But I will see what I can do.

**Comment by strengejacke** [comment]
@DominiqueMakowski There are some tests that need to be fixed after all our updates (my prior stuff and your .95 stuff). And I suggest for now skipping CI testing for windows OS, until we found how to fix that strange error. After doing that, we could think about submitting bayestestR to CRAN, no?

**Comment by DominiqueMakowski** [comment]
> And I suggest for now skipping CI testing for windows OS, until we found how to fix that strange error. 

Ok will give it a go now

> After doing that, we could think about submitting bayestestR to CRAN, no?

Yes!

**Comment by DominiqueMakowski** [comment]
> And I suggest for now skipping CI testing for windows OS

You mean just for the GH action or in general?
