### ISSUE TITLE
Opaque warning when rope_range is called from other packages

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#402]
The verbose-argument wasn't properly passed to `describe_posterior()` from `model_parameters()`, but this is fixed now:

``` r
library(rstanarm)
#> Loading required package: Rcpp
#> This is rstanarm version 2.21.1
#> - See https://mc-stan.org/rstanarm/articles/priors for changes to default priors!
#> - Default priors may change, so it's safest to specify priors, even if equivalent to the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#>   options(mc.cores = parallel::detectCores())
library(dotwhisker)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'broom.mixed':
#>   method      from 
#>   tidy.gamlss broom

fit <- stan_lm(mpg ~ wt + qsec + cyl,
               data = mtcars, prior = R2(0.75),
               refresh = 0, seed = 101
)
#> Warning: There were 19 divergent transitions after warmup. See
#> http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup
#> to find out why this is a problem and how to eliminate them.
#> Warning: Examine the pairs() plot to diagnose sampling problems
dwplot(fit, verbose = FALSE)
```

![](https://i.imgur.com/HgSeIkK.png)

<sup>Created on 2021-03-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

_Originally posted by @strengejacke in https://github.com/easystats/bayestestR/issues/364#issuecomment-804693335_

**Comment by strengejacke** [comment]
@mattansb @DominiqueMakowski 

The general problem here is:
  
> but it's super-opaque to figure out what to do about it if it pops up (apparently) out of nowhere ...

The chain of functions calls is roughly:
dwplot -> dw_tidy -> model_parameters -> describe_posterior -> rope -> rope_range.

While it make sense to have that warning when calling `describe_posterior()`, or `model_parameters()`, as we report the rope and rope-range in that output, it really isn't clear what this warning would mean in the context of a simple coefficient plot.

I see two options (pinging @bbolker), which mainly require changes in the _dotwhisker_ package:
  
1. use the `verbose`-argument, which will - however - only work after _insight_, _bayestestR_ and _parameters_ are updated on CRAN (probably somewhere around mid to end of April)
2. Don't request tests: `dotwhisker::dwplot(fit, test = NULL)`. As you can see from the docs (https://easystats.github.io/parameters/reference/model_parameters.stanreg.html), there is a `test` argument that runs different "tests" on the posterior distribution, which is not necessary if the goal is just plotting coefficients.

But of course, we would be happy if @bbolker also has ideas on [this ussue](https://github.com/easystats/bayestestR/issues/364). :-)

**Comment by mattansb** [comment]
Seeing as how `dwplot()` doesn't actually use the rope,
it should be calling `describe_posterior()`/`model_parameters()` with `test = NULL`....
