### ISSUE TITLE
include prior info in `describe_posterior()`

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#404]
It was not possible before to show prior information for brms-models in `describe_posterior()`. I now enabled that feature and tried to ensure in different places in _bayestestR_ (`check_prior()`, `describe_prior()`) that the parameter names match. 

There are several special cases, where we have priors that are not explicitly defined for each parameter and then "vectorized", so `insight::get_priors()` returns a data frame of different length then parameters (via `get_parameters()`). Now this should be fixed, and prior information should be possible to print for different models. You may check if everything still works as intended :-)

(pinging @IndrajeetPatil )

``` r
library(bayestestR)
library(magrittr)

describe_posterior(model1, priors = TRUE) %>% print_md()
```

<table style="width:100%;">
<caption>Summary of Posterior Distribution</caption>
<colgroup>
<col style="width: 11%" />
<col style="width: 6%" />
<col style="width: 14%" />
<col style="width: 4%" />
<col style="width: 13%" />
<col style="width: 9%" />
<col style="width: 5%" />
<col style="width: 7%" />
<col style="width: 23%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Median</th>
<th style="text-align: left;">95% CI</th>
<th style="text-align: left;">pd</th>
<th style="text-align: left;">ROPE</th>
<th style="text-align: right;">% in ROPE</th>
<th style="text-align: left;">Rhat</th>
<th style="text-align: left;">ESS</th>
<th style="text-align: left;">Prior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">37.27</td>
<td style="text-align: left;">[33.23, 41.02]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.60, 0.60]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">1.001</td>
<td style="text-align: left;">3555.00</td>
<td style="text-align: left;">Normal (20.09 +- 15.07)</td>
</tr>
<tr class="even">
<td style="text-align: left;">wt</td>
<td style="text-align: right;">-5.34</td>
<td style="text-align: left;">[-6.47, -4.11]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.60, 0.60]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">1.001</td>
<td style="text-align: left;">3679.00</td>
<td style="text-align: left;">Normal (0.00 +- 15.40)</td>
</tr>
</tbody>
</table>

``` r

describe_posterior(model2, priors = TRUE) %>% print_md()
```

<table>
<caption>Summary of Posterior Distribution</caption>
<colgroup>
<col style="width: 11%" />
<col style="width: 6%" />
<col style="width: 13%" />
<col style="width: 6%" />
<col style="width: 12%" />
<col style="width: 9%" />
<col style="width: 5%" />
<col style="width: 7%" />
<col style="width: 26%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Median</th>
<th style="text-align: left;">95% CI</th>
<th style="text-align: right;">pd</th>
<th style="text-align: left;">ROPE</th>
<th style="text-align: right;">% in ROPE</th>
<th style="text-align: left;">Rhat</th>
<th style="text-align: left;">ESS</th>
<th style="text-align: left;">Prior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept[1]</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: left;">[ 0.36, 0.72]</td>
<td style="text-align: right;">100%</td>
<td style="text-align: left;">[-0.18, 0.18]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">1.000</td>
<td style="text-align: left;">2474.00</td>
<td style="text-align: left;">Student_t (df=3) (0 +- 2.50)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Intercept[2]</td>
<td style="text-align: right;">2.36</td>
<td style="text-align: left;">[ 1.85, 3.02]</td>
<td style="text-align: right;">100%</td>
<td style="text-align: left;">[-0.18, 0.18]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">1.000</td>
<td style="text-align: left;">1515.00</td>
<td style="text-align: left;">Student_t (df=3) (0 +- 2.50)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intercept[3]</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: left;">[-0.62, 1.67]</td>
<td style="text-align: right;">78.60%</td>
<td style="text-align: left;">[-0.18, 0.18]</td>
<td style="text-align: right;">20.25%</td>
<td style="text-align: left;">1.000</td>
<td style="text-align: left;">1848.00</td>
<td style="text-align: left;">Student_t (df=3) (0 +- 2.50)</td>
</tr>
<tr class="even">
<td style="text-align: left;">period</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: left;">[-0.08, 0.54]</td>
<td style="text-align: right;">91.25%</td>
<td style="text-align: left;">[-0.18, 0.18]</td>
<td style="text-align: right;">39.51%</td>
<td style="text-align: left;">0.999</td>
<td style="text-align: left;">2395.00</td>
<td style="text-align: left;">Normal (0 +- 5.00)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">carry</td>
<td style="text-align: right;">-0.22</td>
<td style="text-align: left;">[-0.55, 0.12]</td>
<td style="text-align: right;">90.00%</td>
<td style="text-align: left;">[-0.18, 0.18]</td>
<td style="text-align: right;">40.72%</td>
<td style="text-align: left;">1.002</td>
<td style="text-align: left;">1299.00</td>
<td style="text-align: left;">Normal (0 +- 5.00)</td>
</tr>
<tr class="even">
<td style="text-align: left;">treat.1.</td>
<td style="text-align: right;">-0.77</td>
<td style="text-align: left;">[-1.22, -0.30]</td>
<td style="text-align: right;">100%</td>
<td style="text-align: left;">[-0.18, 0.18]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">1.001</td>
<td style="text-align: left;">1540.00</td>
<td style="text-align: left;">Normal (0 +- 5.00)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">treat.2.</td>
<td style="text-align: right;">-1.01</td>
<td style="text-align: left;">[-2.24, 0.14]</td>
<td style="text-align: right;">96.75%</td>
<td style="text-align: left;">[-0.18, 0.18]</td>
<td style="text-align: right;">5.37%</td>
<td style="text-align: left;">0.999</td>
<td style="text-align: left;">1318.00</td>
<td style="text-align: left;">Normal (0 +- 5.00)</td>
</tr>
<tr class="even">
<td style="text-align: left;">treat.3.</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: left;">[-1.30, 3.29]</td>
<td style="text-align: right;">84.50%</td>
<td style="text-align: left;">[-0.18, 0.18]</td>
<td style="text-align: right;">8.63%</td>
<td style="text-align: left;">1.001</td>
<td style="text-align: left;">1802.00</td>
<td style="text-align: left;">Normal (0 +- 5.00)</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-03-31 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
I think this is a bug related to this update right?

``` r
library(blavaan)
#> Loading required package: lavaan
#> This is lavaan 0.6-8
#> lavaan is FREE software! Please report any bugs.
#> Loading required package: Rcpp
#> Loading required package: RcppParallel
#> 
#> Attaching package: 'RcppParallel'
#> The following object is masked from 'package:Rcpp':
#> 
#>     LdFlags
#> This is blavaan 0.3-15
#> On multicore systems, we suggest use of future::plan("multiprocess") for faster post-MCMC computations.

model <- '
    # latent variable definitions
    dem60 =~ y1 + a*y2
    dem65 =~ y5 + a*y6

    # regressions
    dem65 ~ dem60

    # residual correlations
    y1 ~~ y5
  '


bfit <- blavaan::bsem(model, data = lavaan::PoliticalDemocracy, n.chains = 1, burnin = 50, sample = 100)

bayestestR::check_prior(bfit)
#> Error in `[.data.frame`(priors, match(cleaned_parameters$Cleaned_Parameter, : undefined columns selected
```

<sup>Created on 2021-03-31 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
Yes, will look into this later (currently running revdep checks on insight)

**Comment by strengejacke** [comment]
``` r
library(bayestestR)
library(magrittr)
library(blavaan)
model <- '
    # latent variable definitions
    dem60 =~ y1 + a*y2
    dem65 =~ y5 + a*y6

    # regressions
    dem65 ~ dem60

    # residual correlations
    y1 ~~ y5
  '

bfit <- blavaan::bsem(model, data = lavaan::PoliticalDemocracy, n.chains = 1, burnin = 50, sample = 100)
check_prior(bfit)
#> Warning: Parameters and priors could not be fully matched. Only returning
#> results for parameters with matching priors.
#>       Parameter Prior_Quality
#> 1     dem60=~y2   informative
#> 2   dem65~dem60 uninformative
#> 3        y1~~y5   informative
#> 4        y1~~y1   informative
#> 5        y2~~y2   informative
#> 6        y5~~y5   informative
#> 7        y6~~y6   informative
#> 8  dem60~~dem60 uninformative
#> 9  dem65~~dem65 uninformative
#> 10         y1~1 uninformative
#> 11         y2~1 uninformative
#> 12         y5~1 uninformative
#> 13         y6~1 uninformative

describe_posterior(bfit, priors = TRUE) %>% print_md()
```

<table>
<caption>Summary of Posterior Distribution</caption>
<colgroup>
<col style="width: 11%" />
<col style="width: 9%" />
<col style="width: 8%" />
<col style="width: 14%" />
<col style="width: 4%" />
<col style="width: 12%" />
<col style="width: 9%" />
<col style="width: 5%" />
<col style="width: 6%" />
<col style="width: 18%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Component</th>
<th style="text-align: right;">Median</th>
<th style="text-align: left;">95% CI</th>
<th style="text-align: left;">pd</th>
<th style="text-align: left;">ROPE</th>
<th style="text-align: right;">% in ROPE</th>
<th style="text-align: left;">Rhat</th>
<th style="text-align: right;">ESS</th>
<th style="text-align: left;">Prior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">dem60=~y2</td>
<td style="text-align: right;">latent</td>
<td style="text-align: right;">-16.31</td>
<td style="text-align: left;">[-27.82, -8.57]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">1.106</td>
<td style="text-align: right;">18.00</td>
<td style="text-align: left;">Normal (0 +- 10.00)</td>
</tr>
<tr class="even">
<td style="text-align: left;">dem65=~y6</td>
<td style="text-align: right;">latent</td>
<td style="text-align: right;">-16.31</td>
<td style="text-align: left;">[-27.82, -8.57]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">1.106</td>
<td style="text-align: right;">18.00</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">dem65~dem60</td>
<td style="text-align: right;">regression</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: left;">[ 0.43, 1.34]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">1.028</td>
<td style="text-align: right;">70.00</td>
<td style="text-align: left;">Normal (0 +- 10.00)</td>
</tr>
<tr class="even">
<td style="text-align: left;">y1~~y5</td>
<td style="text-align: right;">residual</td>
<td style="text-align: right;">5.70</td>
<td style="text-align: left;">[ 3.68, 8.14]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">0.990</td>
<td style="text-align: right;">79.00</td>
<td style="text-align: left;">Beta (1 +- 1.00)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">y1~~y1</td>
<td style="text-align: right;">residual</td>
<td style="text-align: right;">7.67</td>
<td style="text-align: left;">[ 5.28, 10.30]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">0.990</td>
<td style="text-align: right;">75.00</td>
<td style="text-align: left;">Gamma (1 +- 0.50)</td>
</tr>
<tr class="even">
<td style="text-align: left;">y2~~y2</td>
<td style="text-align: right;">residual</td>
<td style="text-align: right;">2.98</td>
<td style="text-align: left;">[ 0.00, 9.19]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">12.50%</td>
<td style="text-align: left;">1.044</td>
<td style="text-align: right;">54.00</td>
<td style="text-align: left;">Gamma (1 +- 0.50)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">y5~~y5</td>
<td style="text-align: right;">residual</td>
<td style="text-align: right;">7.52</td>
<td style="text-align: left;">[ 5.44, 9.72]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">0.996</td>
<td style="text-align: right;">101.00</td>
<td style="text-align: left;">Gamma (1 +- 0.50)</td>
</tr>
<tr class="even">
<td style="text-align: left;">y6~~y6</td>
<td style="text-align: right;">residual</td>
<td style="text-align: right;">1.32</td>
<td style="text-align: left;">[ 0.00, 6.15]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">20.83%</td>
<td style="text-align: left;">0.997</td>
<td style="text-align: right;">51.00</td>
<td style="text-align: left;">Gamma (1 +- 0.50)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dem60~~dem60</td>
<td style="text-align: right;">residual</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: left;">[ 0.01, 0.11]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">97.92%</td>
<td style="text-align: left;">1.100</td>
<td style="text-align: right;">35.00</td>
<td style="text-align: left;">Gamma (1 +- 0.50)</td>
</tr>
<tr class="even">
<td style="text-align: left;">dem65~~dem65</td>
<td style="text-align: right;">residual</td>
<td style="text-align: right;">6.67e-03</td>
<td style="text-align: left;">[ 0.00, 0.03]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">100%</td>
<td style="text-align: left;">1.058</td>
<td style="text-align: right;">61.00</td>
<td style="text-align: left;">Gamma (1 +- 0.50)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">y1~1</td>
<td style="text-align: right;">intercept</td>
<td style="text-align: right;">5.49</td>
<td style="text-align: left;">[ 4.79, 6.15]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">0.990</td>
<td style="text-align: right;">58.00</td>
<td style="text-align: left;">Normal (0 +- 32.00)</td>
</tr>
<tr class="even">
<td style="text-align: left;">y2~1</td>
<td style="text-align: right;">intercept</td>
<td style="text-align: right;">4.29</td>
<td style="text-align: left;">[ 3.54, 5.02]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">0.991</td>
<td style="text-align: right;">117.00</td>
<td style="text-align: left;">Normal (0 +- 32.00)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">y5~1</td>
<td style="text-align: right;">intercept</td>
<td style="text-align: right;">5.15</td>
<td style="text-align: left;">[ 4.51, 5.67]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">0.992</td>
<td style="text-align: right;">56.00</td>
<td style="text-align: left;">Normal (0 +- 32.00)</td>
</tr>
<tr class="even">
<td style="text-align: left;">y6~1</td>
<td style="text-align: right;">intercept</td>
<td style="text-align: right;">2.91</td>
<td style="text-align: left;">[ 2.29, 3.63]</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">[-0.10, 0.10]</td>
<td style="text-align: right;">0%</td>
<td style="text-align: left;">0.995</td>
<td style="text-align: right;">169.00</td>
<td style="text-align: left;">Normal (0 +- 32.00)</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-03-31 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
``` r
parameters::model_parameters(bfit, priors = TRUE) %>% print_md()
```

<table>
<caption>Latent</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Median</th>
<th style="text-align: center;">89% CI</th>
<th style="text-align: center;">pd</th>
<th style="text-align: center;">% in ROPE</th>
<th style="text-align: center;">Rhat</th>
<th style="text-align: center;">ESS</th>
<th style="text-align: center;">Prior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">dem60=~y2</td>
<td style="text-align: center;">1.73</td>
<td style="text-align: center;">(1.29, 2.39)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">1.099</td>
<td style="text-align: center;">39.00</td>
<td style="text-align: center;">Normal (0 +- 10)</td>
</tr>
<tr class="even">
<td style="text-align: left;">dem65=~y6</td>
<td style="text-align: center;">1.73</td>
<td style="text-align: center;">(1.29, 2.39)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">1.099</td>
<td style="text-align: center;">39.00</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>

<table>
<caption>Regression</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Median</th>
<th style="text-align: center;">89% CI</th>
<th style="text-align: center;">pd</th>
<th style="text-align: center;">% in ROPE</th>
<th style="text-align: center;">Rhat</th>
<th style="text-align: center;">ESS</th>
<th style="text-align: center;">Prior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">dem65~dem60</td>
<td style="text-align: center;">0.89</td>
<td style="text-align: center;">(0.77, 1.05)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">0.991</td>
<td style="text-align: center;">93.00</td>
<td style="text-align: center;">Normal (0 +- 10)</td>
</tr>
</tbody>
</table>

<table>
<caption>Residual</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Median</th>
<th style="text-align: center;">89% CI</th>
<th style="text-align: center;">pd</th>
<th style="text-align: center;">% in ROPE</th>
<th style="text-align: center;">Rhat</th>
<th style="text-align: center;">ESS</th>
<th style="text-align: center;">Prior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">y1~~y5</td>
<td style="text-align: center;">1.69</td>
<td style="text-align: center;">(0.87, 2.79)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">2.00%</td>
<td style="text-align: center;">1.002</td>
<td style="text-align: center;">44.00</td>
<td style="text-align: center;">Beta (1 +- 1.00)</td>
</tr>
<tr class="even">
<td style="text-align: left;">y1~~y1</td>
<td style="text-align: center;">3.16</td>
<td style="text-align: center;">(2.13, 4.48)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">0.990</td>
<td style="text-align: center;">78.00</td>
<td style="text-align: center;">Gamma (1 +- 0.50)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">y2~~y2</td>
<td style="text-align: center;">5.65</td>
<td style="text-align: center;">(3.22, 7.81)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">1.029</td>
<td style="text-align: center;">61.00</td>
<td style="text-align: center;">Gamma (1 +- 0.50)</td>
</tr>
<tr class="even">
<td style="text-align: left;">y5~~y5</td>
<td style="text-align: center;">3.87</td>
<td style="text-align: center;">(3.04, 5.44)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">1.017</td>
<td style="text-align: center;">61.00</td>
<td style="text-align: center;">Gamma (1 +- 0.50)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">y6~~y6</td>
<td style="text-align: center;">2.59</td>
<td style="text-align: center;">(0.95, 4.75)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">4.00%</td>
<td style="text-align: center;">1.040</td>
<td style="text-align: center;">30.00</td>
<td style="text-align: center;">Gamma (1 +- 0.50)</td>
</tr>
<tr class="even">
<td style="text-align: left;">dem60~~dem60</td>
<td style="text-align: center;">3.79</td>
<td style="text-align: center;">(1.48, 5.36)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">1.029</td>
<td style="text-align: center;">62.00</td>
<td style="text-align: center;">Gamma (1 +- 0.50)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dem65~~dem65</td>
<td style="text-align: center;">0.04</td>
<td style="text-align: center;">(4.70e-04, 0.32)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">68.00%</td>
<td style="text-align: center;">0.996</td>
<td style="text-align: center;">20.00</td>
<td style="text-align: center;">Gamma (1 +- 0.50)</td>
</tr>
</tbody>
</table>

<table>
<caption>Intercept</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Median</th>
<th style="text-align: center;">89% CI</th>
<th style="text-align: center;">pd</th>
<th style="text-align: center;">% in ROPE</th>
<th style="text-align: center;">Rhat</th>
<th style="text-align: center;">ESS</th>
<th style="text-align: center;">Prior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">y1~1</td>
<td style="text-align: center;">5.48</td>
<td style="text-align: center;">(5.10, 6.04)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">1.015</td>
<td style="text-align: center;">29.00</td>
<td style="text-align: center;">Normal (0 +- 32)</td>
</tr>
<tr class="even">
<td style="text-align: left;">y2~1</td>
<td style="text-align: center;">4.23</td>
<td style="text-align: center;">(3.51, 4.92)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">0.991</td>
<td style="text-align: center;">38.00</td>
<td style="text-align: center;">Normal (0 +- 32)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">y5~1</td>
<td style="text-align: center;">5.14</td>
<td style="text-align: center;">(4.61, 5.56)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">1.020</td>
<td style="text-align: center;">37.00</td>
<td style="text-align: center;">Normal (0 +- 32)</td>
</tr>
<tr class="even">
<td style="text-align: left;">y6~1</td>
<td style="text-align: center;">2.95</td>
<td style="text-align: center;">(2.43, 3.63)</td>
<td style="text-align: center;">100%</td>
<td style="text-align: center;">0%</td>
<td style="text-align: center;">1.027</td>
<td style="text-align: center;">27.00</td>
<td style="text-align: center;">Normal (0 +- 32)</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-03-31 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
