### ISSUE TITLE
CRAN 0.9

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#410]
Dear maintainer,

package bayestestR_0.9.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/bayestestR_0.9.0_20210406_142628/Windows/00check.log>
Status: 3 ERRORs, 2 WARNINGs, 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/bayestestR_0.9.0_20210406_142628/Debian/00check.log>
Status: 2 ERRORs, 1 WARNING, 3 NOTEs

**Comment by strengejacke** [comment]
1. All tests in _test-rope.R_ and _test-rope_range.R_ involving _brms_ are failing:

> Error: D:/Compiler/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file81149352f3d.o:file81149352f3d.cpp:

I suggest skipping them on CRAN.


2. Vignette fails:

> SUMMARY: processing the following file failed:  'indicesEstimationComparison.Rmd'

Not sure why, maybe disable on CRAN?

3. RD errors

> * checking PDF version of manual ... WARNING
> LaTeX errors when creating PDF version.
> This typically indicates Rd problems.
> LaTeX errors found:
> ! LaTeX Error: There's no line here to end.

Here, you need to create the PDF manually and scan the log-file to find the error in the latex-docs.

4. Remove LazyData from DESCRIPTION

> Check: LazyData, Result: NOTE
>    'LazyData' is specified without a 'data' directory

If _bayestestR_ has no data directory, remove the LazaData field from the DESCRIPTION

5. Invalid tex-file:

> ‘bayestestR-manual.tex’

Remove that file from your directory and/or add it to RBuildIgnore.

**Comment by strengejacke** [comment]
ok, using "possibly fix" as commit message also closes the issue apparently. ^^
But I think all issues should be resolved. I'll submit to winbuilder.

**Comment by DominiqueMakowski** [comment]
Thanks a lot Daniel, trying one last thing for the vignette

**Comment by DominiqueMakowski** [comment]
```
pandoc.exe: Unknown extension: gfm_auto_identifiers
Error: processing vignette 'indicesEstimationComparison.Rmd' failed with diagnostics:
pandoc document conversion failed with error 7
--- failed re-building 'indicesEstimationComparison.Rmd'
```
How can we skip a vignette on CRAN?

**Comment by strengejacke** [comment]
Maybe via `.Rbuildignore`?

**Comment by DominiqueMakowski** [comment]
@IndrajeetPatil https://twitter.com/patilindrajeets/status/1379769964752687119?s=20

**Comment by IndrajeetPatil** [comment]
Yeah, I don't think we should be including `brms` examples anywhere `R CMD CHECK` might encounter them. They are rather unstable and making the submission process unnecessarily complicated. We test all these things on CI platforms anyway. 

Better to skip relevant tests and move the vignette containing these examples to web-only.

**Comment by strengejacke** [comment]
Will those vignettes in `web_only` be excluded from the built source package, or are they ignored on CRAN?

**Comment by IndrajeetPatil** [comment]
As far as I understand, they are excluded from the built source package.

For example, in `ggstatsplot`, I've over 10 vignettes, but on CRAN there is just 1 visible:

<img width="268" alt="Screenshot 2021-04-07 at 16 57 51" src="https://user-images.githubusercontent.com/11330453/113888252-75c18b00-97c2-11eb-81d9-e27a1489c93f.png">

**Comment by strengejacke** [comment]
I just looked at the source package. All rmd-files are shipped with the package (including the `web_only` folder), but only those files directly in the `vignettes` folder are built (into `/inst/docs`).

**Comment by IndrajeetPatil** [comment]
Oh, I see. Makes sense I guess. I am not specifying to exclude that folder in `.Rbuildignore`. 

But this will still work for us as a solution, no?

**Comment by strengejacke** [comment]
Yes, I think so.

**Comment by DominiqueMakowski** [comment]
I submitted to CRAN and the error disappeared

**Comment by DominiqueMakowski** [comment]
On its way to CRAN
