### ISSUE TITLE
Digits of print command doesn't extend to CI intervals

### ISSUE THREAD

**Issue by nahorp** [easystats/bayestestR#415]
Hello (again!),

I used the `print` command with `digits = 5` argument on the output of `describe_posterior`, but it only applies this to the centrality measure and not the CIs. Is there a way to get this for the CIs too? I can't recall explicitly but am relatively certain I had this in a previous version (or, more precisely, at some point in the past)...

![Screen Shot 2021-04-15 at 2 33 15 pm](https://user-images.githubusercontent.com/43395036/114814659-f94d2e80-9df7-11eb-98c4-677555ebd3bc.png)

**Comment by strengejacke** [comment]
The `ci_digits` should work for CI.

**Comment by nahorp** [comment]
@strengejacke works like a charm, thank you! :)
