### ISSUE TITLE
CRAN release - fails building

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#425]
I have a problem,

I cannot run the code here:

https://github.com/easystats/bayestestR/blob/5cb67fac40fa561b34e444cf7fc6c0c1aaf55d3a/vignettes/bayes_factors.Rmd#L525-L528

because it apparently requires the rstan backend:

```
 Error: Backend 'rstan' is required for this method. 
11.
stop(..., call. = FALSE) 
10.
stop2("Backend '", backend, "' is required for this method.") 
9.
require_backend("rstan", samples) 
8.
bridge_sampler.brmsfit(x, silent = TRUE) 
7.
bridgesampling::bridge_sampler(x, silent = TRUE) at bayesfactor_models.R#254
6.
FUN(X[[i]], ...) 
5.
lapply(mods, function(x) {
    bridgesampling::bridge_sampler(x, silent = TRUE)
}) at bayesfactor_models.R#253
4.
.bayesfactor_models_stan_REG(mods, denominator, verbose) at bayesfactor_models.R#221
3.
.bayesfactor_models_stan(mods, denominator = denominator, verbose = verbose) at bayesfactor_models.R#329
2.
bayesfactor_models.brmsfit(m1, m2, m3, m4, denominator = m0) at bayesfactor_models.R#147
1.
bayesfactor_models(m1, m2, m3, m4, denominator = m0) 

```

Which I didn't manage to get to run on my machine (and trust me, I tried a long time 😅) - hence switching for `cmdstan`.

But this prevents me from building the package -_-

So either someone would have to build the pkg for me and sent it over by email so that I can submit 😁, or I don't eval this chunk for CRAN vignettes... @mattansb what do you think?

**Comment by mattansb** [comment]
I am also having trouble building the package.... But my problem is that my antivirus is blocking `brms` when not in interactive mode :/ 
@strengejacke Care to give this a go?

**Comment by mattansb** [comment]
I'm also having issues with `rstan`... Let me try something else first...

**Comment by mattansb** [comment]
@DominiqueMakowski You should be able to build now (:

**Comment by DominiqueMakowski** [comment]
noice!

**Comment by DominiqueMakowski** [comment]
works :)
