### ISSUE TITLE
ci()

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#43]
We already have a `ci()` method currently defined in parameters. However, parameters does depend on bayestestR. Thus, we can try defining the method in bayestestR and expanding it to frequentist models in parameters. We just have to find a way to put the links of the online documentation of each method in the docstring of bayestestR's definition.

**Comment by DominiqueMakowski** [comment]
Regarding the proposal of adjusting the CI type based on the type of model (i.e., quantile for glms (binomial?) and hdi for others), I have the feeling it might be a bit weird to do it under the hood. Maybe a better solution would be to stick with HDI as a default, but warn the users in the documentation that if they plan to do some transformation to the response scale, they might want to use the "quantile" method, otherwise, it might lead to inconsistent results.

**Comment by strengejacke** [comment]
Maybe we can implement `ci()` in bayestestR with quantiles in general, and in parameters you can add an option `method`? But I agree, we shouldn't do some black box transforming that is not clear to the user.
