### ISSUE TITLE
describe_posterior not producing BF values for BayesFactor object

### ISSUE THREAD

**Issue by georgekinnear** [easystats/bayestestR#442]
**Describe the bug**
Since updating to v0.10.0 it seems that the BF value is not returned for BayesFactor objects, while it was under previous versions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the old version of bayestestR:
`devtools::install_version("bayestestR", version = "0.8.2", repos = "http://cran.us.r-project.org")`
2. Run the following code:
```
bf <- BayesFactor::correlationBF(c(1:10), rep(c(1:5), 2), rscale = "ultrawide")
x <- bayestestR::describe_posterior(bf)
x$BF
```
This produces the output
`[1] 0.9799116`

3. Install the latest version of bayestestR.
`install.packages("bayestestR")`
4. Re-run the code above -- `x$BF` is now NULL.

**Expected behaviour**
The BF should be returned by describe_posterior, as in the old version.

**Specifiations (please complete the following information):**
 - Package Version 0.10.0 (compared with 0.8.2)

**Comment by mattansb** [comment]
Two things going on.

1.  There was a bug.
2.  The `BF` column is now `log_BF`

Working with the fixed version:

``` r
bf <- BayesFactor::correlationBF(c(1:10), rep(c(1:5), 2), rscale = "ultrawide")
x <- bayestestR::describe_posterior(bf)
exp(x$log_BF)
#> [1] 0.9799116
```

<sup>Created on 2021-07-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by georgekinnear** [comment]
That's great, thanks for the speedy fix (and the great package)!
