### ISSUE TITLE
how to specify ROPE for multivariate models

### ISSUE THREAD

**Issue by LindaWvanR** [easystats/bayestestR#446]
First of all, this is a great package, thank you!

I have one question. In the case of multiple dependent variables, you describe the following:

_range: ROPE’s lower and higher bounds. Should be "default" or depending on the
number of outcome variables a vector or a list. In models with one response,
‘range‘ should be a vector of length two (e.g., c(-0.1,0.1)). In multivariate
models, ‘range‘ should be a list with a numeric vectors for each response variable. Vector names should correspond to the name of the response variables. If "default" and input is a vector, the range is set to c(-0.1,0.1). If "default"
and input is a Bayesian model, rope_range() is used._

My question is if you could give me an example of how to create this list and how to put it in the script. I have made many attempts, but it doesn't work.  The error messages work fine, but I don't understand what I should do.

Thanks for your help!
Linda

**Comment by bwiernik** [comment]
If your model has one response variable (most models), then use: `c(lower, upper)`. For example `c(-.5, 1.0)`

**Comment by LindaWvanR** [comment]
Thank you, Brenton, for your reply. My brms model has two response variables. I am not sure how to adapt the range to make it possible to call for ROPE.

**Comment by bwiernik** [comment]
In that case, it should be something like:

```r
range = list(performance = c(-.5, 1), satisfaction = c(-10, 2), knowledge = c(-.1, .1))
```

**Comment by LindaWvanR** [comment]
Hi Brenton, thanks again for your reply. When I apply the above, in

rope(model, range = list(DV1=c(-.1, .1), DV2=c(-.5, .1)), ci=.89, ci_method = "HDI", effects = "all", component = "all", verbose = TRUE)
I get the following error:

Error in rope.brmsfit(model, range = list(DV1 = c(-.1, .1), DV2 = c(-.5,  : 
  With a multivariate model, `range` should be 'default' or a list of named numeric vectors with length 2.

Could you help me understand what is going wrong here?
Thank you!

**Comment by bwiernik** [comment]
Ah, there is a bug in the checks in this function. Will fix.

**Comment by bwiernik** [comment]
Ah, there is a bug in the checks in this function. Will fix.

**Comment by LindaWvanR** [comment]
Thank you! I am glad you found the problem.
