### ISSUE TITLE
Support `rvar` objects (and `draws`)

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#460]
https://mc-stan.org/posterior/articles/posterior.html
https://mc-stan.org/posterior/articles/rvar.html
https://mc-stan.org/posterior/reference/rvar.html

**Comment by strengejacke** [comment]
Just saw this 🤣 
But closed in https://github.com/easystats/bayestestR/pull/518, PR was opened w/o recognizing this issue...
