### ISSUE TITLE
emmeans Input into describe_posterior

### ISSUE THREAD

**Issue by awaldman123** [easystats/bayestestR#462]
My apologies for the additional question. I'm progressing with understanding the analysis paradigm and am trying to integrate the output of the emmeans contrast function with describe_posterior in the following way:

```R
data("bioChemists", package = "pscl")

m <- brm(formula = bf(art ~ mar,
zi ~ mar),
data = bioChemists,
family = zero_inflated_poisson())

expected<-emmeans(m, ~ mar, epred = TRUE)

contrasts<-contrast(expected,"pairwise")

describe_posterior(contrast,test=c("all"))
```
However, the last function returned the following warning:

```
Warning message:
In .clean_priors_and_posteriors.emmGrid(posteriors, bf_prior) :
  Prior not specified! Please provide the original model to get meaningful results.
```
When I added the model to the call, I got the following error:

```
Sampling priors, please wait...
Error: Cannot sample from flat priors (such as the default priors for fixed-effects in a 'brmsfit' model).
```

Since It looks like the other tests can be tabulated, I just wanted to confirm that the issue was that Bayes Factors cannot be tabulated when using the default priors set by brms? 

As an aside, with the equivalence test, it seems that undecided is a common outcome and I'm wondering if there is any consensus on making the threshold for accept and reject more stringent to avoid undecided as a result or whether I use another parameter like pd instead if I'm looking for a more concrete accept/reject answer? I think I'm having a hard time wrapping my head around "undecided" as an answer.

As always, thank you so much for your help as I continue to learn and read more about Bayesian analysis.

**Comment by mattansb** [comment]
@awaldman123 As the warning states, prior draws cannot be sampled from a model with flat priors.

As for the Q about equivalence tests, it was answered in #464
