### ISSUE TITLE
describe_posterior input scale

### ISSUE THREAD

**Issue by delucalab** [easystats/bayestestR#463]
I am performing a bayesian logistic regression of the bernoulli family and want to identify significant contrasts. I feed my brms output into emmeans before using the describe_posterior function. However, I get different results from describe_posterior depending on whether I use type="response" or not in my emmeans call. Therefore, I wanted to know whether the input to describe_posterior should be the contrasts I tabulated from emmeans on the log odds ratio scale or response scale?

**Comment by bwiernik** [comment]
They should be on the log odds scale

**Comment by mattansb** [comment]
(They *can* be either, but you would have to adjust your interpretation and ROPE accordingly.)

**Comment by bwiernik** [comment]
My suggestion regarding log odds has to do with how emmeans works (at least in my understanding). emmeans relies on a general method for computing linear contrasts using the variance covariance matrix. That method is valid for linear models (like the model on the log odds scale). It’s not valid for models that are nonlinear, such as the exponentiated form of the model.

**Comment by mattansb** [comment]
emmeans gets the linear estiamtes, but it can then transform those using the delta method and and contrast them... So it realy depends what level and what type of analysis you want to do.

``` r
m <- rstanarm::stan_glm(am ~ factor(cyl), data = mtcars,
                        family = binomial(), refresh = 0)

(Elogodds <- emmeans::emmeans(m, ~ cyl))
#>  cyl emmean lower.HPD upper.HPD
#>    4  0.999    -0.328     2.513
#>    6 -0.288    -1.984     1.162
#>    8 -1.872    -3.641    -0.453
#> 
#> Point estimate displayed: median 
#> Results are given on the logit (not the response) scale. 
#> HPD interval probability: 0.95

# logOR diffs
emmeans::contrast(Elogodds, method = "pairwise")
#>  contrast estimate lower.HPD upper.HPD
#>  4 - 6        1.32    -0.749      3.49
#>  4 - 8        2.90     1.058      5.27
#>  6 - 8        1.59    -0.487      4.00
#> 
#> Point estimate displayed: median 
#> Results are given on the log odds ratio (not the response) scale. 
#> HPD interval probability: 0.95



# prob diffs
(Eprobs <- emmeans::regrid(Elogodds, transform = "response"))
#>  cyl  prob lower.HPD upper.HPD
#>    4 0.731   0.46191     0.947
#>    6 0.428   0.11328     0.750
#>    8 0.133   0.00986     0.328
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95
emmeans::contrast(Eprobs, method = "pairwise")
#>  contrast estimate lower.HPD upper.HPD
#>  4 - 6       0.290   -0.1147     0.716
#>  4 - 8       0.580    0.2665     0.859
#>  6 - 8       0.281   -0.0873     0.651
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95



# log prob diffs
(Elogprobs <- emmeans::regrid(Eprobs, transform = "log"))
#>  cyl   prob lower.HPD upper.HPD
#>    4 -0.313     -0.76   -0.0439
#>    6 -0.848     -1.89   -0.1941
#>    8 -2.015     -3.52   -0.8429
#> 
#> Point estimate displayed: median 
#> Results are given on the log (not the response) scale. 
#> HPD interval probability: 0.95
emmeans::contrast(Elogprobs, method = "pairwise")
#>  contrast estimate lower.HPD upper.HPD
#>  4 - 6       0.517    -0.324      1.68
#>  4 - 8       1.654     0.546      3.40
#>  6 - 8       1.120    -0.498      2.91
#> 
#> Point estimate displayed: median 
#> Results are given on the log (not the response) scale. 
#> HPD interval probability: 0.95
```

<sup>Created on 2021-09-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

See also this blog post:
https://shouldbewriting.netlify.app/posts/2020-04-13-estimating-and-testing-glms-with-emmeans/

**Comment by mattansb** [comment]
Sorry, the delta method is not used for Bayesian models since the posteriors themselves can just be transformed (:

Also in the context of Bayesian models, emmeans can be used for nonlinear models in an very extended way (see recent update to {brms}).
