### ISSUE TITLE
ROPE Range Issues

### ISSUE THREAD

**Issue by awaldman123** [easystats/bayestestR#464]
My apologies for the double post. I have run into a couple of issues with ROPE calculations using describe_posterior:

**_Example 1_**:

When I use the describe_posterior function on an emmeans object, the ROPE range is always -0.1 to 0.1. However, if I call the describe_posterior function on the model object, a different rope range is tabulated. 

I'll attach a reproducible example here:

[Example.csv](https://github.com/easystats/bayestestR/files/7148359/Example.csv)

install.packages("brms")
library(brms)
install.packages("emmeans")
library(emmeans)

example<-read.csv("Example.csv",header=T)
as.factor(example$ID)->example$ID
as.factor(example$Region)->example$Region
as.factor(example$Lesion)->example$Lesion

example_model<-brm(formula=Lesion ~ Region + Age + (1 | ID), data=example, family="bernoulli",warmup=2000,iter=4000,seed=34)

describe_posterior(example_model)

Summary of Posterior Distribution 

Parameter   | Median |         95% CI |     pd |          ROPE | % in ROPE |  Rhat |      ESS
---------------------------------------------------------------------------------------------
(Intercept) |   9.56 | [ 6.20, 13.11] |   100% | [-0.18, 0.18] |        0% | 1.000 |  4103.00
Region1     |  -0.73 | [-1.52,  0.06] | 96.67% | [-0.18, 0.18] |     6.60% | 1.000 | 10642.00
Region2     |  -1.39 | [-2.18, -0.56] | 99.95% | [-0.18, 0.18] |        0% | 1.000 |  8098.00
Age         |  -0.13 | [-0.19, -0.08] |   100% | [-0.18, 0.18] |    98.34% | 1.000 |  4218.00

example_emmeans<- emmeans(example_model, ~ Region, re_formula=NULL)

describe_posterior(example_emmeans)

Summary of Posterior Distribution

Parameter | Median |        95% CI |     pd |          ROPE | % in ROPE
-----------------------------------------------------------------------
0         |   1.29 | [ 0.67, 1.94] |   100% | [-0.10, 0.10] |        0%
1         |   0.56 | [ 0.02, 1.12] | 97.79% | [-0.10, 0.10] |     2.60%
2         |  -0.10 | [-0.64, 0.44] | 63.51% | [-0.10, 0.10] |    27.38%

contrasts_example<- contrast(example_emmeans, "pairwise")

describe_posterior(contrasts_example)

Parameter | Median |        95% CI |     pd |          ROPE | % in ROPE
-----------------------------------------------------------------------
0 - 1     |   0.73 | [-0.06, 1.52] | 96.67% | [-0.10, 0.10] |     3.70%
0 - 2     |   1.39 | [ 0.56, 2.18] | 99.95% | [-0.10, 0.10] |        0%
1 - 2     |   0.65 | [-0.06, 1.43] | 95.66% | [-0.10, 0.10] |     4.76%

**_Example 2_**:

When I use describe_posterior on a zero-inflated model, I get a warning that a good ROPE range could not be estimated.

install.packages("brms")
library(brms)
install.packages("emmeans")
library(emmeans)

data("bioChemists", package = "pscl")

m <- brm(formula = bf(art ~ fem,
zi ~ fem),
data = bioChemists,
family = zero_inflated_poisson())

describe_posterior(m)

Summary of Posterior Distribution 

Parameter   | Median |         95% CI |     pd |          ROPE | % in ROPE |  Rhat |     ESS
--------------------------------------------------------------------------------------------
(Intercept) |   0.85 | [ 0.78,  0.93] |   100% | [-0.10, 0.10] |        0% | 1.000 | 4118.00
femWomen    |  -0.24 | [-0.36, -0.12] | 99.98% | [-0.10, 0.10] |        0% | 0.999 | 2997.00
Warning message:
Could not estimate a good default ROPE range. Using 'c(-0.1, 0.1)'.

As always, thanks for your help with understanding where I may be going wrong here.

**Comment by bwiernik** [comment]
If you look at the documentation for the rope functions, the default is +/- .1 times the SD of the response variable (corresponding to a Cohen's d value of .1 per 1 unit change in X)

**Comment by delucalab** [comment]
Thanks I did see that but was still confused as to why in example 1 the ROPE range changes dependent on when I call describe_posterior and why in example 2 the default ROPE range couldn't be calculated?

**Comment by awaldman123** [comment]
Thanks I did see that but was still confused as to why in example 1 the ROPE range changes dependent on when I call describe_posterior and why in example 2 the default ROPE range couldn't be calculated?

**Comment by awaldman123** [comment]
My apologies but I'm not sure why this was closed. Forgive me if I'm just not understanding but the documentation didn't seem to help me rationalize why in example 1 the ROPE range changes dependent on when I call describe_posterior (before or after emmeans) and why in example 2 the default ROPE range couldn't be calculated?
