### ISSUE TITLE
error in describe_posterior

### ISSUE THREAD

**Issue by idoba2030** [easystats/bayestestR#465]
Hey all,
It's my first post here so thanks for the great package.
My problem is I am trying to run describe_posterior function and am unable to run it on a model having more than one predictor.
It does run smoothly when I am using it on a model with only one predictor.

I am getting the following error message:
```
describe_posterior(Bayes_Model_Binary2)
Error in `[.data.frame`(as.data.frame(model, optional = FALSE), , valid_parameters,  : 
  undefined columns selected
```
Thanks for the help,

**Comment by bwiernik** [comment]
Can you give a reproducible example ?

**Comment by idoba2030** [comment]
I tried to add the brmsfit object as a zip file but wasn't able to. The error was "is not included in the list". Therefore, I am adding only a sample code of what's relevant. The model itself runs OK with other summary or plotting functions.

`library(bayestestR)

load('myfolder/02_models/model_rw_ss.Rdata')

describe_posterior(Bayes_Model_Binary)`

**Comment by mattansb** [comment]
@idoba2030 We can't reproduce this error.
Please provide a reproducible example and your session info.

**Comment by bwiernik** [comment]
A reproducible example means a set of R commands that produce the error. You can fit any model with any dataset (one that we can access either because it’s included in R or we can download it using the script) so long as it produces the error.

**Comment by strengejacke** [comment]
I can't reproduce your issue. Are your packages up to date?

**Comment by idoba2030** [comment]
Yes I updated the packages and it is working now, thank you :)

**Comment by IndrajeetPatil** [comment]
https://yihui.org/en/2017/05/when-in-doubt-upgrade/
