### ISSUE TITLE
The dataset datasets::sleep should be analysed as a one-sample dataset

### ISSUE THREAD

**Issue by jhmaindonald** [easystats/bayestestR#466]
This issue arises in connecton witht the vignette bayestestR::bayes_factors (I've not checked other vignettes).   The data in the dataset datasets::sleep is from 10 matched pairs, with ID referring to the individual, and group (confusingly) to the drug.  The model should be specified as:
```
set.seed(123)
library(rstanarm)

model <- stan_glm(
    formula = extra[group==1]-extra[group==2] ~ 1,
    data = sleep,
    prior = normal(0, 3, autoscale = FALSE)
)
```
Then one gets:
```
My_first_BF <- bayestestR::bayesfactor_parameters(model, null = c(-1,1))
My_first_BF
## Bayes Factor (Null-Interval) 

## Parameter   |   BF
------------------
## (Intercept) | 2.84

## * Evidence Against The Null: [-1.000, 1.000]
```

The difference is even greater for a 0 point NULL.  I get a Bayes factor that equals 14.86

**Comment by mattansb** [comment]
True - the current example doesn't account for possible dependency in the data.
However, this is just a simple example used for illustrative purposes.... 
(Also I can argue that I have a prior that the random effects are 0 😋)

Feel free to make pull request with this correction if you think it's worth the effort 💪

**Comment by jhmaindonald** [comment]
The Pearson correlation is 0.8.
John.

**Comment by bwiernik** [comment]
In my experience, R users rarely do simple dependent sample t tests like this. If this example is kept and changed to account for dependency, I would suggest specifying it as a fixed effects model with the person id as a factor covariate. Otherwise another dataset for two-group comparison would be better.

**Comment by mattansb** [comment]
I don't see how making the analysis in this example more "accurate" would benefit any potential readers\*.
That section of the vignette is about univariate Bayes factors, not about mixed models, or dependencies or the assumptions of iid. Such information is irrelevant to the point of the exercise...

<sub>(*) Or myself, who would have to edit and re-write the example.</sub>

Does the "incorrectness" of the model specification somehow take away from how a variety of hypothesis tests on a single parameter can be done which Bayes factors? 
IMO no...

**Comment by mattansb** [comment]
![image](https://user-images.githubusercontent.com/35330040/135440252-0d36c0ef-ae5a-4673-96b8-c87395c484d9.png)
