### ISSUE TITLE
update on cran before 30/10

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#469]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_bayestestR.html>.

Please correct before 2021-10-19 to safely retain your package on CRAN.

<sub>*which is also the date of my birthday*</sub>

**Comment by strengejacke** [comment]
> <sup><em>which is also the date of my birthday</em></sup>

🥳

**Comment by bwiernik** [comment]
Ain't no party like a CRAN deadline party.

**Comment by strengejacke** [comment]
@mattansb @DominiqueMakowski There a few tests failing on CRAN (https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/bayestestR-00check.html), but some more here on GitHub. Are you able to fix these in time?

**Comment by mattansb** [comment]
I have a PR (#474) that I will *not* merge yet, as it introduces some more complications.

I don't know what the CRAN errors are about - looks like Dom's domain.

As for the error on the `main` branch - do you know where the error is happening? I can't figure it out from the log at https://github.com/easystats/bayestestR/runs/3895314216?check_suite_focus=true

**Comment by strengejacke** [comment]
Looks like some recent changes in _insight_ that cause problems in _bayestestR_ need to be fixed...

**Comment by strengejacke** [comment]
@mattansb I'm not sure, there seem to be some issues with `unupdate()`: https://github.com/easystats/bayestestR/runs/3913495285#step:10:1014

**Comment by mattansb** [comment]
Weird... Seems like `cmdstanr` needs to be added to Suggests 🤷

**Comment by mattansb** [comment]
The current errors seem to have something to do with BRMS? Taking too long? I'm not quite sure how to read the logs...

**Comment by strengejacke** [comment]
```
══ Failed tests ════════════════════════════════════════════════════════════════
── Error (test-bayesfactor_parameters.R:85:7): bayesfactor_parameters BRMS ─────
Error: Error in `unupdate.brmsfit(brms_mixed_6)`: Error : Please install the 'cmdstanr' package.

Backtrace:
    █
 1. ├─bayestestR::unupdate(brms_mixed_6) test-bayesfactor_parameters.R:85:6
 2. └─bayestestR:::unupdate.brmsfit(brms_mixed_6)
── Failure (test-check_prior.R:36:3): (code run outside of `test_that()`) ──────
check_prior(model2)$Prior_Quality (`actual`) not equal to c(...) (`expected`).

    actual          | expected           
[1] "uninformative" | "uninformative" [1]
[2] "informative"   - "uninformative" [2]
[3] "informative"   | "informative"   [3]
[4] "uninformative" | "uninformative" [4]
[5] "uninformative" | "uninformative" [5]
── Failure (test-check_prior.R:44:3): (code run outside of `test_that()`) ──────
check_prior(model2, method = "lakeland")$Prior_Quality (`actual`) not equal to c(...) (`expected`).

    actual           | expected         
[1] "informative"    | "informative" [1]
[2] "misinformative" - "informative" [2]
[3] "informative"    | "informative" [3]
[4] "informative"    | "informative" [4]
[5] "informative"    | "informative" [5]
── Failure (test-describe_posterior.R:265:7): (code run outside of `test_that()`) ──
describe_posterior(ttestBF(mtcars$wt, mu = 3), ci = 0.95) (`actual`) not equal to structure(...) (`expected`).

actual vs expected
                  CI_high
- actual[1, ]   0.1557581
+ expected[1, ] 0.1792614

  `actual[[5]]`: 0.16
`expected[[5]]`: 0.18

[ FAIL 4 | WARN 23 | SKIP 3 | PASS 317 ]
Error: Error: Test failures
```

**Comment by mattansb** [comment]
That `cmdstanr` error is very weird... What that model `insight::download_model("brms_mixed_6")` fit with `cmdstanr`???

Anyway, you can comment that chunk out for now (sorry, I don't have time to get to this.......)

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/VvnwB1Cyt7MJ
https://win-builder.r-project.org/vNdFyScOlN9
https://win-builder.r-project.org/yelYQqydBFDO

**Comment by strengejacke** [comment]
https://easystats.github.io/parameters/reference/ci.merMod.html is now https://easystats.github.io/parameters/reference/ci.default.html

The two failing tests are probably cmdstanr issues? I suggest skipping those on CRSN.

**Comment by strengejacke** [comment]
Oh, and you need to remove the remotes field from the description file :-)

**Comment by strengejacke** [comment]
> Thanks, we see:
> 
> ```
>  URL: https://easystats.github.io/parameters/reference/ci.merMod.html
>    From: man/ci.Rd
>    Status: 404
>    Message: Not Found
> ```
> 
> Please fix and resubmit.

See my comment (https://github.com/easystats/bayestestR/issues/469#issuecomment-945361772) above:
https://easystats.github.io/parameters/reference/ci.merMod.html is now https://easystats.github.io/parameters/reference/ci.default.html

**Comment by DominiqueMakowski** [comment]
> See my comment 

Oops, sorry I am now an old man my memory and attention span are gone ^^

**Comment by IndrajeetPatil** [comment]
I am guessing the archival deadline was extended to 2021-11-02?

**Comment by DominiqueMakowski** [comment]
til the 31/10, but i submitted yesterday and I am now waiting for a reply about some dead links false positives

**Comment by DominiqueMakowski** [comment]
On its way to cran

![](https://media2.giphy.com/media/NWoJQ8peVE78A/giphy.gif)

**Comment by strengejacke** [comment]
Interestingly, _see_ does not yet fail on CRAN: https://cran.r-project.org/web/checks/check_results_see.html

Not sure if we will expect something else the next days?

**Comment by DominiqueMakowski** [comment]
I don't think there will be more breaking changes related to Vizrecipes as what led to breaks was the iterative moving of the function definition and related changes, but now that's stabilized so it should be okay. I don't know why but today I feel like the new dawn of a stable easytats has started 🌄

**Comment by strengejacke** [comment]
> I don't think there will be more breaking changes related to Vizrecipes

No no, I was referring to the CRAN issue from revdep checks (breaking _see_), but still, as of today, CRAN checks for _see_ are all ok. So the revdep-issue _could_ have been a false positive.

**Comment by IndrajeetPatil** [comment]
Maybe we can submit `{modelbased}` now?

**Comment by DominiqueMakowski** [comment]
should we wait for `see` ?

**Comment by strengejacke** [comment]
Do we need to wait for _see_? And I'm not sure current _see_ works with _parameters_.

**Comment by DominiqueMakowski** [comment]
well then ok i'll submit modelbased asap

**Comment by IndrajeetPatil** [comment]
Any update on the submission? Is it stuck at some stage?

**Comment by DominiqueMakowski** [comment]
stuck at the "didn't submit yet" stage ^^ but will move it to "submit now"

**Comment by strengejacke** [comment]
If you're talking about _modelbased_, are all relevant issues resolved and PRs merged? Is there any hurry, or should we see until all relevant stuff is implemented?

**Comment by DominiqueMakowski** [comment]
I don't think there's a hurry unless @IndrajeetPatil knows something I missed

**Comment by IndrajeetPatil** [comment]
No hurry. I just wanted the ecosystem to remain in sync. 
The last release for all packages was in September/October, _except_ `{modelbased}`.

**Comment by strengejacke** [comment]
I'd say following should at least be addressed before submission:
https://github.com/easystats/modelbased/pull/152/
https://github.com/easystats/modelbased/issues/157
https://github.com/easystats/modelbased/issues/151
https://github.com/easystats/modelbased/issues/142

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/ZOTSh2lnt6DWTekGii/giphy.gif)
