### ISSUE TITLE
Static images missing from Bayes factor vignette

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#476]
@DominiqueMakowski (and maybe @IndrajeetPatil @strengejacke ) do you know where I can recover the static images that were used to be in the [Bayes factor vignette](https://easystats.github.io/bayestestR/articles/bayes_factors.html)?

Eg.:

![image](https://user-images.githubusercontent.com/35330040/137152729-7174f44e-b73e-4feb-a94c-427c41d66d18.png)

**Comment by IndrajeetPatil** [comment]
It's due to a recent change in `{pkgdown}`: https://github.com/r-lib/pkgdown/commit/bb461bae2a1ac47e20f1a64afe0334524907d446

We need to have all external images in `man/figures` folder and then refer to them with a relative path from vignette folder.

So this 

https://github.com/easystats/bayestestR/blob/14f4a616e2c7045256c01242392629c38d01ac4a/vignettes/bayes_factors.Rmd#L132-L134

should instead be

```
knitr::include_graphics("../man/figures/deathsticks.jpg")
```

**Comment by strengejacke** [comment]
How to include the pkg logo in the readme?

**Comment by strengejacke** [comment]
Yeah, I think this should work. I was confused about the error message, but I think that is related to another issue.

**Comment by mattansb** [comment]
Thanks!

**Comment by IndrajeetPatil** [comment]
As I mentioned [here](https://github.com/easystats/bayestestR/commit/7f11b24a89fd8115010c47bb76af1496c7c8989b#commitcomment-57979756), we need to only keep the key figures (i.e., `.png`/`.jpg`/etc.) we are referring to in the `vignettes`/`README`, and delete the rest.

**Comment by IndrajeetPatil** [comment]
The copies are already here: https://github.com/easystats/easystats/tree/master/hextools/bayestestR

>  Our backup will always be the hextools folder in {easystats}, the official shelf to save all things figures.

We will never delete them from here.

**Comment by bwiernik** [comment]
What we do to manage file size in some of my other packages is to exclude some images from the R package build and refer to them in the README via https URLs instead of relative links

**Comment by IndrajeetPatil** [comment]
Remote URL is what we initially had but that was creating problems for the pkgdown workflow, so we decided to make this change. Strange that the relative path is not working.
