### ISSUE TITLE
handle lognormal family in brms for ROPE calculation

### ISSUE THREAD

**Issue by douggetty** [easystats/bayestestR#487]
I needed to compute a ROPE on a brms model today, but the model I ran used `family = lognormal()`. However, the `rope_range` function computes the ROPE interval based on the untransformed response variable. Would it be possible to add the capability to log transform the response when necessary? 

I was able to make my own ROPE interval by computing the SD of the log-transformed response myself, but it took me a while to diagnose the issue so it may save some time to users in the future. Alternately, adding documentation about how to compute the interval by hand in this case could be helpful as well! 

Thanks!

**Comment by bwiernik** [comment]
Can you give a reproducible example of what you mean?

**Comment by douggetty** [comment]
Sure! this is my first attempt at one of these, so please  let me know if there's anything else I need to provide to make it useful.

##################
library(brms)
library(bayestestR)

set.seed(12345)
y <- rlnorm(n = 1000, meanlog = 6, sdlog = .5)
x <- ifelse(y > median(y), 1/2, -1/2 )

df <- data.frame(y = y, x = x)

mod <- brm(y ~ x, data = df,  family = lognormal())

#ROPE calculation not accounting for the log-transformation in the response (default behavior)
per_in_rope <- rope(mod, ci = 0.89)
per_in_rope

#ROPE calculation accounting for the log-transformation
response <- insight::get_response(mod)
sd_y <- sd(log(response))
#define ROPE range from log-transformed sample
range <- c(-0.1 * sd_y, sd_y * 0.1)

per_in_rope_log <- rope(mod, range, ci = 0.89)
per_in_rope_log
##################

The default behavior for the `rope` function, if I understand correctly, is to compute the ROPE based on the untransformed response. But under the hood, brms applies a log-transformation to the response when `family = lognormal()`, which currently needs to be accounted for by the user when computing the ROPE.

**Comment by mattansb** [comment]
The scale of the lognormal distribution is a logarithmic scale, and the un/conditional variance of this scale is dependent on `mu`. This is why `log(sd(Y))` will not give you the correct "variance".

@DominiqueMakowski The current default from `rope_range()` is incorrect in this case - it gives the rope on the response. This is also the case for the Poisson model.

Instead we need to think what size (log) **ratio** of change would be practically equivalent to 0 (ratio, because the coefficients in the model represent the change ratio, not the change difference). 

Arguably, a default could be `log(c(-0.05, 0.05))`, for any log-link, maybe?

**Comment by douggetty** [comment]
I agree that `log(sd(Y))` would be be problematic for the reason you mentioned, but wouldn't the reverse order of `sd(log(Y))` give the correct SD? Since the outcome should be approximately gaussian after the log-transform.

**Comment by mattansb** [comment]
Hang on, what link function are you using?

All of my above comments are assuming a log-link function.

**Comment by bwiernik** [comment]
If the rope is on the log(y) regression coefficient, then .05 standardized coefficient would be

`c(-.05, .05) * sd(log(y))`

or approximately `c(-.05, .05) * sd(y) / mean(y)`

**Comment by bwiernik** [comment]
But not sure that’s the best approach here. 

The lognormal regression coefficients are interpretable as percent increases with x. 

So, say y ~ Lognormal(0, 1). The rope would pick a coefficient of .05 as the bound. But that is a five percent increase in y per unit increase in x — exp(.05) ≈ 1.05. In most cases with a log transformed response, a coefficient of .05 is very large. I might suggest we just fix the default rope for log responses at c(-.01, .01)

**Comment by mattansb** [comment]
Yes, that's what I meant but my math was all messed up 😅

If the link is "identity", I think none of this nonsense is needed, and the rope can be based on ±0.1×sd(y).

**Comment by bwiernik** [comment]
But with log response model, I'm not sure the .1/.05 * sd(log(y)) heuristic makes sense. 

The coefficient in such a model is interpretable as the percent increase. A 5% increase is usually huge! So I think for a model with a log transformed response (not log link), we might just set something like .01 flat as the default rope

**Comment by mattansb** [comment]
brms has a lognormal family, so I don't think that is the case here. Y isn't transformed pre-model fitting.

**Comment by bwiernik** [comment]
It's the same model.

**Comment by mattansb** [comment]
That's true for a lognormal with a log link. However, you can have a lognormal with an identity link, which means the relationship is linear, but the conditional distribution is lognormal.

**Comment by mattansb** [comment]
Actually, also with a log link they're not exactly the same - log(normal) is modeling E[log(x)], while lognormal with log-link is modeling E[x].

**Comment by bwiernik** [comment]
The lognormal family doesn't have a log link, only identity or inverse. 

```

.family_lognormal <- function() {
  list(
    links = c("identity", "inverse"),
    dpars = c("mu", "sigma"), type = "real", 
    ybounds = c(0, Inf), closed = c(FALSE, NA),
    ad = c("weights", "subset", "cens", "trunc", "mi", "index"),
    specials = "logscale"
  )
}
```

The lognormal family in brms is just syntax sugar for log(y) ~ x, family = "gaussian"

**Comment by bwiernik** [comment]
```r
library(brms)

m1 <- brm(mpg ~ hp, family = lognormal(), data = mtcars)
summary(m1)
#>  Family: lognormal 
#>   Links: mu = identity; sigma = identity 
#> Formula: mpg ~ hp 
#>    Data: mtcars (Number of observations: 32) 
#>   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
#>          total post-warmup draws = 4000
#> 
#> Population-Level Effects: 
#>           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> Intercept     3.46      0.08     3.29     3.63 1.00     3726     2918
#> hp           -0.00      0.00    -0.00    -0.00 1.00     4887     3014
#> 
#> Family Specific Parameters: 
#>       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> sigma     0.19      0.03     0.15     0.25 1.00     1256     1238
#> 
#> Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
#> and Tail_ESS are effective sample size measures, and Rhat is the potential
#> scale reduction factor on split chains (at convergence, Rhat = 1).

m2 <- brm(log(mpg) ~ hp, family = gaussian(), data = mtcars)
summary(m2)
#>  Family: gaussian 
#>   Links: mu = identity; sigma = identity 
#> Formula: log(mpg) ~ hp 
#>    Data: mtcars (Number of observations: 32) 
#>   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
#>          total post-warmup draws = 4000
#> 
#> Population-Level Effects: 
#>           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> Intercept     3.46      0.08     3.29     3.62 1.00     3678     2944
#> hp           -0.00      0.00    -0.00    -0.00 1.00     4749     2668
#> 
#> Family Specific Parameters: 
#>       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> sigma     0.19      0.03     0.15     0.25 1.00     1616     1845
#> 
#> Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
#> and Tail_ESS are effective sample size measures, and Rhat is the potential
#> scale reduction factor on split chains (at convergence, Rhat = 1).
```

**Comment by mattansb** [comment]
Oh man, that is not cool! [What is "identity" about that??](https://discourse.mc-stan.org/t/lognormal-family-in-brms-with-true-identity-link/252520) 😒

So yeah, I guess what you were saying - the ROPE should be like `[-0.01, 0.01]` for log-links ***and*** for identity link for lognormal family. Hmpf...

**Comment by bwiernik** [comment]
It's not a link function, it's a data transformation. A "log link" would apply only to the mean function, not to the sigma. 

A lognormal model is a model fit to the log-transformed (not log linked) response with a normal likelihood. 

I am thinking The `[-.01, .01]` should apply to:
  - The `brms::lognormal()` family
  - "gaussian" models with a **log transformation** (not log link) (see the new `insight::find_transformation()` function)
  - "gaussian" models with a log link

**Comment by bwiernik** [comment]
I don't really understand your concern. Lognormal regression is universally defined in my experience to mean assuming log(y) ~ Normal(). In what context are you seeing a need for something otherwise?

**Comment by bwiernik** [comment]
Also important to remember that what is being modeled in any regression is the linear model on the main distribution parameter. In a gaussian model, that's the conditional mean of the response. 

The lognormal distribution is parameterized use the mean and SD of log(y), so it's entirely consistent to say that this is an identity link--the distribution parameter isn't being transformed at all.

**Comment by bwiernik** [comment]
You could do median regression by fitting a lognormal() family with an exp() link. That would model exp(mu) with a linear model, which is the median of the lognormal.

**Comment by mattansb** [comment]
> I don't really understand your concern. Lognormal regression is universally defined in my experience to mean assuming log(y) ~ Normal(). In what context are you seeing a need for something otherwise?

I mean, they are different distributions - many distributions are some transformation of one-another, but that doesn't mean we always treat one *as* a transformation of the other.

``` r
dnorm(0.3)
#> [1] 0.3813878
dlnorm(exp(0.3))
#> [1] 0.282539
```

(Would produce different likelihoods)

So its just, I guess, "disappointing" if `brms` is only using syntactic sugar here, and not using a true lognormal model.

As we've discussed elsewhere, if I just wanted multiplicative coefficients/relationships, I could using `gaussian("log")`, but I was expecting `lognormal("identity")` to have additive coefficients/relationships but a logrnomal conditional distribution.

Is there any other case where "identity"-link produces something other that a linear relationship?

> You could do median regression by fitting a lognormal() family with an exp() link

```
Error: 'exp' is not a supported link for family 'lognormal'.
```

**Comment by mattansb** [comment]
Okay, the link is about the parameter, and mu and sigma are, by definition, on the log scale. That *is* their identity. Oomf.

We can do better.

<Starts writing custom brms family>

(Have I mentioned I've been bedridden for the last 4 days with a fever? I would take anything I've said with a Himalayan sized pinch of salt [regular salt, not Himalayan])

**Comment by strengejacke** [comment]
What's the state of this issue? Can someone summarize (like I'm 5) what we need to change in _bayestestR_?

**Comment by bwiernik** [comment]
When family is lognormal or the response has a log() transformation, we should use a fixed ROPE range default rather than one based on the SD of the response. 

I think a 1% change is a gold default “negligible” threshold. So we just fix the default rope for log responses at c(-.01, .01)

**Comment by strengejacke** [comment]
ok. we could check this with `insight::find_transformation()`?

**Comment by mattansb** [comment]
No, because the log-normal regression in brms is an actual family, so this would be detected with `family()`.

**Comment by strengejacke** [comment]
So we need both? Checking response and family? (https://github.com/easystats/bayestestR/issues/487#issuecomment-1087197036)

**Comment by bwiernik** [comment]
Yes

**Comment by strengejacke** [comment]
last commit should cover these cases
