### ISSUE TITLE
hdi with BFmcmc-objects

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#49]
Move here from https://github.com/strengejacke/sjstats/issues/68

@IndrajeetPatil due to the re-organization of some packages, all Bayes-related stuff will now be implemented in the _bayestestR_-package. So I'm moving your issue over here.

**Comment by strengejacke** [comment]
@DominiqueMakowski Do you want to check this, or should I try a first attempt?

**Comment by DominiqueMakowski** [comment]
I'll look into it

**Comment by DominiqueMakowski** [comment]
I think that it's better to do this right rather than in a clunky way, so it will have to wait for insight (minimal) support Might also go to v2

**Comment by DominiqueMakowski** [comment]
- [x] p_direction
- [ ] hdi
- [ ] ci
- [ ] equivalence_test
- [ ] p_map
- [ ] p_rope
- [ ] rope

**Comment by DominiqueMakowski** [comment]
We're almost there. 

Related to #104

**Comment by DominiqueMakowski** [comment]
🎉 @IndrajeetPatil Hopefully a basic support is now implemented for most of the functions (in the github version). It highly relies on the ability of [`insight::get_parameters`](https://github.com/easystats/insight/blob/master/R/get_parameters.R#L587) to retrieve the parameters' posteriors correctly, but it *seems* to work.

Don't hesitate to play around with it to test and see if it works as expected ☺️ 

Will close this and we can open new issues in case of bugs etc.
