### ISSUE TITLE
Return BF column to output objects

### ISSUE THREAD

**Issue by JeffreyRStevens** [easystats/bayestestR#493]
**Describe the solution you'd like**
Would it be possible to add the `BF` column back to the output objects from `bf_models()`, etc. in addition to `log_BF`? It can be confusing for users to see the BF printed to the console, but it is not directly available in the object when trying to extract the BF (for R Markdown documents for example). While there is a straightforward solution on the user's end (use `exp()` as demonstrated in #442), (1) there is a conceptual disconnect between the two forms output (console and object), (2) this breaks older code that extracted BFs with the `BF` column, and (3) it requires an additional step by users to convert between the two.

**How could we do it?**
Create additional column `BF` that is `exp(log_BF)`. If there is a technical/philosophical reason to only output one column of BFs, perhaps there could be an argument that would let users decide if they want BFs or log BFs.

Thanks for the package!

**Comment by mattansb** [comment]
The decision to have log(BF) instead of BF was done for precision needs - especially dealing with very large / very small Bayes factors. We thought (and I still think) that having both columns would be more confusing.

Here's what I've done:

I've fixed the `as.numeric` method for all `bayesfactor_*` related outputs (see below), as well as updated the docs to let user know how they can extract the Bayes factors from the objects.

``` r
library(bayestestR)


m0 <- lm(mpg ~ 1, mtcars)
m1 <- lm(mpg ~ hp, mtcars)
mX <- lm(mpg ~ ., mtcars)

(bf_mods <- bayesfactor_models(m0, m1, mX))
#> Bayes Factors for Model Comparison
#> 
#>      Model                                                            BF
#> [m1] hp                                                         4.54e+05
#> [mX] cyl + disp + hp + drat + wt + qsec + vs + am + gear + carb 3.97e+06
#> 
#> * Against Denominator: [m0] (Intercept only)
#> *   Bayes Factor Type: BIC approximation

print(bf_mods, log = TRUE)
#> Bayes Factors for Model Comparison
#> 
#>      Model                                                         BF
#> [m1] hp                                                         13.03
#> [mX] cyl + disp + hp + drat + wt + qsec + vs + am + gear + carb 15.19
#> 
#> * Against Denominator: [m0] (Intercept only)
#> *   Bayes Factor Type: BIC approximation
#> 
#> Bayes Factors are on the log-scale.

as.numeric(bf_mods)
#> [1]       1.0  453874.3 3969589.8

as.numeric(bf_mods, log = TRUE)
#> [1]  0.00000 13.02558 15.19417
```

<sup>Created on 2021-12-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
