### ISSUE TITLE
BIC to BF conversion: add more reference and details

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#500]
https://github.com/easystats/bayestestR/blob/c0c33571ad4b26389a5ff88277fbbad7106de7bf/R/bic_to_bf.R#L1-L3

Although it's pretty trivial, it would be good to add a minimal explanation here, as well as some references :)

Also here it says "only for non-nested models":

https://github.com/easystats/bayestestR/blob/c0c33571ad4b26389a5ff88277fbbad7106de7bf/vignettes/bayes_factors.Rmd#L599-L603

but in [this paper](http://math.bu.edu/people/sray/preprints/smr_MS242_mar10.pdf) (p.2) it says:

![image](https://user-images.githubusercontent.com/8875533/151090777-7d4c1b62-aa3b-4983-b7a5-1684d1a58fc8.png)

**Comment by mattansb** [comment]
> "allowing a Bayesian comparison of non-nested frequentist models"

Not *only*, but it allows it (cf. LRTs that do not allow the comparison of non-nested models)

**Comment by mattansb** [comment]
You can reference:

- Wagenmakers, E. J. (2007). A practical solution to the pervasive problems of p values. Psychonomic bulletin & review, 14(5), 779-804.

And some papers about BICs in general.
