### ISSUE TITLE
Avoiding warning in R CMD Check about generic/method consistency

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/bayestestR#502]
```r
❯ checking S3 generic/method consistency ... WARNING
Warning:   as.vector:
    function(x, mode)
  as.vector.bayesfactor_inclusion:
    function(x, log, ...)
  
  as.vector:
    function(x, mode)
  as.vector.bayesfactor_models:
    function(x, log, ...)
  
  as.vector:
    function(x, mode)
  as.vector.bayesfactor_parameters:
    function(x, log, ...)
  
  as.vector:
    function(x, mode)
  as.vector.bayesfactor_restricted:
    function(x, log, ...)
  
  See section ‘Generic functions and methods’ in the ‘Writing R
  Extensions’ manual.
```

**Comment by bwiernik** [comment]
That's not possible. The generic as.vector doesn't have a ... argument

**Comment by IndrajeetPatil** [comment]
But that's what I see on [GHA](https://github.com/easystats/bayestestR/runs/4956249718?check_suite_focus=true) for R-devel:

![image](https://user-images.githubusercontent.com/11330453/151280613-c0152076-f40c-4d20-a471-443e531f3f9e.png)

**Comment by bwiernik** [comment]
I mean, it's not possible to fix this. The only permissible arguments for as.vector methods are x and mode

We should just get rid of these as.vector methods.

**Comment by strengejacke** [comment]
Why not replace by `as.numeric()`?

**Comment by bwiernik** [comment]
Good call

**Comment by IndrajeetPatil** [comment]
We no longer get this warning, so the issue seems to be resolved somewhere upstream.

**Comment by strengejacke** [comment]
https://github.com/easystats/bayestestR/commit/5a8fdf74f71d7ec81a9c648822037b1f57a3c2aa

**Comment by IndrajeetPatil** [comment]
_"Daniel fixed it"_ should always be my first guess 😅
