### ISSUE TITLE
Use `{datawizard}` instead of `{tidyr}`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/bayestestR#507]
cf. https://github.com/easystats/easystats/issues/167

Where it's used:
https://github.com/easystats/bayestestR/search?q=tidyr

**Comment by strengejacke** [comment]
We should probably switch to _poorman_, then we have dply, tidyr and pipe covered.

**Comment by IndrajeetPatil** [comment]
Agreed. I had already created an issue for that here: https://github.com/easystats/bayestestR/issues/506.
