### ISSUE TITLE
Non-conformable arguments error when calling `bayesfactor()` on `emmGrid` object created with `emtrends()`

### ISSUE THREAD

**Issue by qdread** [easystats/bayestestR#510]
Great package, thanks so much!!!

I want to call `bayesfactor()` on an `emmGrid` object created with `emtrends()`. However I get this error: 

`Error in PB %*% t(object@linfct) : non-conformable arguments`

But if I manually go in to the `emmGrid` object, say `x`, and extract the elements and do matrix multiplication on them, the dimensions are conformable and it works fine.

`x@post.beta %*% t(x@linfct)`

This makes me think it should be possible to calculate Bayes factors for an `emtrends` object and maybe there is a bug in the code?

## Reprex

Even this simple case produces the error.

```
library(emmeans)
library(bayestestR)
library(brms)

mod <- brm(y ~ x * g, data = data.frame(y = 1:10, x = runif(10), g = letters[1:2]),
           prior = prior('student_t(3, 0, 5)', class = 'b'))

emt <- emtrends(mod, ~ g, var = 'x')

bayesfactor(emt, prior = mod) # Throws error.

emt@post.beta %*% t(emt@linfct) # This works.
```

## Versions

- R 4.1.2
- Windows 10
- bayestestR_0.11.5, emmeans_1.7.1-1, brms_2.16.3

**Comment by mattansb** [comment]
Hi @qdread 

Currently, we can't internally handle `brmsfit`-based-`emmGrid`s (due to how `brms` builds `emmGrid`s).
I will fit this in the docs and throw a better error.

You should instead:

```R
library(emmeans)
library(bayestestR)
library(brms)

mod <- brm(y ~ x * g, data = data.frame(y = 1:10, x = runif(10), g = letters[1:2]),
           prior = prior('student_t(3, 0, 5)', class = 'b'),
           backend = "cmdstanr")

emt <- emtrends(mod, ~ g, var = 'x')

# ADD THIS STEP
prior_mod <- unupdate(mod)
prior_emt <- emtrends(prior_mod, ~ g, var = 'x')
  
bayesfactor_parameters(emt, prior = prior_emt)
#> Bayes Factor (Savage-Dickey density ratio)
#> 
#> Parameter |    BF
#> -----------------
#> a         | 0.946
#> b         | 0.858
#> 
#> * Evidence Against The Null: 0
#> Warning message:
#> Bayes factors might not be precise.
#> For precise Bayes factors, sampling at least 40,000 posterior samples is recommended. 
```

**Comment by qdread** [comment]
Thanks that's extremely helpful. That's basically what I was doing except in a much more cumbersome way as I didn't know the `unupdate` function existed!
