### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#512]
- [ ] https://github.com/easystats/bayestestR/runs/5527752575?check_suite_focus=true#step:10:522 @mattansb looks like results changed their sign - is this expected?

**Comment by mattansb** [comment]
I see not reason this should have changed - was there are changes made in how a one-sample posterior is extracted?

``` r
BFtt <- BayesFactor::ttestBF(mtcars$wt, mu = 3)
BayesFactor::posterior(BFtt, iterations = 6)
#> Object of class "mcmc"
#> Markov Chain Monte Carlo (MCMC) output:
#> Start = 1 
#> End = 6 
#> Thinning interval = 1 
#>            mu      sig2    delta         g
#> [1,] 3.139734 1.2213239 2.841040 91.479429
#> [2,] 3.020231 0.5901505 3.931504 13.934648
#> [3,] 3.371019 0.8113361 3.742491 24.644521
#> [4,] 3.056213 0.7629623 3.498904 25.671975
#> [5,] 3.183744 0.9156050 3.327240  5.158026
#> [6,] 2.859737 1.0355251 2.810256 29.083063
#> ---
#>  Model:
#> Type: BFoneSample, JZS
#> Alternative, r = 0.707106781186548, mu =/= 3 
#> Data types:
```

None of those seem to match:

``` r
insight::get_parameters(BFtt)[1:6, , drop =F]
#>   Difference
#> 1  0.1392439
#> 2  0.1743972
#> 3  0.1658558
#> 4  0.3066358
#> 5  0.5531304
#> 6  0.1782939
```

Which seems to be giving Cohen’s d:

``` r
effectsize::cohens_d(BFtt)
#> Cohen's d |        95% CI
#> -------------------------
#> 0.19      | [-0.15, 0.54]
#> 
#> - Deviation from a difference of 3.
```

<sup>Created on 2022-03-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
hm, I'm not sure. Is there anything that needs to be addressed in _insight_? Planning to submit the next days...

**Comment by mattansb** [comment]
Sorry, it's not giving Cohen's d - the `sd(wt)` is just 1 😅

All seems good in insight, but my guess is that something changed at some point, which is causing the tests here to fail.
(Nothing changed in bayestestR)

**Comment by IndrajeetPatil** [comment]
Closing, since these tests are not failing anymore. I am assuming this was fixed in _insight_ itself.

**Comment by DominiqueMakowski** [comment]
waiting until it magically goes away... my favourite way to fix issues 😁

**Comment by strengejacke** [comment]
No, I just adapted the test. So the test works, but I'm not sure the function returns the valid results? Since I don't work with BayesFactor, I don't care much about it ;-) But feel free to check if the function still returns correct results.
