### ISSUE TITLE
Cran 04/04

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#516]
NEWS for R-devel has

     • Calling && or || with either argument of length greater than one
       now gives a warning (which it is intended will become an error).

and checks with this made into a fatal error can be seen at

https://www.stats.ox.ac.uk/pub/bdr/LENGTH1/

with reproduction instructions in the 00README.txt file.  (As this was
made a fatal error, only the first error will be shown so please do run
those instructions before re-submission.)

The problems are occurring in a different package and there is a table
of which in that 00README.txt,  In some cases this is from misuse but
you may need to contact the maintainer of the other package

Please correct before 2022-04-04 to safely retain your package on CRAN.

**Comment by DominiqueMakowski** [comment]
The error seems to have occured in `bci()`: 

```r
> posterior <- rnorm(1000)
> bci(posterior)
```

**Comment by strengejacke** [comment]
I _think_ the issue is fixed already. What I find strange is this issue, which only occurs when we add class attributes:

``` r
x <- rnorm(1000)
ci <- c(.8, .9, .95)

out <- do.call(rbind, lapply(ci, function(i) {
  bayestestR:::.bci(x = x, ci = i, verbose = TRUE)
}))

attr(out, "data") <- x
str(out)
#> 'data.frame':    3 obs. of  3 variables:
#>  $ CI     : num  0.8 0.9 0.95
#>  $ CI_low : num  -1.38 -1.71 -2.05
#>  $ CI_high: num  1.26 1.64 2
#>  - attr(*, "data")= num [1:1000] -0.474 -0.0264 0.927 -0.0835 -2.1598 ...



x <- rnorm(1000)
ci <- c(.8, .9, .95)

out <- do.call(rbind, lapply(ci, function(i) {
  bayestestR:::.bci(x = x, ci = i, verbose = TRUE)
}))
class(out) <- unique(c("bayestestR_eti", "see_eti", "bayestestR_ci", "see_ci", class(out)))
attr(out, "data") <- x
str(out)
#> Classes 'bayestestR_eti', 'see_eti', 'bayestestR_ci', 'see_ci' and 'data.frame': 3 obs. of  3 variables:
#>  $ CI     :
#> Error in oTypes[[i]]: subscript out of bounds
```

<sup>Created on 2022-03-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
ok, it comes from `utils::str.default()`:

``` r
x <- rnorm(1000)
ci <- c(.8, .9, .95)

out <- do.call(rbind, lapply(ci, function(i) {
  bayestestR:::.bci(x = x, ci = i, verbose = TRUE)
}))
vapply(out, typeof, "")
#>       CI   CI_low  CI_high 
#> "double" "double" "double"

class(out) <- unique(c("bayestestR_ci", "see_ci", "data.frame"))
vapply(out, typeof, "")
#> character(0)
```

<sup>Created on 2022-03-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
@mattansb I think you fixed it here:
https://github.com/easystats/insight/commit/6180770921cf70e4448fdf827c91a4d8370d6af5

See initial issue here:
https://www.stats.ox.ac.uk/pub/bdr/LENGTH1/bayestestR.out

**Comment by mattansb** [comment]
Looks like I did!

**Comment by IndrajeetPatil** [comment]
What's the status of the submission? Only 3 days remaining for archival.

**Comment by strengejacke** [comment]
It's on CRAN, I think?

**Comment by strengejacke** [comment]
Yep, https://cloud.r-project.org/web/packages/bayestestR/index.html

**Comment by IndrajeetPatil** [comment]
Oh, I see. The _insight_ update fixed this, and so an update is necessary. 

But let's keep an eye on it after 04/04 to make sure that it has not been archived.

**Comment by strengejacke** [comment]
Sorry, the CRAN site still show 0.11.5 - I thought that bayestestR 0.12.0 was already submitted? @DominiqueMakowski ?

**Comment by strengejacke** [comment]
Dom?

**Comment by strengejacke** [comment]
(ping explicitly @DominiqueMakowski 😁 )

**Comment by IndrajeetPatil** [comment]
Wasn't archived, so seems like an update became unnecessary after _insight_ CRAN update.

**Comment by DominiqueMakowski** [comment]
I do't know but I confirmed submitted it and validated it (and it *was* in the pipeline when I submitted it) and since then no news 😠  it's not the first time this happens for bayestestR it seems
