### ISSUE TITLE
diagnostic_posterior bug

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#517]
I've encountered a few times a bug (that led to upstream bugs in `parameters()`)

But I can't reproduce it... I don't know if it's a matter of like model convergence of what, but opening that issue in case someone confirms the bug or manages to reproduce it.

``` r
data <- lme4::sleepstudy
model <- brms::brm(Reaction ~ Days + (1 | Subject), data = data, refresh = 0, algorithm = "meanfield", seed = 333)

bayestestR::diagnostic_posterior(model)
#>     Parameter     Khat
#> 1      b_Days 4.609439
#> 2 b_Intercept 5.122897
```

<sup>Created on 2022-03-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
What's the issue here?

**Comment by DominiqueMakowski** [comment]
I got an error while running the example above, but I can't reproduce it 😕

**Comment by strengejacke** [comment]
Seems to be related to the sampling algorithm? If you remove "meanfield", more diagnostics are done.

**Comment by DominiqueMakowski** [comment]
no but the error was a complete error, it failed entirely... I'll post a reprex if I manage to reproduce it someday
