### ISSUE TITLE
Document HDI algorithms

### ISSUE THREAD

**Issue by bwiernik** [easystats/bayestestR#520]
The `bayestestR` package documentation for `hdi()` doesn't tell which algorithm is used for HDI.
Anyway, I think it's great if `bayestestR` will support `posterior` objects.

__Originally posted by @avehtari in https://github.com/stan-dev/posterior/issues/216#issuecomment-1086889706__

**Comment by bwiernik** [comment]
Would also be good to add other options, like the SPIn algorithm discussed at the linked issue

**Comment by strengejacke** [comment]
This _could_ be a duplicate of #519, not quite sure, though. 😁
