### ISSUE TITLE
Default to ETI instead of HDI?

### ISSUE THREAD

**Issue by bwiernik** [easystats/bayestestR#521]
The more that I'm reading about HDI, the more I'm skeptical about the additional assumptions they require and their performance (especially for >80% intervals). I'm wondering if we should switch to using ETI as the default interval method for Bayesian samples?

> the paper illustrates the challenge of reducing the variance without additional assumptions about the target distribution. After the paper had been published, Andrew started to think that HDI is not that useful, and thus hasn't advocated the paper and the package. In that paper the focus was on 95% HDI, and since then Andrew has advocated, e.g. 20% and 80% quantiles as they have less variance.

__Originally posted by @avehtari in https://github.com/stan-dev/posterior/issues/216#issuecomment-1074177572__

Also: https://twitter.com/betanalpha/status/1479106549519831040?s=21&t=-bBVfRH2pajMzY_ZkqY1Ng

> Highest density intervals are not defined by expectation values and so they cannot be constructed from samples alone.  Like density estimators they require additional assumptions that can significantly affect the outcome of the intervals, especially if the credibility is large.

> Because of this sensitivity to additional assumptions, in particular assumptions that are often only implicit with in a particular HDI estimation method,  I strongly recommend that they be avoided entirely.

**Comment by strengejacke** [comment]
btw, @DominiqueMakowski, here's an argument for 89% instead of 95% interval range ;-)

**Comment by mattansb** [comment]
![image](https://user-images.githubusercontent.com/35330040/161490860-ca50f8d2-4d32-46d8-9714-cb471e22d3d6.png)

**Comment by bwiernik** [comment]
No, those will be about the same. You need to get down to about 60% before the variance is meaningfully smaller.

**Comment by strengejacke** [comment]
That's a strong opinion about HDI:

>  I strongly recommend that they be avoided entirely.

(https://twitter.com/betanalpha/status/1479107186030624771)

**Comment by strengejacke** [comment]
#522 implements SPI (shortest probability intervals)

**Comment by strengejacke** [comment]
Any reason for closing this?

**Comment by bwiernik** [comment]
It was done wasn't it?

**Comment by strengejacke** [comment]
In parameters, not yet bayestestR I think

**Comment by bwiernik** [comment]
Oops

**Comment by strengejacke** [comment]
@DominiqueMakowski any opinions? And: have you submitted _bayestestR_ the last time, and it got suck somewhere? If so, we probably resolve this issue and then submit (again) to CRAN?

**Comment by DominiqueMakowski** [comment]
I am okay to change it, but my knowledge of the underlying algorithms is a bit limited to improve the documentation :/

**Comment by bwiernik** [comment]
Just stating the name of the algorithm used should be sufficient
