### ISSUE TITLE
CRAN before 09/05

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#526]
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_bayestestR.html>.

Please correct before 2022-05-09 to safely retain your package on CRAN.

It seems we need to remind you of the CRAN policy:

'Packages which use Internet resources should fail gracefully with an informative message
if the resource is not available or has changed (and not give a check warning nor error).'

This needs correction whether or not the resource recovers.

**Comment by DominiqueMakowski** [comment]
submitted

**Comment by strengejacke** [comment]
Have you fixed the issue?

**Comment by strengejacke** [comment]
503 are false positive, remaining URLs should be fixed.

**Comment by strengejacke** [comment]
Have you already resubmitted?

**Comment by DominiqueMakowski** [comment]
yes, pending manual inspection !

**Comment by IndrajeetPatil** [comment]
On CRAN.
