### ISSUE TITLE
Docs format

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#53]
- Minor issues formatting related to bat sticks here in [**details**](https://easystats.github.io/bayestestR/reference/p_direction.html)

**Comment by strengejacke** [comment]
I just updated the website, fixing all typos I found. Can you please check again, ans see if this issue is resolved?

btw., I'm finished with reading now, so I won't commit more for now, to give you the chance to pull the latest version ;-)

**Comment by strengejacke** [comment]
"bat sticks" is nice. :-D

**Comment by strengejacke** [comment]
btw, readme._rmd_ is updated, but readme._md_ seems not to be compiled / updated yet. Isn't this done automatically?

**Comment by DominiqueMakowski** [comment]
I think it is compiled for the website (i.e. transformed to html) but the .md file is not saved when ran through `build_site()`. I'll update it!
