### ISSUE TITLE
`describe_posterior` performance and re-use

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/bayestestR#531]
Hi,

I notice that `describe_posterior` can be slow sometimes with `brms` models. Profiling shows that most of its time is spent calling `insight::get_parameters` 4 times.

![image](https://user-images.githubusercontent.com/987057/170883696-c9ecf0ae-6d34-473b-9211-7ad212f3b966.png)

Do you think it would be possible to call it once and then re-use the results in the various subfunctions like `point_estimate`?

**Comment by mattansb** [comment]
This should be easy to do - all (?) bayestestR functions have a data frame method, and get_parametera returns a data frame.

**Comment by strengejacke** [comment]
I think we just need to add something like 

```r
  effects <- match.arg(effects)
  component <- match.arg(component)
  cleaned_parameters <- insight::clean_parameters(posteriors )

  posteriors <- .prepare_output(
    insight::get_parameters(posteriors , effects = effects, component = component, parameters = parameters),
    cleaned_parameters
  )
  out <- .describe_posterior(
  ...
  )
  
```

**Comment by strengejacke** [comment]
See #532

**Comment by vincentarelbundock** [comment]
Fixed by https://github.com/easystats/bayestestR/pull/532 now merged

Thanks @strengejacke

**Comment by strengejacke** [comment]
@DominiqueMakowski @vincentarelbundock Looking at the code from `.describe_posterior()` (https://github.com/easystats/bayestestR/blob/b58580cf9de65cdbaa16f2b2da8a82a6134039e6/R/describe_posterior.R#L114), I think we have much overhead here (_bayestestR_ was the first package in the easystats-ecosystem, and we just wanted it to work for even complex models, so we didn't really do very "clean coding").

I _think_ that all functions that are called (like point_estimate, ci, or the test_* functions) _should_ return the parameters in the same order. I wonder whether we can just add a "rowid" to each of these data frame, merge by parameter and ID, and then use `.prepare_output()` only once at the end? This makes the code a bit cleaner and - but probably not that relevant - _slightly_ improves performance.
