### ISSUE TITLE
diagnostic indices are not reported by the describe_posterior function

### ISSUE THREAD

**Issue by JulianGaviriaL** [easystats/bayestestR#549]
The diagnostic indices are not reported by the describe_posterior function: 
```
describe_posterior(compare.a1, diagnostic = "all")
describe_posterior(compare.a1, diagnostic = "Rhat")
```

See sample data in:
https://drive.switch.ch/index.php/s/F5qJDLkv0Pkb6ce

Specifications:
-R version 4.1.2 (2021-11-01) 
-Rstudio version ‘2022.2.3.492’
 -bayestestR [ 0.11.5]

**Comment by mattansb** [comment]
What is the class of `compare.a1`?

**Comment by JulianGaviriaL** [comment]
Thanks a lot @mattansb  for replying

`compare.a1` is data.frame 
`describe_posterior` perfectly works with blavaan objects

Best,

**Comment by mattansb** [comment]
A data frame does not contain information about the number of chains used (or their indices) and so it is not possible to to return these diagnostics. 

For model objects, this information is stored and can thus be used.
