### ISSUE TITLE
Possible issues

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#55]
Is the absence of variable expected? 
https://github.com/easystats/bayestestR/blob/c3309782549f902f64d10e531f80951c4f14b7e5/R/utils_hdi_ci.R#L141

**Comment by strengejacke** [comment]
Yes. It just means that the assignment for `zi` is passed to the next line, some kind of "capturing groups" in the `switch()`-command.

from `?switch

> If there is a match then that element is evaluated unless it is missing, in which case the next non-missing element is evaluated, so for example `switch("cc", a = 1, cc =, cd =, d = 2)` evaluates to `2`.

**Comment by DominiqueMakowski** [comment]
Didn't know :) thanks
