### ISSUE TITLE
Rope range for z-scored response 

### ISSUE THREAD

**Issue by Dallak** [easystats/bayestestR#554]
Dear all,

I'm wondering if you have some advice on how to set the rope range for z-scored response variables. I'm aware of 0.1*sd(y) as nicely documented in the package.

Many thanks!

**Comment by bwiernik** [comment]
You can set the `rope_range` argument to a vector with the lower and upper bounds (eg, `rope_range = c(-.2, .2)`. .1 or .2 SDs is probably a good range for standardized variables (.2 is the 25%ile for categorical effect sizes observed in psychology research, .1 is the 25%ile for continuous effect sizes)
