### ISSUE TITLE
Reorder vignettes order

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#56]
Turns out vignettes files can't start with numbers, which was added for dealing with their order in the website. Must specify it in pkgdown parameters:

- [example](https://github.com/tidyverse/dplyr/blob/b3837f5dbf435458358f28ae47bbd0eb71796daa/_pkgdown.yml#L104)

**Comment by strengejacke** [comment]
I had the same difficulties when I wanted to reorder vignettes for ggeffects, finally I gave up. ;-)

**Comment by DominiqueMakowski** [comment]
I think I've managed to do it, and rearranged stuff a bit. What do you think?

**Comment by strengejacke** [comment]
Can't check from here (on vacation), I just saw that there's a long section in bold formatting (https://easystats.github.io/bayestestR/articles/guidelines.html), is this intended?
Else, go ahead, I trust you in all decisions needed for CRAN submission. :-)
