### ISSUE TITLE
ROPE vs. posterior distribution edge

### ISSUE THREAD

**Issue by Dallak** [easystats/bayestestR#560]
Dear all,

This is more of a clarification question. I'm using the package `emmeans` to calculate estimate for each pair in my brm model. As is seen in the table, the posterior distribution of two of the contrasts fall outside the rope, Rope = 0.

```
   Contrast   Estimate      Q2.5      Q97.5      Rope
1 fin - ini -0.4130980 -0.685896 -0.1401137 0.0000000
2 fin - med -0.0202940 -0.342101  0.3002460 0.4921786
3 ini - med  0.3934325  0.146396  0.6463180 0.0000000
```
But when plotting this, I still see the edges of both contrasts fall inside the rope. Is there any discrepancy going on? Or if the posterior 95% CI are outside the rope as shown by the lighter blue color, this would simply mean ROPE = 0?   
The rope in the plot is set to (-0.1, 0.1), and the rope in the table is calculated suing `rope()`. 

![Rplot17](https://user-images.githubusercontent.com/47871346/185116505-c54656c3-eb89-46f9-ad78-cdda70aafa74.png)

Thanks in advance!

**Comment by strengejacke** [comment]
Yes, see documentation. The results refer to the proportion of the 95% HDI of the posterior that fall inside the rope range.
