### ISSUE TITLE
Making `contr.orthonorm` (`.bayes`) more intuitive 

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#562]
Currently, the code for `contr.orthonorm` (previously `contr.bayes`) makes setting priors on the resulting coefficients quite difficult.

If I have set a prior of $Norm(0, 3)$ I am actually setting this prior on all the pairwise differences divided by a constant:

$$
\frac{\mu_i - \mu_{j\neq i}}{\sqrt{2}} \sim Norm(0, 3)
$$

Which is a shame :/

## Suggestion

Divide the output of `contr.orthonorm` by `sqrt(2)` will make the prior on the pairwise differences.

This is a ***breaking change***, however I think this change will dubstatnially improve the usability of the function.

What do you think @easystats/maintainers? Also tagging @singmann and @quentingronau who originally implemented the function from [Rouder et al's paper (p. 363)](https://doi.org/10.1016/j.jmp.2012.08.001).

## Demo

``` r
library(bayestestR)

set.seed(444)

k <- 5 # number of groups
```

Current behavior:

``` r
contr <- contr.orthonorm(k)
coefs <- replicate(k - 1, {
  rnorm(4e3, mean = 0, sd = 3.12) # sample some priors ~Norm(0, 3.12)
})

means <- t(contr %*% t(coefs)) # conver contrasts and coefs to means


mean(means[,1] - means[,2])
#> [1] -0.06991937
sd(means[,1] - means[,2])
#> [1] 4.429295

# Convert to prior scale...
mean(means[,1] - means[,2])/(sqrt(2))
#> [1] -0.04944046
sd(means[,1] - means[,2])/(sqrt(2))
#> [1] 3.131985
```

Suggested solution

``` r
contr_fix <- contr / sqrt(2) # HERE

means_fix <- t(contr_fix %*% t(coefs)) # conver contrasts and coefs to means

# Results are on prior's scale
mean(means_fix[,1] - means_fix[,2])
#> [1] -0.04944046
sd(means_fix[,1] - means_fix[,2])
#> [1] 3.131985
```

<sup>Created on 2022-08-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

## Changes

- [x] Change function
- [x] Update function docs to detail:
  1. That it should be used only with 0-centered priors
  2. That it is a prior for all pairwise differences
- [x] Update BF vignette

**Comment by quentingronau** [comment]
I think this would be a nice addition. My only comment is that, by dividing by sqrt(2), the resulting contrasts will still be orthogonal, but not "orthonormal" anymore, since the vectors do not have length 1. I think this is fine, but something to perhaps consider for the function name. Furthermore, I would suggest to give users the option to still use the current version if they want to (e.g., to obtain results in line with other software that uses these contrasts).

**Comment by mattansb** [comment]
Good points. So we can have `contr.orthonorm` (old) and `contr.ortho` (old / `sqrt(2)`) (unless anyone has a better name?).

@quentingronau Do you know how the matrix can be scaled so that it can be used to set priors on deviations from the mean? I feel like that would also be something quite useful, but I can't figure out what the scaling factor is (some computation of K I suspect?)

**Comment by DominiqueMakowski** [comment]
contr.orthogonal 👍

**Comment by singmann** [comment]
I am not such a big fan of `contr.orthogonal` as there are other orthogonal contrasts, such as base R, `contr.helmert`. So orthgonality is not really what defines the contrast. 

What defines the contrast is that the marginal prior is equal for each factor level. So how about something that is descriptive along these lines. Maybe `contr.equal_prior`?

**Comment by DominiqueMakowski** [comment]
`contr.equalprior` sounds good

**Comment by mattansb** [comment]
`contr.equalprior`  and `contr.equalprior_pairs`?

And if we can figure out how to scale to priors on deviation's from the mean https://github.com/easystats/bayestestR/issues/562#issuecomment-1231795780, we can have `contr.equalprior_deviation`.

**Comment by singmann** [comment]
If we can find the scaling factor for the deviation from the mean, that function pair of `contr.equalprior_pairs` and `contr.equalprior_deviation` does sound like a nice addition. But not sure if it is easy to get the latter. As far as I remember my playing around with the original `contr.bayes` function, the deviation from the means is different for each value of `k`. I have to see whether I can find my old notes.

**Comment by mattansb** [comment]
@singmann If you could find those, that would be great!

I got pretty close with:

$$
\text{Scale factor} \approx 1 - \frac{1-\sqrt{0.5}}{\sqrt{k-1}}
$$

Which is off by about 3%...:

|   k| factor_sim| factor_approx|
|---:|----------:|-------------:|
|   2|  0.6952666|     0.7071068|
|   3|  0.8168733|     0.7928932|
|   4|  0.8703299|     0.8308980|
|   5|  0.8970935|     0.8535534|
|   6|  0.9226207|     0.8690142|
|   7|  0.9242206|     0.8804268|
|   8|  0.9261717|     0.8892968|
|   9|  0.9603309|     0.8964466|
|  10|  0.9490705|     0.9023689|
|  20|  0.9730912|     0.9328057|
| 100|  0.9893293|     0.9705631|
| 200|  1.0223710|     0.9792374|
| 500|  0.9876504|     0.9868883|

**Comment by mattansb** [comment]
Solved!

``` r
library(bayestestR)

k <- 5 # number of groups

# Analytical

r <- -1 / (k - 1)
V <- 1 - 1 / k
VCOV_a <- matrix(r * V, k, k)
diag(VCOV_a) <- V
wts <- c(1 - 1 / k, rep(-1 / k, k - 1))
scale_a <- sqrt(wts %*% VCOV_a %*% wts)


# Empirical
set.seed(444)
contr <- contr.orthonorm(k)
coefs <- replicate(k - 1, {
  rnorm(4e3, mean = 0, sd = 1) # sample some priors ~Norm(0, 3.12)
})

means <- t(contr %*% t(coefs)) # conver contrasts and coefs to means

VCOV_e <- cov(means)
scale_e <- apply(means, 2, sd)

# Compare:
VCOV_a
#>      [,1] [,2] [,3] [,4] [,5]
#> [1,]  0.8 -0.2 -0.2 -0.2 -0.2
#> [2,] -0.2  0.8 -0.2 -0.2 -0.2
#> [3,] -0.2 -0.2  0.8 -0.2 -0.2
#> [4,] -0.2 -0.2 -0.2  0.8 -0.2
#> [5,] -0.2 -0.2 -0.2 -0.2  0.8
VCOV_e
#>            [,1]       [,2]       [,3]       [,4]       [,5]
#> [1,]  0.8107491 -0.1938427 -0.1927068 -0.1922509 -0.2319488
#> [2,] -0.1938427  0.8169599 -0.2141874 -0.2084857 -0.2004442
#> [3,] -0.1927068 -0.2141874  0.8157957 -0.2157517 -0.1931498
#> [4,] -0.1922509 -0.2084857 -0.2157517  0.8023770 -0.1858887
#> [5,] -0.2319488 -0.2004442 -0.1931498 -0.1858887  0.8114315

scale_a
#>           [,1]
#> [1,] 0.8944272
scale_e
#> [1] 0.9004161 0.9038584 0.9032141 0.8957550 0.9007949
```

## Test

``` r
contr.equalprior <- bayestestR::contr.orthonorm

contr.equalprior_pairs <- function (n, contrasts = TRUE, sparse = FALSE) {
  contr <- contr.equalprior(n, contrasts, sparse) / sqrt(2)
}

contr.equalprior_deviation <- function (n, contrasts = TRUE, sparse = FALSE) {
  contr <- contr.equalprior(n, contrasts, sparse)
  k <- nrow(contr)
  
  r <- -1 / (k - 1)
  V <- 1 - 1 / k
  VCOV <- matrix(r * V, k, k)
  diag(VCOV) <- V
  wts <- c(1 - 1 / k, rep(-1 / k, k - 1))
  scale <- c(sqrt(wts %*% VCOV %*% wts))
  
  contr / scale
}

## Pairs
k <- 3

contr <- contr.equalprior_pairs(k)
coefs <- replicate(k - 1, {
  rnorm(4e3, mean = 0, sd = 0.14) # sample some priors ~Norm(0, 0.14)
})

means <- t(contr %*% t(coefs)) # conver contrasts and coefs to means

# Should be ~0.14
c(sd(means[,1] - means[,2]),
  sd(means[,1] - means[,3]),
  sd(means[,2] - means[,3]))
#> [1] 0.1443596 0.1404179 0.1415690


## Dev
k <- 4

contr <- contr.equalprior_deviation(k)
coefs <- replicate(k - 1, {
  rnorm(4e3, mean = 0, sd = 1.48) # sample some priors ~Norm(0, 1.48)
})

means <- t(contr %*% t(coefs)) # conver contrasts and coefs to means

# Should be ~1.48
apply(means, 2, sd)
#> [1] 1.479879 1.498521 1.485856 1.457733
```

<sup>Created on 2022-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
