### ISSUE TITLE
Support `posterior::rvar()` objects

### ISSUE THREAD

**Issue by bwiernik** [easystats/bayestestR#569]
`rvar` class objects are really convenient for working with posteriors. We should support them in our functions.

That can be as easy as:

```r
p_direction.rvar <- function(x, ...) {
  p_direction(attr(x, "draws"))
}
```

**Comment by mattansb** [comment]
Supposedly this support was added in #518 (#460)?

**Comment by bwiernik** [comment]
Looks like that added methods for "draws" but not "rvar" classes
