### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#57]
I have revised the docs slightly in this commit: https://github.com/easystats/bayestestR/commit/856cd255610203f50df991a2de8d03de93c955cb

1) I changed _Value or vector of HDI probability_ to _alue or vector of probability of the interval_ as we inherits the docs from `hdi()` also in `ci()`, so this is more general.

2) In `ci()`. I removed _For Bayesian Credible Intervals, CIs are often computed by the hdi method._ I'm not sure if HDI's are really more often computed than equal-tailed credible intervals, so unless we don't have a proof for this statement, we may better remove it.

**Comment by DominiqueMakowski** [comment]
totally agreed :)
