### ISSUE TITLE
Example broken because data moved

### ISSUE THREAD

**Issue by etiennebacher** [easystats/bayestestR#578]
Trying to fix https://github.com/easystats/easystats/issues/326, it turns out the data used in the following example is not accessible anymore and I can't find it in another place online.

https://github.com/easystats/bayestestR/blob/1b66d6faabc880adcba9b5b2becbc3354c8c3368/R/bayesfactor_restricted.R#L88-L89

Does someone know if this data can be found elsewhere (and if so can this person put a copy in [easystats/circus](https://github.com/easystats/circus))? Otherwise, should this example be removed?

**Comment by IndrajeetPatil** [comment]
cc @strengejacke, @DominiqueMakowski, @mattansb

**Comment by strengejacke** [comment]
Can't find it after a quick search, so let's remove it?

**Comment by mattansb** [comment]
I'll try and find it, and if I can't I'll replace it with another example (:

**Comment by mattansb** [comment]
Hey @richarddmorey, would you be willing to share the `disgust_example` dataset, as seen here https://www.r-bloggers.com/2015/01/multiple-comparisons-with-bayesfactor-part-1/?

**Comment by richarddmorey** [comment]
Sure - it got broken when my website got hacked. I put it in a gist which will be more stable: https://gist.github.com/richarddmorey/494a3cfa4c9871bc49a7503226efdc9e

**Comment by mattansb** [comment]
Thanks! I'm assuming this is simulated data?

**Comment by richarddmorey** [comment]
Yes, it is simulated. You can do what you like with it, no obligations.
