### ISSUE TITLE
Check if website is available

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#585]
Currently, we have failing tests on CRAN
https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/bayestestR-00check.html

due to ` Service Unavailable (HTTP 503).`. Is there a way to check whether the URL is working? @IndrajeetPatil ?

**Comment by IndrajeetPatil** [comment]
This is the same issue as: https://github.com/easystats/easystats/issues/322

I have already made a feature request to catch such failures early-on: https://github.com/r-lib/actions/issues/658

**Comment by IndrajeetPatil** [comment]
Closed in https://github.com/easystats/bayestestR/commit/2e6aa8054450ca22ae0f9cd9826f4f9fdb601b97
