### ISSUE TITLE
Fatal error: length > 1 in coercion to logical

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/bayestestR#588]
I am not sure which one but, as seen in [the failure log](https://github.com/easystats/bayestestR/actions/runs/3977550561/jobs/6818780579), one of the conditional expressions here is producing a boolean vector of length 11 instead of 1:

https://github.com/easystats/bayestestR/blob/fce0baa7ee20890a997c1fb68782dbf351d82add/R/rope_range.R#L126-L162

**Comment by strengejacke** [comment]
I just revisited this issue, but cannot reproduce nor debug. Checks are now running on latest insight, let's see if this issue still persists.

**Comment by strengejacke** [comment]
For _insight_, this example does not produce unexpected output, I added a test [here](https://github.com/easystats/insight/commit/5283f8d292d8a778341249da17f7e657b41c1f11).

**Comment by strengejacke** [comment]
This must have been a scoping issue. It works interactively, and it now works where I have added a `source` argument to `get_response()`. Retrieving the data from the model frame (the former default behaviour in _insight_) now resolves this issue.
