### ISSUE TITLE
bayestestR broken after revising `pd()`.

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#619]
This PR wasn't ready, and breaks parts of the code, e.g.

``` r
library(bayestestR)
x <- distribution_normal(4000)

describe_posterior(
  x,
  centrality = "all",
  dispersion = TRUE,
  test = "all",
  ci = 0.89,
  verbose = FALSE
)
#> Error in fix.by(by.y, y): 'by' must specify a uniquely valid column
```

<sup>Created on 2023-07-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Because those functions expect numerics instead of data frames for `pd()`, I guess.

_Originally posted by @strengejacke in https://github.com/easystats/bayestestR/issues/618#issuecomment-1658052172_

**Comment by DominiqueMakowski** [comment]
@mattansb would adding `as.numeric()` be sufficient here?

**Comment by mattansb** [comment]
I have no idea how describe posterior does all the merging. I think pd and p-map already have a as.numeric method.

**Comment by DominiqueMakowski** [comment]
I'm on it but it's a weird error

**Comment by DominiqueMakowski** [comment]
```r
describe_posterior(x, test = "p_map")
```
```
Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column
7.
stop(ngettext(sum(bad), "'by' must specify a uniquely valid column",
"'by' must specify uniquely valid columns"), domain = NA)
6.
fix.by(by.y, y)
5.
merge.data.frame(out, test_pmap, by = merge_by, all = TRUE)
4.
merge(out, test_pmap, by = merge_by, all = TRUE) at describe_posterior.R#474
3.
.describe_posterior(posteriors, centrality = centrality, dispersion = dispersion,
ci = ci, ci_method = ci_method, test = test, rope_range = rope_range,
rope_ci = rope_ci, keep_iterations = keep_iterations, bf_prior = bf_prior,
BF = BF, ...) at describe_posterior.R#540
2.
describe_posterior.double(x, verbose = FALSE, test = "p_map") at describe_posterior.R#109
1.
describe_posterior(x, verbose = FALSE, test = "p_map")
```

it also fails with other tests 🤔 🤔

**Comment by DominiqueMakowski** [comment]
![image](https://github.com/easystats/bayestestR/assets/8875533/743e6413-7778-488a-af5c-b09f40cd2307)

It happens here, we're trying to merge these dfs by the cols but there is no `Parameter` columns... is it that last PR that removed it??

**Comment by strengejacke** [comment]
This code is no longer run, because `p_map()` now always returns a data frame:

https://github.com/easystats/bayestestR/blob/dc049fd22169cade385688cac417bbe732376860/R/describe_posterior.R#L243-L249

Since the structure of the returned data frame for numeric input in `p_map()` differs from those in models, it now fails.

**Comment by DominiqueMakowski** [comment]
Do you think we should re-add a Parameter argument to the output of p_dir and p_map or fix it at the merging level?

I should have checked the tests more thoroughly 🤕  (and *not* listen to Mattan's mellow voice softly whispering *merge it* in my ear)

**Comment by strengejacke** [comment]
I think the easiest thing would be that the numeric method returns an additional column named `Posterior`, like what we do in `describe_posterior()`, i.e. something like

```r
   data.frame( 
     Parameter = "Posterior", 
     p_map = pmap, 
     stringsAsFactors = FALSE 
   ) 
```

**Comment by mattansb** [comment]
Okay, I can fix that.

**Comment by mattansb** [comment]
Okay, I've changed the `.numeric()` method for `p_map()`, `p_direction()`, `map_estimate()` and `p_significance()`, and `describe_posterior()` now works:

```{r}
describe_posterior(x)
#> Warning: Could not estimate a good default ROPE range. Using 'c(-0.1, 0.1)'.Summary of Posterior Distribution
#> 
#> Parameter | Median |        95% CI |     pd |          ROPE | % in ROPE
#> -----------------------------------------------------------------------
#> Posterior |   1.04 | [-0.91, 2.92] | 86.00% | [-0.10, 0.10] |     5.89%
```

However, this did change the printing method - 

Before:

```{r}
library(bayestestR)

x <- rnorm(1000, 1)
pd(x)
#> Probability of Direction: 86.00%
```

After:


```{r}
pd(x)
#> Probability of Direction
#> 
#> Parameter |     pd
#> ------------------
#> Posterior | 86.00%
```

I don't know if you want to preserve the previous behavior or not...

**Comment by DominiqueMakowski** [comment]
That's okay

**Comment by strengejacke** [comment]
Can this be closed?
