### ISSUE TITLE
Docs for frequentist CI and equivalence test

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#62]
It seems that the extension of `ci` and `equivalence_test` in parameters works, although documenting their methods separately is not straightforward. Users will probably be shown bayestestR's documentation instead of the one specific to frequentist models.

Thus, I think we will have to add a link to the parameters' website "for frequentist models, you can find the documentation here" and/or directly a small paragraph in details documenting the method for frequentist models.

**Comment by strengejacke** [comment]
Ok, sounds good!
