### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#64]
it would be good if we managed to improve testing coverage to > 90% before submitting to JOSS or somewhere else, which might necessitate to try making testing work for brms models.

**Comment by DominiqueMakowski** [comment]
After some trials/errors, it seems like brms tests pass on OSX (but not on linux (otherwise it passes on both)), which is good

**Comment by DominiqueMakowski** [comment]
`describe_posterior` doesn't work [(see here)](https://github.com/easystats/bayestestR/blob/master/tests/testthat/test-describe_posterior.R#L34)  if BFs are regquested. @mattansb What would you recommend, do not allow for now the computation of BFs for brms models?

**Comment by mattansb** [comment]
I suspect that this fails because `brms_mixed_1` uses default priors, which `brms` does not sample priors from. I think if you changed that test to `brms_mixed_6` (currently the only `brmsfit` object in `circus` to have custom priors) it should work - this is the one I use [here](https://github.com/easystats/bayestestR/blob/master/tests/testthat/test-bayesfactor.R#L33).

Let me know if this does not resolve this problem.

**Comment by DominiqueMakowski** [comment]
But is there a way to avoid the error? Or maybe throw a custom error message like "Bayes Factors cannot be computed due to the absence of priors explicit specification. Please re-fit the model and explicitly enter the priors"?

**Comment by mattansb** [comment]
Do we need to? `brms` provides the following error:
``` r
library(bayestestR)
library(brms)

x <- insight::download_model("brms_mixed_1")
bayesfactor_savagedickey(x)
#> Error: Sampling from priors is not possible as some parameters have no proper priors. Error occured for class 'b'.
```

**Comment by DominiqueMakowski** [comment]
``` r
library(bayestestR)
library(brms)

x <- insight::download_model("brms_mixed_1")
describe_posterior(x, test="all")
#> Error: Sampling from priors is not possible as some parameters have no proper priors. Error occured for class 'b'.
```

<sup>Created on 2019-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

When the error is thrown in `describe_posterior`, it becomes rather unclear for the user that the errors is related to BFs (and that he can avoid it by removing BFs from the indices list). I say either we change this message to make it more explicit in BFsd, or we can put the BFsd extraction in `describe_posterior` in a `try` block, but this seems clunkier than the first option. What do you say?

**Comment by mattansb** [comment]
I would change this in 
```R
```

**Comment by mattansb** [comment]
I would change this in `describe_posterior`, as when this error pops up in sdBF it is clear what the issue is.

How's this:
```R
test_bf <- try(bayesfactor_savagedickey(x, prior = bf_prior, ...), silent = TRUE)
if (is(test_bf,"try-error")) {
  if (grepl('proper priors', test_bf)) {
    stop("Cannot compute BF for 'brmsfit' models fit with default priors. See '?bayesfactor_savagedickey'")
  } else {
    stop(test_bf)
  }
}
```

**Comment by DominiqueMakowski** [comment]
I am not sure that it is easier than replacing the message in BFsd (TBH I do not find the brms message crystal clear: "some parameters do not have *proper* priors" might be quite vague for beginners). But if you think that's the best option, I'll update `describe_posterior`.

**Comment by mattansb** [comment]
Hmm perhaps you're right. I'll add this to sdBF.

**Comment by DominiqueMakowski** [comment]
I'll close this, I think it's a general easystats issue ^^

If I ever give an "intro github course / developing in R" course, I'll suggest improving easystats testing as a hands-on exercice 😅
