### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#641]
@DominiqueMakowski I think we can submit a new version to CRAN, no?
Last update is quite some time ago, and we have made several fixes in between.

**Comment by strengejacke** [comment]
@DominiqueMakowski What are the results from win builder?

**Comment by strengejacke** [comment]
@DominiqueMakowski ping

**Comment by DominiqueMakowski** [comment]
builder: 

- https://win-builder.r-project.org/3wH7YidlRX2n/00check.log

> Mismatches for apparent methods not registered:
.clean_priors_and_posteriors:
  function(posterior, prior, verbose, ...)
.clean_priors_and_posteriors.emm_list:
  function(posterior, prior, verbose)

> .clean_priors_and_posteriors:
  function(posterior, prior, verbose, ...)
.clean_priors_and_posteriors.emmGrid:
  function(posterior, prior, verbose)

> Missing link or links in Rd file 'p_direction.Rd':
  'pd_tp_p' 'density estimation

**Comment by strengejacke** [comment]
Ok, should be fixed in https://github.com/easystats/bayestestR/commit/ffd511fd65757685f63fe62500e8405725e968ff

**Comment by strengejacke** [comment]
@mattansb When fixing this, I realized that the `.clean_priors_and_posteriors()` is called from `bayesfactor_parameters.stanreg()` with a `parameters` argument, but that argument seems to have no effect in `.clean_priors_and_posteriors.stanreg()`?

**Comment by strengejacke** [comment]
I think you can submit.

**Comment by mattansb** [comment]
@strengejacke Oops, fixing that here #642

**Comment by DominiqueMakowski** [comment]
submitted (with bumped version)
gosh it feels like haven't done that for years lol

**Comment by DominiqueMakowski** [comment]
They are not:


   Unknown, possibly misspelled, fields in DESCRIPTION:
     'Remotes'

Please drop that field.

Flavor: r-devel-windows-x86_64
Check: examples, Result: NOTE
   Examples with CPU (user + system) or elapsed time > 10s
                          user system elapsed
   bayesfactor_parameters 5.17   0.14   55.17

Please reduce each example to less than 5 sec.


--- 

This 5 sec rule is starting to be a bit annoying

**Comment by strengejacke** [comment]
I think these issues should be fixed on main.

**Comment by DominiqueMakowski** [comment]
It should be on CRAN
