### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#65]
Thanks,

we see:
   Size of tarball: 5048980 bytes

Not more than 5 MB for a CRAN package, please.

If there are any references describing the methods in your package, 
please add these in the Description field of your DESCRIPTION file in 
the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
with no space after 'doi:', 'arXiv:' and angle brackets for auto-linking.

Please fix and resubmit.

**Comment by DominiqueMakowski** [comment]
It says [here](https://cran.r-project.org/web/packages/submission_checklist.html):

- Relevant citations should be included in the description. These should be in author-year style, preferably followed by an identifier such as DOI, arXiv id, or ISBN for published materials.
- DOIs should be enclosed in angle brackets, and formatted as \<doi:10.prefix/suffix\>. Example: Sugihara (1994) \<doi:10.1098/rsta.1994.0106\>.

I am not sure if that applies to in text citations or references section. Any suggestions?

**Comment by strengejacke** [comment]
According the size: you need to remove all logos from the man folder.

Have you checked the package with winbuilder before submission?

**Comment by strengejacke** [comment]
For citation, maybe here? 
https://cran.r-project.org/web/packages/bayesammi/index.html

**Comment by strengejacke** [comment]
And remember to check the tarball here before submission:
https://win-builder.r-project.org

**Comment by DominiqueMakowski** [comment]
Yep but we have no references in DESCRIPTION...

winbuilder says everything ok but:

```
* checking DESCRIPTION meta-information ... NOTE
Author field differs from that derived from Authors@R
  Author:    'Dominique Makowski [aut, cre] (<https://orcid.org/0000-0001-5375-9967>), Daniel L�decke [aut] (<https://orcid.org/0000-0002-8895-3206>)'
  Authors@R: 'Dominique Makowski [aut, cre] (0000-0001-5375-9967), Daniel L�decke [aut] (0000-0002-8895-3206)'
```

However it is pretty much the same as for insight mutatis mutandis 😕

**Comment by strengejacke** [comment]
I just saw, in the tar-ball, the largest file is [this vignette](https://easystats.github.io/bayestestR/articles/indicesExistenceComparison.html). After removing the logos, the package is ~1.5 MB, which is ok. We could only reduce the image size (figure width/height) if it's still too large.

According the description: I think they asked for citing / adding a refrence to the concepts:

> Maximum A Posteriori (MAP), measures of dispersion (Highest Density Interval - HDI) and indices used for null-hypothesis testing (such as ROPE percentage and pd).

It would be great if all happen to be in just one publication, maybe Kruschke 2015?

**Comment by strengejacke** [comment]
See in my pkg-example:
> Performs Bayesian estimation of the additive main effects and multiplicative interaction (AMMI) model. The method is explained in Crossa, J., Perez-Elizalde, S., Jarquin, D., Cotes, J.M., Viele, K., Liu, G. and Cornelius, P.L. (2011) (<doi:10.2135/cropsci2010.06.0343>).

I _think_ (but not sure) that they meant this.

**Comment by DominiqueMakowski** [comment]
Let's try adding Kruschke. Maybe the author thing is a false positive

**Comment by DominiqueMakowski** [comment]
You meant Kruschke, John K., and Wolf Vanpaemel. "Bayesian estimation in hierarchical models." The Oxford handbook of computational and mathematical psychology (2015): 279-299. ?

**Comment by strengejacke** [comment]
Sorry, no, this one:
https://www.amazon.de/Doing-Bayesian-Data-Analysis-Tutorial/dp/0124058884

which is very comprehensive.

**Comment by strengejacke** [comment]
McElreath (Statistical Rethinking) says something about MAP, but not ROPE. Kruschke says something to ROPE, but not MAP (at least not easily findable)... :-D

**Comment by DominiqueMakowski** [comment]
Let's add Kruschke and try

**Comment by DominiqueMakowski** [comment]
"Thanks,
on its way to CRAN."

🎉

**Comment by strengejacke** [comment]
Nice! Then maybe we should revert the paranthesis changes I made to the description, and just update the DOI and year.

**Comment by DominiqueMakowski** [comment]
Na, I guess we can keep all the changes (maybe bump to 0.1.1). From now on, I must also force myself to update the changelog :)
