### ISSUE TITLE
Fix CRAN note

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/bayestestR#658]
cf. https://cloud.r-project.org/web/checks/check_results_bayestestR.html

```
Version: 0.14.0
Check: Rd cross-references
Result: WARN 
  Missing link or links in documentation object 'estimate_density.Rd':
    ‘[datawizard:extract_column_names]{datawizard::extract_column_names()}
```

**Comment by IndrajeetPatil** [comment]
I see nothing wrong here; why this note?

**Comment by strengejacke** [comment]
That function exists since datawizard 0.11.0 (https://github.com/easystats/datawizard/commit/139c61aee554cbafe347b1f186fc1cd1b9261837), which is not available for mac os x old-rel.
