### ISSUE TITLE
Consistent structure for HDI_area attribute in rope()

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#69]
@strengejacke I am having issues for ROPE support (see bottom of README for example). It seems the `rope` object based on models does contain all the information regarding `HDI_area`. It has (in attributes) only one value for it, instead of several for parameters and levels of ci. Is it possible to address it here, or modify the thing in bayestestR?

**Comment by DominiqueMakowski** [comment]
I also thought, but somehow I think it got aggregated for models into a matrix of vectors of some sort. I am sure it's a matter of single square brackets instead of double somewhere or something :)

**Comment by strengejacke** [comment]
Here's the code for extracting the HDI_area for `equivalence_test()`'
https://github.com/easystats/bayestestR/blob/master/R/equivalence_test.R#L92

**Comment by DominiqueMakowski** [comment]
I wasn't clear, sorry. The point is that this code, for models, returns not enough values. It doesn't return the values of HDI low and high for all posteriors. 

``` r
library(bayestestR)
junk <- capture.output(data <- rstanarm::stan_glm(Sepal.Length ~ Petal.Width * Species, data=iris))
x <- rope(data)
sapply(attr(x, "HDI_area", exact = TRUE), function(i) i[1])
#> [1] 4.523453
sapply(attr(x, "HDI_area", exact = TRUE), function(i) i[2])
#> [1] 5.050646
x <- rope(data, ci=c(0.8, 0.9))
sapply(attr(x, "HDI_area", exact = TRUE), function(i) i[1])
#> [1] 4.583047 4.523453
sapply(attr(x, "HDI_area", exact = TRUE), function(i) i[2])
#> [1] 4.999028 5.050646
```

<sup>Created on 2019-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

It works alright when single posteriors are passed:
``` r
library(bayestestR)

data <- rnorm(1000, 1)
x <- rope(data)
sapply(attr(x, "HDI_area", exact = TRUE), function(i) i[1])
#> [1] -0.6601529
sapply(attr(x, "HDI_area", exact = TRUE), function(i) i[2])
#> [1] 2.54503
attributes(x)$HDI_area
#> [[1]]
#> [1] -0.6601529  2.5450297
x <- rope(data, ci=c(0.8, 0.9))
sapply(attr(x, "HDI_area", exact = TRUE), function(i) i[1])
#> [1] -0.2680050 -0.6601529
sapply(attr(x, "HDI_area", exact = TRUE), function(i) i[2])
#> [1] 2.21893 2.54503
```

<sup>Created on 2019-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

anyway it's not a *major* problem since we can dig in and adapt the extraction depending on what has been passed, but it would be cool if the design of the attribute was constant. 

For example, an easy workaround is to replace the current HDI_area content by the dataframe created by `hdi`.

**Comment by strengejacke** [comment]
Quite relieved that it didn't affect any functions, so `equivalence_test()` is still correct, though.

**Comment by strengejacke** [comment]
The attribute still differs between _models_ and vectors, because models have an additional `CI` column now. But I think this is necessary.

**Comment by strengejacke** [comment]
btw, how should we address this in the news? as "minor fixes", or completely ignore it for the news? it has no effect for users, maybe a bit for developers.

**Comment by DominiqueMakowski** [comment]
minor changes seems appropriate :)

**Comment by DominiqueMakowski** [comment]
Altough brms test fails for me 😮 

```
testthat::expect_is(rope(model), "data.frame")
```

**Comment by strengejacke** [comment]
yes, no good idea to have duplicate code and only fix it at one place, not the other... ;-)
Should work now.

**Comment by DominiqueMakowski** [comment]
``` r
model <- rstanarm::stan_glm(mpg ~ wt + cyl, data = mtcars)
attributes(rope(model))$HDI_area
#> $`(Intercept)`
#>     CI  HDI_low HDI_high
#> 1 0.90 36.60966 42.66055
#> 2 0.95 36.12163 43.45867
#> 
#> $wt
#>     CI   HDI_low  HDI_high
#> 1 0.90 -4.432082 -1.776227
#> 2 0.95 -4.668768 -1.481225
#> 
#> $cyl
#>     CI   HDI_low   HDI_high
#> 1 0.90 -2.254774 -0.8010249
#> 2 0.95 -2.396010 -0.6578996
```

Since we return one or multiple dataframes for models (which I like), could we also return such dataframe for the cases where a vector is passed to ROPE?

``` r
library(bayestestR)
attributes(rope(x = rnorm(1000, 1, 1)))$HDI_area
#> [[1]]
#> [1] -0.5071979  2.7443272
attributes(rope(x = rnorm(1000, 1, 1), ci = c(.90, .95)))$HDI_area
#> [[1]]
#> [1] -0.8034466  2.5204936
#> 
#> [[2]]
#> [1] -0.8451218  2.9656530
```

So the output would like:
``` r
attributes(rope(x = rnorm(1000, 1, 1), ci = c(.90, .95)))$HDI_area
#>     CI  HDI_low HDI_high
#> 1 0.90 36.60966 42.66055
#> 2 0.95 36.12163 43.45867
```
Sorry to bother with this, I would gladly change it myself but I am afraid of breaking everything since the attribute code is still not perfectly clear to me (I am studying it tho :)

**Comment by strengejacke** [comment]
> since the attribute code is still not perfectly clear to me

Neither to me. :-D

This change will require some additional code-revision, since it would affect how attributes then will be handled for models (like `rope.stanreg()`), where these functions all call `rope.numeric()` when iterating over all parameter vectors of the posterior.
