### ISSUE TITLE
class class class

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#72]
``` r
library(bayestestR)
library(insight)
m <- insight::download_model("stanreg_glm_5")

class(hdi(m))
#> [1] "hdi"        "hdi"        "hdi"        "data.frame"

class(ci(m, ci = c(.5, .8)))
#> [1] "ci"         "data.frame"

class(rope(m))
#> [1] "rope"       "data.frame"
```

<sup>Created on 2019-04-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Have found this only for `hdi()` yet. We should make sure that class-attributes simply are `unique()`.

**Comment by DominiqueMakowski** [comment]
oh definitely. How did it happen tho?

**Comment by strengejacke** [comment]
We put some of the code to calculate intervals into a helper-function after we have implemented `ci()`. This helper function already sets the attribute, but we also set the attributes in the hdi-functions, as well as the hdi.numeric (which is called for model objects), so we had it three times...
