### ISSUE TITLE
Unify printing methods

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#74]
Would be nice to unify the printing output up to the standard of ROPE/equivalence test.

- [x] `p_direction`: dataframe-like output needed
- [ ] `p_map`: everything needed

**Comment by DominiqueMakowski** [comment]
I wonder if the print methods could be easily unified by the creation of single internal function that would display the blue title and the dataframe, authorizing additional arguments to display a footer (e.g. for the Bayes Factors)?

**Comment by strengejacke** [comment]
That is a good thing, I think. Maybe we can think of a unified "design", currently some print method are very strongly influenced by my personal preferences ;-)

**Comment by DominiqueMakowski** [comment]
I like your current design, with the title in blue and the nice dataframe-like organization. I tried to implement the latter for p_direction, but didn't succeed. Hence the idea of a unified internal :)

**Comment by strengejacke** [comment]
Somewhat related to this are unified column names in return values. I guess we have this in most cases, but probably we could "collect" function in a tabular overiew and check that column names are unified according spelling / case etc. I don't want `hdi(model)$Parameter` and `ci(model)$parameters`.

**Comment by DominiqueMakowski** [comment]
definitely

**Comment by strengejacke** [comment]
> I wonder if the print methods could be easily unified by the creation of single internal function that would display the blue title and the dataframe, authorizing additional arguments to display a footer (e.g. for the Bayes Factors)?

I can imagine that once we have `clean_parameters()` officially available:

1) we can take any output from the functions (that use either `get_parameters()` or `find_parameters()`, and use exactly those parameter names)
2) `merge()` the result from `clean_parameters()` to this output (maybe we have to store this information as attribute, not sure the model is always available for `clean_parameters()`), _only preserving those columns from `clean_parameters()` where parameter names match the output_.
3) then we process the available columns and rows from `clean_parameters()` in a standardized way. we then just need to look for the parameter name, take the data for these row(s) from the output from rope(), hdi() etc. and print it.

If column names from hdi(), rope() have a consistent pattern, and all functions have at least one column with the same name (`Parameter`) that contains the parameters, it should be easy to have just _one_ print-method for most functions.

**Comment by DominiqueMakowski** [comment]
Yes, although there is an exception  when the object is a single vector, in which case there is no `Parameter` column. This can be easily bypassed (`describe_posterior`) does it by adding a `Parameter = "Posterior"` column.

**Comment by strengejacke** [comment]
Here we have associated all values from `hdi()` with the components / parts of the model, so all the print()-function needs to do is to process this data frame, columns "effects", "component" etc. and do some filtering for nice printing all of the parts.

``` r
library(bayestestR)
library(insight)

model <- download_model("brms_zi_3")
result <- hdi(model, effects = "all", component = "all")
cp <- clean_parameters(model)

# haha!
colnames(cp)[1] <- "Parameter"

merge(result, cp, by = "Parameter")
#>                     Parameter CI      CI_low     CI_high   Component  Group effects     component     group cleaned_parameter
#> 1                    b_camper 90  0.58749391  0.86409145 conditional  fixed   fixed   conditional                      camper
#> 2                     b_child 90 -1.32542923 -0.97967405 conditional  fixed   fixed   conditional                       child
#> 3                 b_Intercept 90 -0.06841519  2.32080133 conditional  fixed   fixed   conditional                 (Intercept)
#> 4                 b_zi_camper 90 -1.34375287 -0.21606710          zi  fixed   fixed zero_inflated                      camper
#> 5                  b_zi_child 90  1.43864338  2.47840386          zi  fixed   fixed zero_inflated                       child
#> 6              b_zi_Intercept 90 -1.93391715  0.24177981          zi  fixed   fixed zero_inflated                 (Intercept)
#> 7      r_persons.1.Intercept. 90 -2.69776252 -0.03875132 conditional random  random   conditional persons.1       (Intercept)
#> 8      r_persons.2.Intercept. 90 -1.46855516  1.02132175 conditional random  random   conditional persons.2       (Intercept)
#> 9      r_persons.3.Intercept. 90 -0.61462281  1.77170094 conditional random  random   conditional persons.3       (Intercept)
#> 10     r_persons.4.Intercept. 90  0.27438293  2.64117332 conditional random  random   conditional persons.4       (Intercept)
#> 11 r_persons__zi.1.Intercept. 90  0.30853992  2.65916269          zi random  random zero_inflated persons.1       (Intercept)
#> 12 r_persons__zi.2.Intercept. 90 -0.72615999  1.56284623          zi random  random zero_inflated persons.2       (Intercept)
#> 13 r_persons__zi.3.Intercept. 90 -1.29963950  1.04199945          zi random  random zero_inflated persons.3       (Intercept)
#> 14 r_persons__zi.4.Intercept. 90 -2.50755248 -0.06091139          zi random  random zero_inflated persons.4       (Intercept)
```

<sup>Created on 2019-05-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
So we would have one long printing function that the returned object from each function should work with?
I think my personal preference would be to have small, easy to maintain printing functions for each object type... (Which is what we have now?)

**Comment by DominiqueMakowski** [comment]
> So we would have one long printing function

It doesn't to be that long... And one unified processing is necessary as there are many caveats, so one flexible and consistent way of dealing with it sounds like a plus

> So all the print()-function needs to do is to process this data frame, columns "effects", "component" etc. and do some filtering for nice printing all of the parts.

... Ok I'll work on the `bayesfactor()` function 😅

**Comment by strengejacke** [comment]
Ok, I have implemented the new `insight::print_parameters()` in `sjstats::tidy_stan()`. Here's an example. Usually, it's pretty straightforward to print, except if you need some special preparation - in this case, I print multiple HDI's side-by-side (this is something we could think of doing in bayestestR as well by default?):

``` r
library(sjstats)
library(easystats)
m <- download_model("brms_zi_3")
tidy_stan(m, prob = c(.5, .89, .95))
#> 
#> Summary Statistics of Stan-Model
#> 
#> # Fixed effects (conditional) 
#> 
#>    Parameter Estimate Std.Error      HDI(50%)      HDI(89%)      HDI(95%) ESS Rhat MCSE
#>  (Intercept)     1.32      0.75 [ 1.19  2.11] [ 0.05  2.27] [-0.59  2.95]  78 1.00 0.10
#>        child    -1.16      0.11 [-1.25 -1.11] [-1.32 -0.98] [-1.40 -0.97] 172 1.00 0.01
#>       camper     0.73      0.09 [ 0.64  0.76] [ 0.59  0.86] [ 0.59  0.92] 233 1.00 0.01
#> 
#> 
#> # Fixed effects (zero-inflated) 
#> 
#>    Parameter Estimate Std.Error      HDI(50%)      HDI(89%)      HDI(95%) ESS Rhat MCSE
#>  (Intercept)    -0.78      0.63 [-1.39 -0.57] [-1.89  0.22] [-2.31  0.61]  92 1.00 0.08
#>        child     1.89      0.29 [ 1.72  2.10] [ 1.30  2.30] [ 1.25  2.48]  72 1.01 0.04
#>       camper    -0.84      0.30 [-1.05 -0.64] [-1.34 -0.23] [-1.50 -0.23] 182 1.00 0.04
```

<sup>Created on 2019-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And by the way, `tidy_stan()` might be something we could re-implement in bayestestR as well, any thoughts?

**Comment by DominiqueMakowski** [comment]
> n this case, I print multiple HDI's side-by-side (this is something we could think of doing in bayestestR as well by default?):

definitely

> tidy_stan() 

Isn't it the whole purpose of `parameters`?

**Comment by strengejacke** [comment]
> Isn't it the whole purpose of parameters?

True, now that you're mentioning it... I could start working on such a function, as the basics are now there in _insight_.

**Comment by DominiqueMakowski** [comment]
I meant, isn't it specifically what `model_parameters` is for? returning "tidy" (the nice prining has to be added though) summaries for all models

``` r
knitr::kable(parameters::model_parameters(insight::download_model("stanreg_glm_1")), digits=2)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">pd</th>
<th style="text-align: right;">ROPE_Percentage</th>
<th style="text-align: right;">ESS</th>
<th style="text-align: right;">Rhat</th>
<th style="text-align: left;">Prior_Distribution</th>
<th style="text-align: right;">Prior_Location</th>
<th style="text-align: right;">Prior_Scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">5.75</td>
<td style="text-align: right;">2.44</td>
<td style="text-align: right;">9.44</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2419</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">normal</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">10.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">wt</td>
<td style="text-align: right;">-1.93</td>
<td style="text-align: right;">-3.04</td>
<td style="text-align: right;">-0.82</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2323</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">normal</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.56</td>
</tr>
</tbody>
</table>

<sup>Created on 2019-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


It also supports standardization and parameters selection (the dev branch).

**Comment by DominiqueMakowski** [comment]
Can close this, as the main point has been addressed. For describe_posterior and the more comprehensive methods, we can discuss that on the related issue on parameters.
