### ISSUE TITLE
how to plot the figure that you mentioned in the example?

### ISSUE THREAD

**Issue by lixingguang** [easystats/bayestestR#75]
Could you please tell me how to plot the figures that showed in the example, these are very nice, thanks.

**Comment by DominiqueMakowski** [comment]
Hey, if you're referring to the plots in the README (the yellow distributions), the code to generate them can be found [here](https://github.com/easystats/bayestestR/blob/master/README.Rmd).

**Comment by lixingguang** [comment]
@DominiqueMakowski,thanks. I now find it.:)

**Comment by lixingguang** [comment]
@DominiqueMakowski , do you hear about BEAST software, BEAST is a cross-platform program for Bayesian analysis of molecular sequences using MCMC. It is entirely orientated towards rooted, time-measured phylogenies inferred using strict or relaxed molecular clock models. It can be used as a method of reconstructing phylogenies but is also a framework for testing evolutionary hypotheses without conditioning on a single tree topology. BEAST uses MCMC to average over tree space, so that each tree is weighted proportional to its posterior probability. We include a simple to use user-interface program for setting up standard analyses and a suit of programs for analysing the results. you can find it at http://beast.community/index.html, may be we can have new ideas using your methods to do analysis in my field, thanks.

**Comment by DominiqueMakowski** [comment]
I work in a field quite different from BEAST's target (which acronym is definitely super cool), so I am not sure how bayestestR can be of any help or interest to BEAST. However, if you ever have any ideas, feel free to share them ;)
