### ISSUE TITLE
`equivalence_test()` plot shows error

### ISSUE THREAD

**Issue by PCK1992** [easystats/bayestestR#76]
I ran a Bayesian multilevel model in `brms` and tried to plot the results using the `equivalence_test()` function:

```
library(bayestestR)
x <- equivalence_test(model)
plot(x)
```
and got the following error:
`Error in FUN(X[[i]], ...) : object 'grp' not found`

I then used the function `equi_test` from the `sjstats` package and it worked:
```
library(sjstats)
equi_test(x, rope = c(-0.05, 0.05), plot = TRUE, out = 'plot')
```
which did not give me the error. I wonder if I am doing something wrong or if this might be a bug?

**Comment by strengejacke** [comment]
I assume it's a bug. Do you have a reproducible example?

**Comment by PCK1992** [comment]
Unfortunately not, but I can provide general example of the code I used:

```
library(brms)
model1 <- brm(binary_var ~ continous_var + categorical_car + (1|level1), prior = prior, data = MLM_data, family =  bernoulli(), chains = 4, cores = 4)
```
