### ISSUE TITLE
Add function for Savage-Dickey density ratio Bayes factors

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#77]
Would you consider adding a function for a Savage-Dickey density ratio Bayes factor?

Something like this, perhaps?

````
savage_dickey_BF <- function(xpost,xprior,null = 0,direction = 0){
  if (!require(logspline)) {
    stop('Need logspline to run')
  }
  f_post <- suppressWarnings(logspline(xpost))
  f_prior <- suppressWarnings(logspline(xprior))
  
  d_post <- dlogspline(null,f_post)
  d_prior <- dlogspline(null,f_prior)
  
  norm_post <- norm_prior <- 1
  if (direction < 0) {
    norm_post <- plogspline(null,f_post)
    norm_prior <- plogspline(null,f_prior)
  } else if (direction > 0) {
    norm_post <- 1-plogspline(null,f_post)
    norm_prior <- 1-plogspline(null,f_prior)
  }
  
  (d_post/norm_post)/(d_prior/norm_prior)
}
````

**Comment by strengejacke** [comment]
Do you have any references on this approach / method?

**Comment by DominiqueMakowski** [comment]
I am currently reading [this](https://www.ejwagenmakers.com/2010/WagenmakersEtAlCogPsy2010.pdf) and [this](https://michael-franke.github.io/statistics,/modeling/2017/07/07/BF_computation.html). I wasn't aware of this approach ☺️

**Comment by mattansb** [comment]
Seems like @DominiqueMakowski found the Wagenmakers reference ☺️

**Comment by DominiqueMakowski** [comment]
And also [Heck 2018](https://www.ncbi.nlm.nih.gov/pubmed/30451277)  for a "generalized" version in regards to the strong assumptions of this approach.

It *seems* to me that this index is used more in the context of model performance than parameters (coefficients) testing. Thus, I wonder whether we should add it here or in [performance](https://github.com/easystats/performance) where R2_bayes is currently implemented.

**Comment by mattansb** [comment]
IMO it should be here, as it goes very well with your other [NHST](https://github.com/easystats/bayestestR#null-hypothesis-significance-testing-nhst) functions.

Note also that `brms` uses this method in the `hypothesis` function for testing parameters and parameter-combinations.

**Comment by DominiqueMakowski** [comment]
In order to be consistent with other easystats functions, one of the design options would be to have a general function, for instance, `bayesfactor` (with `bf` as a shortcut) with a `method` argument (that would at first only support `"savage-dickey"`), that would call internal (or external as does `r2_*`) functions specific to each method. 

This could be a nice addition to the package indeed. @mattansb since you had the idea and implementation, would you be interested in being a contributor of the package and adding this feature?

**Comment by strengejacke** [comment]
Short note: I would also put this function into _bayestestR_ as it's too Bayes related, I think.

**Comment by mattansb** [comment]
@DominiqueMakowski sure - how should we proceed?

**Comment by DominiqueMakowski** [comment]
@mattansb Well you could open a pull request with an initial proposition, and then we will work together to refine it if needed :)

**Comment by DominiqueMakowski** [comment]
I would say that we can fairly close this :)
