### ISSUE TITLE
add `BFGrid` and `inclusionBF` from `BFEffects`

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#80]
I think it could be interesting to transfer my [`BFGrid` functions](https://github.com/mattansb/BFEffects/blob/master/R/BF_Grids.R) and their accompanying [`inclusionBF` function](https://github.com/mattansb/BFEffects/blob/master/R/inclusionBF.R) from `BFeffects` into `bayestestR` (I would of course polish them up a bit more, and reduce their discrepancies from other packages, as I see you like to keep dependencies to a minimum).

Thoughts?

**Comment by strengejacke** [comment]
Sounds good! I have no real idea what the functions exactly do, but my impression is that they fit well into the package. I would leave this to Dominique, as he's the maintainer... :-)

**Comment by DominiqueMakowski** [comment]
This could definitely be interesting!
Although I too am not 100% clear about what they do 😅 It would be worth to document these methods a bit more ☺️ Do not hesitate to draft a new PR (we can start by BFgrid as it is the basis if I am not mistaken) and we'll work on that.

However, I think that there is a design decision to be made there (that could be related to the name of BFgrid, which seems to return the BF for models):

From what I've seen from the savage-dickey BF function, which computes the BayesFactor for a posterior distribution, it seems to me that this index could be used to test the parameters of a model. Similarly to ROPE or p_direction. Am I right?

If that's the case, it would make sense to expand this function similarly so that when applied on a model (`bayesfactor(model)`), it computes the Bayes factor for all the parameters of the model.

On the other hand, Bayes factors are also used to test (i.e., compare) whole models. In which case one would expect `bayesfactor(model)` to return a single value corresponding to the BF *of the entire model*.

Thus, I wonder what is the way to go. What are your thoughts?

**Comment by mattansb** [comment]
# BFGrid
`BFGrid` is basically a `data.frame` with some attributes that holds Bayes factors for a bunch of models predicting the same DV. It is similar (and inspired by) how `BayesFactor` computed and displays Bayes factors: when fitting a regression model, some combination of models are fitted, and the output is the BF of all of the models against one of the models.
I have 3 methods that return a `BFGrid` object:
1. For `brms` \ `rstanarm` fitted models, the function takes *a few* models, and using the `bridgesampling` package, returns the BFs for all the models against one of them.
1. For `BayesFactor` object, it just extracts the BFs.
1. For other models (non Bayesian), I use a BIC based approximation ([ref](https://doi.org/10.3758/BF03194105)) to get BFs for all the models against one of them. An example of this method can be seem [here](https://github.com/mattansb/BFEffects#bayes-factors-from-other-model-types), but note that the output is the same of all methods.

Thus each model gets it's own BF, but as always, it is relative to some user-specified other model. i.e., the user can't just fit 1 model.

# inclusionBF
This is a recreation of the `effects` method used in JASP. See comparison [here](https://htmlpreview.github.io/?https://github.com/mattansb/BFEffects/blob/master/vignettes/compare_to_JASP.html).
What this function does is take a `BFGrid` (or `BayesFactor` object) and compute the BF of each effect by comparing the difference between the "average" change from prior posterior probability in models that have this effect and the same change in models the do not have this effect.

I will try and get a PR done this week (maybe next).

**Comment by mattansb** [comment]
My deadline for having these functions imported fully into `bayestestR` is June 10th - that's when I'm teaching Bayesian stats to MA students (a very brief, more practical-R-oriented then theoretical) and would be nice to show 2 packages (`BayesFactor` and `bayestestR`) instead of 3 (+`BFEffects`) 😁

**Comment by strengejacke** [comment]
I think a CRAN release to that date is possible, so we have an official package version for teaching

**Comment by mattansb** [comment]
@strengejacke great!
Also, might want to think of function names. `bayesfactor_models` and `bayesfactor_model_effects` seem long to me? Maybe `comapre_models` and `bayesfactor_effects`?

Also not sure how they would relate to the main `bayesfactor` function as methods (if at all). 

I'm open so suggestions

**Comment by DominiqueMakowski** [comment]
this deadline seems fairly realistic :)

For `BFgrid`, one possibility would be to use the `bayesfactor` method as a name. This would result in the following:

- `bayesfactor.numeric`: would do the savage-dickey method or such on a posterior distribution.
- `bayesfactor.BFBayesFactor`: would extract the BF from the object.
- `bayesfactor.brmsfit`/`bayesfactor.stanreg`: If only one model is provided, would ask to provide another model as an "alternative" argument.
- `bayesfactor.frequentistmodel`: would work similarly to Bayesian models but through the BIC approximation.

Thus, the bayesfactor function would consistently return one value, being the Bayes factor of what the main object provided (against an alternative hypothesis). 

For `bayesfactor.model`, we could also imagine that if no model as alternative is provided, then it would compute the Bayes factor for all *parameters* (similarly to equivalence test).

On top of that, we could imagine some `compare_bayesfactor` to compare multiple objects (similarly to [`compare_performance`](https://github.com/easystats/performance/blob/master/R/model_performance.R#L39).

Then, `bayesfactor_inclusion` could be implemented on top of that, or as a method for `compare_bayesfactor`.

How does that sound?

**Comment by strengejacke** [comment]
> bayesfactor.brmsfit/bayesfactor.stanreg: If only one model is provided, would ask to provide another model as an "alternative" argument.

Either test against a distribution with mean zero, or we extend the function to accept an arbitrary amount of model objects. If only one, test against `prior`, else test against models.

That would reduce the amount of functions needed.

**Comment by DominiqueMakowski** [comment]
> Ok, then we have `equivalence_test()` to test against "null", and then it indeed makes sense to have something like `compare_models()` or so for bayesfactor comparison.

_Originally posted by @strengejacke in https://github.com/easystats/bayestestR/pull/79#issuecomment-487279892_

But it is still not clear to me whether Bayes factor can also be used to test the model parameters (against 0) in a similar way to equivalence test...

In my head previously:

- equivalence_test, p_direction etc. were used to test the model's parameters
- R2 bayes, LOOIC, ELPD  etc. were used to compare models

Until yesterday, I thought that Bayes factors were rather belonging to the second group, being able to test the comparison between models. In this context, 1 model = 1 Bayes factor (the odds that the model is better than another, roughly speaking). Then I discovered the Savage-Dickeys BF, which can be easily applied to single posteriors. Thus, it seems that Bayes factors could be used both to test models comparison and *maybe* each of their parameters. Thus, I genuinely wonder if it's possible to have only one function that covers all these use cases...

Maybe it would be easier if we had two functions, `bayesfactor` and `compare_bayesfactor`.

Let's say `model` is a rstanarm model with 3 parameters (y ~ x1 * x2). 

- `bayesfactor(model)` would return a dataframe with 3 BFs, each representing the BF of each parameter's posterior against whatever default value (I guess we could use something similar to ROPE).
- `compare_bayesfactor(model)` would return the BF of the model compared to an alternative model (a default could be a constant model y ~ 1). 
- `compare_bayesfactor(model1, model2, model3, alternative=model4)`: this function would accept an arbitrary number of models and specific alternatives.

**Comment by mattansb** [comment]
As @DominiqueMakowski noted, BF can come in many varieties. Thus, I think it is appropriate that just as you have several "p-value" like functions that are not all methods of a single unifying function, there is a need for several, unrelated `bayesfactor_*` functions. I suggest the following:

## `bayesfactor_savagedickey`
returns `data.frame` of `BFsd` class:

1. `bayesfactor_savagedickey.numeric(posterior,prior,direction = "both", null = 0)` (suggests `logspline`).
1. (It might be possible to have a `bayesfactor_savagedickey.brmsfit` function (as a wrap around `brms::hypothesis`), but I think that can wait right now. )

## `bayesfactor_models`
(I think `compare_bayesfactor` is confusing, as all BFs are some type of comparison)
returns `data.frame` of `BFGrid` class:

1. `bayesfactor_models.default(..., .denominator)` (requires `insight::find_formula`) - will return BIC Bayes factors from other models (`g/lm/er` etc).
1. `bayesfactor_models.brmsfit(..., .denominator)` (requires `insight::find_formula` and `bridgesampling`)
1. `bayesfactor_models.stanreg(..., .denominator)` (requires `insight::find_formula` and `bridgesampling`)
1. `bayesfactor_models.BFBayesFactor(models)` (requires `BayesFactor`)

## `bayesfactor_inclusion`
returns `data.frame` of `BFinc` class:

1. `bayesfactor_inclusion.BFGrid(models, match_models = FALSE, prior_odds = NULL)`
1. `bayesfactor_inclusion.BFBayesFactor(models, match_models = FALSE, prior_odds = NULL)` (requires `BayesFactor`)

(each would have a print function, and maybe (?) a plot function - based on `ggplot2`)

Maybe we can have a `bayesfactor-types` help page (`?`) that has a short explnations of the different types and when to use each of them.

Thoughts?

**Comment by mattansb** [comment]
@DominiqueMakowski If this is fine, I will start work on these (will push to dev).

**Comment by DominiqueMakowski** [comment]
sure go ahead, I think a first implementation make things clearer for me and @strengejacke so itll be easier to discuss then the organisation of the functions :)

**Comment by mattansb** [comment]
I pushed the new functions into `dev` (with their printing functions).

Some to-dos:
  - [ ] Delete old `bayesfactor.R` - the new `bayesfactor_savagedickey.R` will replace it.
  - [ ] Add `example` to `bayesfactor_models`.
  - [ ] Until [this issue](https://github.com/easystats/insight/issues/87) is resolved, `bayesfactor_models` might return some weird reconstructed formulas on some specific edge cases (but all the BF calculations are correct).
  - [ ] Add tests for all functions.

# Example use:
Here is some example use:
(`bayesfactor_savagedickey` is the same function, slightly re-organized)

## `bayesfactor_models`
````
# lm
mo0 <- lm(Sepal.Length ~ 1, data = iris)
mo1 <- lm(Sepal.Length ~ Species, data = iris)
mo2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
mo3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)

bayesfactor_models(mo1,mo2,mo3,mo0,.denominator = 4)
bayesfactor_models(mo1,mo2,mo3,.denominator = mo0)

# lmer
library(lmerTest)
mo0 <- lm(Sepal.Length ~ 1, data = iris)
mo1 <- lmer(Sepal.Length ~ (1|Species), data = iris)
mo2 <- lmer(Sepal.Length ~ Petal.Length + (1|Species), data = iris)
mo3 <- lmer(Sepal.Length ~ Petal.Length + (Petal.Length|Species), data = iris)
mo4 <- lmer(Sepal.Length ~ Petal.Length + (Petal.Length|Species) + (1|Petal.Width), data = iris)
BF_models <- bayesfactor_models(mo0,mo1,mo2,mo3,mo4,.denominator = 1)
bayesfactor_models(mo1,mo2,mo3,mo4,.denominator = mo0)

# BayesFactor
library(BayesFactor)
data(puzzles)
models <- anovaBF(RT ~ shape * color + ID, data = puzzles,
                  whichRandom = "ID", progress = FALSE)
models
bayesfactor_models(models)

# brms
library(brms)
mo0 <- brm(Sepal.Length ~ 1, data = iris,chains = 2, iter = 100, save_all_pars = TRUE)
mo1 <- brm(Sepal.Length ~ Species, data = iris,chains = 2, iter = 100, save_all_pars = TRUE)
mo2 <- brm(Sepal.Length ~ Species + Petal.Length, data = iris,chains = 2, iter = 100, save_all_pars = TRUE)

BF_models_brms <- bayesfactor_models(mo0,mo1,mo2,.denominator = 1)
bayesfactor_models(mo1,mo2,.denominator = mo0)
````
## `bayesfactor_inclusion`
````
# based on objects returned from bayesfactor_models:
bayesfactor_inclusion(BF_models)
bayesfactor_inclusion(BF_models_brms)

# based on BFBayesFactor objects
bayesfactor_inclusion(models))
bayesfactor_inclusion(models, prior_odds = c(10,1,1,1)) # custom priors
bayesfactor_inclusion(models, match_models = TRUE) # only matched models
````

**Comment by DominiqueMakowski** [comment]
I am trying to run your examples but somehow it doens't work. 

``` r
library(bayestestR)
# lm
mo0 <- lm(Sepal.Length ~ 1, data = iris)
mo1 <- lm(Sepal.Length ~ Species, data = iris)
mo2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
mo3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)

bayesfactor_models(mo1,mo2,mo3,mo0,.denominator = 4)
#> Error in UseMethod("bayesfactor_models"): no applicable method for 'bayesfactor_models' applied to an object of class "lm"
```

<sup>Created on 2019-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


Anyway, a few comments:

- the `.denominator` kind of breaks the style (why use a dot argument?). I would reuse the `hypothesis` from savage dickey argument to accept either an integer OR the model itself to compare against `bayesfactor_models(m1, m2, hypothesis=m0)`
- I think it could still all be wrapped in a single wrapper function `bayesfactor`. Here's how:
  - `bayesfactor(vector)`: runs by default savage-dickey BF.
  - `bayesfactor(model)`: runs by default savage-dickey BF for all parameters' posteriors
  - `bayesfactor(model1, model2)` = `bayesfactor(model2, hypothesis=model1)`: runs by default `bayesfactor_models` on the models. 
  - if we pass the result of the precedent function (`bayesfactor_models`) to `bayesfactor`, it runs by default `bayesfactor_inclusion` on the models.

In the end, we still have 3 subfunctions `bayesfactor_*`, which can be all accessed in a quite intuitive way (IMO) via the wrapper `bayesfactor`.

**Comment by mattansb** [comment]
That is weird. For some reason both these functions don't seem to have methods! Any idea what I did wrong?
``` r
methods("bayesfactor_models")
#> no methods found

methods("bayesfactor_inclusion")
#> no methods found
```

I agree `.denominator` should lose the `.`, but I don't think this should be changed to `hypothesis`, as all the models together are multiple hypotheses. In the `BayesFactor` world, it is common to regard the compared-to model as the denominator, so I think a simple change to `denominator` would be enough.

I still think these should be separate functions, as there really are quite different in what they return, and the types of decisions they are used for: `_savagedickey` for a single posterior of any kind (estimate, contrast, slope, mean), `_models` to compare models, `_inclusion` to compare averaged effects across models.

**Comment by DominiqueMakowski** [comment]
No problem, if that's common in the "Bayes factor world" 😅 

I am also for keeping these functions as separate. That doesn't preclude having an *additional* wrapper function.

**Comment by mattansb** [comment]
So I'll remove the `.` from `.denominator`.
Let's table the wrapper function for last? For some reason it seems like a weird idea to me...

@DominiqueMakowski , do you have any idea why the methods for `bayesfactor_models` and `bayesfactor_inclusion` aren't exporting?

**Comment by DominiqueMakowski** [comment]
I'll check

**Comment by DominiqueMakowski** [comment]
I think you needed to export the methods. Should work now.

**Comment by mattansb** [comment]
> I am trying to run your examples but somehow it doens't work.

Now works! Tested on all examples in the `examples` section. Thanks @DominiqueMakowski !

**Comment by mattansb** [comment]
How do you feel about adding a vignette (or some other documentation) comparing `bayesfactor_inclusion` to JASP's effects option? We can take it from [here](https://htmlpreview.github.io/?https://github.com/mattansb/BFEffects/blob/master/vignettes/compare_to_JASP.html)

**Comment by DominiqueMakowski** [comment]
Yes. I think that a vignette under "Articles" named "Bayes factors" would be most welcomed.

More than a comparison with JASP (which can be included with a conclusion "bayestestR's implementation gives similar (or not) results to the JASP software"), I would see a description of what these indices are, what purposes can they serve and how/when to use them ☺️ It will be easier to add this technical description first to the docs of the indices, then copy paste them in the vignette, and lastly summarise them in a blog post ^^

**Comment by mattansb** [comment]
Sounds good - I'll start working on this in the upcoming days.

**Comment by mattansb** [comment]
While working on the "article", I thought of an `update` method for `BFGrid`. Super simple. Check it out (:

**Comment by mattansb** [comment]
Completed the tests!

**Comment by mattansb** [comment]
I've finished a draft of the article / vignette. Where should I add this to for you(s) to review?

**Comment by DominiqueMakowski** [comment]
awesome! If possible on dev 😉

**Comment by mattansb** [comment]
What folder? :D

**Comment by DominiqueMakowski** [comment]
vignettes!
