### ISSUE TITLE
Savage Dickey's BF: adding defaults

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#82]
@mattansb I understood that you don't like defaults and prefer users to come up with their own explicitly specified priors.

Nevertheless, in order to match the behaviour of other functions (rope), I guess we could think of some sensible defaults. Moreover, I tend to think that defaults can be good, as they allow the user to easily "have some output" and rise his/her interest, which would increase the probability of them looking in the documentation. Thus, these defaults must indeed be thoroughly documented (and why not adding some "we strongly recommend the user to explicitly re-define the prior" or something).

Currently, the default ROPE region is defined (for continuous variables) as -0.1 - 0.1, which would correspond to Cohen's 1988 "very small" or "negligible". For models, this region is additionally scaled based on the SD of the response.

As BF-SD and ROPE are likely to be used in the same context of NHST, I think having related defaults could make sense. 

Some suggestions:
- first of all, the `prior` could accept either a vector, used as a distribution, or a numeric value, that would be passed to the SD of `rnorm_perfect()` (I think it is a sensible default to have a normal distribution centred at 0 (or at the value of `null`/`h0`/`alternative`?).
- A possible default for this value could be either `0.1/3` so that the corresponding distribution spans approximately across -0.1 - 0.1, corresponding to the default ROPE. However, when I did some checks with this value, it seems that the resulting BFs for parameters are overpowered (i.e., easily very high even if the posterior is only slightly different from 0). Thus, maybe an SD of 0.1 as default would work and give more sensible results.

How does that sound?

**Comment by mattansb** [comment]
Since priors can have different distributions / locations / scales / parameters, setting a default that would make sense in even a single use case is hard.
If we really must, we could add the following:
````
if (missing(prior)) {
  prior <- rcauchy(
    n        = length(posterior),
    location = null,
    scale    = sd(posterior)
  )
  warning("Prior not specified!\n",
          "Used Cauchy prior with location = ", null, " and sacle = ", round(sd(posterior)), ".\n",
          "Please specify your own priors appropriate prior!")
}
````

What do you think?

**Comment by DominiqueMakowski** [comment]
This is a good compromise. 👍 

(there's a small typo in the warning).

**Comment by strengejacke** [comment]
@mattansb A bit off-topic, but I would suggest removing the arguments `h0` and `direction` from the function-definition, something like:

```r
bayesfactor <- function(x, prior, method = "savage-dickey", ...){
  UseMethod("bayesfactor")
}
```

because these are initiated in all other methods (i.e. users don't need to provide a value for these arguments). This makes the extension of the `bayesfactor()`-generic easier.

**Comment by strengejacke** [comment]
In the last commit, I added explicit namespace for functions (`stats::rcauchy` and `stats::sd`). Furthermore, I think the variables `posterior` and `null` are not defined in this code-chunk:

```r
  if (missing(prior)) {
    prior <- stats::rcauchy(
      n        = length(posterior),
      location = null,
      scale    = stats::sd(posterior)
    )
```

**Comment by mattansb** [comment]
@strengejacke oops - totally correct!

**Comment by DominiqueMakowski** [comment]
I am still not convinced by the name of `null` though 😬 @strengejacke do you think of that?

**Comment by strengejacke** [comment]
Currently, we have `h0`, not `null` as name.

**Comment by DominiqueMakowski** [comment]
And what do you think of `h0` ^^?

**Comment by strengejacke** [comment]
I don't think anymore, it's monday... ;-)

- having a name that implies with `null` (like `null` or `h0`) is strange when this argument is _not_ null / zero.
- `alternative` is more generic, but for implemented tests, this term stands for two-sided, less or greater than the test-value
- funcitons like `t.test()` use `mu`, but this is not always appropriate.

Maybe `alternative` and `direction` is a good pair.

**Comment by strengejacke** [comment]
or `hypothesis`? our hypothesis is that a parameter equals 0 or 1 or whatever...

**Comment by DominiqueMakowski** [comment]
`hypothesis` is ok, as it is the hypothesis that we want to test in the end (although @mattansb could argue that the hypothesis is actually the conjunction of this value and of the prior... 😁 ). But it's close to `h0`. 
Maybe a little bit more expressive though.

**Comment by mattansb** [comment]
I like `hypothesis`, or `test_value` - something to let them know *this* is what they're checking.

**Comment by DominiqueMakowski** [comment]
I think I vote for `hypothesis` ☺️

**Comment by DominiqueMakowski** [comment]
Should we add `rcauchy_perfect` and use it for the default instead of regular rcauchy?

**Comment by DominiqueMakowski** [comment]
Reopening to discuss this time the prior distribution 😅 

Cauchy is used because it has bigger tails than normal. However, some consider them too flats, and turn to student t distributions (which are "in between" normal and cauchy).

Looking at this makes me wonder:

``` r
library(bayestestR)
library(tidyverse)
library(see)

rbind(
  mutate(as.data.frame(density(rnorm_perfect(100))), type = "normal"),
  mutate(as.data.frame(density(rcauchy_perfect(100))), type = "cauchy"),
  mutate(as.data.frame(density(rt_perfect(100, df=2))), type = "student_2"),
  mutate(as.data.frame(density(rt_perfect(100, df=3))), type = "student_3")
) %>%
  ggplot(aes(x=x, y=y, color=type)) +
  geom_line(size=1) +
  coord_cartesian(xlim=c(-12, 12)) +
  theme_modern() +
  scale_color_material()
```

![](https://i.imgur.com/5sSf5xK.png)

<sup>Created on 2019-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


I started looking a bit, and found stuff like this:

> The Cauchy distribution is similar to a normal distribution, but has fatter tails and less central mass [19]. Normal and t-distributions are also common choices for prior distributions [20]. It should be noted that the lack of general rules for choosing priors is often used as an objection against the Bayesian framework. (Quintana, 2018)

However, this issue seems to has been investigated by [Ghosh, 2017](https://arxiv.org/pdf/1507.07170.pdf) which suggest: 

> in order to resolve the issue of extremely heavy tailed posteriors for Cauchy priors under separation, one would need to consider lighter tailed priors such as normal priors or Student-t priors with degrees of freedom larger than one.

Of course, these people are investigating this issue for particular priors for particular issues in particular problems. Still, it makes me wonder, @mattansb what would be the pros "in general" for Cauchy?

**Comment by mattansb** [comment]
Cauchy with a scale factor of 1 are quite wide, that's why for example even though `BayesFactor` uses a Cauchy prior, it uses a scaled Cauchy prior (scale = 0.707). As you can see, this gives a prior somewhere between the Cauchy (scale=1) and the Normal.
``` r
library(ggplot2)
ggplot(mapping = aes(0,0)) +
  stat_function(aes(color = 'Normal'),fun = dnorm,xlim = c(-10,10), size = 1) +
  stat_function(aes(color = 'Cauchy (scale=1)'),fun = dcauchy,xlim = c(-10,10), size = 1) +
  stat_function(aes(color = 't (df=2)'),fun = dt,xlim = c(-10,10), size = 1,
                args = list(df = 2)) +
  stat_function(aes(color = 'Cauchy (scale=.7)'),fun = dcauchy,xlim = c(-10,10), size = 1,
                args = list(scale = .7))
```

![](https://i.imgur.com/GU8riFf.png)

<sup>Created on 2019-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


Note that all of these discussions are about the standardized priors. To compute the BD-SD, both the prior and the posterior need to be on the same general unit-scale. All this to say that *any* default would be *extremely* inappropriate as they all need to take into account the distribution, the distribution's parameters, and the DV unit scale for any proper comparison to be made with the posterior distribution.

**Comment by mattansb** [comment]
Warning should really be `Pr(results being true | missing prior) = 0`

**Comment by DominiqueMakowski** [comment]
> Note that all of these discussions are about the standardized priors. To compute the BD-SD, both the prior and the posterior need to be on the same general unit-scale. All this to say that any default would be extremely inappropriate as they all need to take into account the distribution, the distribution's parameters, and the DV unit scale for any proper comparison to be made with the posterior distribution.

Yes yes, same applies to ROPE. But still I have the feeling that having a function that works + a warning + a documentation is somewhat more smooth for the user than directly facing an argument for which you have no idea what to provide, and for which you have to dive into the documentation without having a glimpse of what the function returns.

I am closing now. Although I am worried by the "bumps" that the `rcauchy` and `rt` have in their tails, as it could unnecessarily inflate the range of the prior. I don't know if that's important though.

**Comment by DominiqueMakowski** [comment]
In the BF vignette you show how to extract the priors from rstanarm/brms to use *them* as priors for savage-dickey BFs. Maybe we could add this behaviour as a default for these methods?

**Comment by mattansb** [comment]
I didn't really extract the priors, as much as the parameters describing them, which I then used to simulate the prior distribution. If you can figure out how to automatize this for `brmsfit`\`stanreg` objects that would be awesome...!

**Comment by strengejacke** [comment]
Since brms does not automatic scaling of priors (for technical reasons, I had a little exchange with Paul on this topic), I wrote a small function that does exactly this, however, it's a bit limited:

https://github.com/strengejacke/sjstats/blob/master/R/auto_prior.R

Or am I talking about something completely different here?

**Comment by mattansb** [comment]
Not quite - for the SD BF I would need code that accepts a `brmsfit` \ `stanreg` model and would return samples from the prior distributions of all the model parameters..

**Comment by mattansb** [comment]
I think I got it for `rstanarm`, but can one of you check please?

**Comment by mattansb** [comment]
Not sure how implement this for `brms`, as the `prior_samples` does not seems to behave nicely...

````
library(brms)
fit <- brm(count ~ zAge + zBase * Trt + (1|patient),
           data = epilepsy, sample_prior = TRUE)

fit
#>  Family: gaussian 
#>   Links: mu = identity; sigma = identity 
#> Formula: count ~ zAge + zBase * Trt + (1 | patient) 
#>    Data: epilepsy (Number of observations: 236) 
#> Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
#>          total post-warmup samples = 4000
#> 
#> Group-Level Effects: 
#> ~patient (Number of levels: 59) 
#>               Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
#> sd(Intercept)     5.33      0.69     4.10     6.82       1383 1.00
#> 
#> Population-Level Effects: 
#>            Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
#> Intercept      8.47      1.16     6.24    10.75       1246 1.00
#> zAge           1.65      0.85     0.02     3.33       1381 1.00
#> zBase          7.05      1.19     4.71     9.41       1001 1.00
#> Trt1          -0.55      1.64    -3.77     2.71       1220 1.00
#> zBase:Trt1     4.80      1.63     1.64     7.96       1113 1.00
#> 
#> Family Specific Parameters: 
#>       Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
#> sigma     5.75      0.30     5.21     6.39       3103 1.00
#> 
#> Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
#> is a crude measure of effective sample size, and Rhat is the potential 
#> scale reduction factor on split chains (at convergence, Rhat = 1).

prior_samples(fit, pars = "zAge")
#> data frame with 0 columns and 0 rows
````

It seems to only allow for non-default priors (i.e., ones specified by the user).

**Comment by strengejacke** [comment]
Not sure,I think you may need to save priors in your `brm()` call...

Here's how I extract priors for diagnostic plots, this seems to go in your direction:
https://github.com/strengejacke/sjPlot/blob/master/R/plot_diag_stan.R

I'm currently in a workshop, so I can get back to this earliest at the weekend.

**Comment by mattansb** [comment]
I have `sample_prior = TRUE`, but I don't get any of the estimates...

````
library(brms)
fit <- brm(count ~ zAge + zBase * Trt + (1|patient),
           data = epilepsy, sample_prior = TRUE)
head(prior_samples(fit))
#>       sigma sd_patient
#> 1  6.278791   4.713223
#> 2  2.149120  17.706091
#> 3 22.146855   5.794206
#> 4 15.530783   5.857891
#> 5 12.323070  12.195976
#> 6 19.459139  28.506752
````

**Comment by DominiqueMakowski** [comment]
I was thinking 'simply' about extracting (with `insight`) prior info (type, location and scale), and then pass this info to `distribution()` and using its output for the prior of BFs. 

The problem of the retrieval of scaled priors in brms is indeed a limitation...

**Comment by mattansb** [comment]
For some reason `brms` is no longer working on my machine, so I will try to get back to that after fixing this.

However, the `.stanreg` method seems to be working properly. Any ideas about how to deal with these random effects? 
````
library(rstanarm)
library(bayestestR)
fit <- stan_lmer(extra ~ group + (1|ID), data = sleep)
bayesfactor_savagedickey(fit)
#>                                   Bayes Factor
#> (Intercept)                            6.9e-02
#> group2                                 5.2e+00
#> b[(Intercept) ID:1]                    4.8e+00
#> b[(Intercept) ID:2]                    1.9e+01
#> b[(Intercept) ID:3]                    9.6e+00
#> b[(Intercept) ID:4]                    3.3e+01
#> b[(Intercept) ID:5]                    1.4e+01
#> b[(Intercept) ID:6]                    3.7e+01
#> b[(Intercept) ID:7]                    7.4e+01
#> b[(Intercept) ID:8]                    4.4e+00
#> b[(Intercept) ID:9]                    6.8e+00
#> b[(Intercept) ID:10]                   8.7e+00
#> sigma                                  2.3e+07
#> Sigma[ID:(Intercept),(Intercept)]      5.0e+01
#> ---
#> Method: Savage-Dickey density ratio
#> Test Value: 0
````

**Comment by mattansb** [comment]
Should I filter the parameters according to `insight::find_parameters(fit)[["conditional"]]`? I.e., should this function by default only return sdbf for fixed effects? Seems reasonable to me... @DominiqueMakowski ?

**Comment by DominiqueMakowski** [comment]
by default yes: I think that its behaviour should mimic other indices such as rope, equivalence test or pd (i.e., having an "effect" argument), see [here](https://github.com/easystats/bayestestR/blob/master/R/p_direction.R#L102)

**Comment by mattansb** [comment]
Done!
I think this issue can be closed.

**Comment by mattansb** [comment]
Sorry to open this again, but I think the default prior of `bayesfactor_savagedickey.numeric` be changed to the posterior. This will have two advantages over the current default:

1. It will return a `BF=1`, the most uninformative BF possible.
2. It will prevent frustration from the following situation where the default gives evidence against the null, but the true results are *actually* uninformative:

``` r
library(rstanarm)
library(bayestestR)

fit <- stan_glm(extra ~ group, sleep, family = gaussian())

group2 <- as.data.frame(fit)$group2

# uses some odd rule?
bayesfactor_savagedickey(group2)
#> Warning in bayesfactor_savagedickey.numeric(group2): Prior not specified!
#> Used Cauchy prior with location = 0 and scale = 1.
#> It is recommended to explicitly define the prior!
#>   Bayes Factor
#> 1          4.4
#> ---
#> Method: Savage-Dickey density ratio
#> Test Value: 0

# extracts true prior
bayesfactor_savagedickey(fit)
#> Loading required namespace: logspline
#>             Bayes Factor
#> (Intercept)        0.064
#> group2             1.012
#> ---
#> Method: Savage-Dickey density ratio
#> Test Value: 0
```

Suggested behavior:
```R
bayesfactor_savagedickey(group2)
#> Warning in bayesfactor_savagedickey.numeric(group2): Prior not specified!
#> Please specify a prior to get meaningful results!
#>   Bayes Factor
#> 1          1
#> ---
#> Method: Savage-Dickey density ratio
#> Test Value: 0

```

**Comment by DominiqueMakowski** [comment]
That seems ok to me. 

Maybe an example in the warning to show how to provide a prior? like:

`Please specify a prior (e.g., 'prior = distribution_normal(1000, 0, 1)') to get meaningful results!`

Because one of the common issues is that it is not clear at first for the user how to provide priors (by parameters or by an empirical distribution etc.)

**Comment by mattansb** [comment]
That again looks like were suggesting something.... How can we make it clear that any suggestion we make is categorically ***not valid***?

**Comment by DominiqueMakowski** [comment]
instead of example (which suggests indeed something valid), maybe:

`Please specify a prior (in the form 'prior = distribution_normal(1000, 0, 1)') to get meaningful results!`

**Comment by mattansb** [comment]
how about ?

`Please specify a prior (in the form 'prior = distribution_normal(...)') to get meaningful results!`

**Comment by DominiqueMakowski** [comment]
Well, in this case, it seems that `normal` is mandatory... 

I think that the surrounding warning + the thorough documentaiton will make the users understand, I wouldn't worry too much :) 

Again, I feel like the important thing is for them that the function *works* right ahead, i.e., give some "results" and does not error or wait for them to have read the whole documentation through and through to know how to fill the arguments. This increases the level of motivation to *then* read the docs and understand if the results make sense or not. 

A "working" example as above + the warning is okay IMO
