### ISSUE TITLE
HDI_area attributes in equitest

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#84]
We should also pass the hdi_area attribute to equivalence_test, as it will then be very straightforward to plot based on the [ROPE plot](https://github.com/easystats/see#region-of-practical-equivalence-rope). We could simply fill the distributions with different colours shades depending on the decision.

**Comment by strengejacke** [comment]
I'm not sure what you mean. This attribute is used in equivamence_test(), actually that was the whole intention for having this attribute.

**Comment by DominiqueMakowski** [comment]
I meant keeping this attribute in the equi test output. I.e. remove this line:

https://github.com/easystats/bayestestR/blob/868c95166d99ce917081dc6ea724a6fe608abc2f/R/equivalence_test.R#L105

**Comment by strengejacke** [comment]
But the two lines before:

```r
  out$HDI_low <- attr(rope_data, "HDI_area", exact = TRUE)$CI_low
  out$HDI_high <- attr(rope_data, "HDI_area", exact = TRUE)$CI_high
```

copy these attributes directly into the return-value.

**Comment by DominiqueMakowski** [comment]
my bad 😅

**Comment by DominiqueMakowski** [comment]
Maybe we should return the HDI area as attribute in equitest... ?

**Comment by strengejacke** [comment]
We can preserve the attribute, but should also keep the HDI in the output, as this is a relevant information that should not be "hidden" from the user.

If you need this information as attribute as well, feel free to remove the line 105 from the code (directly in master, please ;-) )

**Comment by DominiqueMakowski** [comment]
Okay. It's a bit redundant to have it also as attribute, so I'll try first to do without its copy.

**Comment by DominiqueMakowski** [comment]
In fact, let's start by keeping it :)
