### ISSUE TITLE
Change `rnorm_perfect` (etc) names?

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#86]
I think the `rnorm_perfect` family names' might be misleading - they don't actually return random generated numbers... For example, they could not be used in simulations.

Maybe drop the `r`?

**Comment by DominiqueMakowski** [comment]
That's a good point, I used the "rnorm" as the arguments are similar to the random version in terms of the arguments, but you're right that it doesn't really make sense.

Maybe then `distribution_normal`, `distribution_poisson` etc.? With a `distribution` wrapper function with a "type" argument "normal", "poisson" etc.

**Comment by mattansb** [comment]
Sounds good!

**Comment by ChristophHanck** [comment]
Regarding the discussion with Xi'an on your blog, even after renaming the function(s) it, in my opinion, is still necessary to further clarify what the added value of the function is relative to just calling the theoretical density dnorm.

**Comment by DominiqueMakowski** [comment]
@ChristophHanck Thanks for your suggestion ☺️  We will clarify in the docs that these functions do nothing fancier than returning a sequence of n-quantiles.

**Comment by ChristophHanck** [comment]
Yes, that sounds useful. To get the "real" perfect normal distribution, so to speak, one might always call

```
library(bayestestR)
x <- rnorm_perfect(n=1000)
plot(x, dnorm(x), type="l", col="blue", lwd=2)
lines(density(x), col="red", lwd=2)

```
The kernel density estimate called in density does not "know" that the underlying distribution is normal and hence may lead to somewhat less accurate results, see snippet above.

**Comment by DominiqueMakowski** [comment]
Funny story. About 1 year ago I needed a function to create "perfect distributions". Long story short, my method was to generate a large number of `rnorm` and average them... not very efficient. So I asked on StackOverflow for a better method, and after a few suggestions, someone ("Melissa Key", we should credit her somewhere now that I think of it) came up with the qnorm trick. I was happy, so I implemented it my `psycho` package. You know the rest, this function made its way to bayestestR where it got expanded, improved, criticized and renamed. 

The funny part is, I just received a StackOverflow notification; "someone answered your question". I thought "why dug up this old and, frankly, not very interesting problem" and what new answer can we bring? The answer is at the bottom of the [thread](https://stackoverflow.com/questions/50258330/generate-a-perfectly-normally-distributed-sample-of-size-n-in-r/56239294#56239294), by "Gaspar" (Gaspar if you see this thanks, you made my day :)
