### ISSUE TITLE
Bayesfactor documentation

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#89]
@DominiqueMakowski @mattansb 
As you probably know, I'm quite skeptical about the computation of the BF, beside the importance of informative priors as requirement for a "valid" BF, another reason is shown here:

https://discourse.mc-stan.org/t/bayes-factor-using-brms/4469/11

We should definitely add details to the docs, and probably also warn the user if the model object has not sufficient samples.

**Comment by DominiqueMakowski** [comment]
Do you suggest adding a paragraph about the limits of the BFs?

**Comment by strengejacke** [comment]
I rather thought about adding the requirements to gain "valid inference", so it depends if you consider _requirements_ as _limits_ ;-)

**Comment by mattansb** [comment]
Yes, I read elsewhere that Bürkner suggest at least 10,000 posterior samples.
We can add these two point (proper priors, many posteriors) to the documentation. I think a *real* discussion of these is beyond the scope of the doc, though...

**Comment by strengejacke** [comment]
> I think a real discussion of these is beyond the scope of the doc, though...

Yes, and I don't think this is something we should include in our pkg (maybe later in a vignette, with reference to statistical papers)

For now, I suggest
a) adding to the docs
b) maybe also throw a warning for too few samples?

**Comment by DominiqueMakowski** [comment]
Yes... well we can still briefly touch on these points, add a few references/links, but ultimately leave the responsibility to the user. In a sense, this is kind of the scope of bayestestR, "providing utilities", without being too much oriented. What do you think?

**Comment by strengejacke** [comment]
I think @mattansb additions are sufficient. Maybe we find another ref for the 40,000 samples suggestions, I think a good starting point for finding artilcles might be here:
https://www.rdocumentation.org/packages/bridgesampling/versions/0.6-0/topics/bridge_sampler

**Comment by mattansb** [comment]
This [https://doi.org/10.1007/s11336-018-9648-3](https://doi.org/10.1007/s11336-018-9648-3) seems to suggest **a lot** 😱 of posterior samples (page 31).

**Comment by strengejacke** [comment]
Can you add this reference to the `bayesfactor_models()` as well?

**Comment by strengejacke** [comment]
I don't find page 31 :-)

**Comment by DominiqueMakowski** [comment]
> We ran three MCMC chains with overdispersed start values, discarded the first 4000 posterior
samples as burn in, and retained only every 20th sample to reduce autocorrelation. Results reported
below are based on a total of 90,000 posterior samples.

There use either 90 000 or 180 000 posterior samples...

**Comment by mattansb** [comment]
Sorry, page 278 :)

![image](https://user-images.githubusercontent.com/35330040/57215327-2cc09500-6ff5-11e9-8e35-ed260c09aa3c.png)
