### ISSUE TITLE
estimate_density

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#92]
Unfortunately, there is some compiled C code in the package that it makes it copy non-trivial. Should we exceptionally add logspline to the dependencies (it is quite light)?

_Originally posted by @DominiqueMakowski in https://github.com/easystats/bayestestR/pull/88/review_comment/create_

-----

Having a function for better density estimation could be a plus, as it could be used quite often. Interestingly, there seems to be quite a lot of alternatives:

- [Hadley's paper](https://vita.had.co.nz/papers/density-estimation.pdf)

So this is something to investigate.

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/57204855-fbdc6200-6fec-11e9-9f19-35d613964d21.png)

In black, regular density, in blue KernSmooth and red logsplines, which sometimes seems to do bizarre thing.

**Comment by strengejacke** [comment]
I had a quick look at the paper. Given that logspline does not have major performance or accuracy benefits over stats::density I would vote against making logspline a dependency. Also, there are many other packages that could be justified as alternative as well?

**Comment by DominiqueMakowski** [comment]
in the new `estimate_density`, I switched the default's `bw` of stats::density to what they recommend in the docs:

> the smoothing bandwidth to be used. The kernels are scaled such that this is the standard deviation of the smoothing kernel. (Note this differs from the reference books cited below, and from S-PLUS.) bw can also be a character string giving a rule to choose the bandwidth. See bw.nrd. The default, "nrd0", has remained the default for historical and compatibility reasons, rather than as a general recommendation, where e.g., "SJ" would rather fit, see also Venables and Ripley (2002).

This seems to give way better results, so it could be a start.

**Comment by DominiqueMakowski** [comment]
In feature release, I think it would make sense to change the current density's default kernel by the one recommended in the docs. However, it will (although very slightly) affect other functions, in particular, those related to MAP. 

At first, I was thinking about adding a warning or a deprecation, but on second thought  I don't think people will even notice... So it might be an overshoot in regards to our current base of users.

**Comment by DominiqueMakowski** [comment]
closing.

Note that I would love to implement a Bayesian estimation of density. Besides being able to compute the MAP of the MAP of distribution 💥, I feel like this could open the door for interesting things. Unfortunately, I've looked at the literature and on the internet but didn't really found anything directly useful. 
 
There is this [julia implementation](https://github.com/danmerl/PFBDE.jl/blob/master/kernel_density_estimate_example.ipynb) of a particular algorithm.
