### ISSUE TITLE
describe_posterior

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#93]
I wonder if we should move [`describe_posterior`](https://github.com/easystats/parameters/blob/master/R/describe_posterior.R#L18) from parameters to here?

**Comment by strengejacke** [comment]
yes. You can argument it's related to parameters and to Bayes, so it could be in either pkg, but why not move it to here? I think this increases the visibility...

**Comment by DominiqueMakowski** [comment]
yes, and then model_parameters for Bayesian models will just wrap around it with additional features such as standardization

**Comment by DominiqueMakowski** [comment]
- [ ] Added to the readme

**Comment by DominiqueMakowski** [comment]
In fact, this needs a whole refactoring. 

I will start by adding, for all existing indices, methods for dataframes (which should simplify even more the code for models). Once this is done, `describe_posterior` will be refactored, as it needs to run differently for models and for dataframes.

**Comment by strengejacke** [comment]
I would say that those arguments that **all** methods have in common should go into the generic. Than, only use `@rdname` for those class-specific functions that have additional arguments.

**Comment by mattansb** [comment]
Also [add Savage-Dickey Bf alongside ROPE etc?](https://github.com/easystats/estimate/issues/8#)

**Comment by DominiqueMakowski** [comment]
@mattansb Could you add the sdBF method for dataframes also? (a wrapper for sapply(sdBF.numeric)). That would help in the refactoring of `describe_posterior`

**Comment by mattansb** [comment]
Sure - but I'll only get to that later this week.

**Comment by DominiqueMakowski** [comment]
Thanks to your help in the support of dataframes by the functions, the refactored `describe_posterior` is getting in shape :)

Check it out!

**Comment by DominiqueMakowski** [comment]
I talked too fast, still some minor issues to iron out 😬
