### ISSUE TITLE
custom `distribution` function?

### ISSUE THREAD

**Issue by mattansb** [easystats/bayestestR#95]
What do you think of the following?

``` r
distribution_custom <- function(n, dist = "norm", ..., random = FALSE) {
  if (random) {
    f <- match.fun(paste0("r",dist))
    f(n, ...)
  } else {
    f <- match.fun(paste0("q",dist))
    f(seq(1 / n, 1 - 1 / n, length.out = n), ...)
  }
}

X <- distribution_custom(1000, "chisq", df = 2)
hist(X)
```

![](https://i.imgur.com/K6X9zyy.png)

``` r

X <- distribution_custom(1000, "f", df1 = 3, df2 = 100)
hist(X)
```

![](https://i.imgur.com/outp5Bp.png)

``` r

X <- distribution_custom(1000, "unif")
hist(X)
```

![](https://i.imgur.com/ZPIE1GO.png)

<sup>Created on 2019-05-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
You mean changing the code of [distribution](https://github.com/easystats/bayestestR/blob/master/R/utils_distribution.R)?

**Comment by mattansb** [comment]
Hmmm maybe? And have some specific `distribution_*` functions that are wrap-arounds with a specific `dist` argument?

**Comment by mattansb** [comment]
Haha yeah, that's good too, but `distribution_custom` will let users use literally any distribution they want (including those not in the `stats` package).
But I'm fine with not including it :)

**Comment by DominiqueMakowski** [comment]
oh I see what you mean. Yes we should find a way to make `distribution()` (the generic function) more flexible to work with more distribuons!

**Comment by mattansb** [comment]
Maybe:
````
distribution <- function(type = "normal", ...) {
  switch(
    match.arg(arg = type, choices = c("normal", "cauchy", "poisson", "student", "chisquared", "uniform")),
    "normal" = distribution_normal(...),
    "cauchy" = distribution_cauchy(...),
    "poisson" = distribution_poisson(...),
    "student" = distribution_student(...),
    "chisquared" = distribution_chisquared(...),
    "uniform" = distribution_uniform(...),
    distribution_custom(dist = type, ...)
  )
}
````

With `distribution_custom` being the function I started with?
