### ISSUE TITLE
equivalence test error?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#98]
The error that was happening on travis, but not in local at my place, is suddenly also happening for me:

``` r
  set.seed(333)

  library(brms)
  library(bayestestR)
  model <- insight::download_model("brms_mixed_1")
  equivalence_test(model)
#> Error in .subset(x, j): invalid subscript type 'list'
```

<sup>Created on 2019-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

```
 Error in .subset(x, j) : invalid subscript type 'list' 
6.
`[.data.frame`(as.data.frame(model), , insight::find_parameters(model, 
    flatten = TRUE)) at equivalence_test.R#165
5.
as.data.frame(model)[, insight::find_parameters(model, flatten = TRUE)] at equivalence_test.R#165
4.
.check_parameter_correlation(x) at equivalence_test.R#114
3.
.equivalence_test_models(x, range, ci, parameters, verbose) at equivalence_test.R#155
2.
equivalence_test.brmsfit(model) at equivalence_test.R#79
1.
equivalence_test(model) 
```

Same for rstanarm:

```r
model <- insight::download_model("stanreg_lm_1")
equivalence_test(model)
```
@strengejacke any idea?

**Comment by strengejacke** [comment]
Can't reproduce this. Have you updated insight?

**Comment by DominiqueMakowski** [comment]
It works (again) after re-updating insight. Very odd... as it worked, then stopped working, then works again. Anyway, this allowed to confirm that this is the issue that makes travis fails, so I will leave the tests disabled until insight is updated on CRAN :)
