### ISSUE TITLE
BF for anovas

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#99]
Just came across [this tweet](https://twitter.com/tomfaulkenberry/status/1127248501354708992). I  don't know what it's worth, but supporting aov objects could also be an additional value.

On a side note, I am seeing more and more BFs represented with [pie charts](https://www.bayesianspectacles.org/lets-poke-a-pizza-a-new-cartoon-to-explain-the-strength-of-evidence-in-a-bayes-factor/) (or "pizza" charts 🍕), which I find funny. Maybe this could be something we could add in `see` through plot methods for our BFs.

**Comment by strengejacke** [comment]
![1cbc30c16b667dbae8f2daa65b5b7cf4](https://user-images.githubusercontent.com/26301769/57578182-9a524280-7487-11e9-81e2-681a87a2f2f6.png)

**Comment by mattansb** [comment]
> Just came across this tweet. I don't know what it's worth, but supporting aov objects could also be an additional value.

This can be done for *one-way* only ANOVAs (in which case, we would be wrapping around `BayesFactor::oneWayAOV.Fstat`).
Any other model can get a BF with the BIC method in `bayesfactor_models` :)

**Comment by mattansb** [comment]
For example:
``` r
library(bayestestR)

options(contrasts=c('contr.sum', 'contr.poly'))

mo0 <- aov(yield ~ 1, npk)
mo1 <- aov(yield ~ block, npk)
mo2 <- aov(yield ~ N, npk)
mo3 <- aov(yield ~ block + N, npk)
mo4 <- aov(yield ~ block * N, npk)

BF_models <- bayesfactor_models(mo1,mo2,mo3,mo4, denominator = mo0)
BF_models
#> Bayes factor analysis
#> --------------                     
#> [1] block        0.14
#> [2] N            3.78
#> [3] block + N    5.45
#> [4] block * N    0.11
#> 
#> Against denominator:
#>   [5] (Intercept only)   
#> ---
#> Bayes factor type:  BIC approximation

bayesfactor_inclusion(BF_models)
#>         Pr(prior) Pr(posterior) Inclusion.BF
#> block         0.6         0.543        0.794
#> N             0.6         0.891        5.472
#> block:N       0.2         0.011        0.043
```

<sup>Created on 2019-05-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
👍 

Although in the blogpost I think it shows the computation of a BF for every set of F value, df 1 et df 2. Thus, implementing this would return:

```r
mo4 <- aov(yield ~ block * N, npk)
bayesfactor_savagedickey_or_othermethod(mo4)
```

A dataframe of 3 rows corresponding to the BF of the 3 Parameters (block, N and the interaction). Like `bayesfactor_inclusion`, but with a unique model provided.
I am not sure how / if it is possible to implement or if that even makes sense, but hey I am not the expert of BFs 😅 

On a side note, for consistency with other methods, could we add a `Parameter` column to bayesfactor_inclusion instead of having them as row.names?

**Comment by mattansb** [comment]
Though technically you can get a BF for a set of F value, df 1 et df 2, this computation is only meaningful for *balanced, homoscedastic / spherical, one-way designs*.

See `?BayesFactor::oneWayAOV.Fstat` documentation.

**Comment by DominiqueMakowski** [comment]
haha well respecting assumptions is a whole other general issue :D

**Comment by mattansb** [comment]
Well, if we don't care about meaning or assumptions, let's add this function too :P
```R
bayesfactor_give_me <- function(x,size = c("small","medium","large"), H0 = FALSE) {
  size <- match.arg(size)
  bf <- switch(
    size,
    "small" = runif(1,1,3),
    "medium" = runif(1,3,30),
    "large" = runif(1,30,100),
  )
  
  if (H0) {
    1/bf
  } else {
    bf
  }
  
}
```

bayesfactor_give_me(rnorm(10000),"large")
#> [1] 95.37319

**Comment by DominiqueMakowski** [comment]
I reckon this would be the most used function!

**Comment by mattansb** [comment]
We can add a complimentary `pvalue_give_me` :D

**Comment by DominiqueMakowski** [comment]
`?BayesFactor::oneWayAOV.Fstat` based on this, it seems that this could be more easily handled with, if we decide to do so, in `parameters` (which cleanly extracts the required values). Closing this.

**Comment by mattansb** [comment]
Just to make sure we're on the same page - this is only applicable in any sensible way for single-factor/one-way ANOVAs, yes? 😀

**Comment by DominiqueMakowski** [comment]
I suppose yes, assuming that anovas are sensible in the first place 😁

**Comment by mattansb** [comment]
![](https://media.giphy.com/media/NORFfJzhC6iPe/200.gif)

**Comment by DominiqueMakowski** [comment]
This new preprint might be relevant:

Faulkenberry, T. J. (2019). Estimating Bayes factors from minimal ANOVA summaries for repeated-measures designs. arXiv preprint arXiv:1905.05569.

what do you think?

**Comment by mattansb** [comment]
Same reservation - only applicable to one-way ANOVAs.
Additionally, this seems that Faulkenberry's solution is a simplification of the BIC approximation to BF (whereas `BayesFactor::oneWayAOV.Fstat` calculates the marginal likelihood, but only for balanced one-way designs) - so technically you can say that we already implemented this in `bayesfactor_models`:

``` r
library(bayestestR)

m1 <- lm(yield ~ block, npk)
m0 <- lm(yield ~ 1, npk)
anova(m1)
#> Analysis of Variance Table
#> 
#> Response: yield
#>           Df Sum Sq Mean Sq F value  Pr(>F)  
#> block      5 343.29  68.659  2.3184 0.08607 .
#> Residuals 18 533.07  29.615                  
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

N <- 24
df1 <- 5
df2 <- 18
F <- 2.3184


list("BIC BF" = 1/bayesfactor_models(m1, denominator = m0)$BF[1],
     "Faulkenberry" = sqrt(N^df1 * (1+F*df1/df2)^(-N)))
#> $`BIC BF`
#> [1] 7.239669
#> 
#> $Faulkenberry
#> [1] 7.239463
```

<sup>Created on 2019-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
